name: bodyfitclubtt
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.6
  shared_preferences: ^2.5.3
  flutter_stripe: ^10.0.0
  http: ^1.2.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/splash.png
    - assets/auth/google.png
    - assets/auth/facebook.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#E2A9F1"
  adaptive_icon_foreground: "assets/icon.png"

flutter_native_splash:
  color: "#E2A9F1"
  image: assets/splash.png
  android: true
  ios: true