// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKHztwyy-ZJcMX9YT29M7C48Ygez35gnw',
    appId: '1:759454344713:web:249a3657306777785bbad8',
    messagingSenderId: '759454344713',
    projectId: 'bodyfitclubtt-9acd8',
    authDomain: 'bodyfitclubtt-9acd8.firebaseapp.com',
    storageBucket: 'bodyfitclubtt-9acd8.firebasestorage.app',
    measurementId: 'G-EDMXRSYECM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNVXcO8yl5JYVAoqQKMzTRpk5bqYyq4QQ',
    appId: '1:759454344713:android:fed08a612d4c49e65bbad8',
    messagingSenderId: '759454344713',
    projectId: 'bodyfitclubtt-9acd8',
    storageBucket: 'bodyfitclubtt-9acd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7JD99D5y4b4tA-hDMpXdxt666wippD-s',
    appId: '1:759454344713:ios:23d36540931ab62d5bbad8',
    messagingSenderId: '759454344713',
    projectId: 'bodyfitclubtt-9acd8',
    storageBucket: 'bodyfitclubtt-9acd8.firebasestorage.app',
    iosBundleId: 'com.example.bodyfitclubtt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7JD99D5y4b4tA-hDMpXdxt666wippD-s',
    appId: '1:759454344713:ios:23d36540931ab62d5bbad8',
    messagingSenderId: '759454344713',
    projectId: 'bodyfitclubtt-9acd8',
    storageBucket: 'bodyfitclubtt-9acd8.firebasestorage.app',
    iosBundleId: 'com.example.bodyfitclubtt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKHztwyy-ZJcMX9YT29M7C48Ygez35gnw',
    appId: '1:759454344713:web:428d732a1f46f2305bbad8',
    messagingSenderId: '759454344713',
    projectId: 'bodyfitclubtt-9acd8',
    authDomain: 'bodyfitclubtt-9acd8.firebaseapp.com',
    storageBucket: 'bodyfitclubtt-9acd8.firebasestorage.app',
    measurementId: 'G-RKD4LKTK35',
  );
}
