// Poľské texty aplikácie.
const Map<String, String> appTextsPl = {
  'appName': 'Body Fit Club TT',
  'loading': 'Ładowanie...',
  'ok': 'OK',
  'save': 'Zapisz',
  'delete': 'Usuń',
  'cancel': 'Anuluj',
  'back': 'Wstecz',
  'today': 'Dzisiaj',
  'tomorrow': 'Jutro',
  'todayLower': 'dzisiaj',
  'tomorrowLower': 'jutro',
  'minutes': 'min.',
  'refresh': 'Odśwież',
  'yesterday': 'Wczoraj',
  'last7Days': 'Ostatnie 7 dni',
  'last30Days': 'Ostatnie 30 dni',
  'allTime': 'Cały okres',
  'close': 'Zamknij',
  'reason': 'Powód',
  'unknownDate': 'Nieznana data',
  'notSet': 'Nie ustawiono',
  'confirm': 'Potwierdź',
  'menu': 'Menu',
  'home': 'Strona główna',
  'schedule': 'Harmonogram',
  'reservations': 'Rezerwacje',
  'management': 'Zarządzanie',
  'profile': 'Profil',
  'settings': 'Ustawienia',
  'appearance': 'Wygląd',
  'appearanceDescription': 'Wybierz tryb jasny, ciemny albo zgodny z systemem.',
  'themeSystem': 'Według systemu',
  'themeLight': 'Tryb jasny',
  'themeDark': 'Tryb ciemny',
  'menuPosition': 'Położenie menu',
  'menuPositionDescription':
      'Wybierz, po której stronie ma być wyświetlane menu główne.',
  'rightHanded': 'Praworęczny',
  'leftHanded': 'Leworęczny',
  'menuRightPositionDescription': 'Menu będzie w prawym górnym rogu.',
  'menuLeftPositionDescription': 'Menu będzie w lewym górnym rogu.',
  'language': 'Język',
  'languageDescription': 'Wybierz język aplikacji.',
  'languageSlovak': '🇸🇰 Słowacki',
  'languageEnglish': '🇬🇧 Angielski',
  'languageGerman': '🇩🇪 Niemiecki',
  'languageFrench': '🇫🇷 Francuski',
  'languagePolish': '🇵🇱 Polski',
  'languageHungarian': '🇭🇺 Węgierski',
  'languageUkrainian': '🇺🇦 Ukraiński',
  'languageRussian': '🇷🇺 Rosyjski',
  'languageSerbian': '🇷🇸 Serbski',
  'languageCzech': '🇨🇿 Czeski',
  'role': 'Rola',
  'roleUser': 'Użytkownik',
  'roleTrainer': 'Trener',
  'roleAdmin': 'Administrator',
  'roleUnknown': 'Nieznana rola',
  'privacyPolicy': 'Ochrona danych osobowych',
  'emailContact': 'E-mail',
  'loginTitle': 'Logowanie',
  'registerTitle': 'Rejestracja',
  'continueWithGoogle': 'Kontynuuj przez Google',
  'continueWithFacebook': 'Kontynuuj przez Facebook',
  'or': 'albo',
  'email': 'E-mail',
  'password': 'Hasło',
  'login': 'Zaloguj się',
  'register': 'Zarejestruj się',
  'logout': 'Wyloguj się',
  'noAccountRegister': 'Nie masz konta? Zarejestruj się',
  'hasAccountLogin': 'Masz już konto? Zaloguj się',
  'authError': 'Błąd logowania',
  'acceptTerms': 'Akceptuję regulamin',
  'acceptPrivacy': 'Wyrażam zgodę na przetwarzanie danych osobowych',
  'termsConsentRequired': 'Do rejestracji wymagana jest akceptacja regulaminu.',
  'privacyConsentRequired':
      'Do rejestracji wymagana jest zgoda na przetwarzanie danych osobowych.',
  'openTerms': 'Otwórz regulamin',
  'openPrivacy': 'Otwórz informacje o ochronie danych osobowych',
  'termsVersion': '2026-05-16',
  'privacyVersion': '2026-05-16',
  'continueWithoutAccount': 'Kontynuuj bez konta',
  'completeEmailOrLogout':
      'Jeśli nie chcesz uzupełnić adresu e-mail, możesz kontynuować bez konta i później zalogować się innym kontem.',
  'fillEmailPassword': 'Wpisz e-mail i hasło.',
  'invalidEmailFormat': 'Podaj prawidłowy adres e-mail.',
  'passwordTooShort': 'Hasło musi mieć co najmniej 6 znaków.',
  'wrongEmailOrPassword': 'Podany e-mail albo hasło są nieprawidłowe.',
  'userAlreadyExists': 'Użytkownik z tym adresem e-mail już istnieje.',
  'weakPassword': 'Podane hasło jest zbyt słabe.',
  'tooManyRequests': 'Zbyt wiele prób. Spróbuj później.',
  'networkError': 'Sprawdź połączenie z internetem.',
  'signInCancelled': 'Logowanie zostało anulowane.',
  'facebookLoginFailed': 'Logowanie przez Facebook nie powiodło się.',
  'unknownAuthError': 'Wystąpił nieznany błąd podczas logowania.',
  'inactiveAccount':
      'Twoje konto jest dezaktywowane. Skontaktuj się z administratorem.',
  'verificationEmailSent':
      'Rejestracja zakończyła się pomyślnie. Wysłaliśmy wiadomość weryfikacyjną. Jeśli nie widzisz jej w skrzynce odbiorczej, sprawdź także folder Spam.',
  'emailNotVerified':
      'Najpierw potwierdź rejestrację, klikając link w wiadomości e-mail.',
  'verificationEmailSentAgain':
      'Ponownie wysłaliśmy wiadomość weryfikacyjną. Jeśli nie widzisz jej w skrzynce odbiorczej, sprawdź także folder Spam.',
  'forgotPassword': 'Nie pamiętasz hasła?',
  'resetPasswordTitle': 'Resetowanie hasła',
  'sendResetEmail': 'Wyślij e-mail',
  'passwordResetEmailSent':
      'Jeśli konto z tym adresem e-mail istnieje, wysłaliśmy wiadomość do resetowania hasła.',
  'emailRequired': 'Podaj e-mail.',
  'emailNotProvided': 'E-mail nie został podany',
  'emailSaved': 'E-mail został zapisany.',
  'emailSaveError': 'Nie udało się zapisać adresu e-mail.',
  'emailChangeVerificationSent':
      'Na nowy adres e-mail wysłaliśmy link weryfikacyjny. Zmiana zostanie zakończona po jego potwierdzeniu.',
  'emailChangeRequestError': 'Nie udało się rozpocząć zmiany adresu e-mail.',
  'emailChangeNotAvailable':
      'Zmiana adresu e-mail jest dostępna tylko dla kont utworzonych za pomocą e-maila i hasła.',
  'completeProfileTitle': 'Uzupełnienie profilu',
  'editProfile': 'Edytuj profil',
  'firstName': 'Imię',
  'lastName': 'Nazwisko',
  'publicName': 'Nazwa wyświetlana',
  'publicNameHint': 'Np. Barbora, Katka, Aďo',
  'firstNameRequired': 'Podaj imię.',
  'lastNameRequired': 'Podaj nazwisko.',
  'publicNameRequired': 'Podaj nazwę wyświetlaną.',
  'profileSaved': 'Profil został zapisany.',
  'profileSaveError': 'Nie udało się zapisać profilu.',
  'loggedInUser': 'Zalogowany użytkownik',
  'completeEmailTitle': 'Uzupełnienie e-maila',
  'completeEmailDescription':
      'Do korzystania z aplikacji potrzebujemy Twojego adresu e-mail. Użyjemy go jako kontaktowego adresu e-mail dla Twojego konta.',
  'deleteAccountRequest': 'Poproś o usunięcie konta',
  'deleteAccountRequestTitle': 'Usunięcie konta',
  'deleteAccountRequestDescription':
      'Po wysłaniu wniosku konto zostanie dezaktywowane i nie będzie można się na nie zalogować. Dane zostaną następnie przetworzone przez administratora zgodnie z zasadami ochrony danych osobowych.',
  'deleteAccountReason': 'Powód wniosku',
  'deleteAccountConfirm': 'Czy na pewno chcesz poprosić o usunięcie konta?',
  'deleteAccountRequestSent': 'Wniosek o usunięcie konta został wysłany.',
  'deleteAccountRequestError':
      'Nie udało się wysłać wniosku o usunięcie konta.',
  'deleteAccountBlockedActiveReservations':
      'Nie można usunąć konta, ponieważ masz aktywne rezerwacje.',
  'accountDeletionRequests': 'Wnioski o usunięcie konta',
  'accountDeletionRequestsWithCount': 'Wnioski o usunięcie konta',
  'accountDeletionRequestsLoadError':
      'Nie udało się wczytać wniosków o usunięcie konta.',
  'noAccountDeletionRequests': 'Nie ma żadnych oczekujących wniosków.',
  'completeAccountDeletion': 'Zanonimizuj konto',
  'completeAccountDeletionTitle': 'Zanonimizuj konto',
  'completeAccountDeletionQuestion':
      'Czy na pewno chcesz zanonimizować to konto? Ta akcja nadpisze dane osobowe użytkownika.',
  'accountDeletionCompleted': 'Konto zostało zanonimizowane.',
  'accountDeletionCompleteError': 'Nie udało się zanonimizować konta.',
  'requestedAt': 'Zgłoszono',
  'accountDeletionRequestsWaiting': 'Wnioski oczekujące na przetworzenie.',
  'changeEmail': 'Zmień e-mail',
  'changeEmailTitle': 'Zmiana e-maila',
  'changeEmailDescription':
      'Podaj nowy e-mail i aktualne hasło. Na nowy e-mail wyślemy link weryfikacyjny. Zmiana zostanie zakończona dopiero po potwierdzeniu linku w wiadomości.',
  'changeEmailProfileHint':
      'Dostępne dla kont utworzonych za pomocą e-maila i hasła.',
  'newEmail': 'Nowy e-mail',
  'currentPassword': 'Aktualne hasło',
  'sendVerificationEmail': 'Wyślij e-mail weryfikacyjny',
  'wrongCurrentPassword': 'Aktualne hasło jest nieprawidłowe.',
  'requiresRecentLogin':
      'Aby wykonać tę akcję, najpierw wyloguj się i zaloguj ponownie.',
  'changeProfilePhoto': 'Zmień zdjęcie profilowe',
  'chooseFromGallery': 'Wybierz z galerii',
  'takePhoto': 'Zrób zdjęcie',
  'removePhoto': 'Usuń zdjęcie',
  'editPhoto': 'Edytuj zdjęcie',
  'cropProfilePhoto': 'Przytnij zdjęcie profilowe',
  'profilePhotoUpdated': 'Zdjęcie profilowe zostało zapisane.',
  'profilePhotoUpdateError': 'Nie udało się zapisać zdjęcia profilowego.',
  'profilePhotoRemoveError': 'Nie udało się usunąć zdjęcia profilowego.',
  'requestDiscount': 'Poproś o zniżkę',
  'discountStatus': 'Status zniżki',
  'discountStatusNone': 'Bez zniżki',
  'discountStatusPending': 'Oczekuje na zatwierdzenie',
  'discountStatusApproved': 'Zniżka zatwierdzona',
  'discountStatusRejected': 'Wniosek odrzucony',
  'discountStatusExpired': 'Ważność zniżki wygasła',
  'discountType': 'Typ zniżki',
  'discountTypeNormal': 'Zwykły użytkownik',
  'discountTypeStudent': 'Student',
  'discountTypeSenior': 'Senior',
  'discountTypeZtp': 'Osoba z niepełnosprawnością',
  'discountTypeIndividual': 'Indywidualna zniżka',
  'discountRequestDescription':
      'Wybierz typ zniżki, o którą wnioskujesz. Po wysłaniu wniosek sprawdzi administrator.',
  'discountRequestNote': 'Notatka do wniosku',
  'discountRequestSent': 'Wniosek o zniżkę został wysłany.',
  'discountRequestError': 'Nie udało się wysłać wniosku o zniżkę.',
  'discountRequestAlreadyPending': 'Masz już rozpoczęty wniosek o zniżkę.',
  'discountRequestPending': 'Wniosek oczekuje na zatwierdzenie',
  'sendRequest': 'Wyślij wniosek',
  'discountDocument': 'Dokument do zniżki',
  'discountDocumentDescription':
      'Prześlij zdjęcie dokumentu, na podstawie którego administrator zweryfikuje prawo do zniżki.',
  'chooseDiscountDocument': 'Wybierz dokument',
  'discountDocumentRequired': 'Do wysłania wniosku trzeba dołączyć dokument.',
  'discountDocumentSelected': 'Dokument został wybrany',
  'takeDiscountDocumentPhoto': 'Zrób zdjęcie dokumentu',
  'chooseDiscountDocumentFromGallery': 'Wybierz z galerii',
  'discountRequests': 'Wnioski o zniżkę',
  'discountRequestsDescription':
      'Zatwierdzanie albo odrzucanie wniosków użytkowników o zniżkę.',
  'discountRequestsLoadError': 'Nie udało się wczytać wniosków o zniżkę.',
  'noDiscountRequests': 'Nie ma żadnych oczekujących wniosków o zniżkę.',
  'approveDiscount': 'Zatwierdź zniżkę',
  'rejectDiscount': 'Odrzuć wniosek',
  'discountApproved': 'Zniżka została zatwierdzona.',
  'discountRejected': 'Wniosek o zniżkę został odrzucony.',
  'discountDecisionError': 'Nie udało się zapisać decyzji dotyczącej wniosku.',
  'discountValidUntilRequired': 'Wybierz datę ważności zniżki.',
  'discountAdminNote': 'Notatka administratora',
  'selectDiscountValidUntil': 'Wybierz ważność zniżki',
  'discountDocumentPreview': 'Podgląd dokumentu',
  'todayReservations': 'Dzisiejsze rezerwacje',
  'noTodayReservations': 'Nie masz dziś zarezerwowanych żadnych zajęć.',
  'nearestTraining': 'Najbliższe zajęcia',
  'nearestTrainings': 'Najbliższe zajęcia',
  'noNearestTraining': 'Nie ma zaplanowanych najbliższych zajęć.',
  'todaysTrainings': 'Dzisiejsze zajęcia',
  'noTodaysTrainings': 'Na dziś nie zaplanowano żadnych zajęć.',
  'myMemberships': 'Moje karnety',
  'activeMembershipsCount': 'Aktywne karnety',
  'availableEntriesSummary': 'Dostępne wejścia',
  'reservedEntriesSummary': 'Zarezerwowane wejścia',
  'dailyMembershipsSummary': 'Karnety dzienne',
  'tapToShowQrCode': 'Kliknij, aby wyświetlić kod QR.',
  'nearestReservations': 'Najbliższe rezerwacje',
  'noNearestReservations': 'Nie masz żadnych najbliższych rezerwacji.',
  'qrShort': 'QR',
  'membershipStatus': 'Status karnetu',
  'remainingEntries': 'Pozostałe wejścia',
  'upcomingTraining': 'Najbliższe dzisiejsze zajęcia',
  'schedulePlaceholder': 'Tutaj będzie harmonogram zajęć.',
  'reservationsPlaceholder': 'Tutaj będą rezerwacje.',
  'newsPlaceholder': 'Tutaj będą wyświetlane nowości i wiadomości od trenerów.',
  'aboutApp': 'O aplikacji',
  'aboutUs': 'O nas',
  'aboutAppDescription':
      'Aplikacja Body Fit Club TT służy do zarządzania treningami, rezerwacjami, karnetami oraz komunikacją między centrum fitness a użytkownikami.',
  'aboutUsDescription':
      'Body Fit Club to centrum fitness w Trnawie nastawione na treningi grupowe i indywidualne, ruch, zdrowy styl życia oraz osobiste podejście do klientów.',
  'bodyFitClubWebsite': 'https://bodyfitclub.sk/',
  'openWebsite': 'Otwórz stronę internetową',
  'businessTerms': 'Regulamin',
  'legalDocumentsInfo':
      'Regulamin oraz informacje o ochronie danych osobowych będą dostępne na stronie internetowej Body Fit Club.',
  'contacts': 'Kontakty',
  'billingDetails': 'Dane rozliczeniowe',
  'address': 'Adres',
  'phone': 'Telefon',
  'website': 'Strona internetowa',
  'socialNetworks': 'Sieci społecznościowe',
  'openMap': 'Otwórz mapę',
  'openFacebook': 'Facebook',
  'openInstagram': 'Instagram',
  'multisport': 'MultiSport',
  'multisportInfo':
      'Akceptujemy kartę MultiSport zgodnie z aktualnymi warunkami obiektu.',
  'bodyFitClubCompanyName': 'BODYFIT CLUB s.r.o.',
  'bodyFitClubOperationAddress': 'V Jame 24, Trnava',
  'bodyFitClubBillingAddress': 'J. G. Tajovského 18, 917 08 Trnava',
  'bodyFitClubPhonePrimary': '+421 902 860 008',
  'bodyFitClubPhoneSecondary': '+421 903 946 895',
  'bodyFitClubEmail': 'bodyfitclubtt@gmail.com',
  'bodyFitClubIco': '48074128',
  'ico': 'IČO: ',
  'companySeat': 'Siedziba',
  'operation': 'Obiekt',
  'bodyFitClubFacebookUrl': 'https://www.facebook.com/bodyfitclub.sk',
  'bodyFitClubInstagramUrl': 'https://www.instagram.com/bodyfitclub.tt/',
  'bodyFitClubMapUrl':
      'https://www.google.com/maps/search/?api=1&query=V%20Jame%206641%2F24%2C%20917%2001%20Trnava',
  'bodyFitClubMultiSportUrl':
      'https://multi-sport.sk/aktivity/partner/bodyfit-club/',
  'multisportInfo2':
      'Body Fit Club jest partnerem programu MultiSport. Akceptowanie karty MultiSport odbywa się zgodnie z aktualnymi warunkami obiektu.',
  'bodyFitClubWebsiteLabel': 'www.bodyfitclub.sk',
  'dic': 'DIČ: ',
  'bodyFitClubDic': '2120035445',
  'notVatPayer': 'Spółka nie jest płatnikiem VAT',
  'legalDocuments': 'Dokumenty prawne',
  'priceList': 'Cennik',
  'priceListAudience': 'Dla',
  'priceListAudienceNormal': 'zwykłych użytkowników',
  'priceListAudienceDiscount': 'użytkowników ze zniżką',
  'priceListAudienceAll': 'wszystkich',
  'price': 'Cena',
  'singleEntries': 'Jednorazowe wejścia',
  'priceListMemberships': 'Karnety',
  'chooseEntry': 'Wybierz wejście',
  'noAvailablePlans': 'Obecnie nie ma dostępnych opcji zakupu.',
  'news': 'Nowości',
  'noPublicMessages': 'Nie ma jeszcze żadnych wiadomości.',
  'writeMessage': 'Napisz wiadomość',
  'writeMessageShort': 'Napisz',
  'editMessage': 'Edytuj wiadomość',
  'deleteMessage': 'Usuń wiadomość',
  'deleteMessageQuestion': 'Czy na pewno chcesz usunąć tę wiadomość?',
  'messageText': 'Tekst wiadomości',
  'messageHint': 'Napisz wiadomość...',
  'sendMessage': 'Wyślij',
  'updateMessage': 'Zapisz zmiany',
  'messageSaved': 'Wiadomość została zapisana.',
  'messageDeleted': 'Wiadomość została usunięta.',
  'messageSaveError': 'Nie udało się zapisać wiadomości.',
  'messageDeleteError': 'Nie udało się usunąć wiadomości.',
  'editedBy': 'Edytowano',
  'editedByAdmin': 'Edytowane przez administratora',
  'editedByTrainer': 'Edytowane przez trenera',
  'userFallback': 'Użytkownik',
  'noTrainings': 'Obecnie nie ma dostępnych żadnych zajęć.',
  'noTrainingsForSelectedDay': 'W tym dniu nie zaplanowano żadnych zajęć.',
  'trainer': 'Trener',
  'freeSpots': 'Wolne miejsca',
  'reserve': 'Zarezerwuj',
  'reserved': 'Zarezerwowane',
  'fullCapacity': 'Brak miejsc',
  'trainingsLoadError': 'Nie udało się wczytać harmonogramu zajęć.',
  'unknownTraining': 'Nieznane zajęcia',
  'unknownTrainer': 'Nieznany trener',
  'unknownUser': 'Nieznany użytkownik',
  'trainingSessionFinished': 'Odbyło się',
  'trainingSessionTooFarInFuture':
      'Termin jest zbyt odległy w przyszłości. Ręcznie możesz dodać zajęcia tylko w okresie wyświetlanym w harmonogramie.',
  'managementDescription':
      'Tutaj możesz zarządzać terminami zajęć, obecnością, karnetami i użytkownikami.',
  'scheduleManagement': 'Zarządzanie harmonogramem',
  'scheduleManagementDescription':
      'Zarządzanie typami zajęć, szablonami harmonogramu i konkretnymi terminami treningów.',
  'attendanceManagement': 'Zarządzanie obecnością',
  'usersManagement': 'Zarządzanie użytkownikami',
  'usersManagementComingSoon':
      'Zarządzanie użytkownikami zostanie dodane później.',
  'scheduleTemplatesManagement': 'Zarządzanie szablonami harmonogramu',
  'reactivateUser': 'Aktywuj użytkownika ponownie',
  'reactivateUserQuestion':
      'Czy na pewno chcesz ponownie aktywować tego użytkownika?',
  'userReactivated': 'Użytkownik został ponownie aktywowany.',
  'trainingTypesManagement': 'Zarządzanie typami zajęć',
  'addTrainingType': 'Dodaj typ zajęć',
  'editTrainingType': 'Edytuj typ zajęć',
  'deleteTrainingType': 'Usuń typ zajęć',
  'trainingType': 'Typ zajęć',
  'selectTrainingType': 'Wybierz typ zajęć',
  'trainingName': 'Nazwa zajęć',
  'description': 'Opis',
  'defaultDuration': 'Domyślny czas trwania',
  'defaultCapacity': 'Domyślna pojemność',
  'noTrainingTypes': 'Obecnie nie utworzono żadnych typów zajęć.',
  'trainingTypesLoadError': 'Nie udało się wczytać typów zajęć.',
  'trainingTypeCreated': 'Typ zajęć został utworzony.',
  'trainingTypeUpdated': 'Typ zajęć został zaktualizowany.',
  'trainingTypeDeleted': 'Typ zajęć został usunięty.',
  'trainingTypeDeleteQuestion':
      'Czy na pewno chcesz usunąć ten typ zajęć? Nie będzie już oferowany przy nowych terminach.',
  'trainingTypeAlreadyExists': 'Typ zajęć o tej nazwie już istnieje.',
  'trainingTypeUsedByTemplate':
      'Nie można usunąć typu zajęć, ponieważ jest używany w aktywnym szablonie harmonogramu.',
  'trainingTypeUsedBySession':
      'Nie można usunąć typu zajęć, ponieważ jest używany w przyszłym terminie zajęć.',
  'addTrainingSession': 'Dodaj termin zajęć',
  'editTrainingSession': 'Edytuj szczegóły zajęć',
  'trainingSessionCreated': 'Termin treningu został utworzony.',
  'trainingSessionUpdated': 'Termin zajęć został zaktualizowany.',
  'updateTrainingSessionError': 'Nie udało się zaktualizować terminu zajęć.',
  'trainingSessionInPast': 'Termin treningu nie może być w przeszłości.',
  'trainingSessionOverlap': 'W tym czasie zaplanowano już inne zajęcia.',
  'capacityLowerThanReservations':
      'Pojemność nie może być niższa niż liczba istniejących rezerwacji.',
  'cancelTrainingSession': 'Anuluj termin',
  'cancelTrainingSessionTitle': 'Anuluj termin treningu',
  'cancelTrainingSessionQuestion':
      'Czy na pewno chcesz anulować ten termin treningu? Aktywne rezerwacje zostaną anulowane, a przydzielone wejścia zostaną zwolnione. Jeśli wejście zostało już użyte, zostanie zwrócone użytkownikowi.',
  'cancelTrainingSessionConfirm': 'Anuluj termin',
  'trainingSessionCancelled': 'Termin treningu został anulowany.',
  'cancelTrainingSessionError': 'Nie udało się anulować terminu treningu.',
  'trainerCanCancelOnlyOwnSession': 'Trener może anulować tylko własny termin.',
  'trainerCannotCancelStartedSession':
      'Trener nie może anulować terminu, który już się rozpoczął albo odbył.',
  'date': 'Data',
  'startTime': 'Początek',
  'duration': 'Czas trwania',
  'capacity': 'Pojemność',
  'selectDate': 'Wybierz datę',
  'selectTrainer': 'Wybierz trenera',
  'trainersLoadError': 'Nie udało się wczytać trenerów.',
  'fillAllFields': 'Wypełnij wszystkie wymagane dane.',
  'invalidCapacity': 'Pojemność musi być większa niż 0.',
  'invalidDuration': 'Czas trwania musi być większy niż 0.',
  'saveError': 'Nie udało się zapisać.',
  'addScheduleTemplate': 'Dodaj szablon harmonogramu',
  'editScheduleTemplate': 'Edytuj szablon harmonogramu',
  'deleteScheduleTemplate': 'Usuń szablon harmonogramu',
  'noScheduleTemplates':
      'Obecnie nie utworzono żadnych szablonów harmonogramu.',
  'weekday': 'Dzień tygodnia',
  'selectWeekday': 'Wybierz dzień tygodnia',
  'scheduleTemplateCreated': 'Szablon harmonogramu został utworzony.',
  'scheduleTemplateUpdated': 'Szablon harmonogramu został zaktualizowany.',
  'scheduleTemplateDeleted': 'Szablon harmonogramu został usunięty.',
  'scheduleTemplateDeleteQuestion':
      'Czy na pewno chcesz usunąć ten szablon harmonogramu? Nie będzie już używany przy generowaniu nowych terminów.',
  'scheduleTemplateAlreadyExists': 'Taki szablon harmonogramu już istnieje.',
  'scheduleTemplateLoadError': 'Nie udało się wczytać szablonów harmonogramu.',
  'scheduleTemplateOverlap':
      'W tym czasie istnieje już inny szablon harmonogramu.',
  'capacityLabel': 'Pojemność',
  'reservationCreated': 'Rezerwacja została utworzona.',
  'reservationAlreadyExists': 'Masz już utworzoną rezerwację na te zajęcia.',
  'reservationTrainingFull': 'Te zajęcia są już pełne.',
  'reservationTrainingNotAvailable':
      'Te zajęcia nie są już dostępne do rezerwacji.',
  'reservationTrainingAlreadyStarted':
      'Na te zajęcia nie można już dokonać rezerwacji.',
  'reservationError': 'Nie udało się utworzyć rezerwacji.',
  'myReservations': 'Moje rezerwacje',
  'noReservations': 'Obecnie nie masz żadnych rezerwacji.',
  'cancelReservation': 'Anuluj rezerwację',
  'cancelReservationTitle': 'Anuluj rezerwację',
  'cancelReservationQuestion': 'Czy na pewno chcesz anulować tę rezerwację?',
  'reservationCancelled': 'Rezerwacja została anulowana.',
  'reservationCancelError': 'Nie udało się anulować rezerwacji.',
  'reservationsLoadError': 'Nie udało się wczytać rezerwacji.',
  'cancelReservations': 'Anuluj rezerwacje',
  'cancelReservationsBeforeDeactivation':
      'Przed dezaktywacją albo anulowaniem karnetu najpierw anuluj przydzielone rezerwacje.',
  'cancelReservationForMembership': 'Anuluj tę rezerwację',
  'cancelReservationForMembershipQuestion':
      'Czy na pewno chcesz anulować tę rezerwację powiązaną z karnetem? Przydzielone wejście zostanie zwolnione.',
  'reservationForMembershipCancelled':
      'Rezerwacja została anulowana, a przydzielone wejście zwolnione.',
  'noReservationsForTrainingHistory':
      'Na tych zajęciach nie ma żadnych rezerwacji.',
  'reservationQrCode': 'Kod QR rezerwacji',
  'memberships': 'Karnety',
  'assignMembership': 'Przypisz karnet',
  'selectUser': 'Wybierz użytkownika',
  'selectMembershipPlan': 'Wybierz typ karnetu',
  'membershipPlansLoadError': 'Nie udało się wczytać typów karnetów.',
  'membershipAssigned': 'Karnet został przypisany.',
  'membershipAssignError': 'Nie udało się przypisać karnetu.',
  'membershipPlan': 'Typ karnetu',
  'client': 'Użytkownik',
  'buyMembership': 'Kup karnet',
  'buySingleEntry': 'Kup jednorazowe wejście',
  'chooseMembership': 'Wybierz karnet',
  'payment': 'Płatność',
  'pay': 'Zapłać',
  'paymentSuccessful': 'Płatność zakończona pomyślnie.',
  'paymentFailed': 'Płatność nie powiodła się.',
  'activeMembership': 'Aktywny karnet',
  'noActiveMembership': 'Nie masz aktywnego karnetu.',
  'validUntil': 'Ważny do',
  'membershipLoadError': 'Nie udało się wczytać karnetu.',
  'noAvailableEntries': 'Nie masz dostępnego wejścia do rezerwacji.',
  'noUpcomingTraining': 'Nie masz dziś zarezerwowanych żadnych zajęć.',
  'membershipsManagement': 'Zarządzanie karnetami',
  'membershipDetail': 'Szczegóły karnetu',
  'noMemberships': 'Obecnie nie ma dostępnych żadnych karnetów.',
  'status': 'Status',
  'validFrom': 'Ważny od',
  'entriesTotal': 'Łączna liczba wejść',
  'entriesRemaining': 'Pozostałe wejścia',
  'entriesReserved': 'Wejścia przydzielone w rezerwacjach',
  'entriesAvailable': 'Dostępne wejścia',
  'adminMembershipEdit': 'Edycja administracyjna',
  'membershipStatusActive': 'Aktywny',
  'membershipStatusInactive': 'Nieaktywny',
  'membershipStatusCancelled': 'Anulowany',
  'membershipStatusExpired': 'Wygasły',
  'membershipStatusUsedUp': 'Wykorzystany',
  'membershipUpdated': 'Karnet został zaktualizowany.',
  'membershipUpdateError': 'Nie udało się zaktualizować karnetu.',
  'invalidRemainingEntries': 'Podaj prawidłową liczbę pozostałych wejść.',
  'allocatedReservations': 'Przydzielone rezerwacje',
  'cancelAllocatedReservations': 'Anuluj przydzielone rezerwacje',
  'cancelAllocatedReservationsQuestion':
      'Czy na pewno chcesz anulować aktywne rezerwacje powiązane z tym karnetem? Przydzielone wejścia zostaną zwolnione.',
  'cancelAllReservations': 'Anuluj wszystkie rezerwacje',
  'cancelAllocatedReservationsError':
      'Nie udało się anulować przydzielonych rezerwacji.',
  'usedEntries': 'Wykorzystane wejścia',
  'noAllocatedReservations':
      'Do tego karnetu nie są aktualnie przydzielone żadne rezerwacje.',
  'noUsedEntries': 'Z tego karnetu nie wykorzystano jeszcze żadnego wejścia.',
  'membershipUsageLoadError': 'Nie udało się wczytać historii karnetu.',
  'searchMemberships': 'Szukaj według użytkownika albo karnetu',
  'allMembershipStatuses': 'Wszystkie statusy',
  'membershipStatusNotYetValid': 'Jeszcze nieważny',
  'membershipStatusUsable': 'Aktywny',
  'invalidRemainingEntriesHigherThanTotal':
      'Pozostałe wejścia nie mogą być większe niż łączna liczba wejść.',
  'invalidRemainingEntriesLowerThanReserved':
      'Pozostałe wejścia nie mogą być mniejsze niż liczba przydzielonych wejść.',
  'membershipPrefix': 'Karnet',
  'statusPrefix': 'Status',
  'attendance': 'Obecność',
  'attendanceLoadError': 'Nie udało się wczytać obecności.',
  'noActiveReservationsForAttendance':
      'Obecnie nie ma aktywnych rezerwacji do oznaczenia obecności.',
  'attended': 'Przyszedł',
  'noShow': 'Nie przyszedł',
  'markAttendedTitle': 'Oznacz obecność',
  'markNoShowTitle': 'Oznacz nieobecność',
  'markAttendedQuestion':
      'Czy na pewno chcesz oznaczyć użytkownika jako obecnego?',
  'markNoShowQuestion':
      'Czy na pewno chcesz oznaczyć użytkownika jako nieobecnego?',
  'attendanceMarked': 'Obecność została zapisana.',
  'attendanceMarkError': 'Nie udało się zapisać obecności.',
  'attendedStatus': 'Przyszedł',
  'noShowStatus': 'Nie przyszedł',
  'attendedCountLabel': 'Przyszli',
  'noShowCountLabel': 'Nie przyszli',
  'attendanceActionDone': 'Zmiana obecności została zapisana.',
  'attendanceActionError': 'Nie udało się zapisać zmiany obecności.',
  'showQrCode': 'Kod QR',
  'showQrToTrainer': 'Pokaż ten kod QR trenerowi po przyjściu na zajęcia.',
  'scanQrCode': 'Skanuj kod QR',
  'scanQrCodes': 'Skanuj kody QR',
  'scanQrCodeHint': 'Skieruj kamerę na kod QR rezerwacji użytkownika.',
  'invalidQrCode': 'Nieprawidłowy kod QR rezerwacji.',
  'qrCodeScanned': 'Kod QR został zeskanowany.',
  'qrScanSuccessful':
      'Kod QR został zeskanowany. Możesz skanować kolejnego użytkownika.',
  'trainerQrScanTooEarly':
      'Kod QR można zeskanować najwcześniej 30 minut przed rozpoczęciem zajęć.',
  'trainingHistory': 'Historia treningów',
  'trainingHistoryDetail': 'Szczegóły treningu',
  'trainingHistoryLoadError': 'Nie udało się wczytać historii treningów.',
  'trainingHistoryReservationsLoadError':
      'Nie udało się wczytać obecności na treningu.',
  'noTrainingHistoryInSelectedPeriod':
      'W wybranym okresie nie ma żadnych treningów.',
  'fromDatePrefix': 'Od',
  'toDatePrefix': 'Do',
  'planned': 'Zaplanowane',
  'cancelled': 'Anulowane',
  'finished': 'Odbyło się',
  'reservedStatus': 'Zarezerwowane',
  'reservedCountLabel': 'Zarezerwowane',
  'cancelledCountLabel': 'Anulowane',
  'markedAtPrefix': 'Oznaczono',
  'markAsAttended': 'Oznacz jako obecny',
  'markAsNoShow': 'Oznacz jako nieobecny',
  'revertAttendance': 'Cofnij oznaczoną obecność',
  'revertNoShow': 'Cofnij oznaczoną nieobecność',
  'markAsAttendedQuestion':
      'Czy na pewno chcesz oznaczyć użytkownika jako obecnego? Wejście z karnetu zostanie wykorzystane.',
  'markAsNoShowQuestion':
      'Czy na pewno chcesz oznaczyć użytkownika jako nieobecnego? Wejście z karnetu zostanie wykorzystane.',
  'revertAttendanceQuestion':
      'Czy na pewno chcesz cofnąć oznaczoną obecność? Wykorzystane wejście wróci na karnet.',
  'revertNoShowQuestion':
      'Czy na pewno chcesz cofnąć oznaczoną nieobecność? Wykorzystane wejście wróci na karnet.',
  'addTrainingAttendance': 'Dodaj uczestnika',
  'selectAttendanceUser': 'Wybierz użytkownika',
  'selectAttendanceMembership': 'Wybierz karnet',
  'noUsersForAttendance': 'Nie znaleziono żadnych aktywnych użytkowników.',
  'noUsableMembershipsForAttendance':
      'Użytkownik nie ma karnetu możliwego do użycia na ten trening.',
  'addTrainingAttendanceQuestion':
      'Czy na pewno chcesz dodatkowo dodać obecność użytkownika na tym treningu? Wejście z karnetu zostanie wykorzystane.',
  'trainingAttendanceAdded': 'Uczestnik został dodany do treningu.',
  'trainingAttendanceAddError': 'Nie udało się dodać uczestnika.',
  'userAlreadyHasReservationForTraining':
      'Użytkownik ma już utworzony wpis dla tego treningu.',
  'usersLoadError': 'Nie udało się wczytać użytkowników.',
  'allRoles': 'Wszystkie role',
  'searchUsers': 'Szukaj użytkownika',
  'noUsersFound': 'Nie znaleziono żadnych użytkowników.',
  'editUser': 'Edytuj użytkownika',
  'userUpdated': 'Użytkownik został zaktualizowany.',
  'userUpdateError': 'Nie udało się zaktualizować użytkownika.',
  'cannotChangeOwnRole': 'Nie możesz zmienić własnej roli.',
  'changeRoleWarning':
      'Zmiana roli użytkownika może zmienić jego uprawnienia w aplikacji.',
  'deactivateUser': 'Dezaktywuj użytkownika',
  'deactivationReason': 'Powód dezaktywacji',
  'userDeactivated': 'Użytkownik został dezaktywowany.',
  'deactivateUserQuestion':
      'Czy na pewno chcesz dezaktywować tego użytkownika? Nie będzie mógł dalej korzystać z zarządzania aplikacją.',
  'cannotDeactivateYourself': 'Nie możesz dezaktywować własnego konta.',
  'userUsedByTemplate':
      'Nie można dezaktywować użytkownika ani zmienić go na zwykłego użytkownika, ponieważ jest przypisany w aktywnym szablonie harmonogramu.',
  'userUsedByFutureSession':
      'Nie można dezaktywować użytkownika ani zmienić go na zwykłego użytkownika, ponieważ jest przypisany do przyszłych zajęć.',
  'userHasActiveReservations':
      'Nie można dezaktywować użytkownika, ponieważ ma aktywne rezerwacje.',
  'userHasActiveMemberships':
      'Nie można dezaktywować użytkownika, ponieważ ma aktywne karnety.',
  'inactiveUser': 'Nieaktywny użytkownik',
  'userCannotBeDeactivated': 'Użytkownika nie można dezaktywować',
  'userCannotBeDeactivatedDescription':
      'Przed dezaktywacją trzeba najpierw rozwiązać jego aktywne rezerwacje albo karnety.',
  'userHasBlockingItems': 'Użytkownik ma:',
  'activeReservationsCount': 'Aktywne rezerwacje',
  'showMemberships': 'Pokaż karnety',
  'auditLogs': 'Historia zmian',
  'auditLogsDescription': 'Przegląd ważnych działań w aplikacji.',
  'auditLogsLoadError': 'Nie udało się wczytać historii zmian.',
  'noAuditLogs': 'Nie znaleziono żadnych działań.',
  'searchAuditLogs': 'Szukaj według użytkownika, e-maila albo opisu',
  'auditCategory': 'Kategoria',
  'auditAction': 'Akcja',
  'auditActor': 'Wykonał',
  'auditActorRole': 'Rola wykonawcy',
  'auditPeriod': 'Okres',
  'auditAllCategories': 'Wszystkie kategorie',
  'auditCategoryMemberships': 'Karnety',
  'auditCategoryReservations': 'Rezerwacje',
  'auditCategoryAttendance': 'Obecność',
  'auditCategoryUsers': 'Użytkownicy',
  'auditCategorySchedule': 'Harmonogram',
  'auditCategoryMessages': 'Wiadomości',
  'auditCategoryPayments': 'Płatności',
  'auditCategoryProfile': 'Profil',
  'auditAllActions': 'Wszystkie akcje',
  'auditActionCreated': 'Utworzenie',
  'auditActionUpdated': 'Edycja',
  'auditActionCancelled': 'Anulowanie',
  'auditActionDeactivated': 'Dezaktywacja',
  'auditActionActivated': 'Aktywacja',
  'auditActionAssigned': 'Przypisanie',
  'auditActionPurchased': 'Zakup',
  'auditActionPaymentSucceeded': 'Płatność udana',
  'auditActionPaymentFailed': 'Płatność nieudana',
  'auditActionAttendanceMarked': 'Obecność',
  'auditActionQrChecked': 'Kontrola QR',
  'auditAllActorRoles': 'Wszystkie role',
  'auditReservationCreatedTitle': 'Utworzenie rezerwacji',
  'auditReservationCreatedDescription':
      'Użytkownik utworzył rezerwację na trening.',
  'auditReservationCancelledTitle': 'Anulowanie rezerwacji',
  'auditReservationCancelledDescription':
      'Rezerwacja użytkownika została anulowana.',
  'auditAttendanceAttendedTitle': 'Oznaczona obecność',
  'auditAttendanceAttendedDescription':
      'Użytkownik został oznaczony jako obecny na treningu.',
  'auditAttendanceNoShowTitle': 'Oznaczona nieobecność',
  'auditAttendanceNoShowDescription':
      'Użytkownik został oznaczony jako nieobecny na treningu.',
  'auditTrainingTypeCreatedTitle': 'Utworzenie typu zajęć',
  'auditTrainingTypeUpdatedTitle': 'Edycja typu zajęć',
  'auditTrainingTypeDeactivatedTitle': 'Dezaktywacja typu zajęć',
  'auditTrainingSessionCreatedTitle': 'Utworzenie terminu',
  'auditTrainingSessionUpdatedTitle': 'Edycja terminu',
  'auditTrainingSessionTimeChangedTitle': 'Zmiana czasu terminu',
  'auditTrainingSessionCancelledTitle': 'Anulowanie terminu',
  'auditScheduleTemplateCreatedTitle': 'Utworzenie szablonu harmonogramu',
  'auditScheduleTemplateUpdatedTitle': 'Edycja szablonu harmonogramu',
  'auditScheduleTemplateDeactivatedTitle': 'Dezaktywacja szablonu harmonogramu',
  'auditUserUpdatedTitle': 'Edycja użytkownika',
  'auditUserUpdatedDescription':
      'Administrator zaktualizował dane użytkownika.',
  'auditUserRoleChangedTitle': 'Zmiana roli użytkownika',
  'auditUserRoleChangedDescription': 'Administrator zmienił rolę użytkownika.',
  'auditUserDeactivatedTitle': 'Dezaktywacja użytkownika',
  'auditUserDeactivatedDescription': 'Administrator dezaktywował użytkownika.',
  'auditUserDeactivationBlockedTitle': 'Nieudana dezaktywacja użytkownika',
  'auditUserDeactivationBlockedDescription':
      'Dezaktywacja użytkownika została zablokowana przez kontrolę aktywnych powiązań.',
  'auditPublicMessageCreatedTitle': 'Utworzenie nowości',
  'auditPublicMessageCreatedDescription': 'Utworzono publiczną nowość.',
  'auditPublicMessageUpdatedTitle': 'Edycja nowości',
  'auditPublicMessageUpdatedDescription': 'Zaktualizowano publiczną nowość.',
  'auditPublicMessageDeletedTitle': 'Usunięcie nowości',
  'auditPublicMessageDeletedDescription': 'Publiczna nowość została usunięta.',
  'auditProfileCompletedTitle': 'Uzupełnienie profilu',
  'auditProfileCompletedDescription':
      'Użytkownik uzupełnił podstawowe dane profilu.',
  'auditProfileUpdatedTitle': 'Edycja profilu',
  'auditProfileUpdatedDescription': 'Użytkownik zaktualizował dane profilu.',
  'auditProfilePhotoUpdatedTitle': 'Edycja zdjęcia profilowego',
  'auditProfilePhotoUpdatedDescription':
      'Użytkownik zaktualizował zdjęcie profilowe.',
  'auditProfilePhotoRemovedTitle': 'Usunięcie zdjęcia profilowego',
  'auditProfilePhotoRemovedDescription':
      'Użytkownik usunął ręcznie ustawione zdjęcie profilowe.',
  'auditPaymentStartedTitle': 'Rozpoczęcie płatności',
  'auditPaymentStartedDescription': 'Użytkownik rozpoczął płatność za karnet.',
  'auditPaymentSucceededTitle': 'Udana płatność',
  'auditPaymentSucceededDescription':
      'Płatność za karnet została pomyślnie zakończona.',
  'auditPaymentFailedTitle': 'Nieudana płatność',
  'auditPaymentFailedDescription':
      'Płatność za karnet nie powiodła się albo została anulowana.',
  'auditMembershipUpdatedTitle': 'Edycja karnetu',
  'auditMembershipUpdatedDescription':
      'Administrator zaktualizował karnet użytkownika.',
  'auditMembershipStatusChangedTitle': 'Zmiana statusu karnetu',
  'auditMembershipStatusChangedDescription':
      'Administrator zmienił status karnetu użytkownika.',
  'auditMembershipEntriesChangedTitle': 'Zmiana liczby wejść w karnecie',
  'auditMembershipEntriesChangedDescription':
      'Administrator zmienił liczbę pozostałych wejść w karnecie.',
  'auditMembershipReservationCancelledTitle':
      'Anulowanie przydzielonej rezerwacji',
  'auditMembershipReservationCancelledDescription':
      'Administrator anulował przydzieloną rezerwację powiązaną z karnetem.',
  'auditMembershipAllReservationsCancelledTitle':
      'Anulowanie wszystkich przydzielonych rezerwacji',
  'auditMembershipAllReservationsCancelledDescription':
      'Administrator anulował wszystkie przydzielone rezerwacje powiązane z karnetem.',
  'auditMembershipAssignedTitle': 'Przypisanie karnetu',
  'auditMembershipAssignedDescription':
      'Użytkownikowi ręcznie przypisano karnet.',
  'auditMembershipPurchasedTitle': 'Zakup karnetu',
  'auditMembershipPurchasedDescription': 'Użytkownik kupił karnet.',
  'auditActionMembershipAssigned': 'Przypisanie karnetu',
  'auditActionMembershipPurchased': 'Zakup karnetu',
  'auditActionMembershipUpdated': 'Edycja karnetu',
  'auditActionMembershipStatusChanged': 'Zmiana statusu karnetu',
  'auditActionMembershipEntriesChanged': 'Zmiana wejść w karnecie',
  'auditActionMembershipReservationCancelled':
      'Anulowanie jednej przydzielonej rezerwacji',
  'auditActionMembershipAllReservationsCancelled':
      'Anulowanie wszystkich przydzielonych rezerwacji',
  'auditActionReservationCreated': 'Utworzenie rezerwacji',
  'auditActionReservationCancelled': 'Anulowanie rezerwacji',
  'auditActionAttendanceAttended': 'Oznaczona obecność',
  'auditActionAttendanceNoShow': 'Oznaczona nieobecność',
  'auditActionTrainingTypeCreated': 'Utworzenie typu zajęć',
  'auditActionTrainingTypeUpdated': 'Edycja typu zajęć',
  'auditActionTrainingTypeDeactivated': 'Dezaktywacja typu zajęć',
  'auditActionTrainingSessionCreated': 'Utworzenie terminu',
  'auditActionTrainingSessionUpdated': 'Edycja terminu',
  'auditActionTrainingSessionTimeChanged': 'Zmiana czasu terminu',
  'auditActionTrainingSessionCancelled': 'Anulowanie terminu',
  'auditActionScheduleTemplateCreated': 'Utworzenie szablonu',
  'auditActionScheduleTemplateUpdated': 'Edycja szablonu',
  'auditActionScheduleTemplateDeactivated': 'Dezaktywacja szablonu',
  'auditActionUserUpdated': 'Edycja użytkownika',
  'auditActionUserRoleChanged': 'Zmiana roli',
  'auditActionUserDeactivationBlocked': 'Zablokowana dezaktywacja',
  'auditActionUserDeactivated': 'Dezaktywacja użytkownika',
  'auditActionPublicMessageCreated': 'Utworzenie nowości',
  'auditActionPublicMessageUpdated': 'Edycja nowości',
  'auditActionPublicMessageDeleted': 'Usunięcie nowości',
  'auditActionProfileCompleted': 'Uzupełnienie profilu',
  'auditActionProfileUpdated': 'Edycja profilu',
  'auditActionProfilePhotoUpdated': 'Edycja zdjęcia profilowego',
  'auditActionProfilePhotoRemoved': 'Usunięcie zdjęcia profilowego',
  'auditActionPaymentStarted': 'Rozpoczęcie płatności',
  'auditUserEmailCompletedTitle': 'Uzupełnienie e-maila',
  'auditUserEmailCompletedDescription':
      'Użytkownik uzupełnił brakujący e-mail do konta.',
  'currentUserShort': 'ty',
  'auditUserEmailUpdatedTitle': 'Edycja e-maila użytkownika',
  'auditUserEmailUpdatedDescription':
      'Administrator zaktualizował kontaktowy e-mail użytkownika.',
  'auditUserReactivatedTitle': 'Aktywacja użytkownika',
  'auditUserReactivatedDescription':
      'Administrator ponownie aktywował użytkownika.',
  'auditActionUserEmailCompleted': 'Uzupełnienie e-maila',
  'auditActionUserEmailUpdated': 'Edycja e-maila użytkownika',
  'auditActionUserReactivated': 'Aktywacja użytkownika',
  'auditCategoryDiscounts': 'Zniżki',
  'auditDiscountRequestedTitle': 'Wniosek o zniżkę',
  'auditDiscountRequestedDescription':
      'Użytkownik wysłał wniosek o zatwierdzenie zniżki.',
  'auditDiscountApprovedTitle': 'Zatwierdzenie zniżki',
  'auditDiscountApprovedDescription':
      'Administrator zatwierdził zniżkę dla użytkownika.',
  'auditDiscountRejectedTitle': 'Odrzucenie zniżki',
  'auditDiscountRejectedDescription':
      'Administrator odrzucił wniosek użytkownika o zniżkę.',
  'auditAccountDeletionRequestedTitle': 'Wniosek o usunięcie konta',
  'auditAccountDeletionRequestedDescription':
      'Użytkownik poprosił o usunięcie konta.',
  'auditEmailChangeRequestedTitle': 'Wniosek o zmianę e-maila',
  'auditEmailChangeRequestedDescription':
      'Użytkownik poprosił o zmianę adresu e-mail.',
  'auditEmailChangeCompletedTitle': 'Zakończenie zmiany e-maila',
  'auditEmailChangeCompletedDescription':
      'Użytkownik zakończył zmianę adresu e-mail.',
  'auditPasswordResetRequestedTitle': 'Wniosek o reset hasła',
  'auditPasswordResetRequestedDescription':
      'Użytkownik poprosił o wysłanie e-maila do resetowania hasła.',
  'auditActionDiscountRequested': 'Wniosek o zniżkę',
  'auditActionDiscountApproved': 'Zatwierdzenie zniżki',
  'auditActionDiscountRejected': 'Odrzucenie zniżki',
  'auditActionAccountDeletionRequested': 'Wniosek o usunięcie konta',
  'auditActionEmailChangeRequested': 'Wniosek o zmianę e-maila',
  'auditActionEmailChangeCompleted': 'Zakończenie zmiany e-maila',
  'auditActionPasswordResetRequested': 'Wniosek o reset hasła',
};

const Map<String, List<String>> appTextListsPl = {
  'shortWeekdays': ['Po', 'Wt', 'Śr', 'Cz', 'Pt', 'So', 'Nd'],
  'weekdays': [
    'Poniedziałek',
    'Wtorek',
    'Środa',
    'Czwartek',
    'Piątek',
    'Sobota',
    'Niedziela',
  ],
};
