// Ruské texty aplikácie.
const Map<String, String> appTextsRu = {
  'appName': 'Body Fit Club TT',
  'loading': 'Загрузка...',
  'ok': 'OK',
  'save': 'Сохранить',
  'delete': 'Удалить',
  'cancel': 'Отмена',
  'back': 'Назад',
  'today': 'Сегодня',
  'tomorrow': 'Завтра',
  'todayLower': 'сегодня',
  'tomorrowLower': 'завтра',
  'minutes': 'мин.',
  'refresh': 'Обновить',
  'yesterday': 'Вчера',
  'last7Days': 'Последние 7 днив',
  'last30Days': 'Последние 30 днив',
  'allTime': 'Весь период',
  'close': 'Закрыть',
  'reason': 'Причина',
  'unknownDate': 'Неизвестная дата',
  'notSet': 'Не задано',
  'confirm': 'Подтвердить',
  'menu': 'Меню',
  'home': 'Главная',
  'schedule': 'Расписание',
  'reservations': 'Бронирование',
  'management': 'Управление',
  'profile': 'Профиль',
  'settings': 'Настройки',
  'appearance': 'Внешний вид',
  'appearanceDescription': 'Выберите светлый, тёмный или системный режим.',
  'themeSystem': 'По системе',
  'themeLight': 'Свитлий режим',
  'themeDark': 'Темний режим',
  'menuPosition': 'Расположение меню',
  'menuPositionDescription':
      'Выберите, с какой стороны должно отображаться главное меню.',
  'rightHanded': 'Правша',
  'leftHanded': 'Левша',
  'menuRightPositionDescription': 'Меню будет справа вверху.',
  'menuLeftPositionDescription': 'Меню будет слева вверху.',
  'language': 'Язык',
  'languageDescription': 'Выберите язык приложения.',
  'languageSlovak': '🇸🇰 Словацкий',
  'languageEnglish': '🇬🇧 Английский',
  'languageGerman': '🇩🇪 Немецкий',
  'languageFrench': '🇫🇷 Французский',
  'languagePolish': '🇵🇱 Польский',
  'languageHungarian': '🇭🇺 Венгерский',
  'languageUkrainian': '🇺🇦 Украинский',
  'languageRussian': '🇷🇺 Русский',
  'languageSerbian': '🇷🇸 Сербский',
  'languageCzech': '🇨🇿 Чешский',
  'role': 'Роль',
  'roleUser': 'Пользователь',
  'roleTrainer': 'Тренер',
  'roleAdmin': 'Администратор',
  'roleUnknown': 'Неизвестная роль',
  'privacyPolicy': 'Политика конфиденциальности',
  'emailContact': 'E-mail',
  'loginTitle': 'Вход',
  'registerTitle': 'Регистрация',
  'continueWithGoogle': 'Продолжить через Google',
  'continueWithFacebook': 'Продолжить через Facebook',
  'or': 'или',
  'email': 'E-mail',
  'password': 'Пароль',
  'login': 'Войти',
  'register': 'Зарегистрироваться',
  'logout': 'Выйти',
  'noAccountRegister': 'Нет аккаунта? Зарегистрироваться',
  'hasAccountLogin': 'Уже есть аккаунт? Войти',
  'authError': 'Ошибка входа',
  'acceptTerms': 'Я согласен с условиями использования',
  'acceptPrivacy': 'Я согласен на обработку персональных данных',
  'termsConsentRequired':
      'Для регистрации необходимо согласиться с условиями использования.',
  'privacyConsentRequired':
      'Для регистрации необходимо согласиться на обработку персональных данных.',
  'openTerms': 'Открыть условия использования',
  'openPrivacy': 'Открыть политику конфиденэтойности',
  'termsVersion': '2026-05-16',
  'privacyVersion': '2026-05-16',
  'continueWithoutAccount': 'Продолжить без аккаунта',
  'completeEmailOrLogout':
      'Якщо ви не хочете додавати e-mail, можете продовжити без аккаунта и пизнише увийти з иншим аккаунтом.',
  'fillEmailPassword': 'Заполните e-mail и пароль.',
  'invalidEmailFormat': 'Введите действительный e-mail адресу.',
  'passwordTooShort': 'Пароль должен содержать не менее 6 символов.',
  'wrongEmailOrPassword': 'Введённый e-mail или пароль неверный.',
  'userAlreadyExists': 'Пользователь с этим e-mail уже существует.',
  'weakPassword': 'Введений пароль слишком слабый.',
  'tooManyRequests': 'Слишком много спроб. Попробуйте пизнише.',
  'networkError': 'Проверьте подключение к интернету.',
  'signInCancelled': 'Вход було отменено.',
  'facebookLoginFailed': 'Не удалось увийти через Facebook.',
  'unknownAuthError': 'При входа сталася неизвестная ошибка.',
  'inactiveAccount': 'Ваш аккаунт деактивирован. Обратитесь до администратора.',
  'verificationEmailSent':
      'Реестрация пройшла успешно. Ми отправили вам лист для подтверждения. Якщо его неимеет у входних, перевирте також папку Спам.',
  'emailNotVerified':
      'Спочатку пидтвердьте реестрацию, натиснувши ссылка в e-mail.',
  'verificationEmailSentAgain':
      'Ми снова отправили вам лист для подтверждения. Якщо его неимеет у входних, перевирте також папку Спам.',
  'forgotPassword': 'Забыли пароль?',
  'resetPasswordTitle': 'Сновлення пароля',
  'sendResetEmail': 'Отправить e-mail',
  'passwordResetEmailSent':
      'Якщо аккаунт з циею e-mail адресою иснуе, ми отправили лист для восстатусовления пароля.',
  'emailRequired': 'Введите e-mail.',
  'emailNotProvided': 'E-mail не надано',
  'emailSaved': 'E-mail сохранено.',
  'emailSaveError': 'Не удалось сохранить e-mail.',
  'emailChangeVerificationSent':
      'На новий e-mail отправлено ссылка для подтверждения. Изменение завершиться писля его подтверждения.',
  'emailChangeRequestError': 'Не удалось розпочати змину e-mail.',
  'emailChangeNotAvailable':
      'Изменение e-mail доступна только для аккаунтов, созданных через e-mail и пароль.',
  'completeProfileTitle': 'Заполнение профиля',
  'editProfile': 'Редактировать профиль',
  'firstName': 'Имя',
  'lastName': 'Фамилия',
  'publicName': 'Отображаемое имя',
  'publicNameHint': 'Напр. Barbora, Katka, Aďo',
  'firstNameRequired': 'Введите им’я.',
  'lastNameRequired': 'Введите призвище.',
  'publicNameRequired': 'Введите видображуване им’я.',
  'profileSaved': 'Профиль сохранён.',
  'profileSaveError': 'Не удалось сохранить профиль.',
  'loggedInUser': 'Увийшов пользователь',
  'completeEmailTitle': 'Додавання e-mail',
  'completeEmailDescription':
      'Для использования приложения нам нужен ваш e-mail. Мы будем использовать его как контактный e-mail вашего аккаунта.',
  'deleteAccountRequest': 'Запросить удаление аккаунта',
  'deleteAccountRequestTitle': 'Удаление аккаунта',
  'deleteAccountRequestDescription':
      'Писля надсилання запросу аккаунт буде деактивирован, и в нього не можна буде увийти. Дани надали опрацюе администратор видповидно до правил защитеу персональних данных.',
  'deleteAccountReason': 'Причина запросу',
  'deleteAccountConfirm':
      'Вы действительно хотите запросить удаление аккаунта?',
  'deleteAccountRequestSent': 'Запрос на удаление аккаунта отправлено.',
  'deleteAccountRequestError':
      'Не удалось надислати запрос на удаление аккаунта.',
  'deleteAccountBlockedActiveReservations':
      'Обликовий запис неможливо Удалить, бо у вас е активни бронирование.',
  'accountDeletionRequests': 'Запроси на удаление аккаунтов',
  'accountDeletionRequestsWithCount': 'Запроси на удаление аккаунтов',
  'accountDeletionRequestsLoadError':
      'Не удалось завантажити запроси на удаление аккаунтов.',
  'noAccountDeletionRequests': 'Неимеет зареестрованих ожидающих запросив.',
  'completeAccountDeletion': 'Анонимизировать аккаунт',
  'completeAccountDeletionTitle': 'Анонимизировать аккаунт',
  'completeAccountDeletionQuestion':
      'Вы действительно хотите анонимизировать этот аккаунт? Это действие перезапишет персональные данные пользователя.',
  'accountDeletionCompleted': 'Обликовий запис анонимизовано.',
  'accountDeletionCompleteError': 'Не удалось анонимизировать аккаунт.',
  'requestedAt': 'Запросано',
  'accountDeletionRequestsWaiting': 'Запроси, що ожидают на обробку.',
  'changeEmail': 'Изменить e-mail',
  'changeEmailTitle': 'Изменение e-mail',
  'changeEmailDescription':
      'Введите новий e-mail и текущий пароль. На новий e-mail ми надишлемо ссылка для подтверждения. Изменение завершиться только писля подтверждения ссылка.',
  'changeEmailProfileHint':
      'доступно для аккаунтов, созданных через e-mail и пароль.',
  'newEmail': 'Новий e-mail',
  'currentPassword': 'Текущий пароль',
  'sendVerificationEmail': 'Отправить лист подтверждения',
  'wrongCurrentPassword': 'Текущий пароль неверный.',
  'requiresRecentLogin': 'Для циеи дии спочатку вийдить и увийдить снова.',
  'changeProfilePhoto': 'Изменить фото профиля',
  'chooseFromGallery': 'Выбрать з галереи',
  'takePhoto': 'Сделать фото',
  'removePhoto': 'Удалить фото',
  'editPhoto': 'Редактировать фото',
  'cropProfilePhoto': 'Обрезать фото профиля',
  'profilePhotoUpdated': 'Фото профиля сохранено.',
  'profilePhotoUpdateError': 'Не удалось сохранить фото профиля.',
  'profilePhotoRemoveError': 'Не удалось Удалить фото профиля.',
  'requestDiscount': 'Подати запрос на скидку',
  'discountStatus': 'Статус скидки',
  'discountStatusNone': 'Без скидки',
  'discountStatusPending': 'Очикуе одобрение',
  'discountStatusApproved': 'Знижку одобрено',
  'discountStatusRejected': 'Запрос отклонено',
  'discountStatusExpired': 'Термин дии скидки закинчився',
  'discountType': 'Тип скидки',
  'discountTypeNormal': 'Звичайний пользователь',
  'discountTypeStudent': 'Студент',
  'discountTypeSenior': 'Пенсионер',
  'discountTypeZtp': 'Особа з инвалиднистю',
  'discountTypeIndividual': 'Индивидуальна скидка',
  'discountRequestDescription':
      'Виберить тип скидки, на яку подаете запрос. Писля надсилання запрос перевирить администратор.',
  'discountRequestNote': 'Примечание до запросу',
  'discountRequestSent': 'Запрос на скидку отправлено.',
  'discountRequestError': 'Не удалось надислати запрос на скидку.',
  'discountRequestAlreadyPending': 'У вас уже е запрос на скидку в обробци.',
  'discountRequestPending': 'Запрос ожидает одобрение',
  'sendRequest': 'Отправить запрос',
  'discountDocument': 'Документ для скидки',
  'discountDocumentDescription':
      'Завантажте фото документа, за яким администратор перевирить право на скидку.',
  'chooseDiscountDocument': 'Выбрать документ',
  'discountDocumentRequired':
      'Для надсилання запросу необходимо додати документ.',
  'discountDocumentSelected': 'Документ вибрано',
  'takeDiscountDocumentPhoto': 'Сфотографувати документ',
  'chooseDiscountDocumentFromGallery': 'Выбрать з галереи',
  'discountRequests': 'Запроси на скидку',
  'discountRequestsDescription':
      'Одобрение или видхилення запросив пользовательив на скидку.',
  'discountRequestsLoadError': 'Не удалось завантажити запроси на скидку.',
  'noDiscountRequests': 'Неимеет зареестрованих ожидающих запросив на скидку.',
  'approveDiscount': 'Одобрить скидку',
  'rejectDiscount': 'Отклонить запрос',
  'discountApproved': 'Знижку одобрено.',
  'discountRejected': 'Запрос на скидку отклонено.',
  'discountDecisionError': 'Не удалось сохранить ришення щодо запросу.',
  'discountValidUntilRequired': 'Виберить дату дии скидки.',
  'discountAdminNote': 'Примечание администратора',
  'selectDiscountValidUntil': 'Виберить термин дии скидки',
  'discountDocumentPreview': 'Попередний перегляд документа',
  'todayReservations': 'Сегодняшни бронирование',
  'noTodayReservations': 'Сегодня у вас неимеет забронированного тренировка.',
  'nearestTraining': 'Ближайшая тренировка',
  'nearestTrainings': 'Ближайшие тренировка',
  'noNearestTraining': 'Неимеет запланированого найближчого тренировка.',
  'todaysTrainings': 'Сегодняшни тренировка',
  'noTodaysTrainings': 'Сегодня неимеет запланованих тренировок.',
  'myMemberships': 'Мои илинементи',
  'activeMembershipsCount': 'Активни илинементи',
  'availableEntriesSummary': 'Доступные входы',
  'reservedEntriesSummary': 'Зарезервовани входы',
  'dailyMembershipsSummary': 'Дневные илинементи',
  'tapToShowQrCode': 'Нажмите, щоб показать QR-код.',
  'nearestReservations': 'Ближайшие бронирование',
  'noNearestReservations': 'У вас неимеет ближайших бронирований.',
  'qrShort': 'QR',
  'membershipStatus': 'Статус илинемента',
  'remainingEntries': 'Остаток входов',
  'upcomingTraining': 'Ближайшая сегодняшне тренировка',
  'schedulePlaceholder': 'Тут буде расписание тренировок.',
  'reservationsPlaceholder': 'Тут будуть бронирование.',
  'newsPlaceholder': 'Тут видображатимуться новости та сообщение вид тренеров.',
  'aboutApp': 'О приложении',
  'aboutUs': 'О нас',
  'aboutAppDescription':
      'Застосунок Body Fit Club TT предназначено для управления тренировками, бронированиеми, илинементами та коммуникацией между фитнес-центром и пользовательами.',
  'aboutUsDescription':
      'Body Fit Club — фитнес-центр у Трнаве, ориентований на групповые та индивидуальные тренировка, движение, здоровый образ жизни та персональный подход до клиентам.',
  'bodyFitClubWebsite': 'https://bodyfitclub.sk/',
  'openWebsite': 'Открыть веб-сайт',
  'businessTerms': 'Условия использования',
  'legalDocumentsInfo':
      'Условия использования и информация о защите персональных данных будут доступны на веб-сайте Body Fit Club.',
  'contacts': 'Контакты',
  'billingDetails': 'Платёжные данные',
  'address': 'Адреса',
  'phone': 'Телефон',
  'website': 'Веб-сайт',
  'socialNetworks': 'Социальные сети',
  'openMap': 'Открыть карту',
  'openFacebook': 'Facebook',
  'openInstagram': 'Instagram',
  'multisport': 'MultiSport',
  'multisportInfo':
      'Мы принимаем карту MultiSport согласно актуальным условиям клуба.',
  'bodyFitClubCompanyName': 'BODYFIT CLUB s.r.o.',
  'bodyFitClubOperationAddress': 'V Jame 24, Trnava',
  'bodyFitClubBillingAddress': 'J. G. Tajovského 18, 917 08 Trnava',
  'bodyFitClubPhonePrimary': '+421 902 860 008',
  'bodyFitClubPhoneSecondary': '+421 903 946 895',
  'bodyFitClubEmail': 'bodyfitclubtt@gmail.com',
  'bodyFitClubIco': '48074128',
  'ico': 'IČO:',
  'companySeat': 'Юридический адрес',
  'operation': 'Помещение',
  'bodyFitClubFacebookUrl': 'https://www.facebook.com/bodyfitclub.sk',
  'bodyFitClubInstagramUrl': 'https://www.instagram.com/bodyfitclub.tt/',
  'bodyFitClubMapUrl':
      'https://www.google.com/maps/search/?api=1&query=V%20Jame%206641%2F24%2C%20917%2001%20Trnava',
  'bodyFitClubMultiSportUrl':
      'https://multi-sport.sk/aktivity/partner/bodyfit-club/',
  'multisportInfo2':
      'Body Fit Club е партнёром программы MultiSport. Приём картки MultiSport регулируется актуальными условиями клуба.',
  'bodyFitClubWebsiteLabel': 'www.bodyfitclub.sk',
  'dic': 'DIČ:',
  'bodyFitClubDic': '2120035445',
  'notVatPayer': 'Компания не является плательщиком НДС',
  'legalDocuments': 'Юридические документы',
  'priceList': 'Прайс-лист',
  'priceListAudience': 'Для',
  'priceListAudienceNormal': 'звичайних пользовательив',
  'priceListAudienceDiscount': 'пользовательив зи знижкою',
  'priceListAudienceAll': 'усих',
  'price': 'Цина',
  'singleEntries': 'Разовые входы',
  'priceListMemberships': 'Абонементы',
  'chooseEntry': 'Виберить вход',
  'noAvailablePlans': 'Сейчас нет доступных вариантов покупки.',
  'news': 'Новости',
  'noPublicMessages': 'Пока нет сообщений.',
  'writeMessage': 'Написать сообщение',
  'writeMessageShort': 'Написати',
  'editMessage': 'Редактировать сообщение',
  'deleteMessage': 'Удалить сообщение',
  'deleteMessageQuestion': 'Вы действительно хотите удалить это сообщение?',
  'messageText': 'Текст сообщение',
  'messageHint': 'Напишите сообщение...',
  'sendMessage': 'Отправить',
  'updateMessage': 'Сохранить изменения',
  'messageSaved': 'Сообщение сохранено.',
  'messageDeleted': 'Сообщение видалено.',
  'messageSaveError': 'Не удалось сохранить сообщение.',
  'messageDeleteError': 'Не удалось Удалить сообщение.',
  'editedBy': 'зминено',
  'editedByAdmin': 'зминено администратором',
  'editedByTrainer': 'зминено тренером',
  'userFallback': 'Пользователь',
  'noTrainings': 'Сейчас нет доступных тренировок.',
  'noTrainingsForSelectedDay': 'На этот день тренировки не запланированы.',
  'trainer': 'Тренер',
  'freeSpots': 'Свободные места',
  'reserve': 'Забронировать',
  'reserved': 'Забронировано',
  'fullCapacity': 'Мест нет',
  'trainingsLoadError': 'Не удалось завантажити расписание тренировок.',
  'unknownTraining': 'Неизвестная тренировка',
  'unknownTrainer': 'Невидомий тренер',
  'unknownUser': 'Невидомий пользователь',
  'trainingSessionFinished': 'Прошло',
  'trainingSessionTooFarInFuture':
      'Дата занадто далеко в майбутньому. Вручну можна додати тренировка только в межах периоду, показаного в расписаниеи.',
  'managementDescription':
      'Тут можна керувати терминами тренировок, видвидуванистю, илинементами та пользовательами.',
  'scheduleManagement': 'Управление расписаниеом',
  'scheduleManagementDescription':
      'Управление типами тренировок, шаблонами расписаниеу та конкретними терминами тренировок.',
  'attendanceManagement': 'Управление видвидуванистю',
  'usersManagement': 'Управление пользовательами',
  'usersManagementComingSoon':
      'Управление пользовательами буде додано пизнише.',
  'scheduleTemplatesManagement': 'Управление шаблонами расписаниеу',
  'reactivateUser': 'Активувати пользовательа',
  'reactivateUserQuestion':
      'Вы действительно хотите снова активировать этого пользователя?',
  'userReactivated': 'Пользовательа снова активовано.',
  'trainingTypesManagement': 'Управление типами занятий',
  'addTrainingType': 'Додати тип тренировка',
  'editTrainingType': 'Редактировать тип тренировка',
  'deleteTrainingType': 'Удалить тип тренировка',
  'trainingType': 'Тип тренировка',
  'selectTrainingType': 'Виберить тип тренировка',
  'trainingName': 'Название занятия',
  'description': 'Опис',
  'defaultDuration': 'Длительность по умолчанию',
  'defaultCapacity': 'Вместимость по умолчанию',
  'noTrainingTypes': 'Сейчас не создано ни одного типа занятия.',
  'trainingTypesLoadError': 'Не удалось завантажити типи тренировок.',
  'trainingTypeCreated': 'Тип тренировка создано.',
  'trainingTypeUpdated': 'Тип тренировка обновлён.',
  'trainingTypeDeleted': 'Тип тренировка видалено.',
  'trainingTypeDeleteQuestion':
      'Вы действительно хотите удалить этот тип занятия? Он больше не будет предлагаться для новых занятий.',
  'trainingTypeAlreadyExists': 'Тип тренировка з такою назвою вже иснуе.',
  'trainingTypeUsedByTemplate':
      'Тип занятия нельзя удалить, потому что он используется в активном шаблоне расписания.',
  'trainingTypeUsedBySession':
      'Тип занятия нельзя удалить, потому что он используется в будущей тренировке.',
  'addTrainingSession': 'Добавить тренировку',
  'editTrainingSession': 'Редактировать детали тренировка',
  'trainingSessionCreated': 'Термин тренировка создано.',
  'trainingSessionUpdated': 'Термин тренировка обновлён.',
  'updateTrainingSessionError': 'Не удалось обновить термин тренировка.',
  'trainingSessionInPast': 'Термин тренировка не може бути в минулому.',
  'trainingSessionOverlap': 'У цей час уже заплановане инше тренировка.',
  'capacityLowerThanReservations':
      'Мисткисть не може бути меншою за количество наявних бронирований.',
  'cancelTrainingSession': 'Отмена термин',
  'cancelTrainingSessionTitle': 'Отмена термин тренировка',
  'cancelTrainingSessionQuestion':
      'Вы действительно хотите отменить эту тренировку? Активные бронирования будут отменены, а зарезервированные входы освобождены. Если вход уже был использован, он будет возвращён пользователю.',
  'cancelTrainingSessionConfirm': 'Отмена термин',
  'trainingSessionCancelled': 'Термин тренировка отменено.',
  'cancelTrainingSessionError': 'Не удалось отменить термин тренировка.',
  'trainerCanCancelOnlyOwnSession':
      'Тренер може отменить только власний термин.',
  'trainerCannotCancelStartedSession':
      'Тренер не може отменить термин, який уже почався или видбувся.',
  'date': 'Дата',
  'startTime': 'Начало',
  'duration': 'Длительность',
  'capacity': 'Вместимость',
  'selectDate': 'Виберить дату',
  'selectTrainer': 'Виберить тренера',
  'trainersLoadError': 'Не удалось завантажити тренеров.',
  'fillAllFields': 'Заполните уси обов’язкови данные.',
  'invalidCapacity': 'Мисткисть имеет бути бильшою за 0.',
  'invalidDuration': 'Тривалисть имеет бути бильшою за 0.',
  'saveError': 'Не удалось сохранить.',
  'addScheduleTemplate': 'Додати шаблон расписаниеу',
  'editScheduleTemplate': 'Редактировать шаблон расписаниеу',
  'deleteScheduleTemplate': 'Удалить шаблон расписаниеу',
  'noScheduleTemplates': 'Сейчас не создано ни одного шаблона расписания.',
  'weekday': 'День недели',
  'selectWeekday': 'Виберить день тижня',
  'scheduleTemplateCreated': 'Шаблон расписаниеу создано.',
  'scheduleTemplateUpdated': 'Шаблон расписаниеу обновлён.',
  'scheduleTemplateDeleted': 'Шаблон расписаниеу видалено.',
  'scheduleTemplateDeleteQuestion':
      'Вы действительно хотите удалить этот шаблон расписания? Он больше не будет использоваться при создании новых занятий.',
  'scheduleTemplateAlreadyExists': 'Такий шаблон расписаниеу вже иснуе.',
  'scheduleTemplateLoadError': 'Не удалось завантажити шаблони расписаниеу.',
  'scheduleTemplateOverlap': 'У цей час уже иснуе инший шаблон расписаниеу.',
  'capacityLabel': 'Мисткисть',
  'reservationCreated': 'Бронирование создано.',
  'reservationAlreadyExists': 'На це тренировка у вас уже е бронирование.',
  'reservationTrainingFull': 'Це тренировка вже заповнене.',
  'reservationTrainingNotAvailable':
      'Це тренировка вже недоступне для бронирование.',
  'reservationTrainingAlreadyStarted':
      'На це тренировка вже не можна забронювати мисце.',
  'reservationError': 'Не удалось создать бронирование.',
  'myReservations': 'Мои бронирования',
  'noReservations': 'Сейчас у вас нет бронирований.',
  'cancelReservation': 'Отмена бронирование',
  'cancelReservationTitle': 'Отмена бронирование',
  'cancelReservationQuestion':
      'Вы действительно хотите отменить это бронирование?',
  'reservationCancelled': 'Бронирование отменено.',
  'reservationCancelError': 'Не удалось отменить бронирование.',
  'reservationsLoadError': 'Не удалось завантажити бронирование.',
  'cancelReservations': 'Отмена бронирование',
  'cancelReservationsBeforeDeactivation':
      'Перед деактивациею или скасуванням илинемента спочатку скасуйте зарезервированные бронирование.',
  'cancelReservationForMembership': 'Отмена це бронирование',
  'cancelReservationForMembershipQuestion':
      'Вы действительно хотите отменить это бронирование, привязанное к абонементу? Зарезервированный вход освободится.',
  'reservationForMembershipCancelled':
      'Бронирование отменено, а зарезервований вход звильнено.',
  'noReservationsForTrainingHistory':
      'На цьому тренировке неимеет бронирований.',
  'reservationQrCode': 'QR-код бронирование',
  'memberships': 'Абонементы',
  'assignMembership': 'Призначити илинемент',
  'selectUser': 'Виберить пользовательа',
  'selectMembershipPlan': 'Виберить тип илинемента',
  'membershipPlansLoadError': 'Не удалось завантажити типи илинементив.',
  'membershipAssigned': 'Абонемент назначен.',
  'membershipAssignError': 'Не удалось призначити илинемент.',
  'membershipPlan': 'Тип илинемента',
  'client': 'Пользователь',
  'buyMembership': 'Купить абонемент',
  'buySingleEntry': 'Купить разовый вход',
  'chooseMembership': 'Виберить илинемент',
  'payment': 'Оплата',
  'pay': 'Оплатить',
  'paymentSuccessful': 'Оплата прошла успешно.',
  'paymentFailed': 'Оплата не удалась.',
  'activeMembership': 'Активный абонемент',
  'noActiveMembership': 'У вас нет активного абонемента.',
  'validUntil': 'Дийсний до',
  'membershipLoadError': 'Не удалось завантажити илинемент.',
  'noAvailableEntries': 'У вас неимеет доступного входа для бронирование.',
  'noUpcomingTraining': 'Сегодня у вас неимеет забронированного тренировка.',
  'membershipsManagement': 'Управление илинементами',
  'membershipDetail': 'Детали илинемента',
  'noMemberships': 'Сейчас нет доступных абонементов.',
  'status': 'Статус',
  'validFrom': 'Дийсний вид',
  'entriesTotal': 'Загальна количество входов',
  'entriesRemaining': 'Остаток входов',
  'entriesReserved': 'Зарезервовано в бронированиех',
  'entriesAvailable': 'Доступные входы',
  'adminMembershipEdit': 'Административна правка',
  'membershipStatusActive': 'Активный',
  'membershipStatusInactive': 'Неактивный',
  'membershipStatusCancelled': 'Отменён',
  'membershipStatusExpired': 'Истёк',
  'membershipStatusUsedUp': 'Использован',
  'membershipUpdated': 'Абонемент обновлён.',
  'membershipUpdateError': 'Не удалось обновить илинемент.',
  'invalidRemainingEntries':
      'Введите действительный количество оставшихся входов.',
  'allocatedReservations': 'Зарезервовани бронирование',
  'cancelAllocatedReservations': 'Отмена зарезервированные бронирование',
  'cancelAllocatedReservationsQuestion':
      'Вы действительно хотите отменить активные бронирования, привязанные к этому абонементу? Зарезервированные входы освободятся.',
  'cancelAllReservations': 'Отмена все бронирование',
  'cancelAllocatedReservationsError':
      'Не удалось отменить зарезервированные бронирование.',
  'usedEntries': 'Использованные входы',
  'noAllocatedReservations':
      'До этого илинемента нарази не прив’язано жодного активного бронирование.',
  'noUsedEntries': 'З этого илинемента ще не було использовано жодного входа.',
  'membershipUsageLoadError': 'Не удалось завантажити историю илинемента.',
  'searchMemberships': 'Искать за пользовательем или илинементом',
  'allMembershipStatuses': 'Все статуси',
  'membershipStatusNotYetValid': 'Ще не действийсний',
  'membershipStatusUsable': 'Активний',
  'invalidRemainingEntriesHigherThanTotal':
      'Остаток входов не може бути бильшим за загальну количество входов.',
  'invalidRemainingEntriesLowerThanReserved':
      'Остаток входов не може бути меншим за количество зарезервованих входов.',
  'membershipPrefix': 'Абонемент',
  'statusPrefix': 'Статус',
  'attendance': 'Посещаемость',
  'attendanceLoadError': 'Не удалось завантажити видвидуванисть.',
  'noActiveReservationsForAttendance':
      'Сейчас нет активных бронирований для отметки посещаемости.',
  'attended': 'Пришёл',
  'noShow': 'Не пришёл',
  'markAttendedTitle': 'Отметить посещение',
  'markNoShowTitle': 'Отметить отсутствие',
  'markAttendedQuestion':
      'Вы действительно хотите отметить пользователя как присутствующего?',
  'markNoShowQuestion':
      'Вы действительно хотите отметить пользователя как отсутствующего?',
  'attendanceMarked': 'Свидуванисть сохранено.',
  'attendanceMarkError': 'Не удалось сохранить видвидуванисть.',
  'attendedStatus': 'Пришёл',
  'noShowStatus': 'Не пришёл',
  'attendedCountLabel': 'Прийшли',
  'noShowCountLabel': 'Не прийшли',
  'attendanceActionDone': 'Змину видвидуваности сохранено.',
  'attendanceActionError': 'Не удалось сохранить змину видвидуваности.',
  'showQrCode': 'QR-код',
  'showQrToTrainer':
      'Покажить цей QR-код тренеру пид час приходу на тренировка.',
  'scanQrCode': 'Сканувати QR-код',
  'scanQrCodes': 'Сканувати QR-коди',
  'scanQrCodeHint': 'Наведить камеру на QR-код бронирование пользовательа.',
  'invalidQrCode': 'Недействийсний QR-код бронирование.',
  'qrCodeScanned': 'QR-код видскановано.',
  'qrScanSuccessful':
      'QR-код видскановано. Можете сканувати наступного пользовательа.',
  'trainerQrScanTooEarly':
      'QR-код можна сканувати не ранише ниж за 30 хвилин до початку тренировка.',
  'trainingHistory': 'История тренировок',
  'trainingHistoryDetail': 'Детали тренировки',
  'trainingHistoryLoadError': 'Не удалось завантажити историю тренировок.',
  'trainingHistoryReservationsLoadError':
      'Не удалось завантажити участие у тренировке.',
  'noTrainingHistoryInSelectedPeriod':
      'У вибраному периоде неимеет тренировок.',
  'fromDatePrefix': 'С',
  'toDatePrefix': 'До',
  'planned': 'Заплановано',
  'cancelled': 'Скасовано',
  'finished': 'Прошло',
  'reservedStatus': 'Заброньовано',
  'reservedCountLabel': 'Заброньовано',
  'cancelledCountLabel': 'Скасовано',
  'markedAtPrefix': 'Отмечено',
  'markAsAttended': 'Отметить как пришёл',
  'markAsNoShow': 'Отметить как не пришёл',
  'revertAttendance': 'Отмена отметку посещение',
  'revertNoShow': 'Отмена отметку отсутствие',
  'markAsAttendedQuestion':
      'Вы действительно хотите отметить пользователя как присутствующего? Вход из абонемента будет использован.',
  'markAsNoShowQuestion':
      'Вы действительно хотите отметить пользователя как отсутствующего? Вход из абонемента будет использован.',
  'revertAttendanceQuestion':
      'Вы действительно хотите отменить отметку посещения? Использованный вход вернётся обратно в абонемент.',
  'revertNoShowQuestion':
      'Вы действительно хотите отменить отметку отсутствия? Использованный вход вернётся обратно в абонемент.',
  'addTrainingAttendance': 'Добавить участника',
  'selectAttendanceUser': 'Виберить пользовательа',
  'selectAttendanceMembership': 'Виберить илинемент',
  'noUsersForAttendance': 'Не найдено активних пользовательив.',
  'noUsableMembershipsForAttendance':
      'Пользователь не имеет подходящего илинемента для этого тренировка.',
  'addTrainingAttendanceQuestion':
      'Вы действительно хотите дополнительно добавить участие пользователя в этой тренировке? Вход из абонемента будет использован.',
  'trainingAttendanceAdded': 'Участник додано до тренировка.',
  'trainingAttendanceAddError': 'Не удалось додати участника.',
  'userAlreadyHasReservationForTraining':
      'Пользователь уже имеет запис для этого тренировка.',
  'usersLoadError': 'Не удалось загрузить пользователей.',
  'allRoles': 'Все роли',
  'searchUsers': 'Искать пользователя',
  'noUsersFound': 'Пользователи не найдены.',
  'editUser': 'Редактировать пользователя',
  'userUpdated': 'Пользователь обновлён.',
  'userUpdateError': 'Не удалось обновить пользователя.',
  'cannotChangeOwnRole': 'Вы не можете изменить собственную роль.',
  'changeRoleWarning':
      'При изменении роли пользователя могут измениться его права в приложении.',
  'deactivateUser': 'Деактивувати пользовательа',
  'deactivationReason': 'Причина деактивации',
  'userDeactivated': 'Пользовательа деактивирован.',
  'deactivateUserQuestion':
      'Вы действительно хотите деактивировать этого пользователя? Он больше не сможет использоваться в управлении приложением.',
  'cannotDeactivateYourself':
      'Вы не можете деактивировать собственный аккаунт.',
  'userUsedByTemplate':
      'Пользователя нельзя деактивировать или изменить на обычного пользователя, потому что он назначен в активном шаблоне расписания.',
  'userUsedByFutureSession':
      'Пользователя нельзя деактивировать или изменить на обычного пользователя, потому что он назначен на будущую тренировку.',
  'userHasActiveReservations':
      'Пользователя нельзя деактивировать, потому что у него есть активные бронирования.',
  'userHasActiveMemberships':
      'Пользователя нельзя деактивировать, потому что у него есть активные абонементы.',
  'inactiveUser': 'Неактивный пользователь',
  'userCannotBeDeactivated': 'Пользователя нельзя деактивировать',
  'userCannotBeDeactivatedDescription':
      'Перед деактивацией необходимо сначала решить его активные бронирования или абонементы.',
  'userHasBlockingItems': 'У пользователя есть:',
  'activeReservationsCount': 'Активные бронирования',
  'showMemberships': 'Показать абонементы',
  'auditLogs': 'История действий',
  'auditLogsDescription': 'Обзор важных действий в приложении.',
  'auditLogsLoadError': 'Не удалось загрузить историю действий.',
  'noAuditLogs': 'Действия не найдены.',
  'searchAuditLogs': 'Искать по пользователю, e-mail или описанию',
  'auditCategory': 'Категория',
  'auditAction': 'Действие',
  'auditActor': 'Виконав',
  'auditActorRole': 'Роль исполнителя',
  'auditPeriod': 'Период',
  'auditAllCategories': 'Все категории',
  'auditCategoryMemberships': 'Абонементы',
  'auditCategoryReservations': 'Бронирование',
  'auditCategoryAttendance': 'Свидуванисть',
  'auditCategoryUsers': 'Пользователи',
  'auditCategorySchedule': 'Расписание',
  'auditCategoryMessages': 'Сообщения',
  'auditCategoryPayments': 'Платежи',
  'auditCategoryProfile': 'Профиль',
  'auditAllActions': 'Все действия',
  'auditActionCreated': 'Создание',
  'auditActionUpdated': 'Изменение',
  'auditActionCancelled': 'Отмена',
  'auditActionDeactivated': 'Деактивация',
  'auditActionActivated': 'Активация',
  'auditActionAssigned': 'Назначение',
  'auditActionPurchased': 'Покупка',
  'auditActionPaymentSucceeded': 'Оплата успишна',
  'auditActionPaymentFailed': 'Оплата не удалась',
  'auditActionAttendanceMarked': 'Свидуванисть',
  'auditActionQrChecked': 'QR-контроль',
  'auditAllActorRoles': 'Все роли',
  'auditReservationCreatedTitle': 'Создание бронирования',
  'auditReservationCreatedDescription':
      'Пользователь создал бронирование на тренировку.',
  'auditReservationCancelledTitle': 'Отмена бронирования',
  'auditReservationCancelledDescription':
      'Бронирование пользователя было отменено.',
  'auditAttendanceAttendedTitle': 'Отмечено посещение',
  'auditAttendanceAttendedDescription':
      'Пользователь отмечен как присутствующий на тренировке.',
  'auditAttendanceNoShowTitle': 'Отмечено отсутствие',
  'auditAttendanceNoShowDescription':
      'Пользователь отмечен как отсутствующий на тренировке.',
  'auditTrainingTypeCreatedTitle': 'Создание типа занятия',
  'auditTrainingTypeUpdatedTitle': 'Изменение типа занятия',
  'auditTrainingTypeDeactivatedTitle': 'Деактивация типа занятия',
  'auditTrainingSessionCreatedTitle': 'Создание тренировки',
  'auditTrainingSessionUpdatedTitle': 'Изменение тренировки',
  'auditTrainingSessionTimeChangedTitle': 'Изменение времени тренировки',
  'auditTrainingSessionCancelledTitle': 'Отмена тренировки',
  'auditScheduleTemplateCreatedTitle': 'Создание шаблона расписания',
  'auditScheduleTemplateUpdatedTitle': 'Изменение шаблона расписания',
  'auditScheduleTemplateDeactivatedTitle': 'Деактивация шаблона расписания',
  'auditUserUpdatedTitle': 'Изменение пользовательа',
  'auditUserUpdatedDescription': 'Администратор изменил данные пользователя.',
  'auditUserRoleChangedTitle': 'Изменение роли пользовательа',
  'auditUserRoleChangedDescription': 'Администратор изменил роль пользователя.',
  'auditUserDeactivatedTitle': 'Деактивация пользовательа',
  'auditUserDeactivatedDescription':
      'Администратор деактивировал пользователя.',
  'auditUserDeactivationBlockedTitle': 'Неудачная деактивация пользователя',
  'auditUserDeactivationBlockedDescription':
      'Деактивация пользователя была заблокирована проверкой активных связей.',
  'auditPublicMessageCreatedTitle': 'Создание новости',
  'auditPublicMessageCreatedDescription': 'Была создана публичная новость.',
  'auditPublicMessageUpdatedTitle': 'Изменение новости',
  'auditPublicMessageUpdatedDescription': 'Публичная новость была изменена.',
  'auditPublicMessageDeletedTitle': 'Удаление новости',
  'auditPublicMessageDeletedDescription': 'Публичная новость была удалена.',
  'auditProfileCompletedTitle': 'Заполнение профиля',
  'auditProfileCompletedDescription':
      'Пользователь заполнил основные данные профиля.',
  'auditProfileUpdatedTitle': 'Изменение профиля',
  'auditProfileUpdatedDescription': 'Пользователь изменил данные профиля.',
  'auditProfilePhotoUpdatedTitle': 'Изменение фото профиля',
  'auditProfilePhotoUpdatedDescription': 'Пользователь изменил фото профиля.',
  'auditProfilePhotoRemovedTitle': 'Удаление фото профиля',
  'auditProfilePhotoRemovedDescription':
      'Пользователь удалил вручную заданное фото профиля.',
  'auditPaymentStartedTitle': 'Запуск оплаты',
  'auditPaymentStartedDescription': 'Пользователь начал оплату абонемента.',
  'auditPaymentSucceededTitle': 'Успишна оплата',
  'auditPaymentSucceededDescription': 'Оплата абонемента успешно завершена.',
  'auditPaymentFailedTitle': 'Неудачная оплата',
  'auditPaymentFailedDescription':
      'Оплата абонемента не удалась или была отменена.',
  'auditMembershipUpdatedTitle': 'Изменение илинемента',
  'auditMembershipUpdatedDescription':
      'Администратор изменил абонемент пользователя.',
  'auditMembershipStatusChangedTitle': 'Изменение статуса абонемента',
  'auditMembershipStatusChangedDescription':
      'Администратор изменил статус абонемента пользователя.',
  'auditMembershipEntriesChangedTitle':
      'Изменение количества входов абонемента',
  'auditMembershipEntriesChangedDescription':
      'Администратор изменил количество оставшихся входов абонемента.',
  'auditMembershipReservationCancelledTitle':
      'Отмена зарезервированного бронирования',
  'auditMembershipReservationCancelledDescription':
      'Администратор отменил зарезервированное бронирование, привязанное к абонементу.',
  'auditMembershipAllReservationsCancelledTitle':
      'Отмена всех зарезервированных бронирований',
  'auditMembershipAllReservationsCancelledDescription':
      'Администратор отменил все зарезервированные бронирования, привязанные к абонементу.',
  'auditMembershipAssignedTitle': 'Назначение абонемента',
  'auditMembershipAssignedDescription':
      'Пользователю был вручную назначен абонемент.',
  'auditMembershipPurchasedTitle': 'Покупка абонемента',
  'auditMembershipPurchasedDescription': 'Пользователь купил абонемент.',
  'auditActionMembershipAssigned': 'Назначение абонемента',
  'auditActionMembershipPurchased': 'Покупка абонемента',
  'auditActionMembershipUpdated': 'Изменение илинемента',
  'auditActionMembershipStatusChanged': 'Изменение статуса абонемента',
  'auditActionMembershipEntriesChanged': 'Изменение входов илинемента',
  'auditActionMembershipReservationCancelled':
      'Отмена одного зарезервированного бронирования',
  'auditActionMembershipAllReservationsCancelled':
      'Отмена всех зарезервированных бронирований',
  'auditActionReservationCreated': 'Создание бронирования',
  'auditActionReservationCancelled': 'Отмена бронирования',
  'auditActionAttendanceAttended': 'Отмечено посещение',
  'auditActionAttendanceNoShow': 'Отмечено отсутствие',
  'auditActionTrainingTypeCreated': 'Создание типа занятия',
  'auditActionTrainingTypeUpdated': 'Изменение типа занятия',
  'auditActionTrainingTypeDeactivated': 'Деактивация типа тренировка',
  'auditActionTrainingSessionCreated': 'Создание тренировки',
  'auditActionTrainingSessionUpdated': 'Изменение тренировки',
  'auditActionTrainingSessionTimeChanged': 'Изменение времени тренировки',
  'auditActionTrainingSessionCancelled': 'Отмена тренировки',
  'auditActionScheduleTemplateCreated': 'Создание шаблона',
  'auditActionScheduleTemplateUpdated': 'Изменение шаблона',
  'auditActionScheduleTemplateDeactivated': 'Деактивация шаблона',
  'auditActionUserUpdated': 'Изменение пользовательа',
  'auditActionUserRoleChanged': 'Изменение роли',
  'auditActionUserDeactivationBlocked': 'Заблокированная деактивация',
  'auditActionUserDeactivated': 'Деактивация пользовательа',
  'auditActionPublicMessageCreated': 'Создание новости',
  'auditActionPublicMessageUpdated': 'Изменение новости',
  'auditActionPublicMessageDeleted': 'Удаление новости',
  'auditActionProfileCompleted': 'Заполнение профиля',
  'auditActionProfileUpdated': 'Изменение профиля',
  'auditActionProfilePhotoUpdated': 'Изменение фото профиля',
  'auditActionProfilePhotoRemoved': 'Удаление фото профиля',
  'auditActionPaymentStarted': 'Запуск оплаты',
  'auditUserEmailCompletedTitle': 'Додавання e-mail',
  'auditUserEmailCompletedDescription':
      'Пользователь добавил отсутствующий e-mail к аккаунту.',
  'currentUserShort': 'вы',
  'auditUserEmailUpdatedTitle': 'Изменение e-mail пользовательа',
  'auditUserEmailUpdatedDescription':
      'Администратор изменил контактный e-mail пользователя.',
  'auditUserReactivatedTitle': 'Активация пользовательа',
  'auditUserReactivatedDescription':
      'Администратор снова активировал пользователя.',
  'auditActionUserEmailCompleted': 'Додавання e-mail',
  'auditActionUserEmailUpdated': 'Изменение e-mail пользовательа',
  'auditActionUserReactivated': 'Активация пользовательа',
  'auditCategoryDiscounts': 'Знижки',
  'auditDiscountRequestedTitle': 'Запрос на скидку',
  'auditDiscountRequestedDescription':
      'Пользователь отправил запрос на одобрение скидки.',
  'auditDiscountApprovedTitle': 'Одобрение скидки',
  'auditDiscountApprovedDescription':
      'Администратор одобрил скидку пользователю.',
  'auditDiscountRejectedTitle': 'Отклонение скидки',
  'auditDiscountRejectedDescription':
      'Администратор отклонил запрос пользователя на скидку.',
  'auditAccountDeletionRequestedTitle': 'Запрос на удаление аккаунта',
  'auditAccountDeletionRequestedDescription':
      'Пользователь подал запрос на удаление аккаунта.',
  'auditEmailChangeRequestedTitle': 'Запрос на змину e-mail',
  'auditEmailChangeRequestedDescription':
      'Пользователь подал запрос на изменение e-mail адреса.',
  'auditEmailChangeCompletedTitle': 'Завершення изменения e-mail',
  'auditEmailChangeCompletedDescription':
      'Пользователь завершил изменение e-mail адреса.',
  'auditPasswordResetRequestedTitle': 'Запрос на восстановление пароля',
  'auditPasswordResetRequestedDescription':
      'Пользователь попросил отправить e-mail для восстановления пароля.',
  'auditActionDiscountRequested': 'Запрос на скидку',
  'auditActionDiscountApproved': 'Одобрение скидки',
  'auditActionDiscountRejected': 'Отклонение скидки',
  'auditActionAccountDeletionRequested': 'Запрос на удаление аккаунта',
  'auditActionEmailChangeRequested': 'Запрос на змину e-mail',
  'auditActionEmailChangeCompleted': 'Завершення изменения e-mail',
  'auditActionPasswordResetRequested': 'Запрос на восстановление пароля',
};

const Map<String, List<String>> appTextListsRu = {
  'shortWeekdays': ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'],
  'weekdays': [
    'Понедельник',
    'Вторник',
    'Среда',
    'Четверг',
    'Пятница',
    'Суббота',
    'Воскресенье',
  ],
};
