// Nemecké texty aplikácie.
const Map<String, String> appTextsDe = {
  'appName': 'Body Fit Club TT',
  'loading': 'Wird geladen...',
  'ok': 'OK',
  'save': 'Speichern',
  'delete': 'Löschen',
  'cancel': 'Abbrechen',
  'back': 'Zurück',
  'today': 'Heute',
  'tomorrow': 'Morgen',
  'todayLower': 'heute',
  'tomorrowLower': 'morgen',
  'minutes': 'Min.',
  'refresh': 'Aktualisieren',
  'yesterday': 'Gestern',
  'last7Days': 'Letzte 7 Tage',
  'last30Days': 'Letzte 30 Tage',
  'allTime': 'Gesamter Zeitraum',
  'close': 'Schließen',
  'reason': 'Grund',
  'unknownDate': 'Unbekanntes Datum',
  'notSet': 'Nicht festgelegt',
  'confirm': 'Bestätigen',
  'menu': 'Menü',
  'home': 'Startseite',
  'schedule': 'Zeitplan',
  'reservations': 'Reservierungen',
  'management': 'Verwaltung',
  'profile': 'Profil',
  'settings': 'Einstellungen',
  'appearance': 'Darstellung',
  'appearanceDescription':
      'Wählen Sie den hellen, dunklen oder systemabhängigen Modus.',
  'themeSystem': 'Nach Systemeinstellung',
  'themeLight': 'Heller Modus',
  'themeDark': 'Dunkler Modus',
  'menuPosition': 'Menüposition',
  'menuPositionDescription':
      'Wählen Sie, auf welcher Seite das Hauptmenü angezeigt werden soll.',
  'rightHanded': 'Rechtshänder',
  'leftHanded': 'Linkshänder',
  'menuRightPositionDescription': 'Das Menü wird oben rechts angezeigt.',
  'menuLeftPositionDescription': 'Das Menü wird oben links angezeigt.',
  'language': 'Sprache',
  'languageDescription': 'Wählen Sie die Sprache der App.',
  'languageSlovak': '🇸🇰 Slowakisch',
  'languageEnglish': '🇬🇧 Englisch',
  'languageGerman': '🇩🇪 Deutsch',
  'languageFrench': '🇫🇷 Französisch',
  'languagePolish': '🇵🇱 Polnisch',
  'languageHungarian': '🇭🇺 Ungarisch',
  'languageUkrainian': '🇺🇦 Ukrainisch',
  'languageRussian': '🇷🇺 Russisch',
  'languageSerbian': '🇷🇸 Serbisch',
  'languageCzech': '🇨🇿 Tschechisch',
  'role': 'Rolle',
  'roleUser': 'Benutzer',
  'roleTrainer': 'Trainer',
  'roleAdmin': 'Administrator',
  'roleUnknown': 'Unbekannte Rolle',
  'privacyPolicy': 'Datenschutzerklärung',
  'emailContact': 'E-Mail',
  'loginTitle': 'Anmeldung',
  'registerTitle': 'Registrierung',
  'continueWithGoogle': 'Mit Google fortfahren',
  'continueWithFacebook': 'Mit Facebook fortfahren',
  'or': 'oder',
  'email': 'E-Mail',
  'password': 'Passwort',
  'login': 'Anmelden',
  'register': 'Registrieren',
  'logout': 'Abmelden',
  'noAccountRegister': 'Noch kein Konto? Registrieren',
  'hasAccountLogin': 'Schon ein Konto? Anmelden',
  'authError': 'Anmeldefehler',
  'acceptTerms': 'Ich stimme den Geschäftsbedingungen zu',
  'acceptPrivacy': 'Ich stimme der Verarbeitung personenbezogener Daten zu',
  'termsConsentRequired':
      'Für die Registrierung müssen Sie den Geschäftsbedingungen zustimmen.',
  'privacyConsentRequired':
      'Für die Registrierung müssen Sie der Verarbeitung personenbezogener Daten zustimmen.',
  'openTerms': 'Geschäftsbedingungen öffnen',
  'openPrivacy': 'Datenschutzerklärung öffnen',
  'termsVersion': '2026-05-16',
  'privacyVersion': '2026-05-16',
  'continueWithoutAccount': 'Ohne Konto fortfahren',
  'completeEmailOrLogout':
      'Wenn Sie keine E-Mail-Adresse ergänzen möchten, können Sie ohne Konto fortfahren und sich später mit einem anderen Konto anmelden.',
  'fillEmailPassword': 'Geben Sie E-Mail und Passwort ein.',
  'invalidEmailFormat': 'Geben Sie eine gültige E-Mail-Adresse ein.',
  'passwordTooShort': 'Das Passwort muss mindestens 6 Zeichen lang sein.',
  'wrongEmailOrPassword':
      'Die eingegebene E-Mail-Adresse oder das Passwort ist falsch.',
  'userAlreadyExists':
      'Ein Benutzer mit dieser E-Mail-Adresse existiert bereits.',
  'weakPassword': 'Das eingegebene Passwort ist zu schwach.',
  'tooManyRequests': 'Zu viele Versuche. Bitte versuchen Sie es später erneut.',
  'networkError': 'Überprüfen Sie Ihre Internetverbindung.',
  'signInCancelled': 'Die Anmeldung wurde abgebrochen.',
  'facebookLoginFailed': 'Die Anmeldung über Facebook ist fehlgeschlagen.',
  'unknownAuthError':
      'Bei der Anmeldung ist ein unbekannter Fehler aufgetreten.',
  'inactiveAccount':
      'Ihr Konto ist deaktiviert. Kontaktieren Sie den Administrator.',
  'verificationEmailSent':
      'Die Registrierung war erfolgreich. Wir haben Ihnen eine Bestätigungs-E-Mail gesendet. Wenn Sie sie nicht im Posteingang sehen, prüfen Sie bitte auch den Spam-Ordner.',
  'emailNotVerified':
      'Bestätigen Sie zuerst Ihre Registrierung, indem Sie auf den Link in der E-Mail klicken.',
  'verificationEmailSentAgain':
      'Wir haben Ihnen die Bestätigungs-E-Mail erneut gesendet. Wenn Sie sie nicht im Posteingang sehen, prüfen Sie bitte auch den Spam-Ordner.',
  'forgotPassword': 'Passwort vergessen?',
  'resetPasswordTitle': 'Passwort zurücksetzen',
  'sendResetEmail': 'E-Mail senden',
  'passwordResetEmailSent':
      'Wenn ein Konto mit dieser E-Mail-Adresse existiert, haben wir eine E-Mail zum Zurücksetzen des Passworts gesendet.',
  'emailRequired': 'Geben Sie eine E-Mail-Adresse ein.',
  'emailNotProvided': 'Es wurde keine E-Mail-Adresse angegeben',
  'emailSaved': 'Die E-Mail-Adresse wurde gespeichert.',
  'emailSaveError': 'Die E-Mail-Adresse konnte nicht gespeichert werden.',
  'emailChangeVerificationSent':
      'Wir haben einen Bestätigungslink an die neue E-Mail-Adresse gesendet. Die Änderung wird nach der Bestätigung abgeschlossen.',
  'emailChangeRequestError':
      'Die Änderung der E-Mail-Adresse konnte nicht gestartet werden.',
  'emailChangeNotAvailable':
      'Die Änderung der E-Mail-Adresse ist nur für Konten verfügbar, die mit E-Mail und Passwort erstellt wurden.',
  'completeProfileTitle': 'Profil vervollständigen',
  'editProfile': 'Profil bearbeiten',
  'firstName': 'Vorname',
  'lastName': 'Nachname',
  'publicName': 'Anzeigename',
  'publicNameHint': 'Z. B. Barbora, Katka, Aďo',
  'firstNameRequired': 'Geben Sie den Vornamen ein.',
  'lastNameRequired': 'Geben Sie den Nachnamen ein.',
  'publicNameRequired': 'Geben Sie den Anzeigenamen ein.',
  'profileSaved': 'Das Profil wurde gespeichert.',
  'profileSaveError': 'Das Profil konnte nicht gespeichert werden.',
  'loggedInUser': 'Angemeldeter Benutzer',
  'completeEmailTitle': 'E-Mail-Adresse ergänzen',
  'completeEmailDescription':
      'Für die Nutzung der App benötigen wir Ihre E-Mail-Adresse. Wir verwenden sie als Kontakt-E-Mail für Ihr Konto.',
  'deleteAccountRequest': 'Kontolöschung beantragen',
  'deleteAccountRequestTitle': 'Kontolöschung',
  'deleteAccountRequestDescription':
      'Nach dem Absenden der Anfrage wird das Konto deaktiviert und eine Anmeldung ist nicht mehr möglich. Die Daten werden anschließend vom Administrator gemäß den Datenschutzregeln verarbeitet.',
  'deleteAccountReason': 'Grund der Anfrage',
  'deleteAccountConfirm':
      'Möchten Sie wirklich die Löschung des Kontos beantragen?',
  'deleteAccountRequestSent': 'Die Anfrage zur Kontolöschung wurde gesendet.',
  'deleteAccountRequestError':
      'Die Anfrage zur Kontolöschung konnte nicht gesendet werden.',
  'deleteAccountBlockedActiveReservations':
      'Das Konto kann nicht gelöscht werden, da Sie aktive Reservierungen haben.',
  'accountDeletionRequests': 'Anfragen zur Kontolöschung',
  'accountDeletionRequestsWithCount': 'Anfragen zur Kontolöschung',
  'accountDeletionRequestsLoadError':
      'Die Anfragen zur Kontolöschung konnten nicht geladen werden.',
  'noAccountDeletionRequests': 'Es sind keine wartenden Anfragen erfasst.',
  'completeAccountDeletion': 'Konto anonymisieren',
  'completeAccountDeletionTitle': 'Konto anonymisieren',
  'completeAccountDeletionQuestion':
      'Möchten Sie dieses Konto wirklich anonymisieren? Diese Aktion überschreibt die personenbezogenen Daten des Benutzers.',
  'accountDeletionCompleted': 'Das Konto wurde anonymisiert.',
  'accountDeletionCompleteError': 'Das Konto konnte nicht anonymisiert werden.',
  'requestedAt': 'Beantragt am',
  'accountDeletionRequestsWaiting': 'Anfragen warten auf Bearbeitung.',
  'changeEmail': 'E-Mail ändern',
  'changeEmailTitle': 'E-Mail ändern',
  'changeEmailDescription':
      'Geben Sie die neue E-Mail-Adresse und das aktuelle Passwort ein. Wir senden einen Bestätigungslink an die neue E-Mail-Adresse. Die Änderung wird erst nach Bestätigung des Links abgeschlossen.',
  'changeEmailProfileHint':
      'Verfügbar für Konten, die mit E-Mail und Passwort erstellt wurden.',
  'newEmail': 'Neue E-Mail',
  'currentPassword': 'Aktuelles Passwort',
  'sendVerificationEmail': 'Bestätigungs-E-Mail senden',
  'wrongCurrentPassword': 'Das aktuelle Passwort ist falsch.',
  'requiresRecentLogin':
      'Für diese Aktion melden Sie sich bitte zuerst ab und danach erneut an.',
  'changeProfilePhoto': 'Profilfoto ändern',
  'chooseFromGallery': 'Aus Galerie auswählen',
  'takePhoto': 'Foto aufnehmen',
  'removePhoto': 'Foto entfernen',
  'editPhoto': 'Foto bearbeiten',
  'cropProfilePhoto': 'Profilfoto zuschneiden',
  'profilePhotoUpdated': 'Das Profilfoto wurde gespeichert.',
  'profilePhotoUpdateError': 'Das Profilfoto konnte nicht gespeichert werden.',
  'profilePhotoRemoveError': 'Das Profilfoto konnte nicht entfernt werden.',
  'requestDiscount': 'Rabatt beantragen',
  'discountStatus': 'Rabattstatus',
  'discountStatusNone': 'Kein Rabatt',
  'discountStatusPending': 'Wartet auf Genehmigung',
  'discountStatusApproved': 'Genehmigter Rabatt',
  'discountStatusRejected': 'Abgelehnte Anfrage',
  'discountStatusExpired': 'Der Rabatt ist abgelaufen',
  'discountType': 'Rabattart',
  'discountTypeNormal': 'Normaler Benutzer',
  'discountTypeStudent': 'Student',
  'discountTypeSenior': 'Senior',
  'discountTypeZtp': 'Person mit Behinderung',
  'discountTypeIndividual': 'Individueller Rabatt',
  'discountRequestDescription':
      'Wählen Sie die Rabattart aus, die Sie beantragen möchten. Nach dem Absenden prüft der Administrator die Anfrage.',
  'discountRequestNote': 'Notiz zur Anfrage',
  'discountRequestSent': 'Die Rabatt Anfrage wurde gesendet.',
  'discountRequestError': 'Die Rabatt Anfrage konnte nicht gesendet werden.',
  'discountRequestAlreadyPending':
      'Sie haben bereits eine laufende Rabatt Anfrage.',
  'discountRequestPending': 'Die Anfrage wartet auf Genehmigung',
  'sendRequest': 'Anfrage senden',
  'discountDocument': 'Rabattnachweis',
  'discountDocumentDescription':
      'Laden Sie ein Foto des Nachweises hoch, anhand dessen der Administrator den Anspruch auf Rabatt prüfen kann.',
  'chooseDiscountDocument': 'Nachweis auswählen',
  'discountDocumentRequired':
      'Vor dem Absenden der Anfrage muss ein Nachweis beigefügt werden.',
  'discountDocumentSelected': 'Der Nachweis wurde ausgewählt',
  'takeDiscountDocumentPhoto': 'Nachweis fotografieren',
  'chooseDiscountDocumentFromGallery': 'Aus Galerie auswählen',
  'discountRequests': 'Rabatt Anfragen',
  'discountRequestsDescription':
      'Genehmigung oder Ablehnung von Rabatt Anfragen der Benutzer.',
  'discountRequestsLoadError':
      'Die Rabatt Anfragen konnten nicht geladen werden.',
  'noDiscountRequests': 'Es sind keine wartenden Rabatt Anfragen erfasst.',
  'approveDiscount': 'Rabatt genehmigen',
  'rejectDiscount': 'Anfrage ablehnen',
  'discountApproved': 'Der Rabatt wurde genehmigt.',
  'discountRejected': 'Die Rabatt Anfrage wurde abgelehnt.',
  'discountDecisionError':
      'Die Entscheidung zur Anfrage konnte nicht gespeichert werden.',
  'discountValidUntilRequired':
      'Wählen Sie das Gültigkeitsdatum des Rabatts aus.',
  'discountAdminNote': 'Administratornotiz',
  'selectDiscountValidUntil': 'Gültigkeit des Rabatts auswählen',
  'discountDocumentPreview': 'Vorschau des Nachweises',
  'todayReservations': 'Heutige Reservierungen',
  'noTodayReservations': 'Sie haben heute keine Trainingseinheit reserviert.',
  'nearestTraining': 'Nächste Trainingseinheit',
  'nearestTrainings': 'Nächste Trainingseinheiten',
  'noNearestTraining': 'Es ist keine nächste Trainingseinheit geplant.',
  'todaysTrainings': 'Heutige Trainingseinheiten',
  'noTodaysTrainings': 'Für heute sind keine Trainingseinheiten geplant.',
  'myMemberships': 'Meine Karten',
  'activeMembershipsCount': 'Aktive Karten',
  'availableEntriesSummary': 'Verfügbare Eintritte',
  'reservedEntriesSummary': 'Reservierte Eintritte',
  'dailyMembershipsSummary': 'Tageskarten',
  'tapToShowQrCode': 'Tippen, um den QR-Code anzuzeigen.',
  'nearestReservations': 'Nächste Reservierungen',
  'noNearestReservations': 'Sie haben keine nächsten Reservierungen.',
  'qrShort': 'QR',
  'membershipStatus': 'Kartenstatus',
  'remainingEntries': 'Verbleibende Eintritte',
  'upcomingTraining': 'Nächste heutige Trainingseinheit',
  'schedulePlaceholder': 'Hier wird der Trainingsplan angezeigt.',
  'reservationsPlaceholder': 'Hier werden Reservierungen angezeigt.',
  'newsPlaceholder':
      'Hier werden Neuigkeiten und Nachrichten von Trainern angezeigt.',
  'aboutApp': 'Über die App',
  'aboutUs': 'Über uns',
  'aboutAppDescription':
      'Die App Body Fit Club TT dient zur Verwaltung von Trainingseinheiten, Reservierungen, Karten und der Kommunikation zwischen Fitnesscenter und Benutzern.',
  'aboutUsDescription':
      'Body Fit Club ist ein Fitnesscenter in Trnava mit Fokus auf Gruppen- und Einzeltrainings, Bewegung, gesunden Lebensstil und persönlichen Zugang zu Kunden.',
  'bodyFitClubWebsite': 'https://bodyfitclub.sk/',
  'openWebsite': 'Website öffnen',
  'businessTerms': 'Geschäftsbedingungen',
  'legalDocumentsInfo':
      'Geschäftsbedingungen und Informationen zum Datenschutz werden auf der Website von Body Fit Club verfügbar sein.',
  'contacts': 'Kontakte',
  'billingDetails': 'Rechnungsdaten',
  'address': 'Adresse',
  'phone': 'Telefon',
  'website': 'Website',
  'socialNetworks': 'Soziale Netzwerke',
  'openMap': 'Karte öffnen',
  'openFacebook': 'Facebook öffnen',
  'openInstagram': 'Instagram öffnen',
  'multisport': 'MultiSport',
  'multisportInfo':
      'Wir akzeptieren die MultiSport-Karte gemäß den aktuellen Betriebsbedingungen.',
  'bodyFitClubCompanyName': 'BODYFIT CLUB s.r.o.',
  'bodyFitClubOperationAddress': 'V Jame 24, Trnava',
  'bodyFitClubBillingAddress': 'J. G. Tajovského 18, 917 08 Trnava',
  'bodyFitClubPhonePrimary': '+421 902 860 008',
  'bodyFitClubPhoneSecondary': '+421 903 946 895',
  'bodyFitClubEmail': 'bodyfitclubtt@gmail.com',
  'bodyFitClubIco': '48074128',
  'ico': 'Ident.-Nr.: ',
  'companySeat': 'Sitz',
  'operation': 'Betrieb',
  'bodyFitClubFacebookUrl': 'https://www.facebook.com/bodyfitclub.sk',
  'bodyFitClubInstagramUrl': 'https://www.instagram.com/bodyfitclub.tt/',
  'bodyFitClubMapUrl':
      'https://www.google.com/maps/search/?api=1&query=V%20Jame%206641%2F24%2C%20917%2001%20Trnava',
  'bodyFitClubMultiSportUrl':
      'https://multi-sport.sk/aktivity/partner/bodyfit-club/',
  'multisportInfo2':
      'Body Fit Club ist Partner des Programms MultiSport. Die Akzeptanz der MultiSport-Karte richtet sich nach den aktuellen Betriebsbedingungen.',
  'bodyFitClubWebsiteLabel': 'www.bodyfitclub.sk',
  'dic': 'Steuer-ID: ',
  'bodyFitClubDic': '2120035445',
  'notVatPayer': 'Das Unternehmen ist kein Mehrwertsteuerzahler',
  'legalDocuments': 'Rechtliche Dokumente',
  'priceList': 'Preisliste',
  'priceListAudience': 'Für',
  'priceListAudienceNormal': 'normale Benutzer',
  'priceListAudienceDiscount': 'Benutzer mit Rabatt',
  'priceListAudienceAll': 'alle',
  'price': 'Preis',
  'singleEntries': 'Einzeleintritte',
  'priceListMemberships': 'Karten',
  'chooseEntry': 'Eintritt auswählen',
  'noAvailablePlans': 'Derzeit sind keine Kaufoptionen verfügbar.',
  'news': 'Neuigkeiten',
  'noPublicMessages': 'Es gibt noch keine Nachrichten.',
  'writeMessage': 'Nachricht schreiben',
  'writeMessageShort': 'Schreiben',
  'editMessage': 'Nachricht bearbeiten',
  'deleteMessage': 'Nachricht löschen',
  'deleteMessageQuestion': 'Möchten Sie diese Nachricht wirklich löschen?',
  'messageText': 'Nachrichtentext',
  'messageHint': 'Nachricht schreiben...',
  'sendMessage': 'Senden',
  'updateMessage': 'Änderungen speichern',
  'messageSaved': 'Die Nachricht wurde gespeichert.',
  'messageDeleted': 'Die Nachricht wurde gelöscht.',
  'messageSaveError': 'Die Nachricht konnte nicht gespeichert werden.',
  'messageDeleteError': 'Die Nachricht konnte nicht gelöscht werden.',
  'editedBy': 'Bearbeitet',
  'editedByAdmin': 'Vom Administrator bearbeitet',
  'editedByTrainer': 'Vom Trainer bearbeitet',
  'userFallback': 'Benutzer',
  'noTrainings': 'Derzeit sind keine Trainingseinheiten verfügbar.',
  'noTrainingsForSelectedDay':
      'Für diesen Tag sind keine Trainingseinheiten geplant.',
  'trainer': 'Trainer',
  'freeSpots': 'Freie Plätze',
  'reserve': 'Reservieren',
  'reserved': 'Reserviert',
  'fullCapacity': 'Ausgebucht',
  'trainingsLoadError': 'Der Trainingsplan konnte nicht geladen werden.',
  'unknownTraining': 'Unbekannte Trainingseinheit',
  'unknownTrainer': 'Unbekannter Trainer',
  'unknownUser': 'Unbekannter Benutzer',
  'trainingSessionFinished': 'Abgeschlossen',
  'trainingSessionTooFarInFuture':
      'Der Termin liegt zu weit in der Zukunft. Manuell können Sie eine Trainingseinheit nur im im Zeitplan angezeigten Zeitraum hinzufügen.',
  'managementDescription':
      'Hier können Sie Trainingstermine, Anwesenheit, Karten und Benutzer verwalten.',
  'scheduleManagement': 'Zeitplanverwaltung',
  'scheduleManagementDescription':
      'Verwaltung von Trainingstypen, Zeitplanvorlagen und konkreten Trainingsterminen.',
  'attendanceManagement': 'Anwesenheitsverwaltung',
  'usersManagement': 'Benutzerverwaltung',
  'usersManagementComingSoon': 'Die Benutzerverwaltung wird später ergänzt.',
  'scheduleTemplatesManagement': 'Verwaltung der Zeitplanvorlagen',
  'reactivateUser': 'Benutzer aktivieren',
  'reactivateUserQuestion':
      'Möchten Sie diesen Benutzer wirklich wieder aktivieren?',
  'userReactivated': 'Der Benutzer wurde wieder aktiviert.',
  'trainingTypesManagement': 'Verwaltung der Trainingstypen',
  'addTrainingType': 'Trainingstyp hinzufügen',
  'editTrainingType': 'Trainingstyp bearbeiten',
  'deleteTrainingType': 'Trainingstyp löschen',
  'trainingType': 'Trainingstyp',
  'selectTrainingType': 'Trainingstyp auswählen',
  'trainingName': 'Name der Trainingseinheit',
  'description': 'Beschreibung',
  'defaultDuration': 'Standarddauer',
  'defaultCapacity': 'Standardkapazität',
  'noTrainingTypes': 'Derzeit sind keine Trainingstypen erstellt.',
  'trainingTypesLoadError': 'Die Trainingstypen konnten nicht geladen werden.',
  'trainingTypeCreated': 'Der Trainingstyp wurde erstellt.',
  'trainingTypeUpdated': 'Der Trainingstyp wurde aktualisiert.',
  'trainingTypeDeleted': 'Der Trainingstyp wurde gelöscht.',
  'trainingTypeDeleteQuestion':
      'Möchten Sie diesen Trainingstyp wirklich löschen? Er wird bei neuen Terminen nicht mehr angeboten.',
  'trainingTypeAlreadyExists':
      'Ein Trainingstyp mit diesem Namen existiert bereits.',
  'trainingTypeUsedByTemplate':
      'Der Trainingstyp kann nicht gelöscht werden, weil er in einer aktiven Zeitplanvorlage verwendet wird.',
  'trainingTypeUsedBySession':
      'Der Trainingstyp kann nicht gelöscht werden, weil er in einem zukünftigen Trainingstermin verwendet wird.',
  'addTrainingSession': 'Trainingstermin hinzufügen',
  'editTrainingSession': 'Details der Trainingseinheit bearbeiten',
  'trainingSessionCreated': 'Der Trainingstermin wurde erstellt.',
  'trainingSessionUpdated': 'Der Trainingstermin wurde aktualisiert.',
  'updateTrainingSessionError':
      'Der Trainingstermin konnte nicht aktualisiert werden.',
  'trainingSessionInPast':
      'Der Trainingstermin darf nicht in der Vergangenheit liegen.',
  'trainingSessionOverlap':
      'Zu dieser Zeit ist bereits eine andere Trainingseinheit geplant.',
  'capacityLowerThanReservations':
      'Die Kapazität darf nicht niedriger sein als die Anzahl bestehender Reservierungen.',
  'cancelTrainingSession': 'Termin absagen',
  'cancelTrainingSessionTitle': 'Trainingstermin absagen',
  'cancelTrainingSessionQuestion':
      'Möchten Sie diesen Trainingstermin wirklich absagen? Aktive Reservierungen werden storniert und reservierte Eintritte werden den Benutzern freigegeben. Wenn der Eintritt bereits verwendet wurde, wird er dem Benutzer zurückgegeben.',
  'cancelTrainingSessionConfirm': 'Termin absagen',
  'trainingSessionCancelled': 'Der Trainingstermin wurde abgesagt.',
  'cancelTrainingSessionError':
      'Der Trainingstermin konnte nicht abgesagt werden.',
  'trainerCanCancelOnlyOwnSession':
      'Der Trainer kann nur den eigenen Termin absagen.',
  'trainerCannotCancelStartedSession':
      'Der Trainer kann keinen Termin absagen, der bereits begonnen hat oder abgeschlossen wurde.',
  'date': 'Datum',
  'startTime': 'Beginn',
  'duration': 'Dauer',
  'capacity': 'Kapazität',
  'selectDate': 'Datum auswählen',
  'selectTrainer': 'Trainer auswählen',
  'trainersLoadError': 'Trainer konnten nicht geladen werden.',
  'fillAllFields': 'Füllen Sie alle Pflichtangaben aus.',
  'invalidCapacity': 'Die Kapazität muss größer als 0 sein.',
  'invalidDuration': 'Die Dauer muss größer als 0 sein.',
  'saveError': 'Speichern fehlgeschlagen.',
  'addScheduleTemplate': 'Zeitplanvorlage hinzufügen',
  'editScheduleTemplate': 'Zeitplanvorlage bearbeiten',
  'deleteScheduleTemplate': 'Zeitplanvorlage löschen',
  'noScheduleTemplates': 'Derzeit sind keine Zeitplanvorlagen erstellt.',
  'weekday': 'Wochentag',
  'selectWeekday': 'Wochentag auswählen',
  'scheduleTemplateCreated': 'Die Zeitplanvorlage wurde erstellt.',
  'scheduleTemplateUpdated': 'Die Zeitplanvorlage wurde aktualisiert.',
  'scheduleTemplateDeleted': 'Die Zeitplanvorlage wurde gelöscht.',
  'scheduleTemplateDeleteQuestion':
      'Möchten Sie diese Zeitplanvorlage wirklich löschen? Sie wird bei der Generierung neuer Termine nicht mehr verwendet.',
  'scheduleTemplateAlreadyExists':
      'Eine solche Zeitplanvorlage existiert bereits.',
  'scheduleTemplateLoadError':
      'Die Zeitplanvorlagen konnten nicht geladen werden.',
  'scheduleTemplateOverlap':
      'Zu dieser Zeit existiert bereits eine andere Zeitplanvorlage.',
  'capacityLabel': 'Kapazität',
  'reservationCreated': 'Die Reservierung wurde erstellt.',
  'reservationAlreadyExists':
      'Sie haben für diese Trainingseinheit bereits eine Reservierung erstellt.',
  'reservationTrainingFull': 'Diese Trainingseinheit ist bereits ausgebucht.',
  'reservationTrainingNotAvailable':
      'Diese Trainingseinheit ist nicht mehr zur Reservierung verfügbar.',
  'reservationTrainingAlreadyStarted':
      'Für diese Trainingseinheit kann keine Reservierung mehr erstellt werden.',
  'reservationError': 'Die Reservierung konnte nicht erstellt werden.',
  'myReservations': 'Meine Reservierungen',
  'noReservations': 'Sie haben derzeit keine Reservierungen.',
  'cancelReservation': 'Reservierung stornieren',
  'cancelReservationTitle': 'Reservierung stornieren',
  'cancelReservationQuestion':
      'Möchten Sie diese Reservierung wirklich stornieren?',
  'reservationCancelled': 'Die Reservierung wurde storniert.',
  'reservationCancelError': 'Die Reservierung konnte nicht storniert werden.',
  'reservationsLoadError': 'Die Reservierungen konnten nicht geladen werden.',
  'cancelReservations': 'Reservierungen stornieren',
  'cancelReservationsBeforeDeactivation':
      'Vor der Deaktivierung oder Stornierung der Karte stornieren Sie zuerst die reservierten Reservierungen.',
  'cancelReservationForMembership': 'Diese Reservierung stornieren',
  'cancelReservationForMembershipQuestion':
      'Möchten Sie diese mit der Karte verbundene Reservierung wirklich stornieren? Der reservierte Eintritt wird freigegeben.',
  'reservationForMembershipCancelled':
      'Die Reservierung wurde storniert und der reservierte Eintritt wurde freigegeben.',
  'noReservationsForTrainingHistory':
      'Für diese Trainingseinheit gibt es keine Reservierungen.',
  'reservationQrCode': 'QR-Code der Reservierung',
  'memberships': 'Karten',
  'assignMembership': 'Karte zuweisen',
  'selectUser': 'Benutzer auswählen',
  'selectMembershipPlan': 'Kartentyp auswählen',
  'membershipPlansLoadError': 'Die Kartentypen konnten nicht geladen werden.',
  'membershipAssigned': 'Die Karte wurde zugewiesen.',
  'membershipAssignError': 'Die Karte konnte nicht zugewiesen werden.',
  'membershipPlan': 'Kartentyp',
  'client': 'Benutzer',
  'buyMembership': 'Karte kaufen',
  'buySingleEntry': 'Einzeleintritt kaufen',
  'chooseMembership': 'Karte auswählen',
  'payment': 'Zahlung',
  'pay': 'Bezahlen',
  'paymentSuccessful': 'Zahlung erfolgreich.',
  'paymentFailed': 'Zahlung fehlgeschlagen.',
  'activeMembership': 'Aktive Karte',
  'noActiveMembership': 'Sie haben keine aktive Karte.',
  'validUntil': 'Gültig bis',
  'membershipLoadError': 'Die Karte konnte nicht geladen werden.',
  'noAvailableEntries':
      'Sie haben keinen verfügbaren Eintritt für eine Reservierung.',
  'noUpcomingTraining': 'Sie haben heute keine Trainingseinheit reserviert.',
  'membershipsManagement': 'Kartenverwaltung',
  'membershipDetail': 'Kartendetail',
  'noMemberships': 'Derzeit sind keine Karten verfügbar.',
  'status': 'Status',
  'validFrom': 'Gültig ab',
  'entriesTotal': 'Gesamtzahl der Eintritte',
  'entriesRemaining': 'Verbleibende Eintritte',
  'entriesReserved': 'In Reservierungen reservierte Eintritte',
  'entriesAvailable': 'Verfügbare Eintritte',
  'adminMembershipEdit': 'Administratorbearbeitung',
  'membershipStatusActive': 'Aktiv',
  'membershipStatusInactive': 'Inaktiv',
  'membershipStatusCancelled': 'Storniert',
  'membershipStatusExpired': 'Abgelaufen',
  'membershipStatusUsedUp': 'Aufgebraucht',
  'membershipUpdated': 'Die Karte wurde aktualisiert.',
  'membershipUpdateError': 'Die Karte konnte nicht aktualisiert werden.',
  'invalidRemainingEntries':
      'Geben Sie eine gültige Anzahl verbleibender Eintritte ein.',
  'allocatedReservations': 'Reservierte Reservierungen',
  'cancelAllocatedReservations': 'Reservierte Reservierungen stornieren',
  'cancelAllocatedReservationsQuestion':
      'Möchten Sie die aktiven Reservierungen, die mit dieser Karte verbunden sind, wirklich stornieren? Reservierte Eintritte werden freigegeben.',
  'cancelAllReservations': 'Alle Reservierungen stornieren',
  'cancelAllocatedReservationsError':
      'Die reservierten Reservierungen konnten nicht storniert werden.',
  'usedEntries': 'Verwendete Eintritte',
  'noAllocatedReservations':
      'Für diese Karte sind derzeit keine Reservierungen reserviert.',
  'noUsedEntries': 'Aus dieser Karte wurde noch kein Eintritt verwendet.',
  'membershipUsageLoadError':
      'Die Historie der Karte konnte nicht geladen werden.',
  'searchMemberships': 'Nach Benutzer oder Karte suchen',
  'allMembershipStatuses': 'Alle Status',
  'membershipStatusNotYetValid': 'Noch nicht gültig',
  'membershipStatusUsable': 'Aktiv',
  'invalidRemainingEntriesHigherThanTotal':
      'Verbleibende Eintritte dürfen nicht höher sein als die Gesamtzahl der Eintritte.',
  'invalidRemainingEntriesLowerThanReserved':
      'Verbleibende Eintritte dürfen nicht niedriger sein als die Anzahl reservierter Eintritte.',
  'membershipPrefix': 'Karte',
  'statusPrefix': 'Status',
  'attendance': 'Anwesenheit',
  'attendanceLoadError': 'Die Anwesenheit konnte nicht geladen werden.',
  'noActiveReservationsForAttendance':
      'Derzeit gibt es keine aktiven Reservierungen zum Markieren der Anwesenheit.',
  'attended': 'Anwesend',
  'noShow': 'Nicht erschienen',
  'markAttendedTitle': 'Anwesenheit markieren',
  'markNoShowTitle': 'Abwesenheit markieren',
  'markAttendedQuestion':
      'Möchten Sie den Benutzer wirklich als anwesend markieren?',
  'markNoShowQuestion':
      'Möchten Sie den Benutzer wirklich als abwesend markieren?',
  'attendanceMarked': 'Die Anwesenheit wurde gespeichert.',
  'attendanceMarkError': 'Die Anwesenheit konnte nicht gespeichert werden.',
  'attendedStatus': 'Anwesend',
  'noShowStatus': 'Nicht erschienen',
  'attendedCountLabel': 'Anwesend',
  'noShowCountLabel': 'Nicht erschienen',
  'attendanceActionDone': 'Die Änderung der Anwesenheit wurde gespeichert.',
  'attendanceActionError':
      'Die Änderung der Anwesenheit konnte nicht gespeichert werden.',
  'showQrCode': 'QR-Code',
  'showQrToTrainer':
      'Zeigen Sie diesen QR-Code dem Trainer bei der Ankunft zur Trainingseinheit.',
  'scanQrCode': 'QR-Code scannen',
  'scanQrCodes': 'QR-Codes scannen',
  'scanQrCodeHint':
      'Richten Sie die Kamera auf den QR-Code der Reservierung des Benutzers.',
  'invalidQrCode': 'Ungültiger QR-Code der Reservierung.',
  'qrCodeScanned': 'Der QR-Code wurde gescannt.',
  'qrScanSuccessful':
      'Der QR-Code wurde gescannt. Sie können den nächsten Benutzer scannen.',
  'trainerQrScanTooEarly':
      'Der QR-Code kann frühestens 30 Minuten vor Beginn der Trainingseinheit gescannt werden.',
  'trainingHistory': 'Trainingshistorie',
  'trainingHistoryDetail': 'Trainingsdetail',
  'trainingHistoryLoadError':
      'Die Trainingshistorie konnte nicht geladen werden.',
  'trainingHistoryReservationsLoadError':
      'Die Teilnahme an der Trainingseinheit konnte nicht geladen werden.',
  'noTrainingHistoryInSelectedPeriod':
      'Im ausgewählten Zeitraum gibt es keine Trainingseinheiten.',
  'fromDatePrefix': 'Von',
  'toDatePrefix': 'Bis',
  'planned': 'Geplant',
  'cancelled': 'Storniert',
  'finished': 'Abgeschlossen',
  'reservedStatus': 'Reserviert',
  'reservedCountLabel': 'Reserviert',
  'cancelledCountLabel': 'Storniert',
  'markedAtPrefix': 'Markiert am',
  'markAsAttended': 'Als anwesend markieren',
  'markAsNoShow': 'Als nicht erschienen markieren',
  'revertAttendance': 'Markierte Anwesenheit zurücknehmen',
  'revertNoShow': 'Markierte Abwesenheit zurücknehmen',
  'markAsAttendedQuestion':
      'Möchten Sie den Benutzer wirklich als anwesend markieren? Ein Eintritt aus der Karte wird verwendet.',
  'markAsNoShowQuestion':
      'Möchten Sie den Benutzer wirklich als abwesend markieren? Ein Eintritt aus der Karte wird verwendet.',
  'revertAttendanceQuestion':
      'Möchten Sie die markierte Anwesenheit wirklich zurücknehmen? Der verwendete Eintritt wird wieder auf die Karte zurückgebucht.',
  'revertNoShowQuestion':
      'Möchten Sie die markierte Abwesenheit wirklich zurücknehmen? Der verwendete Eintritt wird wieder auf die Karte zurückgebucht.',
  'addTrainingAttendance': 'Teilnehmer hinzufügen',
  'selectAttendanceUser': 'Benutzer auswählen',
  'selectAttendanceMembership': 'Karte auswählen',
  'noUsersForAttendance': 'Es wurden keine aktiven Benutzer gefunden.',
  'noUsableMembershipsForAttendance':
      'Der Benutzer hat keine verwendbare Karte für diese Trainingseinheit.',
  'addTrainingAttendanceQuestion':
      'Möchten Sie die Teilnahme dieses Benutzers an dieser Trainingseinheit nachträglich hinzufügen? Ein Eintritt aus der Karte wird verwendet.',
  'trainingAttendanceAdded':
      'Der Teilnehmer wurde zur Trainingseinheit hinzugefügt.',
  'trainingAttendanceAddError':
      'Der Teilnehmer konnte nicht hinzugefügt werden.',
  'userAlreadyHasReservationForTraining':
      'Der Benutzer hat bereits einen Eintrag für diese Trainingseinheit.',
  'usersLoadError': 'Benutzer konnten nicht geladen werden.',
  'allRoles': 'Alle Rollen',
  'searchUsers': 'Benutzer suchen',
  'noUsersFound': 'Es wurden keine Benutzer gefunden.',
  'editUser': 'Benutzer bearbeiten',
  'userUpdated': 'Der Benutzer wurde aktualisiert.',
  'userUpdateError': 'Der Benutzer konnte nicht aktualisiert werden.',
  'cannotChangeOwnRole': 'Sie können Ihre eigene Rolle nicht ändern.',
  'changeRoleWarning':
      'Bei einer Änderung der Benutzerrolle können sich seine Berechtigungen in der App ändern.',
  'deactivateUser': 'Benutzer deaktivieren',
  'deactivationReason': 'Grund der Deaktivierung',
  'userDeactivated': 'Der Benutzer wurde deaktiviert.',
  'deactivateUserQuestion':
      'Möchten Sie diesen Benutzer wirklich deaktivieren? Er kann in der App-Verwaltung nicht weiter verwendet werden.',
  'cannotDeactivateYourself':
      'Sie können Ihr eigenes Konto nicht deaktivieren.',
  'userUsedByTemplate':
      'Der Benutzer kann nicht deaktiviert oder auf normalen Benutzer geändert werden, weil er in einer aktiven Zeitplanvorlage zugewiesen ist.',
  'userUsedByFutureSession':
      'Der Benutzer kann nicht deaktiviert oder auf normalen Benutzer geändert werden, weil er einer zukünftigen Trainingseinheit zugewiesen ist.',
  'userHasActiveReservations':
      'Der Benutzer kann nicht deaktiviert werden, weil er aktive Reservierungen hat.',
  'userHasActiveMemberships':
      'Der Benutzer kann nicht deaktiviert werden, weil er aktive Karten hat.',
  'inactiveUser': 'Inaktiver Benutzer',
  'userCannotBeDeactivated': 'Der Benutzer kann nicht deaktiviert werden',
  'userCannotBeDeactivatedDescription':
      'Vor der Deaktivierung müssen zuerst seine aktiven Reservierungen oder Karten geklärt werden.',
  'userHasBlockingItems': 'Der Benutzer hat:',
  'activeReservationsCount': 'Aktive Reservierungen',
  'showMemberships': 'Karten anzeigen',
  'auditLogs': 'Aktionshistorie',
  'auditLogsDescription': 'Übersicht wichtiger Aktionen in der App.',
  'auditLogsLoadError': 'Die Aktionshistorie konnte nicht geladen werden.',
  'noAuditLogs': 'Es wurden keine Aktionen gefunden.',
  'searchAuditLogs': 'Nach Benutzer, E-Mail oder Beschreibung suchen',
  'auditCategory': 'Kategorie',
  'auditAction': 'Aktion',
  'auditActor': 'Ausgeführt von',
  'auditActorRole': 'Rolle des Ausführenden',
  'auditPeriod': 'Zeitraum',
  'auditAllCategories': 'Alle Kategorien',
  'auditCategoryMemberships': 'Karten',
  'auditCategoryReservations': 'Reservierungen',
  'auditCategoryAttendance': 'Anwesenheit',
  'auditCategoryUsers': 'Benutzer',
  'auditCategorySchedule': 'Zeitplan',
  'auditCategoryMessages': 'Nachrichten',
  'auditCategoryPayments': 'Zahlungen',
  'auditCategoryProfile': 'Profil',
  'auditAllActions': 'Alle Aktionen',
  'auditActionCreated': 'Erstellung',
  'auditActionUpdated': 'Bearbeitung',
  'auditActionCancelled': 'Stornierung',
  'auditActionDeactivated': 'Deaktivierung',
  'auditActionActivated': 'Aktivierung',
  'auditActionAssigned': 'Zuweisung',
  'auditActionPurchased': 'Kauf',
  'auditActionPaymentSucceeded': 'Zahlung erfolgreich',
  'auditActionPaymentFailed': 'Zahlung fehlgeschlagen',
  'auditActionAttendanceMarked': 'Anwesenheit',
  'auditActionQrChecked': 'QR-Kontrolle',
  'auditAllActorRoles': 'Alle Rollen',
  'auditReservationCreatedTitle': 'Reservierung erstellt',
  'auditReservationCreatedDescription':
      'Der Benutzer hat eine Reservierung für eine Trainingseinheit erstellt.',
  'auditReservationCancelledTitle': 'Reservierung storniert',
  'auditReservationCancelledDescription':
      'Die Reservierung des Benutzers wurde storniert.',
  'auditAttendanceAttendedTitle': 'Anwesenheit markiert',
  'auditAttendanceAttendedDescription':
      'Der Benutzer wurde als anwesend bei der Trainingseinheit markiert.',
  'auditAttendanceNoShowTitle': 'Abwesenheit markiert',
  'auditAttendanceNoShowDescription':
      'Der Benutzer wurde als abwesend bei der Trainingseinheit markiert.',
  'auditTrainingTypeCreatedTitle': 'Trainingstyp erstellt',
  'auditTrainingTypeUpdatedTitle': 'Trainingstyp aktualisiert',
  'auditTrainingTypeDeactivatedTitle': 'Trainingstyp deaktiviert',
  'auditTrainingSessionCreatedTitle': 'Termin erstellt',
  'auditTrainingSessionUpdatedTitle': 'Termin aktualisiert',
  'auditTrainingSessionTimeChangedTitle': 'Terminzeit geändert',
  'auditTrainingSessionCancelledTitle': 'Termin abgesagt',
  'auditScheduleTemplateCreatedTitle': 'Zeitplanvorlage erstellt',
  'auditScheduleTemplateUpdatedTitle': 'Zeitplanvorlage aktualisiert',
  'auditScheduleTemplateDeactivatedTitle': 'Zeitplanvorlage deaktiviert',
  'auditUserUpdatedTitle': 'Benutzer aktualisiert',
  'auditUserUpdatedDescription':
      'Der Administrator hat die Benutzerdaten aktualisiert.',
  'auditUserRoleChangedTitle': 'Benutzerrolle geändert',
  'auditUserRoleChangedDescription':
      'Der Administrator hat die Rolle des Benutzers geändert.',
  'auditUserDeactivatedTitle': 'Benutzer deaktiviert',
  'auditUserDeactivatedDescription':
      'Der Administrator hat den Benutzer deaktiviert.',
  'auditUserDeactivationBlockedTitle': 'Benutzerdeaktivierung fehlgeschlagen',
  'auditUserDeactivationBlockedDescription':
      'Die Deaktivierung des Benutzers wurde durch die Kontrolle aktiver Verknüpfungen blockiert.',
  'auditPublicMessageCreatedTitle': 'Neuigkeit erstellt',
  'auditPublicMessageCreatedDescription':
      'Eine öffentliche Neuigkeit wurde erstellt.',
  'auditPublicMessageUpdatedTitle': 'Neuigkeit aktualisiert',
  'auditPublicMessageUpdatedDescription':
      'Eine öffentliche Neuigkeit wurde aktualisiert.',
  'auditPublicMessageDeletedTitle': 'Neuigkeit gelöscht',
  'auditPublicMessageDeletedDescription':
      'Die öffentliche Neuigkeit wurde gelöscht.',
  'auditProfileCompletedTitle': 'Profil vervollständigt',
  'auditProfileCompletedDescription':
      'Der Benutzer hat grundlegende Profildaten ergänzt.',
  'auditProfileUpdatedTitle': 'Profil aktualisiert',
  'auditProfileUpdatedDescription':
      'Der Benutzer hat Profildaten aktualisiert.',
  'auditProfilePhotoUpdatedTitle': 'Profilfoto aktualisiert',
  'auditProfilePhotoUpdatedDescription':
      'Der Benutzer hat das Profilfoto aktualisiert.',
  'auditProfilePhotoRemovedTitle': 'Profilfoto entfernt',
  'auditProfilePhotoRemovedDescription':
      'Der Benutzer hat das manuell eingestellte Profilfoto entfernt.',
  'auditPaymentStartedTitle': 'Zahlung gestartet',
  'auditPaymentStartedDescription':
      'Der Benutzer hat die Zahlung für eine Karte gestartet.',
  'auditPaymentSucceededTitle': 'Zahlung erfolgreich',
  'auditPaymentSucceededDescription':
      'Die Zahlung für die Karte wurde erfolgreich abgeschlossen.',
  'auditPaymentFailedTitle': 'Zahlung fehlgeschlagen',
  'auditPaymentFailedDescription':
      'Die Zahlung für die Karte ist fehlgeschlagen oder wurde abgebrochen.',
  'auditMembershipUpdatedTitle': 'Karte aktualisiert',
  'auditMembershipUpdatedDescription':
      'Der Administrator hat die Karte des Benutzers aktualisiert.',
  'auditMembershipStatusChangedTitle': 'Kartenstatus geändert',
  'auditMembershipStatusChangedDescription':
      'Der Administrator hat den Status der Karte des Benutzers geändert.',
  'auditMembershipEntriesChangedTitle': 'Anzahl der Karteneintritte geändert',
  'auditMembershipEntriesChangedDescription':
      'Der Administrator hat die Anzahl der verbleibenden Eintritte auf der Karte geändert.',
  'auditMembershipReservationCancelledTitle':
      'Reservierte Reservierung storniert',
  'auditMembershipReservationCancelledDescription':
      'Der Administrator hat eine mit der Karte verbundene reservierte Reservierung storniert.',
  'auditMembershipAllReservationsCancelledTitle':
      'Alle reservierten Reservierungen storniert',
  'auditMembershipAllReservationsCancelledDescription':
      'Der Administrator hat alle mit der Karte verbundenen reservierten Reservierungen storniert.',
  'auditMembershipAssignedTitle': 'Karte zugewiesen',
  'auditMembershipAssignedDescription':
      'Dem Benutzer wurde manuell eine Karte zugewiesen.',
  'auditMembershipPurchasedTitle': 'Kartenkauf',
  'auditMembershipPurchasedDescription': 'Der Benutzer hat eine Karte gekauft.',
  'auditActionMembershipAssigned': 'Karte zugewiesen',
  'auditActionMembershipPurchased': 'Karte gekauft',
  'auditActionMembershipUpdated': 'Karte aktualisiert',
  'auditActionMembershipStatusChanged': 'Kartenstatus geändert',
  'auditActionMembershipEntriesChanged': 'Karteneintritte geändert',
  'auditActionMembershipReservationCancelled':
      'Eine reservierte Reservierung storniert',
  'auditActionMembershipAllReservationsCancelled':
      'Alle reservierten Reservierungen storniert',
  'auditActionReservationCreated': 'Reservierung erstellt',
  'auditActionReservationCancelled': 'Reservierung storniert',
  'auditActionAttendanceAttended': 'Anwesenheit markiert',
  'auditActionAttendanceNoShow': 'Abwesenheit markiert',
  'auditActionTrainingTypeCreated': 'Trainingstyp erstellt',
  'auditActionTrainingTypeUpdated': 'Trainingstyp aktualisiert',
  'auditActionTrainingTypeDeactivated': 'Trainingstyp deaktiviert',
  'auditActionTrainingSessionCreated': 'Termin erstellt',
  'auditActionTrainingSessionUpdated': 'Termin aktualisiert',
  'auditActionTrainingSessionTimeChanged': 'Terminzeit geändert',
  'auditActionTrainingSessionCancelled': 'Termin abgesagt',
  'auditActionScheduleTemplateCreated': 'Vorlage erstellt',
  'auditActionScheduleTemplateUpdated': 'Vorlage aktualisiert',
  'auditActionScheduleTemplateDeactivated': 'Vorlage deaktiviert',
  'auditActionUserUpdated': 'Benutzer aktualisiert',
  'auditActionUserRoleChanged': 'Rolle geändert',
  'auditActionUserDeactivationBlocked': 'Deaktivierung blockiert',
  'auditActionUserDeactivated': 'Benutzer deaktiviert',
  'auditActionPublicMessageCreated': 'Neuigkeit erstellt',
  'auditActionPublicMessageUpdated': 'Neuigkeit aktualisiert',
  'auditActionPublicMessageDeleted': 'Neuigkeit gelöscht',
  'auditActionProfileCompleted': 'Profil vervollständigt',
  'auditActionProfileUpdated': 'Profil aktualisiert',
  'auditActionProfilePhotoUpdated': 'Profilfoto aktualisiert',
  'auditActionProfilePhotoRemoved': 'Profilfoto entfernt',
  'auditActionPaymentStarted': 'Zahlung gestartet',
  'auditUserEmailCompletedTitle': 'E-Mail ergänzt',
  'auditUserEmailCompletedDescription':
      'Der Benutzer hat die fehlende E-Mail-Adresse zum Konto ergänzt.',
  'currentUserShort': 'Sie',
  'auditUserEmailUpdatedTitle': 'Benutzer-E-Mail aktualisiert',
  'auditUserEmailUpdatedDescription':
      'Der Administrator hat die Kontakt-E-Mail des Benutzers aktualisiert.',
  'auditUserReactivatedTitle': 'Benutzer aktiviert',
  'auditUserReactivatedDescription':
      'Der Administrator hat den Benutzer wieder aktiviert.',
  'auditActionUserEmailCompleted': 'E-Mail ergänzt',
  'auditActionUserEmailUpdated': 'Benutzer-E-Mail aktualisiert',
  'auditActionUserReactivated': 'Benutzer aktiviert',
  'auditCategoryDiscounts': 'Rabatte',
  'auditDiscountRequestedTitle': 'Rabatt Anfrage',
  'auditDiscountRequestedDescription':
      'Der Benutzer hat eine Anfrage zur Genehmigung eines Rabatts gesendet.',
  'auditDiscountApprovedTitle': 'Rabatt genehmigt',
  'auditDiscountApprovedDescription':
      'Der Administrator hat dem Benutzer den Rabatt genehmigt.',
  'auditDiscountRejectedTitle': 'Rabatt abgelehnt',
  'auditDiscountRejectedDescription':
      'Der Administrator hat die Rabatt Anfrage des Benutzers abgelehnt.',
  'auditAccountDeletionRequestedTitle': 'Anfrage zur Kontolöschung',
  'auditAccountDeletionRequestedDescription':
      'Der Benutzer hat die Löschung des Kontos beantragt.',
  'auditEmailChangeRequestedTitle': 'Anfrage zur E-Mail-Änderung',
  'auditEmailChangeRequestedDescription':
      'Der Benutzer hat die Änderung der E-Mail-Adresse beantragt.',
  'auditEmailChangeCompletedTitle': 'E-Mail-Änderung abgeschlossen',
  'auditEmailChangeCompletedDescription':
      'Der Benutzer hat die Änderung der E-Mail-Adresse abgeschlossen.',
  'auditPasswordResetRequestedTitle': 'Anfrage zum Zurücksetzen des Passworts',
  'auditPasswordResetRequestedDescription':
      'Der Benutzer hat eine E-Mail zum Zurücksetzen des Passworts angefordert.',
  'auditActionDiscountRequested': 'Rabatt Anfrage',
  'auditActionDiscountApproved': 'Rabatt genehmigt',
  'auditActionDiscountRejected': 'Rabatt abgelehnt',
  'auditActionAccountDeletionRequested': 'Anfrage zur Kontolöschung',
  'auditActionEmailChangeRequested': 'Anfrage zur E-Mail-Änderung',
  'auditActionEmailChangeCompleted': 'E-Mail-Änderung abgeschlossen',
  'auditActionPasswordResetRequested': 'Anfrage zum Zurücksetzen des Passworts',
};

const Map<String, List<String>> appTextListsDe = {
  'shortWeekdays': ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'],
  'weekdays': [
    'Montag',
    'Dienstag',
    'Mittwoch',
    'Donnerstag',
    'Freitag',
    'Samstag',
    'Sonntag',
  ],
};
