// Anglické texty aplikácie.
const Map<String, String> appTextsEn = {
  'appName': 'Body Fit Club TT',
  'loading': 'Loading...',
  'ok': 'OK',
  'save': 'Save',
  'delete': 'Delete',
  'cancel': 'Cancel',
  'back': 'Back',
  'today': 'Today',
  'tomorrow': 'Tomorrow',
  'todayLower': 'today',
  'tomorrowLower': 'tomorrow',
  'minutes': 'min.',
  'refresh': 'Refresh',
  'yesterday': 'Yesterday',
  'last7Days': 'Last 7 days',
  'last30Days': 'Last 30 days',
  'allTime': 'All time',
  'close': 'Close',
  'reason': 'Reason',
  'unknownDate': 'Unknown date',
  'notSet': 'Not set',
  'confirm': 'Confirm',
  'menu': 'Menu',
  'home': 'Home',
  'schedule': 'Schedule',
  'reservations': 'Reservations',
  'management': 'Management',
  'profile': 'Profile',
  'settings': 'Settings',
  'appearance': 'Appearance',
  'appearanceDescription': 'Choose light, dark, or system mode.',
  'themeSystem': 'System default',
  'themeLight': 'Light mode',
  'themeDark': 'Dark mode',
  'menuPosition': 'Menu position',
  'menuPositionDescription':
      'Choose which side the main menu should appear on.',
  'rightHanded': 'Right-handed',
  'leftHanded': 'Left-handed',
  'menuRightPositionDescription': 'The menu will be in the top right.',
  'menuLeftPositionDescription': 'The menu will be in the top left.',
  'language': 'Language',
  'languageDescription': 'Choose the application language.',
  'languageSlovak': '🇸🇰 Slovak',
  'languageEnglish': '🇬🇧 English',
  'languageGerman': '🇩🇪 German',
  'languageFrench': '🇫🇷 French',
  'languagePolish': '🇵🇱 Polish',
  'languageHungarian': '🇭🇺 Hungarian',
  'languageUkrainian': '🇺🇦 Ukrainian',
  'languageRussian': '🇷🇺 Russian',
  'languageSerbian': '🇷🇸 Serbian',
  'languageCzech': '🇨🇿 Czech',
  'role': 'Role',
  'roleUser': 'User',
  'roleTrainer': 'Trainer',
  'roleAdmin': 'Administrator',
  'roleUnknown': 'Unknown role',
  'privacyPolicy': 'Privacy Policy',
  'emailContact': 'E-mail',
  'loginTitle': 'Log in',
  'registerTitle': 'Registration',
  'continueWithGoogle': 'Continue with Google',
  'continueWithFacebook': 'Continue with Facebook',
  'or': 'or',
  'email': 'E-mail',
  'password': 'Password',
  'login': 'Log in',
  'register': 'Register',
  'logout': 'Log out',
  'noAccountRegister': 'Don’t have an account? Register',
  'hasAccountLogin': 'Already have an account? Log in',
  'authError': 'Login error',
  'acceptTerms': 'I agree to the Terms and Conditions',
  'acceptPrivacy': 'I agree to the processing of personal data',
  'termsConsentRequired':
      'You must agree to the Terms and Conditions to register.',
  'privacyConsentRequired':
      'You must agree to the processing of personal data to register.',
  'openTerms': 'Open Terms and Conditions',
  'openPrivacy': 'Open Privacy Policy',
  'termsVersion': '2026-05-16',
  'privacyVersion': '2026-05-16',
  'continueWithoutAccount': 'Continue without an account',
  'completeEmailOrLogout':
      'If you do not want to add an e-mail address, you can continue without an '
      'account and log in later with another account.',
  'fillEmailPassword': 'Fill in both e-mail and password.',
  'invalidEmailFormat': 'Enter a valid e-mail address.',
  'passwordTooShort': 'The password must be at least 6 characters long.',
  'wrongEmailOrPassword':
      'The entered e-mail address or password is incorrect.',
  'userAlreadyExists': 'A user with this e-mail address already exists.',
  'weakPassword': 'The entered password is too weak.',
  'tooManyRequests': 'Too many attempts. Please try again later.',
  'networkError': 'Check your internet connection.',
  'signInCancelled': 'Sign-in was cancelled.',
  'facebookLoginFailed': 'Facebook sign-in failed.',
  'unknownAuthError': 'An unknown sign-in error occurred.',
  'inactiveAccount': 'Your account is deactivated. Contact the administrator.',
  'verificationEmailSent':
      'Registration was successful. We have sent you a verification e-mail. If you '
      'cannot see it in your inbox, also check your Spam folder.',
  'emailNotVerified':
      'First confirm your registration by clicking the link in the e-mail.',
  'verificationEmailSentAgain':
      'We have sent you the verification e-mail again. If you cannot see it in your '
      'inbox, also check your Spam folder.',
  'forgotPassword': 'Forgot your password?',
  'resetPasswordTitle': 'Password reset',
  'sendResetEmail': 'Send e-mail',
  'passwordResetEmailSent':
      'If an account with this e-mail exists, we have sent a password reset e-mail.',
  'emailRequired': 'Enter an e-mail address.',
  'emailNotProvided': 'No e-mail address was provided',
  'emailSaved': 'The e-mail address was saved.',
  'emailSaveError': 'The e-mail address could not be saved.',
  'emailChangeVerificationSent':
      'We have sent a verification link to the new e-mail address. The change will be '
      'completed after it is confirmed.',
  'emailChangeRequestError': 'The e-mail change could not be started.',
  'emailChangeNotAvailable':
      'E-mail change is only available for accounts created with e-mail and password.',
  'completeProfileTitle': 'Complete profile',
  'editProfile': 'Edit profile',
  'firstName': 'First name',
  'lastName': 'Last name',
  'publicName': 'Display name',
  'publicNameHint': 'E.g. Barbora, Katka, Aďo',
  'firstNameRequired': 'Enter first name.',
  'lastNameRequired': 'Enter last name.',
  'publicNameRequired': 'Enter display name.',
  'profileSaved': 'The profile was saved.',
  'profileSaveError': 'The profile could not be saved.',
  'loggedInUser': 'Logged-in user',
  'completeEmailTitle': 'Add e-mail address',
  'completeEmailDescription':
      'To use the application, we need your e-mail address. We will use it as the '
      'contact e-mail for your account.',
  'deleteAccountRequest': 'Request account deletion',
  'deleteAccountRequestTitle': 'Account deletion',
  'deleteAccountRequestDescription':
      'After the request is sent, the account will be deactivated and you will no '
      'longer be able to log in. The data will then be processed by the administrator '
      'according to the privacy rules.',
  'deleteAccountReason': 'Request reason',
  'deleteAccountConfirm': 'Do you really want to request account deletion?',
  'deleteAccountRequestSent': 'The account deletion request has been sent.',
  'deleteAccountRequestError':
      'The account deletion request could not be sent.',
  'deleteAccountBlockedActiveReservations':
      'The account cannot be deleted because you have active reservations.',
  'accountDeletionRequests': 'Account deletion requests',
  'accountDeletionRequestsWithCount': 'Account deletion requests',
  'accountDeletionRequestsLoadError':
      'The account deletion requests could not be loaded.',
  'noAccountDeletionRequests': 'There are no pending requests recorded.',
  'completeAccountDeletion': 'Anonymize account',
  'completeAccountDeletionTitle': 'Anonymize account',
  'completeAccountDeletionQuestion':
      'Do you really want to anonymize this account? This action will overwrite the '
      'user’s personal data.',
  'accountDeletionCompleted': 'The account has been anonymized.',
  'accountDeletionCompleteError': 'The account could not be anonymized.',
  'requestedAt': 'Requested',
  'accountDeletionRequestsWaiting': 'Requests waiting to be processed.',
  'changeEmail': 'Change e-mail',
  'changeEmailTitle': 'Change e-mail',
  'changeEmailDescription':
      'Enter the new e-mail address and current password. We will send a verification '
      'link to the new e-mail address. The change will only be completed after the '
      'link in the e-mail is confirmed.',
  'changeEmailProfileHint':
      'Available for accounts created with e-mail and password.',
  'newEmail': 'New e-mail',
  'currentPassword': 'Current password',
  'sendVerificationEmail': 'Send verification e-mail',
  'wrongCurrentPassword': 'The current password is incorrect.',
  'requiresRecentLogin':
      'For this action, please log out first and then log in again.',
  'changeProfilePhoto': 'Change profile photo',
  'chooseFromGallery': 'Choose from gallery',
  'takePhoto': 'Take photo',
  'removePhoto': 'Remove photo',
  'editPhoto': 'Edit photo',
  'cropProfilePhoto': 'Crop profile photo',
  'profilePhotoUpdated': 'The profile photo was saved.',
  'profilePhotoUpdateError': 'The profile photo could not be saved.',
  'profilePhotoRemoveError': 'The profile photo could not be removed.',
  'requestDiscount': 'Request discount',
  'discountStatus': 'Discount status',
  'discountStatusNone': 'No discount',
  'discountStatusPending': 'Waiting for approval',
  'discountStatusApproved': 'Approved discount',
  'discountStatusRejected': 'Rejected request',
  'discountStatusExpired': 'Discount validity has expired',
  'discountType': 'Discount type',
  'discountTypeNormal': 'Regular user',
  'discountTypeStudent': 'Student',
  'discountTypeSenior': 'Senior',
  'discountTypeZtp': 'Disabled person',
  'discountTypeIndividual': 'Individual discount',
  'discountRequestDescription':
      'Choose the type of discount you are requesting. After submission, the request '
      'will be reviewed by an administrator.',
  'discountRequestNote': 'Request note',
  'discountRequestSent': 'The discount request has been sent.',
  'discountRequestError': 'The discount request could not be sent.',
  'discountRequestAlreadyPending':
      'You already have a discount request in progress.',
  'discountRequestPending': 'The request is waiting for approval',
  'sendRequest': 'Send request',
  'discountDocument': 'Discount document',
  'discountDocumentDescription':
      'Upload a photo of the document that the administrator will use to verify your '
      'eligibility for the discount.',
  'chooseDiscountDocument': 'Choose document',
  'discountDocumentRequired':
      'A document must be attached before the request can be sent.',
  'discountDocumentSelected': 'The document has been selected',
  'takeDiscountDocumentPhoto': 'Take a photo of the document',
  'chooseDiscountDocumentFromGallery': 'Choose from gallery',
  'discountRequests': 'Discount requests',
  'discountRequestsDescription': 'Approve or reject user discount requests.',
  'discountRequestsLoadError': 'The discount requests could not be loaded.',
  'noDiscountRequests': 'There are no pending discount requests recorded.',
  'approveDiscount': 'Approve discount',
  'rejectDiscount': 'Reject request',
  'discountApproved': 'The discount has been approved.',
  'discountRejected': 'The discount request has been rejected.',
  'discountDecisionError': 'The decision for the request could not be saved.',
  'discountValidUntilRequired': 'Select the discount validity date.',
  'discountAdminNote': 'Administrator note',
  'selectDiscountValidUntil': 'Select discount validity',
  'discountDocumentPreview': 'Document preview',
  'todayReservations': 'Today’s reservations',
  'noTodayReservations': 'You have no reserved training session today.',
  'nearestTraining': 'Nearest training session',
  'nearestTrainings': 'Nearest training sessions',
  'noNearestTraining': 'No upcoming training session is scheduled.',
  'todaysTrainings': 'Today’s training sessions',
  'noTodaysTrainings': 'No training sessions are scheduled for today.',
  'myMemberships': 'My passes',
  'activeMembershipsCount': 'Active passes',
  'availableEntriesSummary': 'Available entries',
  'reservedEntriesSummary': 'Allocated entries',
  'dailyMembershipsSummary': 'Day passes',
  'tapToShowQrCode': 'Tap to show the QR code.',
  'nearestReservations': 'Upcoming reservations',
  'noNearestReservations': 'You have no upcoming reservations.',
  'qrShort': 'QR',
  'membershipStatus': 'Pass status',
  'remainingEntries': 'Remaining entries',
  'upcomingTraining': 'Next training session today',
  'schedulePlaceholder': 'The training schedule will be shown here.',
  'reservationsPlaceholder': 'Reservations will be shown here.',
  'newsPlaceholder': 'News and messages from trainers will be shown here.',
  'aboutApp': 'About the app',
  'aboutUs': 'About us',
  'aboutAppDescription':
      'The Body Fit Club TT application is used to manage training sessions, '
      'reservations, passes, and communication between the fitness center and users.',
  'aboutUsDescription':
      'Body Fit Club is a fitness center in Trnava focused on group and individual '
      'training, movement, a healthy lifestyle, and a personal approach to clients.',
  'bodyFitClubWebsite': 'https://bodyfitclub.sk/',
  'openWebsite': 'Open website',
  'businessTerms': 'Terms and Conditions',
  'legalDocumentsInfo':
      'The Terms and Conditions and privacy information will be available on the Body '
      'Fit Club website.',
  'contacts': 'Contacts',
  'billingDetails': 'Billing details',
  'address': 'Address',
  'phone': 'Phone',
  'website': 'Website',
  'socialNetworks': 'Social networks',
  'openMap': 'Open map',
  'openFacebook': 'Facebook',
  'openInstagram': 'Instagram',
  'multisport': 'MultiSport',
  'multisportInfo':
      'We accept the MultiSport card according to the current operating conditions.',
  'bodyFitClubCompanyName': 'BODYFIT CLUB s.r.o.',
  'bodyFitClubOperationAddress': 'V Jame 24, Trnava',
  'bodyFitClubBillingAddress': 'J. G. Tajovského 18, 917 08 Trnava',
  'bodyFitClubPhonePrimary': '+421 902 860 008',
  'bodyFitClubPhoneSecondary': '+421 903 946 895',
  'bodyFitClubEmail': 'bodyfitclubtt@gmail.com',
  'bodyFitClubIco': '48074128',
  'ico': 'Company ID: ',
  'companySeat': 'Registered office',
  'operation': 'Premises',
  'bodyFitClubFacebookUrl': 'https://www.facebook.com/bodyfitclub.sk',
  'bodyFitClubInstagramUrl': 'https://www.instagram.com/bodyfitclub.tt/',
  'bodyFitClubMapUrl':
      ' '
      'https://www.google.com/maps/search/?api=1&query=V%20Jame%206641%2F24%2C%20917%2001%20Trnava',
  'bodyFitClubMultiSportUrl':
      'https://multi-sport.sk/aktivity/partner/bodyfit-club/',
  'multisportInfo2':
      'Body Fit Club is a partner of the MultiSport program. Acceptance of the '
      'MultiSport card follows the current operating conditions.',
  'bodyFitClubWebsiteLabel': 'www.bodyfitclub.sk',
  'dic': 'Tax ID: ',
  'bodyFitClubDic': '2120035445',
  'notVatPayer': 'The company is not a VAT payer',
  'legalDocuments': 'Legal documents',
  'priceList': 'Price list',
  'priceListAudience': 'For',
  'priceListAudienceNormal': 'regular users',
  'priceListAudienceDiscount': 'users with a discount',
  'priceListAudienceAll': 'everyone',
  'price': 'Price',
  'singleEntries': 'Single entries',
  'priceListMemberships': 'Passes',
  'chooseEntry': 'Choose entry',
  'noAvailablePlans': 'There are currently no purchase options available.',
  'news': 'News',
  'noPublicMessages': 'There are no messages yet.',
  'writeMessage': 'Write message',
  'writeMessageShort': 'Write',
  'editMessage': 'Edit message',
  'deleteMessage': 'Delete message',
  'deleteMessageQuestion': 'Do you really want to delete this message?',
  'messageText': 'Message text',
  'messageHint': 'Write a message...',
  'sendMessage': 'Send',
  'updateMessage': 'Save changes',
  'messageSaved': 'The message was saved.',
  'messageDeleted': 'The message was deleted.',
  'messageSaveError': 'The message could not be saved.',
  'messageDeleteError': 'The message could not be deleted.',
  'editedBy': 'Edited',
  'editedByAdmin': 'Edited by administrator',
  'editedByTrainer': 'Edited by trainer',
  'userFallback': 'User',
  'noTrainings': 'There are currently no training sessions available.',
  'noTrainingsForSelectedDay':
      'There are no training sessions scheduled for this day.',
  'trainer': 'Trainer',
  'freeSpots': 'Free spots',
  'reserve': 'Reserve',
  'reserved': 'Reserved',
  'fullCapacity': 'Full',
  'trainingsLoadError': 'The training schedule could not be loaded.',
  'unknownTraining': 'Unknown training session',
  'unknownTrainer': 'Unknown trainer',
  'unknownUser': 'Unknown user',
  'trainingSessionFinished': 'Finished',
  'trainingSessionTooFarInFuture':
      'The date is too far in the future. You can manually add a training session '
      'only within the period displayed in the schedule.',
  'managementDescription':
      'Here you can manage training dates, attendance, passes, and users.',
  'scheduleManagement': 'Schedule management',
  'scheduleManagementDescription':
      'Manage training types, schedule templates, and specific training sessions.',
  'attendanceManagement': 'Attendance management',
  'usersManagement': 'User management',
  'usersManagementComingSoon': 'User management will be added later.',
  'scheduleTemplatesManagement': 'Schedule template management',
  'reactivateUser': 'Reactivate user',
  'reactivateUserQuestion': 'Do you really want to reactivate this user?',
  'userReactivated': 'The user has been reactivated.',
  'trainingTypesManagement': 'Training type management',
  'addTrainingType': 'Add training type',
  'editTrainingType': 'Edit training type',
  'deleteTrainingType': 'Delete training type',
  'trainingType': 'Training type',
  'selectTrainingType': 'Choose training type',
  'trainingName': 'Training name',
  'description': 'Description',
  'defaultDuration': 'Default duration',
  'defaultCapacity': 'Default capacity',
  'noTrainingTypes': 'There are currently no training types created.',
  'trainingTypesLoadError': 'The training types could not be loaded.',
  'trainingTypeCreated': 'The training type has been created.',
  'trainingTypeUpdated': 'The training type has been updated.',
  'trainingTypeDeleted': 'The training type has been deleted.',
  'trainingTypeDeleteQuestion':
      'Do you really want to delete this training type? It will no longer be offered '
      'for new sessions.',
  'trainingTypeAlreadyExists': 'A training type with this name already exists.',
  'trainingTypeUsedByTemplate':
      'The training type cannot be deleted because it is used in an active schedule template.',
  'trainingTypeUsedBySession':
      'The training type cannot be deleted because it is used in a future training session.',
  'addTrainingSession': 'Add training session',
  'editTrainingSession': 'Edit training details',
  'trainingSessionCreated': 'The training session has been created.',
  'trainingSessionUpdated': 'The training session has been updated.',
  'updateTrainingSessionError': 'The training session could not be updated.',
  'trainingSessionInPast': 'The training session cannot be in the past.',
  'trainingSessionOverlap':
      'Another training session is already scheduled at this time.',
  'capacityLowerThanReservations':
      'Capacity cannot be lower than the number of existing reservations.',
  'cancelTrainingSession': 'Cancel session',
  'cancelTrainingSessionTitle': 'Cancel training session',
  'cancelTrainingSessionQuestion':
      'Do you really want to cancel this training session? Active reservations will '
      'be cancelled and allocated entries will be released back to users. If an entry '
      'has already been used, it will be returned to the user.',
  'cancelTrainingSessionConfirm': 'Cancel session',
  'trainingSessionCancelled': 'The training session has been cancelled.',
  'cancelTrainingSessionError': 'The training session could not be cancelled.',
  'trainerCanCancelOnlyOwnSession':
      'A trainer can cancel only their own session.',
  'trainerCannotCancelStartedSession':
      'A trainer cannot cancel a session that has already started or finished.',
  'date': 'Date',
  'startTime': 'Start',
  'duration': 'Duration',
  'capacity': 'Capacity',
  'selectDate': 'Select date',
  'selectTrainer': 'Select trainer',
  'trainersLoadError': 'The trainers could not be loaded.',
  'fillAllFields': 'Fill in all required fields.',
  'invalidCapacity': 'Capacity must be greater than 0.',
  'invalidDuration': 'Duration must be greater than 0.',
  'saveError': 'Saving failed.',
  'addScheduleTemplate': 'Add schedule template',
  'editScheduleTemplate': 'Edit schedule template',
  'deleteScheduleTemplate': 'Delete schedule template',
  'noScheduleTemplates': 'There are currently no schedule templates created.',
  'weekday': 'Day of the week',
  'selectWeekday': 'Select day of the week',
  'scheduleTemplateCreated': 'The schedule template has been created.',
  'scheduleTemplateUpdated': 'The schedule template has been updated.',
  'scheduleTemplateDeleted': 'The schedule template has been deleted.',
  'scheduleTemplateDeleteQuestion':
      'Do you really want to delete this schedule template? It will no longer be used '
      'when generating new sessions.',
  'scheduleTemplateAlreadyExists': 'This schedule template already exists.',
  'scheduleTemplateLoadError': 'The schedule templates could not be loaded.',
  'scheduleTemplateOverlap':
      'Another schedule template already exists at this time.',
  'capacityLabel': 'Capacity',
  'reservationCreated': 'The reservation has been created.',
  'reservationAlreadyExists':
      'You already have a reservation for this training session.',
  'reservationTrainingFull': 'This training session is already full.',
  'reservationTrainingNotAvailable':
      'This training session is no longer available for reservation.',
  'reservationTrainingAlreadyStarted':
      'You can no longer reserve this training session.',
  'reservationError': 'The reservation could not be created.',
  'myReservations': 'My reservations',
  'noReservations': 'You currently have no reservations.',
  'cancelReservation': 'Cancel reservation',
  'cancelReservationTitle': 'Cancel reservation',
  'cancelReservationQuestion': 'Do you really want to cancel this reservation?',
  'reservationCancelled': 'The reservation has been cancelled.',
  'reservationCancelError': 'The reservation could not be cancelled.',
  'reservationsLoadError': 'The reservations could not be loaded.',
  'cancelReservations': 'Cancel reservations',
  'cancelReservationsBeforeDeactivation':
      'Before deactivating or cancelling the pass, cancel the allocated reservations first.',
  'cancelReservationForMembership': 'Cancel this reservation',
  'cancelReservationForMembershipQuestion':
      'Do you really want to cancel this reservation linked to the pass? The '
      'allocated entry will be released.',
  'reservationForMembershipCancelled':
      'The reservation has been cancelled and the allocated entry has been released.',
  'noReservationsForTrainingHistory':
      'There are no reservations for this training session.',
  'reservationQrCode': 'Reservation QR code',
  'memberships': 'Passes',
  'assignMembership': 'Assign pass',
  'selectUser': 'Select user',
  'selectMembershipPlan': 'Select pass type',
  'membershipPlansLoadError': 'The pass types could not be loaded.',
  'membershipAssigned': 'The pass has been assigned.',
  'membershipAssignError': 'The pass could not be assigned.',
  'membershipPlan': 'Pass type',
  'client': 'User',
  'buyMembership': 'Buy pass',
  'buySingleEntry': 'Buy single entry',
  'chooseMembership': 'Choose pass',
  'payment': 'Payment',
  'pay': 'Pay',
  'paymentSuccessful': 'Payment successful.',
  'paymentFailed': 'Payment failed.',
  'activeMembership': 'Active pass',
  'noActiveMembership': 'You do not have an active pass.',
  'validUntil': 'Valid until',
  'membershipLoadError': 'The pass could not be loaded.',
  'noAvailableEntries': 'You do not have an available entry for reservation.',
  'noUpcomingTraining': 'You have no reserved training session today.',
  'membershipsManagement': 'Pass management',
  'membershipDetail': 'Pass detail',
  'noMemberships': 'There are currently no passes available.',
  'status': 'Status',
  'validFrom': 'Valid from',
  'entriesTotal': 'Total number of entries',
  'entriesRemaining': 'Remaining entries',
  'entriesReserved': 'Allocated in reservations',
  'entriesAvailable': 'Available entries',
  'adminMembershipEdit': 'Administrator edit',
  'membershipStatusActive': 'Active',
  'membershipStatusInactive': 'Inactive',
  'membershipStatusCancelled': 'Cancelled',
  'membershipStatusExpired': 'Expired',
  'membershipStatusUsedUp': 'Used up',
  'membershipUpdated': 'The pass has been updated.',
  'membershipUpdateError': 'The pass could not be updated.',
  'invalidRemainingEntries': 'Enter a valid number of remaining entries.',
  'allocatedReservations': 'Allocated reservations',
  'cancelAllocatedReservations': 'Cancel allocated reservations',
  'cancelAllocatedReservationsQuestion':
      'Do you really want to cancel active reservations linked to this pass? The '
      'allocated entries will be released.',
  'cancelAllReservations': 'Cancel all reservations',
  'cancelAllocatedReservationsError':
      'The allocated reservations could not be cancelled.',
  'usedEntries': 'Used entries',
  'noAllocatedReservations':
      'There are currently no reservations allocated to this pass.',
  'noUsedEntries': 'No entry from this pass has been used yet.',
  'membershipUsageLoadError': 'The pass history could not be loaded.',
  'searchMemberships': 'Search by user or pass',
  'allMembershipStatuses': 'All statuses',
  'membershipStatusNotYetValid': 'Not yet valid',
  'membershipStatusUsable': 'Active',
  'invalidRemainingEntriesHigherThanTotal':
      'Remaining entries cannot be higher than the total number of entries.',
  'invalidRemainingEntriesLowerThanReserved':
      'Remaining entries cannot be lower than the number of allocated entries.',
  'membershipPrefix': 'Pass',
  'statusPrefix': 'Status',
  'attendance': 'Attendance',
  'attendanceLoadError': 'Attendance could not be loaded.',
  'noActiveReservationsForAttendance':
      'There are currently no active reservations to mark attendance for.',
  'attended': 'Attended',
  'noShow': 'No-show',
  'markAttendedTitle': 'Mark attendance',
  'markNoShowTitle': 'Mark absence',
  'markAttendedQuestion': 'Do you really want to mark the user as present?',
  'markNoShowQuestion': 'Do you really want to mark the user as absent?',
  'attendanceMarked': 'Attendance has been saved.',
  'attendanceMarkError': 'Attendance could not be saved.',
  'attendedStatus': 'Attended',
  'noShowStatus': 'No-show',
  'attendedCountLabel': 'Attended',
  'noShowCountLabel': 'No-shows',
  'attendanceActionDone': 'The attendance change has been saved.',
  'attendanceActionError': 'The attendance change could not be saved.',
  'showQrCode': 'QR code',
  'showQrToTrainer':
      'Show this QR code to the trainer when you arrive for training.',
  'scanQrCode': 'Scan QR code',
  'scanQrCodes': 'Scan QR codes',
  'scanQrCodeHint': 'Point the camera at the user’s reservation QR code.',
  'invalidQrCode': 'Invalid reservation QR code.',
  'qrCodeScanned': 'The QR code has been scanned.',
  'qrScanSuccessful':
      'The QR code has been scanned. You can scan another user.',
  'trainerQrScanTooEarly':
      'The QR code can be scanned no earlier than 30 minutes before the training '
      'session starts.',
  'trainingHistory': 'Training history',
  'trainingHistoryDetail': 'Training detail',
  'trainingHistoryLoadError': 'Training history could not be loaded.',
  'trainingHistoryReservationsLoadError':
      'Training attendance could not be loaded.',
  'noTrainingHistoryInSelectedPeriod':
      'There are no training sessions in the selected period.',
  'fromDatePrefix': 'From',
  'toDatePrefix': 'To',
  'planned': 'Scheduled',
  'cancelled': 'Cancelled',
  'finished': 'Finished',
  'reservedStatus': 'Reserved',
  'reservedCountLabel': 'Reserved',
  'cancelledCountLabel': 'Cancelled',
  'markedAtPrefix': 'Marked',
  'markAsAttended': 'Mark as attended',
  'markAsNoShow': 'Mark as no-show',
  'revertAttendance': 'Revert marked attendance',
  'revertNoShow': 'Revert marked absence',
  'markAsAttendedQuestion':
      'Do you really want to mark the user as present? An entry from the pass will be used.',
  'markAsNoShowQuestion':
      'Do you really want to mark the user as absent? An entry from the pass will be used.',
  'revertAttendanceQuestion':
      'Do you really want to revert the marked attendance? The used entry will be '
      'returned to the pass.',
  'revertNoShowQuestion':
      'Do you really want to revert the marked absence? The used entry will be '
      'returned to the pass.',
  'addTrainingAttendance': 'Add participant',
  'selectAttendanceUser': 'Select user',
  'selectAttendanceMembership': 'Select pass',
  'noUsersForAttendance': 'No active users were found.',
  'noUsableMembershipsForAttendance':
      'The user does not have a usable pass for this training session.',
  'addTrainingAttendanceQuestion':
      'Do you really want to additionally add the user’s attendance to this training '
      'session? An entry from the pass will be used.',
  'trainingAttendanceAdded':
      'The participant has been added to the training session.',
  'trainingAttendanceAddError': 'The participant could not be added.',
  'userAlreadyHasReservationForTraining':
      'The user already has a record for this training session.',
  'usersLoadError': 'Users could not be loaded.',
  'allRoles': 'All roles',
  'searchUsers': 'Search user',
  'noUsersFound': 'No users were found.',
  'editUser': 'Edit user',
  'userUpdated': 'The user has been updated.',
  'userUpdateError': 'The user could not be updated.',
  'cannotChangeOwnRole': 'You cannot change your own role.',
  'changeRoleWarning':
      'Changing the user’s role may change their permissions in the application.',
  'deactivateUser': 'Deactivate user',
  'deactivationReason': 'Deactivation reason',
  'userDeactivated': 'The user has been deactivated.',
  'deactivateUserQuestion':
      'Do you really want to deactivate this user? They will no longer be able to use '
      'the application management.',
  'cannotDeactivateYourself': 'You cannot deactivate your own account.',
  'userUsedByTemplate':
      'The user cannot be deactivated or changed to a regular user because they are '
      'assigned in an active schedule template.',
  'userUsedByFutureSession':
      'The user cannot be deactivated or changed to a regular user because they are '
      'assigned to a future training session.',
  'userHasActiveReservations':
      'The user cannot be deactivated because they have active reservations.',
  'userHasActiveMemberships':
      'The user cannot be deactivated because they have active passes.',
  'inactiveUser': 'Inactive user',
  'userCannotBeDeactivated': 'The user cannot be deactivated',
  'userCannotBeDeactivatedDescription':
      'Before deactivation, their active reservations or passes must be resolved first.',
  'userHasBlockingItems': 'The user has:',
  'activeReservationsCount': 'Active reservations',
  'showMemberships': 'Show passes',
  'auditLogs': 'Action history',
  'auditLogsDescription': 'Overview of important actions in the application.',
  'auditLogsLoadError': 'The action history could not be loaded.',
  'noAuditLogs': 'No actions were found.',
  'searchAuditLogs': 'Search by user, e-mail, or description',
  'auditCategory': 'Category',
  'auditAction': 'Action',
  'auditActor': 'Performed by',
  'auditActorRole': 'Actor role',
  'auditPeriod': 'Period',
  'auditAllCategories': 'All categories',
  'auditCategoryMemberships': 'Passes',
  'auditCategoryReservations': 'Reservations',
  'auditCategoryAttendance': 'Attendance',
  'auditCategoryUsers': 'Users',
  'auditCategorySchedule': 'Schedule',
  'auditCategoryMessages': 'Messages',
  'auditCategoryPayments': 'Payments',
  'auditCategoryProfile': 'Profile',
  'auditAllActions': 'All actions',
  'auditActionCreated': 'Created',
  'auditActionUpdated': 'Updated',
  'auditActionCancelled': 'Cancelled',
  'auditActionDeactivated': 'Deactivated',
  'auditActionActivated': 'Activated',
  'auditActionAssigned': 'Assigned',
  'auditActionPurchased': 'Purchased',
  'auditActionPaymentSucceeded': 'Payment successful',
  'auditActionPaymentFailed': 'Payment failed',
  'auditActionAttendanceMarked': 'Attendance',
  'auditActionQrChecked': 'QR check',
  'auditAllActorRoles': 'All roles',
  'auditReservationCreatedTitle': 'Reservation created',
  'auditReservationCreatedDescription':
      'The user created a reservation for a training session.',
  'auditReservationCancelledTitle': 'Reservation cancelled',
  'auditReservationCancelledDescription':
      'The user’s reservation was cancelled.',
  'auditAttendanceAttendedTitle': 'Attendance marked',
  'auditAttendanceAttendedDescription':
      'The user was marked as present at the training session.',
  'auditAttendanceNoShowTitle': 'Absence marked',
  'auditAttendanceNoShowDescription':
      'The user was marked as absent from the training session.',
  'auditTrainingTypeCreatedTitle': 'Training type created',
  'auditTrainingTypeUpdatedTitle': 'Training type updated',
  'auditTrainingTypeDeactivatedTitle': 'Training type deactivated',
  'auditTrainingSessionCreatedTitle': 'Session created',
  'auditTrainingSessionUpdatedTitle': 'Session updated',
  'auditTrainingSessionTimeChangedTitle': 'Session time changed',
  'auditTrainingSessionCancelledTitle': 'Session cancelled',
  'auditScheduleTemplateCreatedTitle': 'Schedule template created',
  'auditScheduleTemplateUpdatedTitle': 'Schedule template updated',
  'auditScheduleTemplateDeactivatedTitle': 'Schedule template deactivated',
  'auditUserUpdatedTitle': 'User updated',
  'auditUserUpdatedDescription': 'The administrator updated the user’s data.',
  'auditUserRoleChangedTitle': 'User role changed',
  'auditUserRoleChangedDescription':
      'The administrator changed the user’s role.',
  'auditUserDeactivatedTitle': 'User deactivated',
  'auditUserDeactivatedDescription': 'The administrator deactivated the user.',
  'auditUserDeactivationBlockedTitle': 'User deactivation failed',
  'auditUserDeactivationBlockedDescription':
      'User deactivation was blocked by an active-link check.',
  'auditPublicMessageCreatedTitle': 'News item created',
  'auditPublicMessageCreatedDescription': 'A public news item was created.',
  'auditPublicMessageUpdatedTitle': 'News item updated',
  'auditPublicMessageUpdatedDescription': 'A public news item was updated.',
  'auditPublicMessageDeletedTitle': 'News item deleted',
  'auditPublicMessageDeletedDescription': 'The public news item was deleted.',
  'auditProfileCompletedTitle': 'Profile completed',
  'auditProfileCompletedDescription': 'The user filled in basic profile data.',
  'auditProfileUpdatedTitle': 'Profile updated',
  'auditProfileUpdatedDescription': 'The user updated profile data.',
  'auditProfilePhotoUpdatedTitle': 'Profile photo updated',
  'auditProfilePhotoUpdatedDescription': 'The user updated the profile photo.',
  'auditProfilePhotoRemovedTitle': 'Profile photo removed',
  'auditProfilePhotoRemovedDescription':
      'The user removed the manually set profile photo.',
  'auditPaymentStartedTitle': 'Payment started',
  'auditPaymentStartedDescription': 'The user started payment for a pass.',
  'auditPaymentSucceededTitle': 'Payment successful',
  'auditPaymentSucceededDescription':
      'The payment for the pass was completed successfully.',
  'auditPaymentFailedTitle': 'Payment failed',
  'auditPaymentFailedDescription':
      'The payment for the pass failed or was cancelled.',
  'auditMembershipUpdatedTitle': 'Pass updated',
  'auditMembershipUpdatedDescription':
      'The administrator updated the user’s pass.',
  'auditMembershipStatusChangedTitle': 'Pass status changed',
  'auditMembershipStatusChangedDescription':
      'The administrator changed the status of the user’s pass.',
  'auditMembershipEntriesChangedTitle': 'Pass entry count changed',
  'auditMembershipEntriesChangedDescription':
      'The administrator changed the number of remaining entries on the pass.',
  'auditMembershipReservationCancelledTitle': 'Allocated reservation cancelled',
  'auditMembershipReservationCancelledDescription':
      'The administrator cancelled an allocated reservation linked to the pass.',
  'auditMembershipAllReservationsCancelledTitle':
      'All allocated reservations cancelled',
  'auditMembershipAllReservationsCancelledDescription':
      'The administrator cancelled all allocated reservations linked to the pass.',
  'auditMembershipAssignedTitle': 'Pass assigned',
  'auditMembershipAssignedDescription':
      'A pass was manually assigned to the user.',
  'auditMembershipPurchasedTitle': 'Pass purchase',
  'auditMembershipPurchasedDescription': 'The user purchased a pass.',
  'auditActionMembershipAssigned': 'Pass assigned',
  'auditActionMembershipPurchased': 'Pass purchased',
  'auditActionMembershipUpdated': 'Pass updated',
  'auditActionMembershipStatusChanged': 'Pass status changed',
  'auditActionMembershipEntriesChanged': 'Pass entries changed',
  'auditActionMembershipReservationCancelled':
      'One allocated reservation cancelled',
  'auditActionMembershipAllReservationsCancelled':
      'All allocated reservations cancelled',
  'auditActionReservationCreated': 'Reservation created',
  'auditActionReservationCancelled': 'Reservation cancelled',
  'auditActionAttendanceAttended': 'Attendance marked',
  'auditActionAttendanceNoShow': 'Absence marked',
  'auditActionTrainingTypeCreated': 'Training type created',
  'auditActionTrainingTypeUpdated': 'Training type updated',
  'auditActionTrainingTypeDeactivated': 'Training type deactivated',
  'auditActionTrainingSessionCreated': 'Session created',
  'auditActionTrainingSessionUpdated': 'Session updated',
  'auditActionTrainingSessionTimeChanged': 'Session time changed',
  'auditActionTrainingSessionCancelled': 'Session cancelled',
  'auditActionScheduleTemplateCreated': 'Template created',
  'auditActionScheduleTemplateUpdated': 'Template updated',
  'auditActionScheduleTemplateDeactivated': 'Template deactivated',
  'auditActionUserUpdated': 'User updated',
  'auditActionUserRoleChanged': 'Role changed',
  'auditActionUserDeactivationBlocked': 'Deactivation blocked',
  'auditActionUserDeactivated': 'User deactivated',
  'auditActionPublicMessageCreated': 'News item created',
  'auditActionPublicMessageUpdated': 'News item updated',
  'auditActionPublicMessageDeleted': 'News item deleted',
  'auditActionProfileCompleted': 'Profile completed',
  'auditActionProfileUpdated': 'Profile updated',
  'auditActionProfilePhotoUpdated': 'Profile photo updated',
  'auditActionProfilePhotoRemoved': 'Profile photo removed',
  'auditActionPaymentStarted': 'Payment started',
  'auditUserEmailCompletedTitle': 'E-mail added',
  'auditUserEmailCompletedDescription':
      'The user added the missing e-mail address to the account.',
  'currentUserShort': 'you',
  'auditUserEmailUpdatedTitle': 'User e-mail updated',
  'auditUserEmailUpdatedDescription':
      'The administrator updated the user’s contact e-mail.',
  'auditUserReactivatedTitle': 'User activated',
  'auditUserReactivatedDescription': 'The administrator reactivated the user.',
  'auditActionUserEmailCompleted': 'E-mail added',
  'auditActionUserEmailUpdated': 'User e-mail updated',
  'auditActionUserReactivated': 'User activated',
  'auditCategoryDiscounts': 'Discounts',
  'auditDiscountRequestedTitle': 'Discount request',
  'auditDiscountRequestedDescription':
      'The user submitted a discount approval request.',
  'auditDiscountApprovedTitle': 'Discount approved',
  'auditDiscountApprovedDescription':
      'The administrator approved the user’s discount.',
  'auditDiscountRejectedTitle': 'Discount rejected',
  'auditDiscountRejectedDescription':
      'The administrator rejected the user’s discount request.',
  'auditAccountDeletionRequestedTitle': 'Account deletion request',
  'auditAccountDeletionRequestedDescription':
      'The user requested account deletion.',
  'auditEmailChangeRequestedTitle': 'E-mail change request',
  'auditEmailChangeRequestedDescription':
      'The user requested an e-mail address change.',
  'auditEmailChangeCompletedTitle': 'E-mail change completed',
  'auditEmailChangeCompletedDescription':
      'The user completed the e-mail address change.',
  'auditPasswordResetRequestedTitle': 'Password reset request',
  'auditPasswordResetRequestedDescription':
      'The user requested a password reset e-mail.',
  'auditActionDiscountRequested': 'Discount request',
  'auditActionDiscountApproved': 'Discount approved',
  'auditActionDiscountRejected': 'Discount rejected',
  'auditActionAccountDeletionRequested': 'Account deletion request',
  'auditActionEmailChangeRequested': 'E-mail change request',
  'auditActionEmailChangeCompleted': 'E-mail change completed',
  'auditActionPasswordResetRequested': 'Password reset request',
};

const Map<String, List<String>> appTextListsEn = {
  'shortWeekdays': ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  'weekdays': [
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
    'Sunday',
  ],
};
