// Maďarské texty aplikácie.
const Map<String, String> appTextsHu = {
  'appName': 'Body Fit Club TT',
  'loading': 'Betöltés...',
  'ok': 'OK',
  'save': 'Mentés',
  'delete': 'Törlés',
  'cancel': 'Mégse',
  'back': 'Vissza',
  'today': 'Ma',
  'tomorrow': 'Holnap',
  'todayLower': 'Ma',
  'tomorrowLower': 'Holnap',
  'minutes': 'Perc',
  'refresh': 'Frissítés',
  'yesterday': 'Tegnap',
  'last7Days': 'Az elmúlt 7 nap',
  'last30Days': 'Az elmúlt 30 nap',
  'allTime': 'Teljes időszak',
  'close': 'Bezárás',
  'reason': 'Ok',
  'unknownDate': 'Ismeretlen dátum',
  'notSet': 'Nincs beállítva',
  'confirm': 'Megerősítés',
  'menu': 'Menü',
  'home': 'Kezdőlap',
  'schedule': 'Órarend',
  'reservations': 'Foglalások',
  'management': 'Kezelés',
  'profile': 'Profil',
  'settings': 'Beállítások',
  'appearance': 'Megjelenés',
  'appearanceDescription':
      'Válasszon világos, sötét vagy rendszer szerinti módot.',
  'themeSystem': 'Rendszer szerint',
  'themeLight': 'Világos mód',
  'themeDark': 'Sötét mód',
  'menuPosition': 'Menü helye',
  'menuPositionDescription':
      'Válassza ki, melyik oldalon jelenjen meg a főmenü.',
  'rightHanded': 'Jobbkezes',
  'leftHanded': 'Balkezes',
  'menuRightPositionDescription': 'A menü jobb felül jelenik meg.',
  'menuLeftPositionDescription': 'A menü bal felül jelenik meg.',
  'language': 'Nyelv',
  'languageDescription': 'Válassza ki az alkalmazás nyelvét.',
  'languageSlovak': '🇸🇰 Szlovák',
  'languageEnglish': '🇬🇧 Angol',
  'languageGerman': '🇩🇪 Német',
  'languageFrench': '🇫🇷 Francia',
  'languagePolish': '🇵🇱 Lengyel',
  'languageHungarian': '🇭🇺 Magyar',
  'languageUkrainian': '🇺🇦 Ukrán',
  'languageRussian': '🇷🇺 Orosz',
  'languageSerbian': '🇷🇸 Szerb',
  'languageCzech': '🇨🇿 Cseh',
  'role': 'Szerep',
  'roleUser': 'Felhasználó',
  'roleTrainer': 'Edző',
  'roleAdmin': 'Adminisztrátor',
  'roleUnknown': 'Ismeretlen szerep',
  'privacyPolicy': 'Adatvédelmi tájékoztató',
  'emailContact': 'E-mail',
  'loginTitle': 'Bejelentkezés',
  'registerTitle': 'Regisztráció',
  'continueWithGoogle': 'Folytatás Google-fiókkal',
  'continueWithFacebook': 'Folytatás Facebook-fiókkal',
  'or': 'Vagy',
  'email': 'E-mail',
  'password': 'Jelszó',
  'login': 'Bejelentkezés',
  'register': 'Regisztráció',
  'logout': 'Kijelentkezés',
  'noAccountRegister': 'Nincs fiókja? Regisztráció',
  'hasAccountLogin': 'Már van fiókja? Bejelentkezés',
  'authError': 'Bejelentkezési hiba',
  'acceptTerms': 'Elfogadom az üzleti feltételeket',
  'acceptPrivacy': 'Hozzájárulok a személyes adatok kezeléséhez',
  'termsConsentRequired':
      'A regisztrációhoz el kell fogadni az üzleti feltételeket.',
  'privacyConsentRequired':
      'A regisztrációhoz hozzá kell járulni a személyes adatok kezeléséhez.',
  'openTerms': 'Üzleti feltételek megnyitása',
  'openPrivacy': 'Adatvédelmi tájékoztató megnyitása',
  'termsVersion': '2026-05-16',
  'privacyVersion': '2026-05-16',
  'continueWithoutAccount': 'Folytatás fiók nélkül',
  'completeEmailOrLogout':
      'Ha nem szeretné megadni az e-mail-címet, folytathatja fiók nélkül, és később másik fiókkal jelentkezhet be.',
  'fillEmailPassword': 'Töltse ki az e-mail-címet és a jelszót.',
  'invalidEmailFormat': 'Adjon meg érvényes e-mail-címet.',
  'passwordTooShort': 'A jelszónak legalább 6 karakter hosszúnak kell lennie.',
  'wrongEmailOrPassword': 'A megadott e-mail-cím vagy jelszó nem megfelelő.',
  'userAlreadyExists': 'Ezzel az e-mail-címmel már létezik felhasználó.',
  'weakPassword': 'A megadott jelszó túl gyenge.',
  'tooManyRequests': 'Túl sok próbálkozás. Próbálja meg később.',
  'networkError': 'Ellenőrizze az internetkapcsolatot.',
  'signInCancelled': 'A bejelentkezést megszakították.',
  'facebookLoginFailed': 'A Facebook-bejelentkezés nem sikerült.',
  'unknownAuthError': 'Ismeretlen hiba történt a bejelentkezés során.',
  'inactiveAccount':
      'A fiókja deaktiválva van. Vegye fel a kapcsolatot az adminisztrátorral.',
  'verificationEmailSent':
      'A regisztráció sikeres volt. Elküldtük az ellenőrző e-mailt. Ha nem találja a beérkezett üzenetek között, ellenőrizze a Spam mappát is.',
  'emailNotVerified':
      'Először erősítse meg a regisztrációt az e-mailben található hivatkozásra kattintva.',
  'verificationEmailSentAgain':
      'Újra elküldtük az ellenőrző e-mailt. Ha nem találja a beérkezett üzenetek között, ellenőrizze a Spam mappát is.',
  'forgotPassword': 'Elfelejtette a jelszavát?',
  'resetPasswordTitle': 'Jelszó visszaállítása',
  'sendResetEmail': 'E-mail küldése',
  'passwordResetEmailSent':
      'Ha létezik fiók ezzel az e-mail-címmel, elküldtük a jelszó-visszaállító e-mailt.',
  'emailRequired': 'Adja meg az e-mail-címet.',
  'emailNotProvided': 'Nem adott meg e-mail-címet',
  'emailSaved': 'Az e-mail-cím mentve lett.',
  'emailSaveError': 'Az e-mail-címet nem sikerült menteni.',
  'emailChangeVerificationSent':
      'Az új e-mail-címre ellenőrző hivatkozást küldtünk. A módosítás a hivatkozás megerősítése után fejeződik be.',
  'emailChangeRequestError': 'Az e-mail módosítását nem sikerült elindítani.',
  'emailChangeNotAvailable':
      'Az e-mail módosítása csak e-maillel és jelszóval létrehozott fiókoknál érhető el.',
  'completeProfileTitle': 'Profil kiegészítése',
  'editProfile': 'Profil szerkesztése',
  'firstName': 'Keresztnév',
  'lastName': 'Vezetéknév',
  'publicName': 'Megjelenített név',
  'publicNameHint': 'Pl. Barbora, Katka, Aďo',
  'firstNameRequired': 'Adja meg a keresztnevet.',
  'lastNameRequired': 'Adja meg a vezetéknevet.',
  'publicNameRequired': 'Adja meg a megjelenített nevet.',
  'profileSaved': 'A profil mentve lett.',
  'profileSaveError': 'A profilt nem sikerült menteni.',
  'loggedInUser': 'Bejelentkezett felhasználó',
  'completeEmailTitle': 'E-mail-cím megadása',
  'completeEmailDescription':
      'Az alkalmazás használatához szükségünk van az e-mail-címére. Ezt a fiók kapcsolattartási e-mail-címeként használjuk.',
  'deleteAccountRequest': 'Fiók törlésének kérése',
  'deleteAccountRequestTitle': 'Fiók törlése',
  'deleteAccountRequestDescription':
      'A kérelem elküldése után a fiók deaktiválva lesz, és nem lehet majd bejelentkezni. Az adatokat ezután az adminisztrátor az adatvédelmi szabályok szerint kezeli.',
  'deleteAccountReason': 'Kérelem oka',
  'deleteAccountConfirm': 'Biztosan kéri a fiók törlését?',
  'deleteAccountRequestSent': 'A fióktörlési kérelem elküldve.',
  'deleteAccountRequestError': 'A fióktörlési kérelmet nem sikerült elküldeni.',
  'deleteAccountBlockedActiveReservations':
      'A fiók nem törölhető, mert aktív foglalásai vannak.',
  'accountDeletionRequests': 'Fióktörlési kérelmek',
  'accountDeletionRequestsWithCount': 'Fióktörlési kérelmek',
  'accountDeletionRequestsLoadError':
      'A fióktörlési kérelmeket nem sikerült betölteni.',
  'noAccountDeletionRequests': 'Nincs nyilvántartott függőben lévő kérelem.',
  'completeAccountDeletion': 'Fiók anonimizálása',
  'completeAccountDeletionTitle': 'Fiók anonimizálása',
  'completeAccountDeletionQuestion':
      'Biztosan anonimizálni szeretné ezt a fiókot? Ez a művelet felülírja a felhasználó személyes adatait.',
  'accountDeletionCompleted': 'A fiók anonimizálva lett.',
  'accountDeletionCompleteError': 'A fiókot nem sikerült anonimizálni.',
  'requestedAt': 'Kérelmezve',
  'accountDeletionRequestsWaiting': 'Feldolgozásra váró kérelmek.',
  'changeEmail': 'E-mail módosítása',
  'changeEmailTitle': 'E-mail módosítása',
  'changeEmailDescription':
      'Adja meg az új e-mail-címet és a jelenlegi jelszót. Az új e-mail-címre ellenőrző hivatkozást küldünk. A módosítás csak a hivatkozás megerősítése után fejeződik be.',
  'changeEmailProfileHint':
      'E-maillel és jelszóval létrehozott fiókoknál érhető el.',
  'newEmail': 'Új e-mail',
  'currentPassword': 'Jelenlegi jelszó',
  'sendVerificationEmail': 'Ellenőrző e-mail küldése',
  'wrongCurrentPassword': 'A jelenlegi jelszó nem megfelelő.',
  'requiresRecentLogin':
      'Ehhez a művelethez először jelentkezzen ki, majd jelentkezzen be újra.',
  'changeProfilePhoto': 'Profilkép módosítása',
  'chooseFromGallery': 'Kiválasztás a galériából',
  'takePhoto': 'Fénykép készítése',
  'removePhoto': 'Fénykép eltávolítása',
  'editPhoto': 'Fénykép szerkesztése',
  'cropProfilePhoto': 'Profilkép körülvágása',
  'profilePhotoUpdated': 'A profilkép mentve lett.',
  'profilePhotoUpdateError': 'A profilképet nem sikerült menteni.',
  'profilePhotoRemoveError': 'A profilképet nem sikerült eltávolítani.',
  'requestDiscount': 'Kedvezmény igénylése',
  'discountStatus': 'Kedvezmény státusza',
  'discountStatusNone': 'Nincs kedvezmény',
  'discountStatusPending': 'Jóváhagyásra vár',
  'discountStatusApproved': 'Jóváhagyott kedvezmény',
  'discountStatusRejected': 'Elutasított kérelem',
  'discountStatusExpired': 'A kedvezmény érvényessége lejárt',
  'discountType': 'Kedvezmény típusa',
  'discountTypeNormal': 'Normál felhasználó',
  'discountTypeStudent': 'Diák',
  'discountTypeSenior': 'Nyugdíjas',
  'discountTypeZtp': 'Fogyatékkal élő személy',
  'discountTypeIndividual': 'Egyéni kedvezmény',
  'discountRequestDescription':
      'Válassza ki az igényelt kedvezmény típusát. A kérelmet elküldés után az adminisztrátor ellenőrzi.',
  'discountRequestNote': 'Megjegyzés a kérelemhez',
  'discountRequestSent': 'A kedvezménykérelem elküldve.',
  'discountRequestError': 'A kedvezménykérelmet nem sikerült elküldeni.',
  'discountRequestAlreadyPending':
      'Már van folyamatban lévő kedvezménykérelme.',
  'discountRequestPending': 'A kérelem jóváhagyásra vár',
  'sendRequest': 'Kérelem elküldése',
  'discountDocument': 'Kedvezményhez kapcsolódó igazolás',
  'discountDocumentDescription':
      'Töltse fel az igazolás fényképét, amely alapján az adminisztrátor ellenőrzi a kedvezményre való jogosultságot.',
  'chooseDiscountDocument': 'Igazolás kiválasztása',
  'discountDocumentRequired': 'A kérelem elküldéséhez igazolást kell csatolni.',
  'discountDocumentSelected': 'Az igazolás ki lett választva',
  'takeDiscountDocumentPhoto': 'Igazolás lefényképezése',
  'chooseDiscountDocumentFromGallery': 'Kiválasztás a galériából',
  'discountRequests': 'Kedvezménykérelmek',
  'discountRequestsDescription':
      'Felhasználói kedvezménykérelmek jóváhagyása vagy elutasítása.',
  'discountRequestsLoadError': 'A kedvezménykérelmeket nem sikerült betölteni.',
  'noDiscountRequests': 'Nincs nyilvántartott függőben lévő kedvezménykérelem.',
  'approveDiscount': 'Kedvezmény jóváhagyása',
  'rejectDiscount': 'Kérelem elutasítása',
  'discountApproved': 'A kedvezmény jóváhagyva.',
  'discountRejected': 'A kedvezménykérelem elutasítva.',
  'discountDecisionError': 'A kérelemhez tartozó döntést nem sikerült menteni.',
  'discountValidUntilRequired':
      'Válassza ki a kedvezmény érvényességi dátumát.',
  'discountAdminNote': 'Adminisztrátori megjegyzés',
  'selectDiscountValidUntil': 'Válassza ki a kedvezmény érvényességét',
  'discountDocumentPreview': 'Igazolás előnézete',
  'todayReservations': 'Mai foglalások',
  'noTodayReservations': 'Mára nincs lefoglalt edzése.',
  'nearestTraining': 'Legközelebbi edzés',
  'nearestTrainings': 'Legközelebbi edzések',
  'noNearestTraining': 'Nincs tervezett legközelebbi edzés.',
  'todaysTrainings': 'Mai edzések',
  'noTodaysTrainings': 'Mára nincs tervezett edzés.',
  'myMemberships': 'Saját bérleteim',
  'activeMembershipsCount': 'Aktív bérletek',
  'availableEntriesSummary': 'Elérhető belépések',
  'reservedEntriesSummary': 'Lefoglalt belépések',
  'dailyMembershipsSummary': 'Napi bérletek',
  'tapToShowQrCode': 'Kattintson a QR-kód megjelenítéséhez.',
  'nearestReservations': 'Közelgő foglalások',
  'noNearestReservations': 'Nincsenek közelgő foglalásai.',
  'qrShort': 'QR',
  'membershipStatus': 'Bérlet állapota',
  'remainingEntries': 'Hátralévő belépések',
  'upcomingTraining': 'Legközelebbi mai edzés',
  'schedulePlaceholder': 'Itt jelenik meg az edzések órarendje.',
  'reservationsPlaceholder': 'Itt jelennek meg a foglalások.',
  'newsPlaceholder': 'Itt jelennek meg az edzők hírei és üzenetei.',
  'aboutApp': 'Az alkalmazásról',
  'aboutUs': 'Rólunk',
  'aboutAppDescription':
      'A Body Fit Club TT alkalmazás az edzések, foglalások, bérletek és a fitneszközpont és a felhasználók közötti kommunikáció kezelésére szolgál.',
  'aboutUsDescription':
      'A Body Fit Club egy trnavai fitneszközpont, amely csoportos és egyéni edzésekre, mozgásra, egészséges életmódra és személyes ügyfélkezelésre összpontosít.',
  'bodyFitClubWebsite': 'Https://bodyfitclub.sk/',
  'openWebsite': 'Weboldal megnyitása',
  'businessTerms': 'Üzleti feltételek',
  'legalDocumentsInfo':
      'Az üzleti feltételek és az adatvédelmi információk a Body Fit Club weboldalán lesznek elérhetők.',
  'contacts': 'Kapcsolatok',
  'billingDetails': 'Számlázási adatok',
  'address': 'Cím',
  'phone': 'Telefon',
  'website': 'Weboldal',
  'socialNetworks': 'Közösségi hálók',
  'openMap': 'Térkép megnyitása',
  'openFacebook': 'Facebook',
  'openInstagram': 'Instagram',
  'multisport': 'Multisport',
  'multisportInfo':
      'A MultiSport kártyát az aktuális üzemeltetési feltételek szerint fogadjuk el.',
  'bodyFitClubCompanyName': 'BODYFIT CLUB s.r.o.',
  'bodyFitClubOperationAddress': 'V Jame 24, Trnava',
  'bodyFitClubBillingAddress': 'J. G. Tajovského 18, 917 08 Trnava',
  'bodyFitClubPhonePrimary': '+421 902 860 008',
  'bodyFitClubPhoneSecondary': '+421 903 946 895',
  'bodyFitClubEmail': 'Bodyfitclubtt@gmail.com',
  'bodyFitClubIco': '48074128',
  'ico': 'Cégjegyzékszám:',
  'companySeat': 'Székhely',
  'operation': 'Telephely',
  'bodyFitClubFacebookUrl': 'Https://www.facebook.com/bodyfitclub.sk',
  'bodyFitClubInstagramUrl': 'Https://www.instagram.com/bodyfitclub.tt/',
  'bodyFitClubMapUrl':
      'Https://www.google.com/maps/search/?api=1&query=V%20Jame%206641%2F24%2C%20917%2001%20Trnava',
  'bodyFitClubMultiSportUrl':
      'Https://multi-sport.sk/aktivity/partner/bodyfit-club/',
  'multisportInfo2':
      'A Body Fit Club a MultiSport program partnere. A MultiSport kártya elfogadására az aktuális üzemeltetési feltételek vonatkoznak.',
  'bodyFitClubWebsiteLabel': 'Www.bodyfitclub.sk',
  'dic': 'Adószám:',
  'bodyFitClubDic': '2120035445',
  'notVatPayer': 'A társaság nem áfafizető',
  'legalDocuments': 'Jogi dokumentumok',
  'priceList': 'Árlista',
  'priceListAudience': 'Kinek',
  'priceListAudienceNormal': 'Normál felhasználóknak',
  'priceListAudienceDiscount': 'Kedvezményes felhasználóknak',
  'priceListAudienceAll': 'Mindenkinek',
  'price': 'Ár',
  'singleEntries': 'Egyszeri belépések',
  'priceListMemberships': 'Bérletek',
  'chooseEntry': 'Válasszon belépést',
  'noAvailablePlans': 'Jelenleg nincs elérhető vásárlási lehetőség.',
  'news': 'Hírek',
  'noPublicMessages': 'Még nincsenek üzenetek.',
  'writeMessage': 'Üzenet írása',
  'writeMessageShort': 'Írás',
  'editMessage': 'Üzenet szerkesztése',
  'deleteMessage': 'Üzenet törlése',
  'deleteMessageQuestion': 'Biztosan törölni szeretné ezt az üzenetet?',
  'messageText': 'Üzenet szövege',
  'messageHint': 'Írjon üzenetet...',
  'sendMessage': 'Küldés',
  'updateMessage': 'Módosítások mentése',
  'messageSaved': 'Az üzenet mentve lett.',
  'messageDeleted': 'Az üzenet törölve lett.',
  'messageSaveError': 'Az üzenetet nem sikerült menteni.',
  'messageDeleteError': 'Az üzenetet nem sikerült törölni.',
  'editedBy': 'Módosította',
  'editedByAdmin': 'Adminisztrátor módosította',
  'editedByTrainer': 'Edző módosította',
  'userFallback': 'Felhasználó',
  'noTrainings': 'Jelenleg nincs elérhető edzés.',
  'noTrainingsForSelectedDay': 'Erre a napra nincs tervezett edzés.',
  'trainer': 'Edző',
  'freeSpots': 'Szabad helyek',
  'reserve': 'Foglalás',
  'reserved': 'Lefoglalva',
  'fullCapacity': 'Betelt',
  'trainingsLoadError': 'Az órarendet nem sikerült betölteni.',
  'unknownTraining': 'Ismeretlen edzés',
  'unknownTrainer': 'Ismeretlen edző',
  'unknownUser': 'Ismeretlen felhasználó',
  'trainingSessionFinished': 'Lezajlott',
  'trainingSessionTooFarInFuture':
      'Az időpont túl messze van a jövőben. Manuálisan csak az órarendben megjelenített időszakra adhat hozzá edzést.',
  'managementDescription':
      'Itt kezelheti az edzésidőpontokat, a jelenlétet, a bérleteket és a felhasználókat.',
  'scheduleManagement': 'Órarend kezelése',
  'scheduleManagementDescription':
      'Edzéstípusok, órarendsablonok és konkrét edzésidőpontok kezelése.',
  'attendanceManagement': 'Jelenlét kezelése',
  'usersManagement': 'Felhasználók kezelése',
  'usersManagementComingSoon':
      'A felhasználók kezelése később lesz kiegészítve.',
  'scheduleTemplatesManagement': 'Órarendsablonok kezelése',
  'reactivateUser': 'Felhasználó aktiválása',
  'reactivateUserQuestion':
      'Biztosan újra aktiválni szeretné ezt a felhasználót?',
  'userReactivated': 'A felhasználó újra aktiválva lett.',
  'trainingTypesManagement': 'Edzéstípusok kezelése',
  'addTrainingType': 'Edzéstípus hozzáadása',
  'editTrainingType': 'Edzéstípus szerkesztése',
  'deleteTrainingType': 'Edzéstípus törlése',
  'trainingType': 'Edzéstípus',
  'selectTrainingType': 'Válasszon edzéstípust',
  'trainingName': 'Edzés neve',
  'description': 'Leírás',
  'defaultDuration': 'Alapértelmezett időtartam',
  'defaultCapacity': 'Alapértelmezett kapacitás',
  'noTrainingTypes': 'Jelenleg nincs létrehozott edzéstípus.',
  'trainingTypesLoadError': 'Az edzéstípusokat nem sikerült betölteni.',
  'trainingTypeCreated': 'Az edzéstípus létrehozva.',
  'trainingTypeUpdated': 'Az edzéstípus módosítva.',
  'trainingTypeDeleted': 'Az edzéstípus törölve.',
  'trainingTypeDeleteQuestion':
      'Biztosan törölni szeretné ezt az edzéstípust? Új időpontoknál már nem lesz elérhető.',
  'trainingTypeAlreadyExists': 'Már létezik ilyen nevű edzéstípus.',
  'trainingTypeUsedByTemplate':
      'Az edzéstípust nem lehet törölni, mert aktív órarendsablon használja.',
  'trainingTypeUsedBySession':
      'Az edzéstípust nem lehet törölni, mert jövőbeli edzésidőpont használja.',
  'addTrainingSession': 'Edzésidőpont hozzáadása',
  'editTrainingSession': 'Edzés részleteinek szerkesztése',
  'trainingSessionCreated': 'Az edzésidőpont létrehozva.',
  'trainingSessionUpdated': 'Az edzésidőpont módosítva.',
  'updateTrainingSessionError': 'Az edzésidőpontot nem sikerült módosítani.',
  'trainingSessionInPast': 'Az edzésidőpont nem lehet a múltban.',
  'trainingSessionOverlap': 'Ebben az időpontban már van másik edzés.',
  'capacityLowerThanReservations':
      'A kapacitás nem lehet kisebb a meglévő foglalások számánál.',
  'cancelTrainingSession': 'Időpont törlése',
  'cancelTrainingSessionTitle': 'Edzésidőpont törlése',
  'cancelTrainingSessionQuestion':
      'Biztosan törölni szeretné ezt az edzésidőpontot? Az aktív foglalások törlődnek, és a lefoglalt belépések felszabadulnak. Ha a belépés már felhasználásra került, visszakerül a felhasználóhoz.',
  'cancelTrainingSessionConfirm': 'Időpont törlése',
  'trainingSessionCancelled': 'Az edzésidőpont törölve.',
  'cancelTrainingSessionError': 'Az edzésidőpontot nem sikerült törölni.',
  'trainerCanCancelOnlyOwnSession':
      'Az edző csak a saját időpontját törölheti.',
  'trainerCannotCancelStartedSession':
      'Az edző nem törölhet már elkezdődött vagy lezajlott időpontot.',
  'date': 'Dátum',
  'startTime': 'Kezdés',
  'duration': 'Időtartam',
  'capacity': 'Kapacitás',
  'selectDate': 'Válasszon dátumot',
  'selectTrainer': 'Válasszon edzőt',
  'trainersLoadError': 'Az edzőket nem sikerült betölteni.',
  'fillAllFields': 'Töltse ki az összes kötelező adatot.',
  'invalidCapacity': 'A kapacitásnak nagyobbnak kell lennie 0-nál.',
  'invalidDuration': 'Az időtartamnak nagyobbnak kell lennie 0-nál.',
  'saveError': 'A mentés nem sikerült.',
  'addScheduleTemplate': 'Órarendsablon hozzáadása',
  'editScheduleTemplate': 'Órarendsablon szerkesztése',
  'deleteScheduleTemplate': 'Órarendsablon törlése',
  'noScheduleTemplates': 'Jelenleg nincs létrehozott órarendsablon.',
  'weekday': 'A hét napja',
  'selectWeekday': 'Válasszon napot',
  'scheduleTemplateCreated': 'Az órarendsablon létrehozva.',
  'scheduleTemplateUpdated': 'Az órarendsablon módosítva.',
  'scheduleTemplateDeleted': 'Az órarendsablon törölve.',
  'scheduleTemplateDeleteQuestion':
      'Biztosan törölni szeretné ezt az órarendsablont? Új időpontok generálásánál már nem lesz használva.',
  'scheduleTemplateAlreadyExists': 'Már létezik ilyen órarendsablon.',
  'scheduleTemplateLoadError': 'Az órarendsablonokat nem sikerült betölteni.',
  'scheduleTemplateOverlap': 'Ebben az időben már létezik másik órarendsablon.',
  'capacityLabel': 'Kapacitás',
  'reservationCreated': 'A foglalás létrehozva.',
  'reservationAlreadyExists': 'Erre az edzésre már van foglalása.',
  'reservationTrainingFull': 'Ez az edzés már betelt.',
  'reservationTrainingNotAvailable': 'Ez az edzés már nem foglalható.',
  'reservationTrainingAlreadyStarted':
      'Erre az edzésre már nem lehet foglalni.',
  'reservationError': 'A foglalást nem sikerült létrehozni.',
  'myReservations': 'Saját foglalásaim',
  'noReservations': 'Jelenleg nincs foglalása.',
  'cancelReservation': 'Foglalás törlése',
  'cancelReservationTitle': 'Foglalás törlése',
  'cancelReservationQuestion': 'Biztosan törölni szeretné ezt a foglalást?',
  'reservationCancelled': 'A foglalás törölve.',
  'reservationCancelError': 'A foglalást nem sikerült törölni.',
  'reservationsLoadError': 'A foglalásokat nem sikerült betölteni.',
  'cancelReservations': 'Foglalások törlése',
  'cancelReservationsBeforeDeactivation':
      'Deaktiválás vagy bérlet törlése előtt először törölje a lefoglalt foglalásokat.',
  'cancelReservationForMembership': 'Foglalás törlése',
  'cancelReservationForMembershipQuestion':
      'Biztosan törölni szeretné ezt a bérlethez kapcsolódó foglalást? A lefoglalt belépés felszabadul.',
  'reservationForMembershipCancelled':
      'A foglalás törölve lett, és a lefoglalt belépés felszabadult.',
  'noReservationsForTrainingHistory': 'Ezen az edzésen nincsenek foglalások.',
  'reservationQrCode': 'Foglalás QR-kódja',
  'memberships': 'Bérletek',
  'assignMembership': 'Bérlet hozzárendelése',
  'selectUser': 'Válasszon felhasználót',
  'selectMembershipPlan': 'Válasszon bérlettípust',
  'membershipPlansLoadError': 'A bérlettípusokat nem sikerült betölteni.',
  'membershipAssigned': 'A bérlet hozzárendelve.',
  'membershipAssignError': 'A bérletet nem sikerült hozzárendelni.',
  'membershipPlan': 'Bérlettípus',
  'client': 'Felhasználó',
  'buyMembership': 'Bérlet vásárlása',
  'buySingleEntry': 'Egyszeri belépés vásárlása',
  'chooseMembership': 'Válasszon bérletet',
  'payment': 'Fizetés',
  'pay': 'Fizetés',
  'paymentSuccessful': 'Sikeres fizetés.',
  'paymentFailed': 'A fizetés sikertelen.',
  'activeMembership': 'Aktív bérlet',
  'noActiveMembership': 'Nincs aktív bérlete.',
  'validUntil': 'Érvényes eddig',
  'membershipLoadError': 'A bérletet nem sikerült betölteni.',
  'noAvailableEntries': 'Nincs elérhető belépése a foglaláshoz.',
  'noUpcomingTraining': 'Mára nincs lefoglalt edzése.',
  'membershipsManagement': 'Bérletek kezelése',
  'membershipDetail': 'Bérlet részletei',
  'noMemberships': 'Jelenleg nincs elérhető bérlet.',
  'status': 'Állapot',
  'validFrom': 'Érvényes ettől',
  'entriesTotal': 'Belépések összesen',
  'entriesRemaining': 'Hátralévő belépések',
  'entriesReserved': 'Foglalásokban lefoglalva',
  'entriesAvailable': 'Elérhető belépések',
  'adminMembershipEdit': 'Adminisztrátori módosítás',
  'membershipStatusActive': 'Aktív',
  'membershipStatusInactive': 'Inaktív',
  'membershipStatusCancelled': 'Törölt',
  'membershipStatusExpired': 'Lejárt',
  'membershipStatusUsedUp': 'Felhasznált',
  'membershipUpdated': 'A bérlet módosítva.',
  'membershipUpdateError': 'A bérletet nem sikerült módosítani.',
  'invalidRemainingEntries':
      'Adjon meg érvényes számot a hátralévő belépésekhez.',
  'allocatedReservations': 'Lefoglalt foglalások',
  'cancelAllocatedReservations': 'Lefoglalt foglalások törlése',
  'cancelAllocatedReservationsQuestion':
      'Biztosan törölni szeretné az ehhez a bérlethez kapcsolódó aktív foglalásokat? A lefoglalt belépések felszabadulnak.',
  'cancelAllReservations': 'Összes foglalás törlése',
  'cancelAllocatedReservationsError':
      'A lefoglalt foglalásokat nem sikerült törölni.',
  'usedEntries': 'Felhasznált belépések',
  'noAllocatedReservations':
      'Ehhez a bérlethez jelenleg nincs lefoglalt foglalás.',
  'noUsedEntries': 'Ebből a bérletből még nem használtak fel belépést.',
  'membershipUsageLoadError': 'A bérlet előzményeit nem sikerült betölteni.',
  'searchMemberships': 'Keresés felhasználó vagy bérlet szerint',
  'allMembershipStatuses': 'Minden állapot',
  'membershipStatusNotYetValid': 'Még nem érvényes',
  'membershipStatusUsable': 'Aktív',
  'invalidRemainingEntriesHigherThanTotal':
      'A hátralévő belépések száma nem lehet nagyobb az összes belépés számánál.',
  'invalidRemainingEntriesLowerThanReserved':
      'A hátralévő belépések száma nem lehet kisebb a lefoglalt belépések számánál.',
  'membershipPrefix': 'Bérlet',
  'statusPrefix': 'Állapot',
  'attendance': 'Jelenlét',
  'attendanceLoadError': 'A jelenlétet nem sikerült betölteni.',
  'noActiveReservationsForAttendance':
      'Jelenleg nincs aktív foglalás a jelenlét jelöléséhez.',
  'attended': 'Megjelent',
  'noShow': 'Nem jelent meg',
  'markAttendedTitle': 'Jelenlét jelölése',
  'markNoShowTitle': 'Távolmaradás jelölése',
  'markAttendedQuestion': 'Biztosan jelenlévőnek jelöli a felhasználót?',
  'markNoShowQuestion': 'Biztosan távolmaradónak jelöli a felhasználót?',
  'attendanceMarked': 'A jelenlét mentve lett.',
  'attendanceMarkError': 'A jelenlétet nem sikerült menteni.',
  'attendedStatus': 'Megjelent',
  'noShowStatus': 'Nem jelent meg',
  'attendedCountLabel': 'Megjelentek',
  'noShowCountLabel': 'Nem jelentek meg',
  'attendanceActionDone': 'A jelenlét módosítása mentve lett.',
  'attendanceActionError': 'A jelenlét módosítását nem sikerült menteni.',
  'showQrCode': 'QR-kód',
  'showQrToTrainer': 'Érkezéskor mutassa meg ezt a QR-kódot az edzőnek.',
  'scanQrCode': 'QR-kód beolvasása',
  'scanQrCodes': 'QR-kódok beolvasása',
  'scanQrCodeHint': 'Irányítsa a kamerát a felhasználó foglalási QR-kódjára.',
  'invalidQrCode': 'Érvénytelen foglalási QR-kód.',
  'qrCodeScanned': 'A QR-kód beolvasva.',
  'qrScanSuccessful':
      'A QR-kód beolvasva. Beolvashatja a következő felhasználót.',
  'trainerQrScanTooEarly':
      'A QR-kód legkorábban 30 perccel az edzés kezdete előtt olvasható be.',
  'trainingHistory': 'Edzés Előzmények',
  'trainingHistoryDetail': 'Edzés Előzmények Részlet',
  'trainingHistoryLoadError': 'Edzés Előzmények Betöltés Hiba',
  'trainingHistoryReservationsLoadError':
      'Edzés Előzmények foglalások Betöltés Hiba',
  'noTrainingHistoryInSelectedPeriod':
      'Nincs edzés Előzmények in kiválasztva period',
  'fromDatePrefix': 'Ettől',
  'toDatePrefix': 'Eddig',
  'planned': 'Tervezett',
  'cancelled': 'Törölve',
  'finished': 'Befejezve',
  'reservedStatus': 'Foglalt állapot',
  'reservedCountLabel': 'Foglalt szám',
  'cancelledCountLabel': 'Törölve szám',
  'markedAtPrefix': 'Jelölve',
  'markAsAttended': 'Mark as attended',
  'markAsNoShow': 'Mark as Nincs Megjelenítés',
  'revertAttendance': 'Jelenlét visszavonása',
  'revertNoShow': 'Távolmaradás visszavonása',
  'markAsAttendedQuestion': 'Mark as attended',
  'markAsNoShowQuestion': 'Mark as Nincs Megjelenítés',
  'revertAttendanceQuestion':
      'Biztosan visszavonja a jelölt jelenlétet? A felhasznált belépés visszakerül a bérletre.',
  'revertNoShowQuestion':
      'Biztosan visszavonja a jelölt távolmaradást? A felhasznált belépés visszakerül a bérletre.',
  'addTrainingAttendance': 'Hozzáadás edzés jelenlét',
  'selectAttendanceUser': 'Válasszon jelenlét felhasználó',
  'selectAttendanceMembership': 'Válasszon jelenlét bérlet',
  'noUsersForAttendance': 'Nincs felhasználók ehhez: jelenlét',
  'noUsableMembershipsForAttendance':
      'Nincs használható bérletek ehhez: jelenlét',
  'addTrainingAttendanceQuestion': 'Hozzáadás edzés jelenlét',
  'trainingAttendanceAdded': 'Edzés jelenlét added',
  'trainingAttendanceAddError': 'Edzés jelenlét Hozzáadás Hiba',
  'userAlreadyHasReservationForTraining':
      'Felhasználó már has foglalás ehhez: edzés',
  'usersLoadError': 'Felhasználók Betöltés Hiba',
  'allRoles': 'Összes roles',
  'searchUsers': 'Keresés felhasználók',
  'noUsersFound': 'Nincs felhasználók található',
  'editUser': 'Szerkesztés felhasználó',
  'userUpdated': 'A felhasználó módosítva lett.',
  'userUpdateError': 'Felhasználó Frissítés Hiba',
  'cannotChangeOwnRole': 'Nem módosíthatja a saját szerepét',
  'changeRoleWarning': 'Módosítás Szerep warning',
  'deactivateUser': 'Deaktiválás felhasználó',
  'deactivationReason': 'Deactivation Ok',
  'userDeactivated': 'Felhasználó Deaktiválva',
  'deactivateUserQuestion': 'Deaktiválás felhasználó',
  'cannotDeactivateYourself': 'Nem deaktiválhatja a saját fiókját',
  'userUsedByTemplate': 'Felhasználó Használt által sablon',
  'userUsedByFutureSession': 'Felhasználó Használt által future időpont',
  'userHasActiveReservations': 'Felhasználó has Aktív foglalások',
  'userHasActiveMemberships': 'Felhasználó has Aktív bérletek',
  'inactiveUser': 'Inactive felhasználó',
  'userCannotBeDeactivated': 'Felhasználó nem lehet be Deaktiválva',
  'userCannotBeDeactivatedDescription':
      'Deaktiválás előtt először rendezni kell az aktív foglalásait vagy bérleteit.',
  'userHasBlockingItems': 'Felhasználó has blocking items',
  'activeReservationsCount': 'Aktív foglalások szám',
  'showMemberships': 'Megjelenítés bérletek',
  'auditLogs': 'Műveleti előzmények',
  'auditLogsDescription': 'Az alkalmazás fontos műveleteinek áttekintése.',
  'auditLogsLoadError': 'A műveleti előzményeket nem sikerült betölteni.',
  'noAuditLogs': 'Nem található művelet.',
  'searchAuditLogs': 'Keresés felhasználó, e-mail vagy leírás szerint',
  'auditCategory': 'Kategória',
  'auditAction': 'Művelet',
  'auditActor': 'Végrehajtotta',
  'auditActorRole': 'Végrehajtó szerepe',
  'auditPeriod': 'Időszak',
  'auditAllCategories': 'Minden kategória',
  'auditCategoryMemberships': 'Bérletek',
  'auditCategoryReservations': 'Foglalások',
  'auditCategoryAttendance': 'Jelenlét',
  'auditCategoryUsers': 'Felhasználók',
  'auditCategorySchedule': 'Órarend',
  'auditCategoryMessages': 'Üzenetek',
  'auditCategoryPayments': 'Fizetések',
  'auditCategoryProfile': 'Profil',
  'auditAllActions': 'Minden művelet',
  'auditActionCreated': 'Létrehozás',
  'auditActionUpdated': 'Módosítás',
  'auditActionCancelled': 'Törlés',
  'auditActionDeactivated': 'Deaktiválás',
  'auditActionActivated': 'Aktiválás',
  'auditActionAssigned': 'Hozzárendelés',
  'auditActionPurchased': 'Vásárlás',
  'auditActionPaymentSucceeded': 'Sikeres fizetés',
  'auditActionPaymentFailed': 'Sikertelen fizetés',
  'auditActionAttendanceMarked': 'Jelenlét',
  'auditActionQrChecked': 'QR-ellenőrzés',
  'auditAllActorRoles': 'Minden szerep',
  'auditReservationCreatedTitle': 'Foglalás létrehozása',
  'auditReservationCreatedDescription':
      'A felhasználó foglalást hozott létre egy edzésre.',
  'auditReservationCancelledTitle': 'Foglalás törlése',
  'auditReservationCancelledDescription':
      'A felhasználó foglalása törölve lett.',
  'auditAttendanceAttendedTitle': 'Jelenlét jelölve',
  'auditAttendanceAttendedDescription':
      'A felhasználó jelenlévőként lett megjelölve az edzésen.',
  'auditAttendanceNoShowTitle': 'Távolmaradás jelölve',
  'auditAttendanceNoShowDescription':
      'A felhasználó távolmaradóként lett megjelölve az edzésen.',
  'auditTrainingTypeCreatedTitle': 'Edzéstípus létrehozása',
  'auditTrainingTypeUpdatedTitle': 'Edzéstípus módosítása',
  'auditTrainingTypeDeactivatedTitle': 'Edzéstípus deaktiválása',
  'auditTrainingSessionCreatedTitle': 'Időpont létrehozása',
  'auditTrainingSessionUpdatedTitle': 'Időpont módosítása',
  'auditTrainingSessionTimeChangedTitle': 'Időpont módosítása',
  'auditTrainingSessionCancelledTitle': 'Időpont törlése',
  'auditScheduleTemplateCreatedTitle': 'Órarendsablon létrehozása',
  'auditScheduleTemplateUpdatedTitle': 'Órarendsablon módosítása',
  'auditScheduleTemplateDeactivatedTitle': 'Órarendsablon deaktiválása',
  'auditUserUpdatedTitle': 'Felhasználó módosítása',
  'auditUserUpdatedDescription':
      'Az adminisztrátor módosította a felhasználó adatait.',
  'auditUserRoleChangedTitle': 'Felhasználói szerep módosítása',
  'auditUserRoleChangedDescription':
      'Az adminisztrátor módosította a felhasználó szerepét.',
  'auditUserDeactivatedTitle': 'Felhasználó deaktiválása',
  'auditUserDeactivatedDescription':
      'Az adminisztrátor deaktiválta a felhasználót.',
  'auditUserDeactivationBlockedTitle': 'Sikertelen felhasználó-deaktiválás',
  'auditUserDeactivationBlockedDescription':
      'A felhasználó deaktiválását az aktív kapcsolatok ellenőrzése blokkolta.',
  'auditPublicMessageCreatedTitle': 'Hír létrehozása',
  'auditPublicMessageCreatedDescription': 'Nyilvános hír lett létrehozva.',
  'auditPublicMessageUpdatedTitle': 'Hír módosítása',
  'auditPublicMessageUpdatedDescription': 'Nyilvános hír lett módosítva.',
  'auditPublicMessageDeletedTitle': 'Hír törlése',
  'auditPublicMessageDeletedDescription': 'A nyilvános hír törölve lett.',
  'auditProfileCompletedTitle': 'Profil kiegészítése',
  'auditProfileCompletedDescription':
      'A felhasználó kitöltötte a profil alapadatait.',
  'auditProfileUpdatedTitle': 'Profil módosítása',
  'auditProfileUpdatedDescription':
      'A felhasználó módosította a profil adatait.',
  'auditProfilePhotoUpdatedTitle': 'Profilkép módosítása',
  'auditProfilePhotoUpdatedDescription':
      'A felhasználó módosította a profilképét.',
  'auditProfilePhotoRemovedTitle': 'Profilkép eltávolítása',
  'auditProfilePhotoRemovedDescription':
      'A felhasználó eltávolította a manuálisan beállított profilképet.',
  'auditPaymentStartedTitle': 'Fizetés indítása',
  'auditPaymentStartedDescription':
      'A felhasználó elindította a bérlet fizetését.',
  'auditPaymentSucceededTitle': 'Sikeres fizetés',
  'auditPaymentSucceededDescription':
      'A bérlet fizetése sikeresen befejeződött.',
  'auditPaymentFailedTitle': 'Sikertelen fizetés',
  'auditPaymentFailedDescription':
      'A bérlet fizetése sikertelen volt vagy megszakadt.',
  'auditMembershipUpdatedTitle': 'Bérlet módosítása',
  'auditMembershipUpdatedDescription':
      'Az adminisztrátor módosította a felhasználó bérletét.',
  'auditMembershipStatusChangedTitle': 'Bérlet állapotának módosítása',
  'auditMembershipStatusChangedDescription':
      'Az adminisztrátor módosította a felhasználó bérletének állapotát.',
  'auditMembershipEntriesChangedTitle': 'Bérlet belépésszámának módosítása',
  'auditMembershipEntriesChangedDescription':
      'Az adminisztrátor módosította a bérleten hátralévő belépések számát.',
  'auditMembershipReservationCancelledTitle': 'Lefoglalt foglalás törlése',
  'auditMembershipReservationCancelledDescription':
      'Az adminisztrátor törölte a bérlethez kapcsolódó lefoglalt foglalást.',
  'auditMembershipAllReservationsCancelledTitle':
      'Összes lefoglalt foglalás törlése',
  'auditMembershipAllReservationsCancelledDescription':
      'Az adminisztrátor törölte a bérlethez kapcsolódó összes lefoglalt foglalást.',
  'auditMembershipAssignedTitle': 'Bérlet hozzárendelése',
  'auditMembershipAssignedDescription':
      'A felhasználóhoz manuálisan bérlet lett hozzárendelve.',
  'auditMembershipPurchasedTitle': 'Bérletvásárlás',
  'auditMembershipPurchasedDescription': 'A felhasználó bérletet vásárolt.',
  'auditActionMembershipAssigned': 'Bérlet hozzárendelve',
  'auditActionMembershipPurchased': 'Bérlet vásárolva',
  'auditActionMembershipUpdated': 'Bérlet módosítva',
  'auditActionMembershipStatusChanged': 'Bérlet állapota módosítva',
  'auditActionMembershipEntriesChanged': 'Bérlet belépései módosítva',
  'auditActionMembershipReservationCancelled': 'Egy lefoglalt foglalás törlése',
  'auditActionMembershipAllReservationsCancelled':
      'Összes lefoglalt foglalás törlése',
  'auditActionReservationCreated': 'Foglalás létrehozása',
  'auditActionReservationCancelled': 'Foglalás törlése',
  'auditActionAttendanceAttended': 'Jelenlét jelölve',
  'auditActionAttendanceNoShow': 'Távolmaradás jelölve',
  'auditActionTrainingTypeCreated': 'Edzéstípus létrehozása',
  'auditActionTrainingTypeUpdated': 'Edzéstípus módosítása',
  'auditActionTrainingTypeDeactivated': 'Edzéstípus deaktiválása',
  'auditActionTrainingSessionCreated': 'Időpont létrehozása',
  'auditActionTrainingSessionUpdated': 'Időpont módosítása',
  'auditActionTrainingSessionTimeChanged': 'Időpont idejének módosítása',
  'auditActionTrainingSessionCancelled': 'Időpont törlése',
  'auditActionScheduleTemplateCreated': 'Sablon létrehozása',
  'auditActionScheduleTemplateUpdated': 'Sablon módosítása',
  'auditActionScheduleTemplateDeactivated': 'Sablon deaktiválása',
  'auditActionUserUpdated': 'Felhasználó módosítása',
  'auditActionUserRoleChanged': 'Szerep módosítása',
  'auditActionUserDeactivationBlocked': 'Deaktiválás blokkolva',
  'auditActionUserDeactivated': 'Felhasználó deaktiválása',
  'auditActionPublicMessageCreated': 'Hír létrehozása',
  'auditActionPublicMessageUpdated': 'Hír módosítása',
  'auditActionPublicMessageDeleted': 'Hír törlése',
  'auditActionProfileCompleted': 'Profil kiegészítése',
  'auditActionProfileUpdated': 'Profil módosítása',
  'auditActionProfilePhotoUpdated': 'Profilkép módosítása',
  'auditActionProfilePhotoRemoved': 'Profilkép eltávolítása',
  'auditActionPaymentStarted': 'Fizetés indítása',
  'auditUserEmailCompletedTitle': 'E-mail megadása',
  'auditUserEmailCompletedDescription':
      'A felhasználó megadta a fiókhoz hiányzó e-mail-címet.',
  'currentUserShort': 'Ön',
  'auditUserEmailUpdatedTitle': 'Felhasználói e-mail módosítása',
  'auditUserEmailUpdatedDescription':
      'Az adminisztrátor módosította a felhasználó kapcsolattartási e-mail-címét.',
  'auditUserReactivatedTitle': 'Felhasználó aktiválása',
  'auditUserReactivatedDescription':
      'Az adminisztrátor újra aktiválta a felhasználót.',
  'auditActionUserEmailCompleted': 'E-mail megadása',
  'auditActionUserEmailUpdated': 'Felhasználói e-mail módosítása',
  'auditActionUserReactivated': 'Felhasználó aktiválása',
  'auditCategoryDiscounts': 'Kedvezmények',
  'auditDiscountRequestedTitle': 'Kedvezménykérelem',
  'auditDiscountRequestedDescription':
      'A felhasználó kedvezmény jóváhagyását kérte.',
  'auditDiscountApprovedTitle': 'Kedvezmény jóváhagyása',
  'auditDiscountApprovedDescription':
      'Az adminisztrátor jóváhagyta a felhasználó kedvezményét.',
  'auditDiscountRejectedTitle': 'Kedvezmény elutasítása',
  'auditDiscountRejectedDescription':
      'Az adminisztrátor elutasította a felhasználó kedvezménykérelmét.',
  'auditAccountDeletionRequestedTitle': 'Fióktörlési kérelem',
  'auditAccountDeletionRequestedDescription':
      'A felhasználó kérte a fiók törlését.',
  'auditEmailChangeRequestedTitle': 'E-mail módosítási kérelem',
  'auditEmailChangeRequestedDescription':
      'A felhasználó kérte az e-mail-cím módosítását.',
  'auditEmailChangeCompletedTitle': 'E-mail módosítása befejezve',
  'auditEmailChangeCompletedDescription':
      'A felhasználó befejezte az e-mail-cím módosítását.',
  'auditPasswordResetRequestedTitle': 'Jelszó-visszaállítási kérelem',
  'auditPasswordResetRequestedDescription':
      'A felhasználó jelszó-visszaállító e-mail küldését kérte.',
  'auditActionDiscountRequested': 'Kedvezménykérelem',
  'auditActionDiscountApproved': 'Kedvezmény jóváhagyása',
  'auditActionDiscountRejected': 'Kedvezmény elutasítása',
  'auditActionAccountDeletionRequested': 'Fióktörlési kérelem',
  'auditActionEmailChangeRequested': 'E-mail módosítási kérelem',
  'auditActionEmailChangeCompleted': 'E-mail módosítása befejezve',
  'auditActionPasswordResetRequested': 'Jelszó-visszaállítási kérelem',
};

const Map<String, List<String>> appTextListsHu = {
  'shortWeekdays': ['H', 'K', 'Sze', 'Cs', 'P', 'Szo', 'V'],
  'weekdays': [
    'Hétfő',
    'Kedd',
    'Szerda',
    'Csütörtök',
    'Péntek',
    'Szombat',
    'Vasárnap',
  ],
};
