// České texty aplikácie.
const Map<String, String> appTextsCs = {
  'appName': 'Body Fit Club TT',
  'loading': 'Načítám...',
  'ok': 'OK',
  'save': 'Uložit',
  'delete': 'Smazat',
  'cancel': 'Zrušit',
  'back': 'Zpět',
  'today': 'Dnes',
  'tomorrow': 'Zítra',
  'todayLower': 'dnes',
  'tomorrowLower': 'zítra',
  'minutes': 'min.',
  'refresh': 'Aktualizovat',
  'yesterday': 'Včera',
  'last7Days': 'Posledních 7 dní',
  'last30Days': 'Posledních 30 dní',
  'allTime': 'Celé období',
  'close': 'Zavřít',
  'reason': 'Důvod',
  'unknownDate': 'Neznámé datum',
  'notSet': 'Nenastaveno',
  'confirm': 'Potvrdit',
  'menu': 'Menu',
  'home': 'Domů',
  'schedule': 'Rozvrh',
  'reservations': 'Rezervace',
  'management': 'Správa',
  'profile': 'Profil',
  'settings': 'Nastavení',
  'appearance': 'Vzhled',
  'appearanceDescription': 'Vyberte světlý, tmavý nebo systémový režim.',
  'themeSystem': 'Podle systému',
  'themeLight': 'Světlý režim',
  'themeDark': 'Tmavý režim',
  'menuPosition': 'Umístění menu',
  'menuPositionDescription':
      'Vyberte, na které straně se má zobrazovat hlavní menu.',
  'rightHanded': 'Pravák',
  'leftHanded': 'Levák',
  'menuRightPositionDescription': 'Menu bude vpravo nahoře.',
  'menuLeftPositionDescription': 'Menu bude vlevo nahoře.',
  'language': 'Jazyk',
  'languageDescription': 'Vyberte jazyk aplikace.',
  'languageSlovak': '🇸🇰 Slovenština',
  'languageEnglish': '🇬🇧 Angličtina',
  'languageGerman': '🇩🇪 Němčina',
  'languageFrench': '🇫🇷 Francouzština',
  'languagePolish': '🇵🇱 Polština',
  'languageHungarian': '🇭🇺 Maďarština',
  'languageUkrainian': '🇺🇦 Ukrajinština',
  'languageRussian': '🇷🇺 Ruština',
  'languageSerbian': '🇷🇸 Srbština',
  'languageCzech': '🇨🇿 Čeština',
  'role': 'Role',
  'roleUser': 'Uživatel',
  'roleTrainer': 'Trenér',
  'roleAdmin': 'Administrátor',
  'roleUnknown': 'Neznámá role',
  'privacyPolicy': 'Ochrana osobních údajů',
  'emailContact': 'E-mail',
  'loginTitle': 'Přihlášení',
  'registerTitle': 'Registrace',
  'continueWithGoogle': 'Pokračovat přes Google',
  'continueWithFacebook': 'Pokračovat přes Facebook',
  'or': 'nebo',
  'email': 'E-mail',
  'password': 'Heslo',
  'login': 'Přihlásit se',
  'register': 'Registrovat',
  'logout': 'Odhlásit se',
  'noAccountRegister': 'Nemáš účet? Registrovat',
  'hasAccountLogin': 'Už máš účet? Přihlásit se',
  'authError': 'Chyba přihlášení',
  'acceptTerms': 'Souhlasím s obchodními podmínkami',
  'acceptPrivacy': 'Souhlasím se zpracováním osobních údajů',
  'termsConsentRequired':
      'Pro registraci je potřeba souhlasit s obchodními podmínkami.',
  'privacyConsentRequired':
      'Pro registraci je potřeba souhlasit se zpracováním osobních údajů.',
  'openTerms': 'Otevřít obchodní podmínky',
  'openPrivacy': 'Otevřít ochranu osobních údajů',
  'termsVersion': '2026-05-16',
  'privacyVersion': '2026-05-16',
  'continueWithoutAccount': 'Pokračovat bez účtu',
  'completeEmailOrLogout':
      'Pokud nechcete doplnit e-mail, můžete pokračovat bez účtu a přihlásit se později jiným účtem.',
  'fillEmailPassword': 'Vyplň e-mail i heslo.',
  'invalidEmailFormat': 'Zadej platný e-mail.',
  'passwordTooShort': 'Heslo musí mít alespoň 6 znaků.',
  'wrongEmailOrPassword': 'Zadaný e-mail nebo heslo není správné.',
  'userAlreadyExists': 'Uživatel s tímto e-mailem již existuje.',
  'weakPassword': 'Zadané heslo je příliš slabé.',
  'tooManyRequests': 'Příliš mnoho pokusů. Zkuste to později.',
  'networkError': 'Zkontrolujte internetové připojení.',
  'signInCancelled': 'Přihlášení bylo zrušeno.',
  'facebookLoginFailed': 'Přihlášení přes Facebook se nepodařilo.',
  'unknownAuthError': 'Při přihlášení nastala neznámá chyba.',
  'inactiveAccount': 'Váš účet je deaktivován. Kontaktujte administrátora.',
  'verificationEmailSent':
      'Registrace proběhla úspěšně. Poslali jsme vám ověřovací e-mail. Pokud ho nevidíte v doručené poště, zkontrolujte také složku Spam.',
  'emailNotVerified':
      'Nejprve potvrďte registraci kliknutím na odkaz v e-mailu.',
  'verificationEmailSentAgain':
      'Ověřovací e-mail jsme vám poslali znovu. Pokud ho nevidíte v doručené poště, zkontrolujte také složku Spam.',
  'forgotPassword': 'Zapomněli jste heslo?',
  'resetPasswordTitle': 'Obnovení hesla',
  'sendResetEmail': 'Odeslat e-mail',
  'passwordResetEmailSent':
      'Pokud účet s tímto e-mailem existuje, poslali jsme e-mail pro obnovení hesla.',
  'emailRequired': 'Zadejte e-mail.',
  'emailNotProvided': 'E-mail nebyl poskytnut',
  'emailSaved': 'E-mail byl uložen.',
  'emailSaveError': 'E-mail se nepodařilo uložit.',
  'emailChangeVerificationSent':
      'Na nový e-mail jsme poslali ověřovací odkaz. Změna se dokončí po jeho potvrzení.',
  'emailChangeRequestError': 'Změnu e-mailu se nepodařilo spustit.',
  'emailChangeNotAvailable':
      'Změna e-mailu je dostupná pouze pro účty vytvořené e-mailem a heslem.',
  'completeProfileTitle': 'Doplnění profilu',
  'editProfile': 'Upravit profil',
  'firstName': 'Jméno',
  'lastName': 'Příjmení',
  'publicName': 'Zobrazované jméno',
  'publicNameHint': 'Např. Barbora, Katka, Aďo',
  'firstNameRequired': 'Zadejte meno.',
  'lastNameRequired': 'Zadejte priezvisko.',
  'publicNameRequired': 'Zadejte zobrazované meno.',
  'profileSaved': 'Profil byl uložen.',
  'profileSaveError': 'Profil se nepodařilo uložit.',
  'loggedInUser': 'Přihlášený uživatel',
  'completeEmailTitle': 'Doplnění e-mailu',
  'completeEmailDescription':
      'Pro používání aplikace potřebujeme vaši e-mailovou adresu. Použijeme ji jako kontaktní e-mail k vašemu účtu.',
  'deleteAccountRequest': 'Požádat o smazání účtu',
  'deleteAccountRequestTitle': 'Smazání účtu',
  'deleteAccountRequestDescription':
      'Po odeslání žádosti bude účet deaktivován a nebude možné se do něj přihlásit. Údaje budou následně zpracovány administrátorem podle pravidel ochrany osobních údajů.',
  'deleteAccountReason': 'Důvod žádosti',
  'deleteAccountConfirm': 'Opravdu chcete požádat o smazání účtu?',
  'deleteAccountRequestSent': 'Žádost o smazání účtu byla odeslána.',
  'deleteAccountRequestError': 'Žádost o smazání účtu se nepodařilo odeslat.',
  'deleteAccountBlockedActiveReservations':
      'Účet nelze smazat, protože máte aktivní rezervace.',
  'accountDeletionRequests': 'Žádosti o smazání účtu',
  'accountDeletionRequestsWithCount': 'Žádosti o smazání účtu',
  'accountDeletionRequestsLoadError':
      'Žádosti o smazání účtu se nepodařilo načíst.',
  'noAccountDeletionRequests': 'Nejsou evidovány žádné čekající žádosti.',
  'completeAccountDeletion': 'Anonymizovat účet',
  'completeAccountDeletionTitle': 'Anonymizovat účet',
  'completeAccountDeletionQuestion':
      'Opravdu chcete anonymizovat tento účet? Tato akce přepíše osobní údaje uživatele.',
  'accountDeletionCompleted': 'Účet byl anonymizován.',
  'accountDeletionCompleteError': 'Účet se nepodařilo anonymizovat.',
  'requestedAt': 'Požádáno',
  'accountDeletionRequestsWaiting': 'Čekající žádosti na zpracování.',
  'changeEmail': 'Změnit e-mail',
  'changeEmailTitle': 'Zmena e-mailu',
  'changeEmailDescription':
      'Zadejte nový e-mail a aktuální heslo. Na nový e-mail pošleme ověřovací odkaz. Změna se dokončí až po potvrzení odkazu v e-mailu.',
  'changeEmailProfileHint': 'Dostupné pro účty vytvořené e-mailem a heslem.',
  'newEmail': 'Nový e-mail',
  'currentPassword': 'Aktuální heslo',
  'sendVerificationEmail': 'Odeslat ověřovací e-mail',
  'wrongCurrentPassword': 'Aktuální heslo není správné.',
  'requiresRecentLogin': 'Pro tuto akci se nejprve odhlaste a znovu přihlaste.',
  'changeProfilePhoto': 'Změnit profilovou fotku',
  'chooseFromGallery': 'Vybrat z galerie',
  'takePhoto': 'Vyfotit',
  'removePhoto': 'Odstranit fotku',
  'editPhoto': 'Upravit fotku',
  'cropProfilePhoto': 'Oříznout profilovou fotku',
  'profilePhotoUpdated': 'Profilová fotka byla uložena.',
  'profilePhotoUpdateError': 'Profilovou fotku se nepodařilo uložit.',
  'profilePhotoRemoveError': 'Profilovou fotku se nepodařilo odstranit.',
  'requestDiscount': 'Požádat o slevu',
  'discountStatus': 'Slevový status',
  'discountStatusNone': 'Bez slevy',
  'discountStatusPending': 'Čeká na schválení',
  'discountStatusApproved': 'Schválená sleva',
  'discountStatusRejected': 'Zamítnutá žádost',
  'discountStatusExpired': 'Platnost slevy skončila',
  'discountType': 'Typ slevy',
  'discountTypeNormal': 'Běžný uživatel',
  'discountTypeStudent': 'Student',
  'discountTypeSenior': 'Senior',
  'discountTypeZtp': 'ZTP',
  'discountTypeIndividual': 'Individuálna sleva',
  'discountRequestDescription':
      'Vyberte typ slevy, o kterou žádáte. Po odeslání žádost zkontroluje administrátor.',
  'discountRequestNote': 'Poznámka k žádosti',
  'discountRequestSent': 'Žádost o slevu byla odeslána.',
  'discountRequestError': 'Žádost o slevu se nepodařilo odeslat.',
  'discountRequestAlreadyPending': 'Už máte rozpracovanou žádost o slevu.',
  'discountRequestPending': 'Žádost čaká na schválení',
  'sendRequest': 'Odeslat žádost',
  'discountDocument': 'Doklad k slevě',
  'discountDocumentDescription':
      'Nahrajte fotografii dokladu, podle kterého administrátor ověří nárok na slevu.',
  'chooseDiscountDocument': 'Vybrat doklad',
  'discountDocumentRequired':
      'Pro odeslání žádosti je potřeba přiložit doklad.',
  'discountDocumentSelected': 'Doklad byl vybrán',
  'takeDiscountDocumentPhoto': 'Vyfotit doklad',
  'chooseDiscountDocumentFromGallery': 'Vybrat z galerie',
  'discountRequests': 'Žádosti o slevu',
  'discountRequestsDescription':
      'Schvalování nebo zamítnutí žádostí uživatelů o slevu.',
  'discountRequestsLoadError': 'Žádosti o slevu se nepodařilo načíst.',
  'noDiscountRequests': 'Nejsou evidovány žádné čekající žádosti o slevu.',
  'approveDiscount': 'Schválit slevu',
  'rejectDiscount': 'Zamítnout žádost',
  'discountApproved': 'Sleva byla schválená.',
  'discountRejected': 'Žádost o slevu byla zamítnuta.',
  'discountDecisionError': 'Rozhodnutí k žádosti se nepodařilo uložit.',
  'discountValidUntilRequired': 'Vyberte datum platnosti slevy.',
  'discountAdminNote': 'Poznámka administrátora',
  'selectDiscountValidUntil': 'Vyberte platnost slevy',
  'discountDocumentPreview': 'Náhled dokladu',
  'todayReservations': 'Dnešní rezervace',
  'noTodayReservations': 'Dnes nemáte rezervované žádné cvičení.',
  'nearestTraining': 'Nejbližší cvičení',
  'nearestTrainings': 'Nejbližší cvičení',
  'noNearestTraining': 'Není naplánované žádné nejbližší cvičení.',
  'todaysTrainings': 'Dnešní cvičení',
  'noTodaysTrainings': 'Dnes nejsou naplánované žádné cvičení.',
  'myMemberships': 'Moje permanentky',
  'activeMembershipsCount': 'Aktivní permanentky',
  'availableEntriesSummary': 'Dostupné vstupy',
  'reservedEntriesSummary': 'Alokované vstupy',
  'dailyMembershipsSummary': 'Denní permanentky',
  'tapToShowQrCode': 'Kliknutím zobrazíte QR kód.',
  'nearestReservations': 'Nejbližší rezervace',
  'noNearestReservations': 'Nemáte žádné nejbližší rezervace.',
  'qrShort': 'QR',
  'membershipStatus': 'Stav permanentky',
  'remainingEntries': 'Zbývající vstupy',
  'upcomingTraining': 'Nejbližší dnešní cvičení',
  'schedulePlaceholder': 'Zde bude rozvrh tréninků.',
  'reservationsPlaceholder': 'Zde budou rezervace.',
  'newsPlaceholder': 'Tu se budú zobrazovat novinky a zprávy od trenérů.',
  'aboutApp': 'O aplikaci',
  'aboutUs': 'O nás',
  'aboutAppDescription':
      'Aplikace Body Fit Club TT slouží ke správě tréninků, rezervací, permanentek a komunikace mezi fitness centrem a uživateli.',
  'aboutUsDescription':
      'Body Fit Club je fitness centrum v Trnavě zaměřené na skupinové i individuální tréninky, pohyb, zdravý životní styl a osobní přístup ke klientům.',
  'bodyFitClubWebsite': 'https://bodyfitclub.sk/',
  'openWebsite': 'Otevřít webovou stránku',
  'businessTerms': 'Obchodní podmínky',
  'legalDocumentsInfo':
      'Obchodní podmínky a informace o ochraně osobních údajů budou dostupné na webové stránce Body Fit Club.',
  'contacts': 'Kontakty',
  'billingDetails': 'Fakturační údaje',
  'address': 'Adresa',
  'phone': 'Telefon',
  'website': 'Webová stránka',
  'socialNetworks': 'Sociální sítě',
  'openMap': 'Otevřít mapu',
  'openFacebook': 'Facebook',
  'openInstagram': 'Instagram',
  'multisport': 'MultiSport',
  'multisportInfo':
      'Akceptujeme kartu MultiSport podle aktuálních podmínek provozu.',
  'bodyFitClubCompanyName': 'BODYFIT CLUB s.r.o.',
  'bodyFitClubOperationAddress': 'V Jame 24, Trnava',
  'bodyFitClubBillingAddress': 'J. G. Tajovského 18, 917 08 Trnava',
  'bodyFitClubPhonePrimary': '+421 902 860 008',
  'bodyFitClubPhoneSecondary': '+421 903 946 895',
  'bodyFitClubEmail': 'bodyfitclubtt@gmail.com',
  'bodyFitClubIco': '48074128',
  'ico': 'IČO: ',
  'companySeat': 'Sídlo',
  'operation': 'Provozovna',
  'bodyFitClubFacebookUrl': 'https://www.facebook.com/bodyfitclub.sk',
  'bodyFitClubInstagramUrl': 'https://www.instagram.com/bodyfitclub.tt/',
  'bodyFitClubMapUrl':
      ' https://www.google.com/maps/search/?api=1&query=V%20Jame%206641%2F24%2C%20917%2001%20Trnava',
  'bodyFitClubMultiSportUrl':
      'https://multi-sport.sk/aktivity/partner/bodyfit-club/',
  'multisportInfo2':
      'Body Fit Club je partnerem programu MultiSport. Akceptování karty MultiSport se řídí aktuálními podmínkami provozu.',
  'bodyFitClubWebsiteLabel': 'www.bodyfitclub.sk',
  'dic': 'DIČ: ',
  'bodyFitClubDic': '2120035445',
  'notVatPayer': 'Společnost není plátcem DPH',
  'legalDocuments': 'Právní dokumenty',
  'priceList': 'Ceník',
  'priceListAudience': 'Pro',
  'priceListAudienceNormal': 'běžní uživatelé',
  'priceListAudienceDiscount': 'uživatelé se slevou',
  'priceListAudienceAll': 'všichni',
  'price': 'Cena',
  'singleEntries': 'Jednorázové vstupy',
  'priceListMemberships': 'Permanentky',
  'chooseEntry': 'Vyberte vstup',
  'noAvailablePlans': 'Momentálně nejsou dostupné žádné možnosti nákupu.',
  'news': 'Novinky',
  'noPublicMessages': 'Zatím nejsou žádné zprávy.',
  'writeMessage': 'Napsat zprávu',
  'writeMessageShort': 'Napsat',
  'editMessage': 'Upravit zprávu',
  'deleteMessage': 'Smazat zprávu',
  'deleteMessageQuestion': 'Opravdu chcete smazat tuto zprávu?',
  'messageText': 'Text zprávy',
  'messageHint': 'Napiš zprávu...',
  'sendMessage': 'Odeslat',
  'updateMessage': 'Uložit zmeny',
  'messageSaved': 'Správa byla uložena.',
  'messageDeleted': 'Správa byla smazána.',
  'messageSaveError': 'Správu se nepodařilo uložit.',
  'messageDeleteError': 'Správu se nepodařilo smazat.',
  'editedBy': 'Upraveno',
  'editedByAdmin': 'Upraveno administrátorem',
  'editedByTrainer': 'Upraveno trenérom',
  'userFallback': 'Uživatel',
  'noTrainings': 'Momentálně nejsou dostupné žádné tréninky.',
  'noTrainingsForSelectedDay': 'V tento den nejsou naplánovány žádné tréninky.',
  'trainer': 'Trenér',
  'freeSpots': 'Volná místa',
  'reserve': 'Rezervovat',
  'reserved': 'Rezervováno',
  'fullCapacity': 'Obsazeno',
  'trainingsLoadError': 'Nepodařilo se načíst rozvrh tréninků.',
  'unknownTraining': 'Neznámý trénink',
  'unknownTrainer': 'Neznámý trenér',
  'unknownUser': 'Neznámý uživatel',
  'trainingSessionFinished': 'Proběhlo',
  'trainingSessionTooFarInFuture':
      'Termín je příliš daleko v budoucnosti. Ručně můžete přidat cvičení pouze do období zobrazeného v rozvrhu.',
  'managementDescription':
      'Zde můžete spravovat termíny cvičení, docházku, permanentky a uživatele.',
  'scheduleManagement': 'Správa rozvrhu',
  'scheduleManagementDescription':
      'Správa typů cvičení, šablon rozvrhu a konkrétních tréninkových termínů.',
  'attendanceManagement': 'Správa docházky',
  'usersManagement': 'Správa uživatelů',
  'usersManagementComingSoon': 'Správa uživatelů bude doplněna později.',
  'scheduleTemplatesManagement': 'Správa šablon rozvrhu',
  'reactivateUser': 'Aktivovat uživatele',
  'reactivateUserQuestion': 'Opravdu chcete znovu aktivovat tohoto uživatele?',
  'userReactivated': 'Uživatel byl znovu aktivován.',
  'trainingTypesManagement': 'Správa typů cvičení',
  'addTrainingType': 'Přidat typ cvičení',
  'editTrainingType': 'Upravit typ cvičení',
  'deleteTrainingType': 'Smazat typ cvičení',
  'trainingType': 'Typ cvičení',
  'selectTrainingType': 'Vyberte typ cvičení',
  'trainingName': 'Název cvičení',
  'description': 'Popis',
  'defaultDuration': 'Výchozí délka',
  'defaultCapacity': 'Výchozí kapacita',
  'noTrainingTypes': 'Momentálně nejsou vytvořené žádné typy cvičení.',
  'trainingTypesLoadError': 'Nepodařilo se načíst typy cvičení.',
  'trainingTypeCreated': 'Typ cvičení byl vytvořen.',
  'trainingTypeUpdated': 'Typ cvičení byl upraven.',
  'trainingTypeDeleted': 'Typ cvičení byl smazán.',
  'trainingTypeDeleteQuestion':
      'Opravdu chcete smazat tento typ cvičení? Už se nebude nabízet u nových termínů.',
  'trainingTypeAlreadyExists': 'Typ cvičení s tímto názvem již existuje.',
  'trainingTypeUsedByTemplate':
      'Typ cvičení nelze smazat, protože se používá v aktivní šabloně rozvrhu.',
  'trainingTypeUsedBySession':
      'Typ cvičení nelze smazat, protože se používá v budoucím termínu cvičení.',
  'addTrainingSession': 'Přidat termín cvičení',
  'editTrainingSession': 'Upravit detaily cvičení',
  'trainingSessionCreated': 'Termín tréninku byl vytvořen.',
  'trainingSessionUpdated': 'Termín cvičení byl upraven.',
  'updateTrainingSessionError': 'Termín cvičení se nepodařilo upravit.',
  'trainingSessionInPast': 'Termín tréninku nemůže být v minulosti.',
  'trainingSessionOverlap': 'V tomto čase je již naplánován jiný trénink.',
  'capacityLowerThanReservations':
      'Kapacita nemůže být nižší než počet existujících rezervací.',
  'cancelTrainingSession': 'Zrušit termín',
  'cancelTrainingSessionTitle': 'Zrušit termín tréninku',
  'cancelTrainingSessionQuestion':
      'Opravdu chcete zrušit tento termín tréninku? Aktivní rezervace budou zrušeny a alokované vstupy se uživatelům uvolní. Pokud již byl vstup použit, bude uživateli vrácen.',
  'cancelTrainingSessionConfirm': 'Zrušit termín',
  'trainingSessionCancelled': 'Termín tréninku byl zrušen.',
  'cancelTrainingSessionError': 'Termín tréninku se nepodařilo zrušit.',
  'trainerCanCancelOnlyOwnSession': 'Trenér může zrušit pouze vlastní termín.',
  'trainerCannotCancelStartedSession':
      'Trenér nemůže zrušit termín, který již začal nebo proběhl.',
  'date': 'Datum',
  'startTime': 'Začátek',
  'duration': 'Délka',
  'capacity': 'Kapacita',
  'selectDate': 'Vyberte datum',
  'selectTrainer': 'Vyberte trenéra',
  'trainersLoadError': 'Nepodařilo se načíst trenérů.',
  'fillAllFields': 'Vyplňte všechny povinné údaje.',
  'invalidCapacity': 'Kapacita musí být větší než 0.',
  'invalidDuration': 'Délka musí být větší než 0.',
  'saveError': 'Uložení se nepodařilo.',
  'addScheduleTemplate': 'Přidat šablonu rozvrhu',
  'editScheduleTemplate': 'Upravit šablonu rozvrhu',
  'deleteScheduleTemplate': 'Smazat šablonu rozvrhu',
  'noScheduleTemplates': 'Momentálně nejsou vytvořené žádné šablony rozvrhu.',
  'weekday': 'Den v týdnu',
  'selectWeekday': 'Vyberte den v týdnu',
  'scheduleTemplateCreated': 'Šablona rozvrhu byla vytvořena.',
  'scheduleTemplateUpdated': 'Šablona rozvrhu byla upravena.',
  'scheduleTemplateDeleted': 'Šablona rozvrhu byla smazána.',
  'scheduleTemplateDeleteQuestion':
      'Opravdu chcete smazat tuto šablonu rozvrhu? Nebude se už používat při generování nových termínů.',
  'scheduleTemplateAlreadyExists': 'Taková šablona rozvrhu již existuje.',
  'scheduleTemplateLoadError': 'Nepodařilo se načíst šablony rozvrhu.',
  'scheduleTemplateOverlap': 'V tomto čase již existuje jiná šablona rozvrhu.',
  'capacityLabel': 'Kapacita',
  'reservationCreated': 'Rezervace byla vytvořena.',
  'reservationAlreadyExists': 'Na tento trénink již máte vytvořenou rezervaci.',
  'reservationTrainingFull': 'Tento trénink je již obsazen.',
  'reservationTrainingNotAvailable':
      'Tento trénink již není dostupný pro rezervaci.',
  'reservationTrainingAlreadyStarted':
      'Na tento trénink se již nelze rezervovat.',
  'reservationError': 'Rezervaci se nepodařilo vytvořit.',
  'myReservations': 'Moje rezervace',
  'noReservations': 'Momentálně nemáte žádné rezervace.',
  'cancelReservation': 'Zrušit rezervaci',
  'cancelReservationTitle': 'Zrušit rezervaci',
  'cancelReservationQuestion': 'Opravdu chcete zrušit tuto rezervaci?',
  'reservationCancelled': 'Rezervace byla zrušena.',
  'reservationCancelError': 'Rezervaci se nepodařilo zrušit.',
  'reservationsLoadError': 'Rezervace se nepodařilo načíst.',
  'cancelReservations': 'Zrušit rezervace',
  'cancelReservationsBeforeDeactivation':
      'Před deaktivací nebo zrušením permanentky nejprve zrušte alokované rezervace.',
  'cancelReservationForMembership': 'Zrušit tuto rezervaci',
  'cancelReservationForMembershipQuestion':
      'Opravdu chcete zrušit tuto rezervaci navázanou na permanentku? Alokovaný vstup se uvolní.',
  'reservationForMembershipCancelled':
      'Rezervace byla zrušena a alokovaný vstup byl uvolněný.',
  'noReservationsForTrainingHistory':
      'Na tomto tréninku nejsou žádné rezervace.',
  'reservationQrCode': 'QR kód rezervace',
  'memberships': 'Permanentky',
  'assignMembership': 'Přiřadit permanentku',
  'selectUser': 'Vyberte uživatele',
  'selectMembershipPlan': 'Vyberte typ permanentky',
  'membershipPlansLoadError': 'Nepodařilo se načíst typy permanentek.',
  'membershipAssigned': 'Permanentka byla přiřazena.',
  'membershipAssignError': 'Permanentku se nepodařilo přiřadit.',
  'membershipPlan': 'Typ permanentky',
  'client': 'Uživatel',
  'buyMembership': 'Koupit permanentku',
  'buySingleEntry': 'Koupit jednorázový vstup',
  'chooseMembership': 'Vyberte permanentku',
  'payment': 'Platba',
  'pay': 'Zaplatit',
  'paymentSuccessful': 'Platba byla úspěšná.',
  'paymentFailed': 'Platba selhala.',
  'activeMembership': 'Aktivní permanentka',
  'noActiveMembership': 'Nemáte aktivní permanentku.',
  'validUntil': 'Platná do',
  'membershipLoadError': 'Permanentku se nepodařilo načíst.',
  'noAvailableEntries': 'Nemáte dostupný vstup na rezervaci.',
  'noUpcomingTraining': 'Dnes nemáte rezervované žádné cvičení.',
  'membershipsManagement': 'Správa permanentek',
  'membershipDetail': 'Detail permanentky',
  'noMemberships': 'Momentálně nejsou dostupné žádné permanentky.',
  'status': 'Stav',
  'validFrom': 'Platná od',
  'entriesTotal': 'Celkový počet vstupů',
  'entriesRemaining': 'Zbývající vstupy',
  'entriesReserved': 'Alokované v rezervacích',
  'entriesAvailable': 'Dostupné vstupy',
  'adminMembershipEdit': 'Administrátorská úprava',
  'membershipStatusActive': 'Aktivní',
  'membershipStatusInactive': 'Neaktivní',
  'membershipStatusCancelled': 'Zrušená',
  'membershipStatusExpired': 'Expirovaná',
  'membershipStatusUsedUp': 'Vyčerpaná',
  'membershipUpdated': 'Permanentka byla upravena.',
  'membershipUpdateError': 'Permanentku se nepodařilo upravit.',
  'invalidRemainingEntries': 'Zadejte platný počet zbývajících vstupov.',
  'allocatedReservations': 'Alokované rezervace',
  'cancelAllocatedReservations': 'Zrušit alokované rezervace',
  'cancelAllocatedReservationsQuestion':
      'Opravdu chcete zrušit aktivní rezervace navázané na tuto permanentku? Alokované vstupy se uvolní.',
  'cancelAllReservations': 'Zrušit všechny rezervace',
  'cancelAllocatedReservationsError':
      'Alokované rezervace se nepodařilo zrušit.',
  'usedEntries': 'Použité vstupy',
  'noAllocatedReservations':
      'Na tuto permanentku nejsou aktuálně alokované žádné rezervace.',
  'noUsedEntries': 'Z této permanentky zatím nebyl použit žádný vstup.',
  'membershipUsageLoadError': 'Historii permanentky se nepodařilo načíst.',
  'searchMemberships': 'Hledat podle uživatele nebo permanentky',
  'allMembershipStatuses': 'Všechny stavy',
  'membershipStatusNotYetValid': 'Ještě neplatná',
  'membershipStatusUsable': 'Aktivní',
  'invalidRemainingEntriesHigherThanTotal':
      'Zbývající vstupy nemohou být vyššie než celkový počet vstupov.',
  'invalidRemainingEntriesLowerThanReserved':
      'Zbývající vstupy nemohou být nižšie než počet alokovaných vstupov.',
  'membershipPrefix': 'Permanentka',
  'statusPrefix': 'Stav',
  'attendance': 'Docházka',
  'attendanceLoadError': 'Nepodařilo se načíst docházku.',
  'noActiveReservationsForAttendance':
      'Momentálně nejsou žádné aktivní rezervace na označenie dochádzky.',
  'attended': 'Přišel',
  'noShow': 'Nepřišel',
  'markAttendedTitle': 'Označit účast',
  'markNoShowTitle': 'Označit neúčast',
  'markAttendedQuestion': 'Opravdu chcete označit uživatele jako přítomného?',
  'markNoShowQuestion': 'Opravdu chcete označit uživatele jako nepřítomného?',
  'attendanceMarked': 'Docházka byla uložena.',
  'attendanceMarkError': 'Dochádzku se nepodařilo uložit.',
  'attendedStatus': 'Přišel',
  'noShowStatus': 'Nepřišel',
  'attendedCountLabel': 'Přišli',
  'noShowCountLabel': 'Nepřišli',
  'attendanceActionDone': 'Změna účasti byla uložena.',
  'attendanceActionError': 'Změnu účasti se nepodařilo uložit.',
  'showQrCode': 'QR kód',
  'showQrToTrainer': 'Ukažte tento QR kód trenérůi při příchodu na trénink.',
  'scanQrCode': 'Skenovat QR kód',
  'scanQrCodes': 'Skenovat QR kódy',
  'scanQrCodeHint': 'Namiřte kameru na QR kód rezervace uživatele.',
  'invalidQrCode': 'Neplatný QR kód rezervace.',
  'qrCodeScanned': 'QR kód byl naskenován.',
  'qrScanSuccessful':
      'QR kód byl naskenován. Můžete skenovat dalšího uživatele.',
  'trainerQrScanTooEarly':
      'QR kód je možné naskenovat nejdříve 30 minut před začátkem cvičení.',
  'trainingHistory': 'Historie tréninků',
  'trainingHistoryDetail': 'Detail tréninku',
  'trainingHistoryLoadError': 'Historii tréninků se nepodařilo načíst.',
  'trainingHistoryReservationsLoadError':
      'Účast na tréninku se nepodařilo načíst.',
  'noTrainingHistoryInSelectedPeriod':
      'Ve zvoleném období nejsou žádné tréninky.',
  'fromDatePrefix': 'Od',
  'toDatePrefix': 'Do',
  'planned': 'Naplánováno',
  'cancelled': 'Zrušeno',
  'finished': 'Proběhlo',
  'reservedStatus': 'Rezervováno',
  'reservedCountLabel': 'Rezervováno',
  'cancelledCountLabel': 'Zrušeno',
  'markedAtPrefix': 'Označeno',
  'markAsAttended': 'Označit jako přišel',
  'markAsNoShow': 'Označit jako nepřišel',
  'revertAttendance': 'Zrušit označenú účast',
  'revertNoShow': 'Zrušit označenú neúčast',
  'markAsAttendedQuestion':
      'Opravdu chcete označit uživatele jako přítomného? Vstup z permanentky se použije.',
  'markAsNoShowQuestion':
      'Opravdu chcete označit uživatele jako nepřítomného? Vstup z permanentky se použije.',
  'revertAttendanceQuestion':
      'Opravdu chcete zrušit označenou účast? Použitý vstup se vrátí zpět na permanentku.',
  'revertNoShowQuestion':
      'Opravdu chcete zrušit označenou neúčast? Použitý vstup se vrátí zpět na permanentku.',
  'addTrainingAttendance': 'Přidat účastníka',
  'selectAttendanceUser': 'Vyberte uživatele',
  'selectAttendanceMembership': 'Vyberte permanentku',
  'noUsersForAttendance': 'Nenašli se žádní aktivní uživatelé.',
  'noUsableMembershipsForAttendance':
      'Uživatel nemá použitelnou permanentku pro tento trénink.',
  'addTrainingAttendanceQuestion':
      'Opravdu chcete dodatečně přidat účast uživatele na tomto tréninku? Vstup z permanentky se použije.',
  'trainingAttendanceAdded': 'Účastník byl přidán do tréninku.',
  'trainingAttendanceAddError': 'Účastníka se nepodařilo přidat.',
  'userAlreadyHasReservationForTraining':
      'Uživatel už má na tento trénink vytvořený záznam.',
  'usersLoadError': 'Nepodařilo se načíst uživatelů.',
  'allRoles': 'Všechny role',
  'searchUsers': 'Hledat uživatele',
  'noUsersFound': 'Nebyli nalezeni žádní uživatelé.',
  'editUser': 'Upravit uživatele',
  'userUpdated': 'Uživatel byl upraven.',
  'userUpdateError': 'Uživatele se nepodařilo upravit.',
  'cannotChangeOwnRole': 'Nemůžete změnit vlastní roli.',
  'changeRoleWarning':
      'Při změně role uživatele se mohou změnit jeho oprávnění v aplikaci.',
  'deactivateUser': 'Deaktivovat uživatele',
  'deactivationReason': 'Důvod deaktivace',
  'userDeactivated': 'Uživatel byl deaktivován.',
  'deactivateUserQuestion':
      'Opravdu chcete deaktivovat tohoto uživatele? Nebude možné jej dále používat ve správě aplikace.',
  'cannotDeactivateYourself': 'Nemůžete deaktivovat vlastní účet.',
  'userUsedByTemplate':
      'Uživatele není možné deaktivovat nebo změnit na běžného uživatele, protože je přiřazen v aktivní šabloně rozvrhu.',
  'userUsedByFutureSession':
      'Uživatele není možné deaktivovat nebo změnit na běžného uživatele, protože je přiřazen k budoucímu cvičení.',
  'userHasActiveReservations':
      'Uživatele není možné deaktivovat, protože má aktivní rezervace.',
  'userHasActiveMemberships':
      'Uživatele není možné deaktivovat, protože má aktivní permanentky.',
  'inactiveUser': 'Neaktivní uživatel',
  'userCannotBeDeactivated': 'Uživatele nelze deaktivovat',
  'userCannotBeDeactivatedDescription':
      'Před deaktivací je potřeba nejprve vyřešit jeho aktivní rezervace nebo permanentky.',
  'userHasBlockingItems': 'Uživatel má:',
  'activeReservationsCount': 'Aktivní rezervace',
  'showMemberships': 'Zobrazit permanentky',
  'auditLogs': 'Historie zásahů',
  'auditLogsDescription': 'Přehled důležitých zásahů v aplikaci.',
  'auditLogsLoadError': 'Historii zásahů se nepodařilo načíst.',
  'noAuditLogs': 'Nebyly nalezeny žádné zásahy.',
  'searchAuditLogs': 'Hledat podle uživatele, e-mailu nebo popisu',
  'auditCategory': 'Kategorie',
  'auditAction': 'Akce',
  'auditActor': 'Provedl',
  'auditActorRole': 'Role provádějícího',
  'auditPeriod': 'Období',
  'auditAllCategories': 'Všechny kategorie',
  'auditCategoryMemberships': 'Permanentky',
  'auditCategoryReservations': 'Rezervace',
  'auditCategoryAttendance': 'Docházka',
  'auditCategoryUsers': 'Používatelia',
  'auditCategorySchedule': 'Rozvrh',
  'auditCategoryMessages': 'Zprávy',
  'auditCategoryPayments': 'Platby',
  'auditCategoryProfile': 'Profil',
  'auditAllActions': 'Všechny akce',
  'auditActionCreated': 'Vytvoření',
  'auditActionUpdated': 'Úprava',
  'auditActionCancelled': 'Zrušení',
  'auditActionDeactivated': 'Deaktivace',
  'auditActionActivated': 'Aktivace',
  'auditActionAssigned': 'Přiřazení',
  'auditActionPurchased': 'Nákup',
  'auditActionPaymentSucceeded': 'Platba byla úspěšná',
  'auditActionPaymentFailed': 'Platba selhala',
  'auditActionAttendanceMarked': 'Docházka',
  'auditActionQrChecked': 'QR kontrola',
  'auditAllActorRoles': 'Všechny role',
  'auditReservationCreatedTitle': 'Vytvoření rezervace',
  'auditReservationCreatedDescription':
      'Uživatel vytvořil rezervaci na trénink.',
  'auditReservationCancelledTitle': 'Zrušení rezervace',
  'auditReservationCancelledDescription': 'Rezervace uživatele byla zrušena.',
  'auditAttendanceAttendedTitle': 'Označená účast',
  'auditAttendanceAttendedDescription':
      'Uživatel byl označen jako přítomný na tréninku.',
  'auditAttendanceNoShowTitle': 'Označená neúčast',
  'auditAttendanceNoShowDescription':
      'Uživatel byl označen jako nepřítomný na tréninku.',
  'auditTrainingTypeCreatedTitle': 'Vytvoření typu cvičení',
  'auditTrainingTypeUpdatedTitle': 'Úprava typu cvičení',
  'auditTrainingTypeDeactivatedTitle': 'Deaktivace typu cvičení',
  'auditTrainingSessionCreatedTitle': 'Vytvoření termínu',
  'auditTrainingSessionUpdatedTitle': 'Úprava termínu',
  'auditTrainingSessionTimeChangedTitle': 'Změna času termínu',
  'auditTrainingSessionCancelledTitle': 'Zrušení termínu',
  'auditScheduleTemplateCreatedTitle': 'Vytvoření šablony rozvrhu',
  'auditScheduleTemplateUpdatedTitle': 'Úprava šablony rozvrhu',
  'auditScheduleTemplateDeactivatedTitle': 'Deaktivace šablony rozvrhu',
  'auditUserUpdatedTitle': 'Úprava uživatele',
  'auditUserUpdatedDescription': 'Administrátor upravil údaje uživatele.',
  'auditUserRoleChangedTitle': 'Zmena roly uživatele',
  'auditUserRoleChangedDescription': 'Administrátor změnil rolu uživatele.',
  'auditUserDeactivatedTitle': 'Deaktivace uživatele',
  'auditUserDeactivatedDescription': 'Administrátor deaktivoval uživatele.',
  'auditUserDeactivationBlockedTitle': 'Neúspěšná deaktivácia uživatele',
  'auditUserDeactivationBlockedDescription':
      'Deaktivace uživatele byla zablokována kontrolou aktivních vazeb.',
  'auditPublicMessageCreatedTitle': 'Vytvoření novinky',
  'auditPublicMessageCreatedDescription': 'Byla vytvořena veřejná novinka.',
  'auditPublicMessageUpdatedTitle': 'Úprava novinky',
  'auditPublicMessageUpdatedDescription': 'Byla upravena veřejná novinka.',
  'auditPublicMessageDeletedTitle': 'Smazání novinky',
  'auditPublicMessageDeletedDescription': 'Veřejná novinka byla smazána.',
  'auditProfileCompletedTitle': 'Doplnění profilu',
  'auditProfileCompletedDescription':
      'Uživatel doplnil základní údaje profilu.',
  'auditProfileUpdatedTitle': 'Úprava profilu',
  'auditProfileUpdatedDescription': 'Uživatel upravil údaje profilu.',
  'auditProfilePhotoUpdatedTitle': 'Úprava profilové fotky',
  'auditProfilePhotoUpdatedDescription': 'Uživatel upravil profilovou fotku.',
  'auditProfilePhotoRemovedTitle': 'Odstránenie profilové fotky',
  'auditProfilePhotoRemovedDescription':
      'Uživatel odstránil manuálne nastavenú profilovou fotku.',
  'auditPaymentStartedTitle': 'Spustenie platby',
  'auditPaymentStartedDescription': 'Uživatel spustil platbu za permanentku.',
  'auditPaymentSucceededTitle': 'Úspešná platba',
  'auditPaymentSucceededDescription':
      'Platba za permanentku byla úspěšně dokončená.',
  'auditPaymentFailedTitle': 'Neúspěšná platba',
  'auditPaymentFailedDescription':
      'Platba za permanentku selhala nebo byla zrušena.',
  'auditMembershipUpdatedTitle': 'Úprava permanentky',
  'auditMembershipUpdatedDescription':
      'Administrátor upravil permanentku uživatele.',
  'auditMembershipStatusChangedTitle': 'Zmena stavu permanentky',
  'auditMembershipStatusChangedDescription':
      'Administrátor změnil stav permanentky uživatele.',
  'auditMembershipEntriesChangedTitle': 'Zmena počtu vstupov permanentky',
  'auditMembershipEntriesChangedDescription':
      'Administrátor změnil počet zbývajících vstupov permanentky.',
  'auditMembershipReservationCancelledTitle': 'Zrušení alokovanej rezervace',
  'auditMembershipReservationCancelledDescription':
      'Administrátor zrušil alokovanú rezervaci navázanou na permanentku.',
  'auditMembershipAllReservationsCancelledTitle':
      'Zrušení všech alokovaných rezervací',
  'auditMembershipAllReservationsCancelledDescription':
      'Administrátor zrušil všechny alokované rezervace naviazané na permanentku.',
  'auditMembershipAssignedTitle': 'Přiřazení permanentky',
  'auditMembershipAssignedDescription':
      'Uživatelovi byla manuálne přiřazena permanentka.',
  'auditMembershipPurchasedTitle': 'Nákup permanentky',
  'auditMembershipPurchasedDescription': 'Uživatel si zakoupil permanentku.',
  'auditActionMembershipAssigned': 'Přiřazení permanentky',
  'auditActionMembershipPurchased': 'Nákup permanentky',
  'auditActionMembershipUpdated': 'Úprava permanentky',
  'auditActionMembershipStatusChanged': 'Zmena stavu permanentky',
  'auditActionMembershipEntriesChanged': 'Zmena vstupov permanentky',
  'auditActionMembershipReservationCancelled':
      'Zrušení jednej alokovanej rezervace',
  'auditActionMembershipAllReservationsCancelled':
      'Zrušení všech alokovaných rezervací',
  'auditActionReservationCreated': 'Vytvoření rezervace',
  'auditActionReservationCancelled': 'Zrušení rezervace',
  'auditActionAttendanceAttended': 'Označená účast',
  'auditActionAttendanceNoShow': 'Označená neúčast',
  'auditActionTrainingTypeCreated': 'Vytvoření typu cvičení',
  'auditActionTrainingTypeUpdated': 'Úprava typu cvičení',
  'auditActionTrainingTypeDeactivated': 'Deaktivace typu cvičení',
  'auditActionTrainingSessionCreated': 'Vytvoření termínu',
  'auditActionTrainingSessionUpdated': 'Úprava termínu',
  'auditActionTrainingSessionTimeChanged': 'Změna času termínu',
  'auditActionTrainingSessionCancelled': 'Zrušení termínu',
  'auditActionScheduleTemplateCreated': 'Vytvoření šablony',
  'auditActionScheduleTemplateUpdated': 'Úprava šablony',
  'auditActionScheduleTemplateDeactivated': 'Deaktivace šablony',
  'auditActionUserUpdated': 'Úprava uživatele',
  'auditActionUserRoleChanged': 'Zmena roly',
  'auditActionUserDeactivationBlocked': 'Blokovaná deaktivácia',
  'auditActionUserDeactivated': 'Deaktivace uživatele',
  'auditActionPublicMessageCreated': 'Vytvoření novinky',
  'auditActionPublicMessageUpdated': 'Úprava novinky',
  'auditActionPublicMessageDeleted': 'Smazání novinky',
  'auditActionProfileCompleted': 'Doplnění profilu',
  'auditActionProfileUpdated': 'Úprava profilu',
  'auditActionProfilePhotoUpdated': 'Úprava profilové fotky',
  'auditActionProfilePhotoRemoved': 'Odstránenie profilové fotky',
  'auditActionPaymentStarted': 'Spustenie platby',
  'auditUserEmailCompletedTitle': 'Doplnění e-mailu',
  'auditUserEmailCompletedDescription':
      'Uživatel doplnil chýbajúci e-mail k účtu.',
  'currentUserShort': 'vy',
  'auditUserEmailUpdatedTitle': 'Úprava e-mailu uživatele',
  'auditUserEmailUpdatedDescription':
      'Administrátor upravil kontaktní e-mail uživatele.',
  'auditUserReactivatedTitle': 'Aktivace uživatele',
  'auditUserReactivatedDescription': 'Administrátor znovu aktivoval uživatele.',
  'auditActionUserEmailCompleted': 'Doplnění e-mailu',
  'auditActionUserEmailUpdated': 'Úprava e-mailu uživatele',
  'auditActionUserReactivated': 'Aktivace uživatele',
  'auditCategoryDiscounts': 'Slevy',
  'auditDiscountRequestedTitle': 'Žádost o slevu',
  'auditDiscountRequestedDescription':
      'Uživatel odoslal žádost o schválení slevy.',
  'auditDiscountApprovedTitle': 'Schválení slevy',
  'auditDiscountApprovedDescription':
      'Administrátor schválil uživatelůi slevu.',
  'auditDiscountRejectedTitle': 'Zamítnutí slevy',
  'auditDiscountRejectedDescription':
      'Administrátor zamietol uživatelůi žádost o slevu.',
  'auditAccountDeletionRequestedTitle': 'Žádost o smazání účtu',
  'auditAccountDeletionRequestedDescription':
      'Uživatel požádal o smazání účtu.',
  'auditEmailChangeRequestedTitle': 'Žádost o změnu e-mailu',
  'auditEmailChangeRequestedDescription':
      'Uživatel požádal o změnu e-mailové adresy.',
  'auditEmailChangeCompletedTitle': 'Dokončení zmeny e-mailu',
  'auditEmailChangeCompletedDescription':
      'Uživatel dokončil změnu e-mailové adresy.',
  'auditPasswordResetRequestedTitle': 'Žádost o obnovení hesla',
  'auditPasswordResetRequestedDescription':
      'Uživatel požádal o odeslání e-mailu na obnovení hesla.',
  'auditActionDiscountRequested': 'Žádost o slevu',
  'auditActionDiscountApproved': 'Schválení slevy',
  'auditActionDiscountRejected': 'Zamítnutí slevy',
  'auditActionAccountDeletionRequested': 'Žádost o smazání účtu',
  'auditActionEmailChangeRequested': 'Žádost o změnu e-mailu',
  'auditActionEmailChangeCompleted': 'Dokončení zmeny e-mailu',
  'auditActionPasswordResetRequested': 'Žádost o obnovení hesla',
};

const Map<String, List<String>> appTextListsCs = {
  'shortWeekdays': ['Po', 'Út', 'St', 'Čt', 'Pá', 'So', 'Ne'],
  'weekdays': [
    'Pondělí',
    'Úterý',
    'Středa',
    'Čtvrtek',
    'Pátek',
    'Sobota',
    'Neděle',
  ],
};
