// Ukrajinské texty aplikácie.
const Map<String, String> appTextsUk = {
  'appName': 'Body Fit Club TT',
  'loading': 'Завантаження...',
  'ok': 'OK',
  'save': 'Зберегти',
  'delete': 'видалити',
  'cancel': 'Скасувати',
  'back': 'Назад',
  'today': 'Сьогодні',
  'tomorrow': 'Завтра',
  'todayLower': 'сьогодні',
  'tomorrowLower': 'завтра',
  'minutes': 'хв.',
  'refresh': 'Оновити',
  'yesterday': 'Вчора',
  'last7Days': 'Останні 7 днів',
  'last30Days': 'Останні 30 днів',
  'allTime': 'Увесь період',
  'close': 'Закрити',
  'reason': 'Причина',
  'unknownDate': 'Невідома дата',
  'notSet': 'Не встановлено',
  'confirm': 'Підтвердити',
  'menu': 'Меню',
  'home': 'Головна',
  'schedule': 'Розклад',
  'reservations': 'Бронювання',
  'management': 'Керування',
  'profile': 'Профіль',
  'settings': 'Налаштування',
  'appearance': 'Вигляд',
  'appearanceDescription': 'Виберіть світлий, темний або системний режим.',
  'themeSystem': 'За системою',
  'themeLight': 'Світлий режим',
  'themeDark': 'Темний режим',
  'menuPosition': 'Розташування меню',
  'menuPositionDescription':
      'Виберіть, з якого боку має відображатися головне меню.',
  'rightHanded': 'Правша',
  'leftHanded': 'Лівша',
  'menuRightPositionDescription': 'Меню буде праворуч угорі.',
  'menuLeftPositionDescription': 'Меню буде ліворуч угорі.',
  'language': 'Мова',
  'languageDescription': 'Виберіть мову застосунку.',
  'languageSlovak': '🇸🇰 Словацька',
  'languageEnglish': '🇬🇧 Англійська',
  'languageGerman': '🇩🇪 Німецька',
  'languageFrench': '🇫🇷 Французька',
  'languagePolish': '🇵🇱 Польська',
  'languageHungarian': '🇭🇺 Угорська',
  'languageUkrainian': '🇺🇦 Українська',
  'languageRussian': '🇷🇺 Російська',
  'languageSerbian': '🇷🇸 Сербська',
  'languageCzech': '🇨🇿 Чеська',
  'role': 'Роль',
  'roleUser': 'Користувач',
  'roleTrainer': 'Тренер',
  'roleAdmin': 'Адміністратор',
  'roleUnknown': 'Невідома роль',
  'privacyPolicy': 'Політика конфіденційності',
  'emailContact': 'E-mail',
  'loginTitle': 'Вхід',
  'registerTitle': 'Реєстрація',
  'continueWithGoogle': 'Продовжити через Google',
  'continueWithFacebook': 'Продовжити через Facebook',
  'or': 'або',
  'email': 'E-mail',
  'password': 'Пароль',
  'login': 'Увійти',
  'register': 'Зареєструватися',
  'logout': 'Вийти',
  'noAccountRegister': 'Немає облікового запису? Зареєструватися',
  'hasAccountLogin': 'Вже маєте обліковий запис? Увійти',
  'authError': 'Помилка входу',
  'acceptTerms': 'Я погоджуюся з умовами користування',
  'acceptPrivacy': 'Я погоджуюся на обробку персональних даних',
  'termsConsentRequired':
      'Для реєстрації потрібно погодитися з умовами користування.',
  'privacyConsentRequired':
      'Для реєстрації потрібно погодитися на обробку персональних даних.',
  'openTerms': 'Відкрити умови користування',
  'openPrivacy': 'Відкрити політику конфіденційності',
  'termsVersion': '2026-05-16',
  'privacyVersion': '2026-05-16',
  'continueWithoutAccount': 'Продовжити без облікового запису',
  'completeEmailOrLogout':
      'Якщо ви не хочете додавати e-mail, можете продовжити без облікового запису і пізніше увійти з іншим обліковим записом.',
  'fillEmailPassword': 'Заповніть e-mail і пароль.',
  'invalidEmailFormat': 'Введіть дійсну e-mail адресу.',
  'passwordTooShort': 'Пароль має містити щонайменше 6 символів.',
  'wrongEmailOrPassword': 'Введений e-mail або пароль неправильний.',
  'userAlreadyExists': 'Користувач з цією e-mail адресою вже існує.',
  'weakPassword': 'Введений пароль занадто слабкий.',
  'tooManyRequests': 'Забагато спроб. Спробуйте пізніше.',
  'networkError': 'Перевірте інтернет-з’єднання.',
  'signInCancelled': 'Вхід було скасовано.',
  'facebookLoginFailed': 'Не вдалося увійти через Facebook.',
  'unknownAuthError': 'Під час входу сталася невідома помилка.',
  'inactiveAccount':
      'Ваш обліковий запис деактивовано. Зверніться до адміністратора.',
  'verificationEmailSent':
      'Реєстрація пройшла успішно. Ми надіслали вам лист для підтвердження. Якщо його немає у вхідних, перевірте також папку Спам.',
  'emailNotVerified':
      'Спочатку підтвердьте реєстрацію, натиснувши посилання в e-mail.',
  'verificationEmailSentAgain':
      'Ми знову надіслали вам лист для підтвердження. Якщо його немає у вхідних, перевірте також папку Спам.',
  'forgotPassword': 'Забули пароль?',
  'resetPasswordTitle': 'Відновлення пароля',
  'sendResetEmail': 'Надіслати e-mail',
  'passwordResetEmailSent':
      'Якщо обліковий запис з цією e-mail адресою існує, ми надіслали лист для відновлення пароля.',
  'emailRequired': 'Введіть e-mail.',
  'emailNotProvided': 'E-mail не надано',
  'emailSaved': 'E-mail збережено.',
  'emailSaveError': 'Не вдалося зберегти e-mail.',
  'emailChangeVerificationSent':
      'На новий e-mail надіслано посилання для підтвердження. Зміна завершиться після його підтвердження.',
  'emailChangeRequestError': 'Не вдалося розпочати зміну e-mail.',
  'emailChangeNotAvailable':
      'Зміна e-mail доступна лише для облікових записів, створених через e-mail і пароль.',
  'completeProfileTitle': 'Заповнення профілю',
  'editProfile': 'Редагувати профіль',
  'firstName': 'Ім’я',
  'lastName': 'Прізвище',
  'publicName': 'Відображуване ім’я',
  'publicNameHint': 'Напр. Barbora, Katka, Aďo',
  'firstNameRequired': 'Введіть ім’я.',
  'lastNameRequired': 'Введіть прізвище.',
  'publicNameRequired': 'Введіть відображуване ім’я.',
  'profileSaved': 'Профіль збережено.',
  'profileSaveError': 'Не вдалося зберегти профіль.',
  'loggedInUser': 'Увійшов користувач',
  'completeEmailTitle': 'Додавання e-mail',
  'completeEmailDescription':
      'Для використання застосунку нам потрібна ваша e-mail адреса. Ми використаємо її як контактний e-mail вашого облікового запису.',
  'deleteAccountRequest': 'Подати запит на видалення облікового запису',
  'deleteAccountRequestTitle': 'Видалення облікового запису',
  'deleteAccountRequestDescription':
      'Після надсилання запиту обліковий запис буде деактивовано, і в нього не можна буде увійти. Дані надалі опрацює адміністратор відповідно до правил захисту персональних даних.',
  'deleteAccountReason': 'Причина запиту',
  'deleteAccountConfirm':
      'Ви справді хочете подати запит на видалення облікового запису?',
  'deleteAccountRequestSent': 'Запит на видалення облікового запису надіслано.',
  'deleteAccountRequestError':
      'Не вдалося надіслати запит на видалення облікового запису.',
  'deleteAccountBlockedActiveReservations':
      'Обліковий запис неможливо видалити, бо у вас є активні бронювання.',
  'accountDeletionRequests': 'Запити на видалення облікових записів',
  'accountDeletionRequestsWithCount': 'Запити на видалення облікових записів',
  'accountDeletionRequestsLoadError':
      'Не вдалося завантажити запити на видалення облікових записів.',
  'noAccountDeletionRequests': 'Немає зареєстрованих очікуваних запитів.',
  'completeAccountDeletion': 'Анонімізувати обліковий запис',
  'completeAccountDeletionTitle': 'Анонімізувати обліковий запис',
  'completeAccountDeletionQuestion':
      'Ви справді хочете анонімізувати цей обліковий запис? Ця дія перезапише персональні дані користувача.',
  'accountDeletionCompleted': 'Обліковий запис анонімізовано.',
  'accountDeletionCompleteError': 'Не вдалося анонімізувати обліковий запис.',
  'requestedAt': 'Запитано',
  'accountDeletionRequestsWaiting': 'Запити, що очікують на обробку.',
  'changeEmail': 'змінити e-mail',
  'changeEmailTitle': 'Зміна e-mail',
  'changeEmailDescription':
      'Введіть новий e-mail і поточний пароль. На новий e-mail ми надішлемо посилання для підтвердження. Зміна завершиться лише після підтвердження посилання.',
  'changeEmailProfileHint':
      'доступно для облікових записів, створених через e-mail і пароль.',
  'newEmail': 'Новий e-mail',
  'currentPassword': 'Поточний пароль',
  'sendVerificationEmail': 'Надіслати лист підтвердження',
  'wrongCurrentPassword': 'Поточний пароль неправильний.',
  'requiresRecentLogin': 'Для цієї дії спочатку вийдіть і увійдіть знову.',
  'changeProfilePhoto': 'змінити фото профілю',
  'chooseFromGallery': 'Вибрати з галереї',
  'takePhoto': 'Зробити фото',
  'removePhoto': 'видалити фото',
  'editPhoto': 'Редагувати фото',
  'cropProfilePhoto': 'Обрізати фото профілю',
  'profilePhotoUpdated': 'Фото профілю збережено.',
  'profilePhotoUpdateError': 'Не вдалося зберегти фото профілю.',
  'profilePhotoRemoveError': 'Не вдалося видалити фото профілю.',
  'requestDiscount': 'Подати запит на знижку',
  'discountStatus': 'Статус знижки',
  'discountStatusNone': 'Без знижки',
  'discountStatusPending': 'Очікує схвалення',
  'discountStatusApproved': 'Знижку схвалено',
  'discountStatusRejected': 'Запит відхилено',
  'discountStatusExpired': 'Термін дії знижки закінчився',
  'discountType': 'Тип знижки',
  'discountTypeNormal': 'Звичайний користувач',
  'discountTypeStudent': 'Студент',
  'discountTypeSenior': 'Пенсіонер',
  'discountTypeZtp': 'Особа з інвалідністю',
  'discountTypeIndividual': 'Індивідуальна знижка',
  'discountRequestDescription':
      'Виберіть тип знижки, на яку подаєте запит. Після надсилання запит перевірить адміністратор.',
  'discountRequestNote': 'Примітка до запиту',
  'discountRequestSent': 'Запит на знижку надіслано.',
  'discountRequestError': 'Не вдалося надіслати запит на знижку.',
  'discountRequestAlreadyPending': 'У вас уже є запит на знижку в обробці.',
  'discountRequestPending': 'Запит очікує схвалення',
  'sendRequest': 'Надіслати запит',
  'discountDocument': 'Документ для знижки',
  'discountDocumentDescription':
      'Завантажте фото документа, за яким адміністратор перевірить право на знижку.',
  'chooseDiscountDocument': 'Вибрати документ',
  'discountDocumentRequired': 'Для надсилання запиту потрібно додати документ.',
  'discountDocumentSelected': 'Документ вибрано',
  'takeDiscountDocumentPhoto': 'Сфотографувати документ',
  'chooseDiscountDocumentFromGallery': 'Вибрати з галереї',
  'discountRequests': 'Запити на знижку',
  'discountRequestsDescription':
      'Схвалення або відхилення запитів користувачів на знижку.',
  'discountRequestsLoadError': 'Не вдалося завантажити запити на знижку.',
  'noDiscountRequests': 'Немає зареєстрованих очікуваних запитів на знижку.',
  'approveDiscount': 'Схвалити знижку',
  'rejectDiscount': 'Відхилити запит',
  'discountApproved': 'Знижку схвалено.',
  'discountRejected': 'Запит на знижку відхилено.',
  'discountDecisionError': 'Не вдалося зберегти рішення щодо запиту.',
  'discountValidUntilRequired': 'Виберіть дату дії знижки.',
  'discountAdminNote': 'Примітка адміністратора',
  'selectDiscountValidUntil': 'Виберіть термін дії знижки',
  'discountDocumentPreview': 'Попередній перегляд документа',
  'todayReservations': 'Сьогоднішні бронювання',
  'noTodayReservations': 'Сьогодні у вас немає заброньованого тренування.',
  'nearestTraining': 'Найближче тренування',
  'nearestTrainings': 'Найближчі тренування',
  'noNearestTraining': 'Немає запланованого найближчого тренування.',
  'todaysTrainings': 'Сьогоднішні тренування',
  'noTodaysTrainings': 'Сьогодні немає запланованих тренувань.',
  'myMemberships': 'Мої абонементи',
  'activeMembershipsCount': 'Активні абонементи',
  'availableEntriesSummary': 'Доступні входи',
  'reservedEntriesSummary': 'Зарезервовані входи',
  'dailyMembershipsSummary': 'Денні абонементи',
  'tapToShowQrCode': 'Натисніть, щоб показати QR-код.',
  'nearestReservations': 'Найближчі бронювання',
  'noNearestReservations': 'У вас немає найближчих бронювань.',
  'qrShort': 'QR',
  'membershipStatus': 'Стан абонемента',
  'remainingEntries': 'Залишок входів',
  'upcomingTraining': 'Найближче сьогоднішнє тренування',
  'schedulePlaceholder': 'Тут буде розклад тренувань.',
  'reservationsPlaceholder': 'Тут будуть бронювання.',
  'newsPlaceholder':
      'Тут відображатимуться новини та повідомлення від тренерів.',
  'aboutApp': 'Про застосунок',
  'aboutUs': 'Про нас',
  'aboutAppDescription':
      'Застосунок Body Fit Club TT призначений для керування тренуваннями, бронюваннями, абонементами та комунікацією між фітнес-центром і користувачами.',
  'aboutUsDescription':
      'Body Fit Club — фітнес-центр у Трнаві, орієнтований на групові та індивідуальні тренування, рух, здоровий спосіб життя та персональний підхід до клієнтів.',
  'bodyFitClubWebsite': 'https://bodyfitclub.sk/',
  'openWebsite': 'Відкрити вебсторінку',
  'businessTerms': 'Умови користування',
  'legalDocumentsInfo':
      'Умови користування та інформація про захист персональних даних будуть доступні на вебсайті Body Fit Club.',
  'contacts': 'Контакти',
  'billingDetails': 'Платіжні дані',
  'address': 'Адреса',
  'phone': 'Телефон',
  'website': 'Вебсторінка',
  'socialNetworks': 'Соціальні мережі',
  'openMap': 'Відкрити карту',
  'openFacebook': 'Facebook',
  'openInstagram': 'Instagram',
  'multisport': 'MultiSport',
  'multisportInfo':
      'Ми приймаємо картку MultiSport відповідно до актуальних умов закладу.',
  'bodyFitClubCompanyName': 'BODYFIT CLUB s.r.o.',
  'bodyFitClubOperationAddress': 'V Jame 24, Trnava',
  'bodyFitClubBillingAddress': 'J. G. Tajovského 18, 917 08 Trnava',
  'bodyFitClubPhonePrimary': '+421 902 860 008',
  'bodyFitClubPhoneSecondary': '+421 903 946 895',
  'bodyFitClubEmail': 'bodyfitclubtt@gmail.com',
  'bodyFitClubIco': '48074128',
  'ico': 'IČO:',
  'companySeat': 'Юридична адреса',
  'operation': 'Заклад',
  'bodyFitClubFacebookUrl': 'https://www.facebook.com/bodyfitclub.sk',
  'bodyFitClubInstagramUrl': 'https://www.instagram.com/bodyfitclub.tt/',
  'bodyFitClubMapUrl':
      'https://www.google.com/maps/search/?api=1&query=V%20Jame%206641%2F24%2C%20917%2001%20Trnava',
  'bodyFitClubMultiSportUrl':
      'https://multi-sport.sk/aktivity/partner/bodyfit-club/',
  'multisportInfo2':
      'Body Fit Club є партнером програми MultiSport. Прийняття картки MultiSport регулюється актуальними умовами закладу.',
  'bodyFitClubWebsiteLabel': 'www.bodyfitclub.sk',
  'dic': 'DIČ:',
  'bodyFitClubDic': '2120035445',
  'notVatPayer': 'Компанія не є платником ПДВ',
  'legalDocuments': 'Юридичні документи',
  'priceList': 'Прайс-лист',
  'priceListAudience': 'Для',
  'priceListAudienceNormal': 'звичайних користувачів',
  'priceListAudienceDiscount': 'користувачів зі знижкою',
  'priceListAudienceAll': 'усіх',
  'price': 'Ціна',
  'singleEntries': 'Разові входи',
  'priceListMemberships': 'Абонементи',
  'chooseEntry': 'Виберіть вхід',
  'noAvailablePlans': 'Наразі немає доступних варіантів купівлі.',
  'news': 'Новини',
  'noPublicMessages': 'Поки що немає повідомлень.',
  'writeMessage': 'Написати повідомлення',
  'writeMessageShort': 'Написати',
  'editMessage': 'Редагувати повідомлення',
  'deleteMessage': 'видалити повідомлення',
  'deleteMessageQuestion': 'Ви справді хочете видалити це повідомлення?',
  'messageText': 'Текст повідомлення',
  'messageHint': 'Напишіть повідомлення...',
  'sendMessage': 'Надіслати',
  'updateMessage': 'Зберегти зміни',
  'messageSaved': 'Повідомлення збережено.',
  'messageDeleted': 'Повідомлення видалено.',
  'messageSaveError': 'Не вдалося зберегти повідомлення.',
  'messageDeleteError': 'Не вдалося видалити повідомлення.',
  'editedBy': 'змінено',
  'editedByAdmin': 'змінено адміністратором',
  'editedByTrainer': 'змінено тренером',
  'userFallback': 'Користувач',
  'noTrainings': 'Наразі немає доступних тренувань.',
  'noTrainingsForSelectedDay': 'На цей день немає запланованих тренувань.',
  'trainer': 'Тренер',
  'freeSpots': 'Вільні місця',
  'reserve': 'Забронювати',
  'reserved': 'Заброньовано',
  'fullCapacity': 'Місць немає',
  'trainingsLoadError': 'Не вдалося завантажити розклад тренувань.',
  'unknownTraining': 'Невідоме тренування',
  'unknownTrainer': 'Невідомий тренер',
  'unknownUser': 'Невідомий користувач',
  'trainingSessionFinished': 'Відбулося',
  'trainingSessionTooFarInFuture':
      'Дата занадто далеко в майбутньому. Вручну можна додати тренування лише в межах періоду, показаного в розкладі.',
  'managementDescription':
      'Тут можна керувати термінами тренувань, відвідуваністю, абонементами та користувачами.',
  'scheduleManagement': 'Керування розкладом',
  'scheduleManagementDescription':
      'Керування типами тренувань, шаблонами розкладу та конкретними термінами тренувань.',
  'attendanceManagement': 'Керування відвідуваністю',
  'usersManagement': 'Керування користувачами',
  'usersManagementComingSoon': 'Керування користувачами буде додано пізніше.',
  'scheduleTemplatesManagement': 'Керування шаблонами розкладу',
  'reactivateUser': 'Активувати користувача',
  'reactivateUserQuestion':
      'Ви справді хочете знову активувати цього користувача?',
  'userReactivated': 'Користувача знову активовано.',
  'trainingTypesManagement': 'Керування типами тренувань',
  'addTrainingType': 'Додати тип тренування',
  'editTrainingType': 'Редагувати тип тренування',
  'deleteTrainingType': 'видалити тип тренування',
  'trainingType': 'Тип тренування',
  'selectTrainingType': 'Виберіть тип тренування',
  'trainingName': 'назва тренування',
  'description': 'Опис',
  'defaultDuration': 'Стандартна тривалість',
  'defaultCapacity': 'Стандартна місткість',
  'noTrainingTypes': 'Наразі не створено жодного типу тренування.',
  'trainingTypesLoadError': 'Не вдалося завантажити типи тренувань.',
  'trainingTypeCreated': 'Тип тренування створено.',
  'trainingTypeUpdated': 'Тип тренування оновлено.',
  'trainingTypeDeleted': 'Тип тренування видалено.',
  'trainingTypeDeleteQuestion':
      'Ви справді хочете видалити цей тип тренування? Він більше не пропонуватиметься для нових термінів.',
  'trainingTypeAlreadyExists': 'Тип тренування з такою назвою вже існує.',
  'trainingTypeUsedByTemplate':
      'Тип тренування неможливо видалити, бо він використовується в активному шаблоні розкладу.',
  'trainingTypeUsedBySession':
      'Тип тренування неможливо видалити, бо він використовується в майбутньому терміні тренування.',
  'addTrainingSession': 'Додати термін тренування',
  'editTrainingSession': 'Редагувати деталі тренування',
  'trainingSessionCreated': 'Термін тренування створено.',
  'trainingSessionUpdated': 'Термін тренування оновлено.',
  'updateTrainingSessionError': 'Не вдалося оновити термін тренування.',
  'trainingSessionInPast': 'Термін тренування не може бути в минулому.',
  'trainingSessionOverlap': 'У цей час уже заплановане інше тренування.',
  'capacityLowerThanReservations':
      'Місткість не може бути меншою за кількість наявних бронювань.',
  'cancelTrainingSession': 'Скасувати термін',
  'cancelTrainingSessionTitle': 'Скасувати термін тренування',
  'cancelTrainingSessionQuestion':
      'Ви справді хочете скасувати цей термін тренування? Активні бронювання будуть скасовані, а зарезервовані входи звільняться. Якщо вхід уже було використано, його буде повернено користувачу.',
  'cancelTrainingSessionConfirm': 'Скасувати термін',
  'trainingSessionCancelled': 'Термін тренування скасовано.',
  'cancelTrainingSessionError': 'Не вдалося скасувати термін тренування.',
  'trainerCanCancelOnlyOwnSession':
      'Тренер може скасувати лише власний термін.',
  'trainerCannotCancelStartedSession':
      'Тренер не може скасувати термін, який уже почався або відбувся.',
  'date': 'Дата',
  'startTime': 'Початок',
  'duration': 'Тривалість',
  'capacity': 'Місткість',
  'selectDate': 'Виберіть дату',
  'selectTrainer': 'Виберіть тренера',
  'trainersLoadError': 'Не вдалося завантажити тренерів.',
  'fillAllFields': 'Заповніть усі обов’язкові дані.',
  'invalidCapacity': 'Місткість має бути більшою за 0.',
  'invalidDuration': 'Тривалість має бути більшою за 0.',
  'saveError': 'Не вдалося зберегти.',
  'addScheduleTemplate': 'Додати шаблон розкладу',
  'editScheduleTemplate': 'Редагувати шаблон розкладу',
  'deleteScheduleTemplate': 'видалити шаблон розкладу',
  'noScheduleTemplates': 'Наразі не створено жодного шаблону розкладу.',
  'weekday': 'День тижня',
  'selectWeekday': 'Виберіть день тижня',
  'scheduleTemplateCreated': 'Шаблон розкладу створено.',
  'scheduleTemplateUpdated': 'Шаблон розкладу оновлено.',
  'scheduleTemplateDeleted': 'Шаблон розкладу видалено.',
  'scheduleTemplateDeleteQuestion':
      'Ви справді хочете видалити цей шаблон розкладу? Він більше не використовуватиметься для створення нових термінів.',
  'scheduleTemplateAlreadyExists': 'Такий шаблон розкладу вже існує.',
  'scheduleTemplateLoadError': 'Не вдалося завантажити шаблони розкладу.',
  'scheduleTemplateOverlap': 'У цей час уже існує інший шаблон розкладу.',
  'capacityLabel': 'Місткість',
  'reservationCreated': 'Бронювання створено.',
  'reservationAlreadyExists': 'На це тренування у вас уже є бронювання.',
  'reservationTrainingFull': 'Це тренування вже заповнене.',
  'reservationTrainingNotAvailable':
      'Це тренування вже недоступне для бронювання.',
  'reservationTrainingAlreadyStarted':
      'На це тренування вже не можна забронювати місце.',
  'reservationError': 'Не вдалося створити бронювання.',
  'myReservations': 'Мої бронювання',
  'noReservations': 'Наразі у вас немає бронювань.',
  'cancelReservation': 'Скасувати бронювання',
  'cancelReservationTitle': 'Скасувати бронювання',
  'cancelReservationQuestion': 'Ви справді хочете скасувати це бронювання?',
  'reservationCancelled': 'Бронювання скасовано.',
  'reservationCancelError': 'Не вдалося скасувати бронювання.',
  'reservationsLoadError': 'Не вдалося завантажити бронювання.',
  'cancelReservations': 'Скасувати бронювання',
  'cancelReservationsBeforeDeactivation':
      'Перед деактивацією або скасуванням абонемента спочатку скасуйте зарезервовані бронювання.',
  'cancelReservationForMembership': 'Скасувати це бронювання',
  'cancelReservationForMembershipQuestion':
      'Ви справді хочете скасувати це бронювання, пов’язане з абонементом? Зарезервований вхід звільниться.',
  'reservationForMembershipCancelled':
      'Бронювання скасовано, а зарезервований вхід звільнено.',
  'noReservationsForTrainingHistory': 'На цьому тренуванні немає бронювань.',
  'reservationQrCode': 'QR-код бронювання',
  'memberships': 'Абонементи',
  'assignMembership': 'Призначити абонемент',
  'selectUser': 'Виберіть користувача',
  'selectMembershipPlan': 'Виберіть тип абонемента',
  'membershipPlansLoadError': 'Не вдалося завантажити типи абонементів.',
  'membershipAssigned': 'Абонемент призначено.',
  'membershipAssignError': 'Не вдалося призначити абонемент.',
  'membershipPlan': 'Тип абонемента',
  'client': 'Користувач',
  'buyMembership': 'Купити абонемент',
  'buySingleEntry': 'Купити разовий вхід',
  'chooseMembership': 'Виберіть абонемент',
  'payment': 'Оплата',
  'pay': 'Оплатити',
  'paymentSuccessful': 'Оплата успішна.',
  'paymentFailed': 'Оплата не вдалася.',
  'activeMembership': 'Активний абонемент',
  'noActiveMembership': 'У вас немає активного абонемента.',
  'validUntil': 'Дійсний до',
  'membershipLoadError': 'Не вдалося завантажити абонемент.',
  'noAvailableEntries': 'У вас немає доступного входу для бронювання.',
  'noUpcomingTraining': 'Сьогодні у вас немає заброньованого тренування.',
  'membershipsManagement': 'Керування абонементами',
  'membershipDetail': 'Деталі абонемента',
  'noMemberships': 'Наразі немає доступних абонементів.',
  'status': 'Стан',
  'validFrom': 'Дійсний від',
  'entriesTotal': 'Загальна кількість входів',
  'entriesRemaining': 'Залишок входів',
  'entriesReserved': 'Зарезервовано в бронюваннях',
  'entriesAvailable': 'Доступні входи',
  'adminMembershipEdit': 'Адміністративна правка',
  'membershipStatusActive': 'Активний',
  'membershipStatusInactive': 'Неактивний',
  'membershipStatusCancelled': 'Скасований',
  'membershipStatusExpired': 'Прострочений',
  'membershipStatusUsedUp': 'Використаний',
  'membershipUpdated': 'Абонемент оновлено.',
  'membershipUpdateError': 'Не вдалося оновити абонемент.',
  'invalidRemainingEntries': 'Введіть дійсну кількість залишкових входів.',
  'allocatedReservations': 'Зарезервовані бронювання',
  'cancelAllocatedReservations': 'Скасувати зарезервовані бронювання',
  'cancelAllocatedReservationsQuestion':
      'Ви справді хочете скасувати активні бронювання, пов’язані з цим абонементом? Зарезервовані входи звільняться.',
  'cancelAllReservations': 'Скасувати всі бронювання',
  'cancelAllocatedReservationsError':
      'Не вдалося скасувати зарезервовані бронювання.',
  'usedEntries': 'Використані входи',
  'noAllocatedReservations':
      'До цього абонемента наразі не прив’язано жодного активного бронювання.',
  'noUsedEntries': 'З цього абонемента ще не було використано жодного входу.',
  'membershipUsageLoadError': 'Не вдалося завантажити історію абонемента.',
  'searchMemberships': 'Шукати за користувачем або абонементом',
  'allMembershipStatuses': 'Усі стани',
  'membershipStatusNotYetValid': 'Ще не дійсний',
  'membershipStatusUsable': 'Активний',
  'invalidRemainingEntriesHigherThanTotal':
      'Залишок входів не може бути більшим за загальну кількість входів.',
  'invalidRemainingEntriesLowerThanReserved':
      'Залишок входів не може бути меншим за кількість зарезервованих входів.',
  'membershipPrefix': 'Абонемент',
  'statusPrefix': 'Стан',
  'attendance': 'Відвідуваність',
  'attendanceLoadError': 'Не вдалося завантажити відвідуваність.',
  'noActiveReservationsForAttendance':
      'Наразі немає активних бронювань для позначення відвідуваності.',
  'attended': 'Прийшов',
  'noShow': 'Не прийшов',
  'markAttendedTitle': 'Позначити присутність',
  'markNoShowTitle': 'Позначити відсутність',
  'markAttendedQuestion':
      'Ви справді хочете позначити користувача як присутнього?',
  'markNoShowQuestion':
      'Ви справді хочете позначити користувача як відсутнього?',
  'attendanceMarked': 'Відвідуваність збережено.',
  'attendanceMarkError': 'Не вдалося зберегти відвідуваність.',
  'attendedStatus': 'Прийшов',
  'noShowStatus': 'Не прийшов',
  'attendedCountLabel': 'Прийшли',
  'noShowCountLabel': 'Не прийшли',
  'attendanceActionDone': 'Зміну відвідуваності збережено.',
  'attendanceActionError': 'Не вдалося зберегти зміну відвідуваності.',
  'showQrCode': 'QR-код',
  'showQrToTrainer':
      'Покажіть цей QR-код тренеру під час приходу на тренування.',
  'scanQrCode': 'Сканувати QR-код',
  'scanQrCodes': 'Сканувати QR-коди',
  'scanQrCodeHint': 'Наведіть камеру на QR-код бронювання користувача.',
  'invalidQrCode': 'Недійсний QR-код бронювання.',
  'qrCodeScanned': 'QR-код відскановано.',
  'qrScanSuccessful':
      'QR-код відскановано. Можете сканувати наступного користувача.',
  'trainerQrScanTooEarly':
      'QR-код можна сканувати не раніше ніж за 30 хвилин до початку тренування.',
  'trainingHistory': 'Історія тренувань',
  'trainingHistoryDetail': 'Деталі тренування',
  'trainingHistoryLoadError': 'Не вдалося завантажити історію тренувань.',
  'trainingHistoryReservationsLoadError':
      'Не вдалося завантажити участь у тренуванні.',
  'noTrainingHistoryInSelectedPeriod': 'У вибраному періоді немає тренувань.',
  'fromDatePrefix': 'Від',
  'toDatePrefix': 'До',
  'planned': 'Заплановано',
  'cancelled': 'Скасовано',
  'finished': 'Відбулося',
  'reservedStatus': 'Заброньовано',
  'reservedCountLabel': 'Заброньовано',
  'cancelledCountLabel': 'Скасовано',
  'markedAtPrefix': 'Позначено',
  'markAsAttended': 'Позначити як присутній',
  'markAsNoShow': 'Позначити як відсутній',
  'revertAttendance': 'Скасувати позначену присутність',
  'revertNoShow': 'Скасувати позначену відсутність',
  'markAsAttendedQuestion':
      'Ви справді хочете позначити користувача як присутнього? Вхід з абонемента буде використано.',
  'markAsNoShowQuestion':
      'Ви справді хочете позначити користувача як відсутнього? Вхід з абонемента буде використано.',
  'revertAttendanceQuestion':
      'Ви справді хочете скасувати позначену присутність? Використаний вхід повернеться на абонемент.',
  'revertNoShowQuestion':
      'Ви справді хочете скасувати позначену відсутність? Використаний вхід повернеться на абонемент.',
  'addTrainingAttendance': 'Додати учасника',
  'selectAttendanceUser': 'Виберіть користувача',
  'selectAttendanceMembership': 'Виберіть абонемент',
  'noUsersForAttendance': 'Не знайдено активних користувачів.',
  'noUsableMembershipsForAttendance':
      'Користувач не має придатного абонемента для цього тренування.',
  'addTrainingAttendanceQuestion':
      'Ви справді хочете додатково додати участь користувача в цьому тренуванні? Вхід з абонемента буде використано.',
  'trainingAttendanceAdded': 'Учасника додано до тренування.',
  'trainingAttendanceAddError': 'Не вдалося додати учасника.',
  'userAlreadyHasReservationForTraining':
      'Користувач уже має запис для цього тренування.',
  'usersLoadError': 'Не вдалося завантажити користувачів.',
  'allRoles': 'Усі ролі',
  'searchUsers': 'Шукати користувача',
  'noUsersFound': 'Користувачів не знайдено.',
  'editUser': 'Редагувати користувача',
  'userUpdated': 'Користувача оновлено.',
  'userUpdateError': 'Не вдалося оновити користувача.',
  'cannotChangeOwnRole': 'Ви не можете змінити власну роль.',
  'changeRoleWarning':
      'Під час зміни ролі користувача можуть змінитися його права в застосунку.',
  'deactivateUser': 'Деактивувати користувача',
  'deactivationReason': 'Причина деактивації',
  'userDeactivated': 'Користувача деактивовано.',
  'deactivateUserQuestion':
      'Ви справді хочете деактивувати цього користувача? Він більше не зможе використовуватися в керуванні застосунком.',
  'cannotDeactivateYourself':
      'Ви не можете деактивувати власний обліковий запис.',
  'userUsedByTemplate':
      'Користувача неможливо деактивувати або змінити на звичайного користувача, бо він призначений в активному шаблоні розкладу.',
  'userUsedByFutureSession':
      'Користувача неможливо деактивувати або змінити на звичайного користувача, бо він призначений до майбутнього тренування.',
  'userHasActiveReservations':
      'Користувача неможливо деактивувати, бо він має активні бронювання.',
  'userHasActiveMemberships':
      'Користувача неможливо деактивувати, бо він має активні абонементи.',
  'inactiveUser': 'Неактивний користувач',
  'userCannotBeDeactivated': 'Користувача неможливо деактивувати',
  'userCannotBeDeactivatedDescription':
      'Перед деактивацією потрібно спочатку вирішити його активні бронювання або абонементи.',
  'userHasBlockingItems': 'Користувач має:',
  'activeReservationsCount': 'Активні бронювання',
  'showMemberships': 'Показати абонементи',
  'auditLogs': 'Історія дій',
  'auditLogsDescription': 'Огляд важливих дій у застосунку.',
  'auditLogsLoadError': 'Не вдалося завантажити історію дій.',
  'noAuditLogs': 'Дій не знайдено.',
  'searchAuditLogs': 'Шукати за користувачем, e-mail або описом',
  'auditCategory': 'Категорія',
  'auditAction': 'Дія',
  'auditActor': 'Виконав',
  'auditActorRole': 'Роль виконавця',
  'auditPeriod': 'Період',
  'auditAllCategories': 'Усі категорії',
  'auditCategoryMemberships': 'Абонементи',
  'auditCategoryReservations': 'Бронювання',
  'auditCategoryAttendance': 'Відвідуваність',
  'auditCategoryUsers': 'Користувачі',
  'auditCategorySchedule': 'Розклад',
  'auditCategoryMessages': 'Повідомлення',
  'auditCategoryPayments': 'Оплати',
  'auditCategoryProfile': 'Профіль',
  'auditAllActions': 'Усі дії',
  'auditActionCreated': 'Створення',
  'auditActionUpdated': 'Зміна',
  'auditActionCancelled': 'Скасування',
  'auditActionDeactivated': 'Деактивація',
  'auditActionActivated': 'Активація',
  'auditActionAssigned': 'Призначення',
  'auditActionPurchased': 'Купівля',
  'auditActionPaymentSucceeded': 'Оплата успішна',
  'auditActionPaymentFailed': 'Оплата не вдалася',
  'auditActionAttendanceMarked': 'Відвідуваність',
  'auditActionQrChecked': 'QR-контроль',
  'auditAllActorRoles': 'Усі ролі',
  'auditReservationCreatedTitle': 'Створення бронювання',
  'auditReservationCreatedDescription':
      'Користувач створив бронювання на тренування.',
  'auditReservationCancelledTitle': 'Скасування бронювання',
  'auditReservationCancelledDescription':
      'Бронювання користувача було скасовано.',
  'auditAttendanceAttendedTitle': 'Позначена присутність',
  'auditAttendanceAttendedDescription':
      'Користувача позначено як присутнього на тренуванні.',
  'auditAttendanceNoShowTitle': 'Позначена відсутність',
  'auditAttendanceNoShowDescription':
      'Користувача позначено як відсутнього на тренуванні.',
  'auditTrainingTypeCreatedTitle': 'Створення типу тренування',
  'auditTrainingTypeUpdatedTitle': 'Зміна типу тренування',
  'auditTrainingTypeDeactivatedTitle': 'Деактивація типу тренування',
  'auditTrainingSessionCreatedTitle': 'Створення терміну',
  'auditTrainingSessionUpdatedTitle': 'Зміна терміну',
  'auditTrainingSessionTimeChangedTitle': 'Зміна часу терміну',
  'auditTrainingSessionCancelledTitle': 'Скасування терміну',
  'auditScheduleTemplateCreatedTitle': 'Створення шаблону розкладу',
  'auditScheduleTemplateUpdatedTitle': 'Зміна шаблону розкладу',
  'auditScheduleTemplateDeactivatedTitle': 'Деактивація шаблону розкладу',
  'auditUserUpdatedTitle': 'Зміна користувача',
  'auditUserUpdatedDescription': 'Адміністратор змінив дані користувача.',
  'auditUserRoleChangedTitle': 'Зміна ролі користувача',
  'auditUserRoleChangedDescription': 'Адміністратор змінив роль користувача.',
  'auditUserDeactivatedTitle': 'Деактивація користувача',
  'auditUserDeactivatedDescription': 'Адміністратор деактивував користувача.',
  'auditUserDeactivationBlockedTitle': 'Невдала деактивація користувача',
  'auditUserDeactivationBlockedDescription':
      'Деактивацію користувача заблоковано перевіркою активних зв’язків.',
  'auditPublicMessageCreatedTitle': 'Створення новини',
  'auditPublicMessageCreatedDescription': 'Було створено публічну новину.',
  'auditPublicMessageUpdatedTitle': 'Зміна новини',
  'auditPublicMessageUpdatedDescription': 'Публічну новину було змінено.',
  'auditPublicMessageDeletedTitle': 'Видалення новини',
  'auditPublicMessageDeletedDescription': 'Публічну новину було видалено.',
  'auditProfileCompletedTitle': 'Заповнення профілю',
  'auditProfileCompletedDescription':
      'Користувач заповнив основні дані профілю.',
  'auditProfileUpdatedTitle': 'Зміна профілю',
  'auditProfileUpdatedDescription': 'Користувач змінив дані профілю.',
  'auditProfilePhotoUpdatedTitle': 'Зміна фото профілю',
  'auditProfilePhotoUpdatedDescription': 'Користувач змінив фото профілю.',
  'auditProfilePhotoRemovedTitle': 'Видалення фото профілю',
  'auditProfilePhotoRemovedDescription':
      'Користувач видалив вручну встановлене фото профілю.',
  'auditPaymentStartedTitle': 'Запуск оплати',
  'auditPaymentStartedDescription': 'Користувач розпочав оплату абонемента.',
  'auditPaymentSucceededTitle': 'Успішна оплата',
  'auditPaymentSucceededDescription': 'Оплату абонемента успішно завершено.',
  'auditPaymentFailedTitle': 'Невдала оплата',
  'auditPaymentFailedDescription':
      'Оплата абонемента не вдалася або була скасована.',
  'auditMembershipUpdatedTitle': 'Зміна абонемента',
  'auditMembershipUpdatedDescription':
      'Адміністратор змінив абонемент користувача.',
  'auditMembershipStatusChangedTitle': 'Зміна стану абонемента',
  'auditMembershipStatusChangedDescription':
      'Адміністратор змінив стан абонемента користувача.',
  'auditMembershipEntriesChangedTitle': 'Зміна кількості входів абонемента',
  'auditMembershipEntriesChangedDescription':
      'Адміністратор змінив кількість залишкових входів абонемента.',
  'auditMembershipReservationCancelledTitle':
      'Скасування зарезервованого бронювання',
  'auditMembershipReservationCancelledDescription':
      'Адміністратор скасував зарезервоване бронювання, пов’язане з абонементом.',
  'auditMembershipAllReservationsCancelledTitle':
      'Скасування всіх зарезервованих бронювань',
  'auditMembershipAllReservationsCancelledDescription':
      'Адміністратор скасував усі зарезервовані бронювання, пов’язані з абонементом.',
  'auditMembershipAssignedTitle': 'Призначення абонемента',
  'auditMembershipAssignedDescription':
      'Користувачу вручну призначено абонемент.',
  'auditMembershipPurchasedTitle': 'Купівля абонемента',
  'auditMembershipPurchasedDescription': 'Користувач придбав абонемент.',
  'auditActionMembershipAssigned': 'Призначення абонемента',
  'auditActionMembershipPurchased': 'Купівля абонемента',
  'auditActionMembershipUpdated': 'Зміна абонемента',
  'auditActionMembershipStatusChanged': 'Зміна стану абонемента',
  'auditActionMembershipEntriesChanged': 'Зміна входів абонемента',
  'auditActionMembershipReservationCancelled':
      'Скасування одного зарезервованого бронювання',
  'auditActionMembershipAllReservationsCancelled':
      'Скасування всіх зарезервованих бронювань',
  'auditActionReservationCreated': 'Створення бронювання',
  'auditActionReservationCancelled': 'Скасування бронювання',
  'auditActionAttendanceAttended': 'Позначена присутність',
  'auditActionAttendanceNoShow': 'Позначена відсутність',
  'auditActionTrainingTypeCreated': 'Створення типу тренування',
  'auditActionTrainingTypeUpdated': 'Зміна типу тренування',
  'auditActionTrainingTypeDeactivated': 'Деактивація типу тренування',
  'auditActionTrainingSessionCreated': 'Створення терміну',
  'auditActionTrainingSessionUpdated': 'Зміна терміну',
  'auditActionTrainingSessionTimeChanged': 'Зміна часу терміну',
  'auditActionTrainingSessionCancelled': 'Скасування терміну',
  'auditActionScheduleTemplateCreated': 'Створення шаблону',
  'auditActionScheduleTemplateUpdated': 'Зміна шаблону',
  'auditActionScheduleTemplateDeactivated': 'Деактивація шаблону',
  'auditActionUserUpdated': 'Зміна користувача',
  'auditActionUserRoleChanged': 'Зміна ролі',
  'auditActionUserDeactivationBlocked': 'Заблокована деактивація',
  'auditActionUserDeactivated': 'Деактивація користувача',
  'auditActionPublicMessageCreated': 'Створення новини',
  'auditActionPublicMessageUpdated': 'Зміна новини',
  'auditActionPublicMessageDeleted': 'Видалення новини',
  'auditActionProfileCompleted': 'Заповнення профілю',
  'auditActionProfileUpdated': 'Зміна профілю',
  'auditActionProfilePhotoUpdated': 'Зміна фото профілю',
  'auditActionProfilePhotoRemoved': 'Видалення фото профілю',
  'auditActionPaymentStarted': 'Запуск оплати',
  'auditUserEmailCompletedTitle': 'Додавання e-mail',
  'auditUserEmailCompletedDescription':
      'Користувач додав відсутній e-mail до облікового запису.',
  'currentUserShort': 'ви',
  'auditUserEmailUpdatedTitle': 'Зміна e-mail користувача',
  'auditUserEmailUpdatedDescription':
      'Адміністратор змінив контактний e-mail користувача.',
  'auditUserReactivatedTitle': 'Активація користувача',
  'auditUserReactivatedDescription':
      'Адміністратор знову активував користувача.',
  'auditActionUserEmailCompleted': 'Додавання e-mail',
  'auditActionUserEmailUpdated': 'Зміна e-mail користувача',
  'auditActionUserReactivated': 'Активація користувача',
  'auditCategoryDiscounts': 'Знижки',
  'auditDiscountRequestedTitle': 'Запит на знижку',
  'auditDiscountRequestedDescription':
      'Користувач надіслав запит на схвалення знижки.',
  'auditDiscountApprovedTitle': 'Схвалення знижки',
  'auditDiscountApprovedDescription':
      'Адміністратор схвалив користувачу знижку.',
  'auditDiscountRejectedTitle': 'Відхилення знижки',
  'auditDiscountRejectedDescription':
      'Адміністратор відхилив запит користувача на знижку.',
  'auditAccountDeletionRequestedTitle': 'Запит на видалення облікового запису',
  'auditAccountDeletionRequestedDescription':
      'Користувач подав запит на видалення облікового запису.',
  'auditEmailChangeRequestedTitle': 'Запит на зміну e-mail',
  'auditEmailChangeRequestedDescription':
      'Користувач подав запит на зміну e-mail адреси.',
  'auditEmailChangeCompletedTitle': 'Завершення зміни e-mail',
  'auditEmailChangeCompletedDescription':
      'Користувач завершив зміну e-mail адреси.',
  'auditPasswordResetRequestedTitle': 'Запит на відновлення пароля',
  'auditPasswordResetRequestedDescription':
      'Користувач попросив надіслати e-mail для відновлення пароля.',
  'auditActionDiscountRequested': 'Запит на знижку',
  'auditActionDiscountApproved': 'Схвалення знижки',
  'auditActionDiscountRejected': 'Відхилення знижки',
  'auditActionAccountDeletionRequested': 'Запит на видалення облікового запису',
  'auditActionEmailChangeRequested': 'Запит на зміну e-mail',
  'auditActionEmailChangeCompleted': 'Завершення зміни e-mail',
  'auditActionPasswordResetRequested': 'Запит на відновлення пароля',
};

const Map<String, List<String>> appTextListsUk = {
  'shortWeekdays': ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Нд'],
  'weekdays': [
    'Понеділок',
    'Вівторок',
    'Середа',
    'Четвер',
    'П’ятниця',
    'Субота',
    'Неділя',
  ],
};
