// Srpski tekstovi aplikacije.
const Map<String, String> appTextsSr = {
  'appName': 'Body Fit Club TT',
  'loading': 'Učitavam...',
  'ok': 'OK',
  'save': 'Sačuvaj',
  'delete': 'Obriši',
  'cancel': 'Otkaži',
  'back': 'Nazad',
  'today': 'Danas',
  'tomorrow': 'Sutra',
  'todayLower': 'danas',
  'tomorrowLower': 'sutra',
  'minutes': 'min.',
  'refresh': 'Osveži',
  'yesterday': 'Juče',
  'last7Days': 'Poslednjih 7 dana',
  'last30Days': 'Poslednjih 30 dana',
  'allTime': 'Ceo period',
  'close': 'Zatvori',
  'reason': 'Razlog',
  'unknownDate': 'Nepoznat datum',
  'notSet': 'Nije podešeno',
  'confirm': 'Potvrdi',
  'menu': 'Meni',
  'home': 'Početna',
  'schedule': 'Raspored',
  'reservations': 'Rezervacije',
  'management': 'Upravljanje',
  'profile': 'Profil',
  'settings': 'Podešavanja',
  'appearance': 'Izgled',
  'appearanceDescription': 'Izaberite svetli, tamni ili sistemski režim.',
  'themeSystem': 'Prema sistemu',
  'themeLight': 'Svetli režim',
  'themeDark': 'Tamni režim',
  'menuPosition': 'Položaj menija',
  'menuPositionDescription':
      'Izaberite na kojoj strani će se prikazivati glavni meni.',
  'rightHanded': 'Desnoruk',
  'leftHanded': 'Levoruk',
  'menuRightPositionDescription': 'Meni će biti gore desno.',
  'menuLeftPositionDescription': 'Meni će biti gore levo.',
  'language': 'Jezik',
  'languageDescription': 'Izaberite jezik aplikacije.',
  'languageSlovak': '🇸🇰 Slovački',
  'languageEnglish': '🇬🇧 Engleski',
  'languageGerman': '🇩🇪 Nemački',
  'languageFrench': '🇫🇷 Francuski',
  'languagePolish': '🇵🇱 Poljski',
  'languageHungarian': '🇭🇺 Mađarski',
  'languageUkrainian': '🇺🇦 Ukrajinski',
  'languageRussian': '🇷🇺 Ruski',
  'languageSerbian': '🇷🇸 Srpski',
  'languageCzech': '🇨🇿 Češki',
  'role': 'Uloga',
  'roleUser': 'Korisnik',
  'roleTrainer': 'Trener',
  'roleAdmin': 'Administrator',
  'roleUnknown': 'Nepoznata uloga',
  'privacyPolicy': 'Zaštita ličnih podataka',
  'emailContact': 'E-mail',
  'loginTitle': 'Prijava',
  'registerTitle': 'Registracija',
  'continueWithGoogle': 'Nastavi preko Google-a',
  'continueWithFacebook': 'Nastavi preko Facebook-a',
  'or': 'ili',
  'email': 'E-mail',
  'password': 'Lozinka',
  'login': 'Prijavi se',
  'register': 'Registruj se',
  'logout': 'Odjavi se',
  'noAccountRegister': 'Nemaš nalog? Registruj se',
  'hasAccountLogin': 'Već imaš nalog? Prijavi se',
  'authError': 'Greška pri prijavi',
  'acceptTerms': 'Slažem se sa uslovima korišćenja',
  'acceptPrivacy': 'Slažem se sa obradom ličnih podataka',
  'termsConsentRequired':
      'Za registraciju je potrebno prihvatiti uslove korišćenja.',
  'privacyConsentRequired':
      'Za registraciju je potrebno prihvatiti obradu ličnih podataka.',
  'openTerms': 'Otvori uslove korišćenja',
  'openPrivacy': 'Otvori zaštitu ličnih podataka',
  'termsVersion': '2026-05-16',
  'privacyVersion': '2026-05-16',
  'continueWithoutAccount': 'Nastavi bez naloga',
  'completeEmailOrLogout':
      'Ako ne želite da dopunite e-mail, možete nastaviti bez naloga i kasnije se prijaviti drugim nalogom.',
  'fillEmailPassword': 'Popunite e-mail i lozinku.',
  'invalidEmailFormat': 'Unesite važeći e-mail.',
  'passwordTooShort': 'Lozinka mora imati najmanje 6 znakova.',
  'wrongEmailOrPassword': 'Uneti e-mail ili lozinka nisu tačni.',
  'userAlreadyExists': 'Korisnik sa ovim e-mailom već postoji.',
  'weakPassword': 'Uneta lozinka je preslaba.',
  'tooManyRequests': 'Previše pokušaja. Pokušajte kasnije.',
  'networkError': 'Proverite internet vezu.',
  'signInCancelled': 'Prijava je otkazana.',
  'facebookLoginFailed': 'Prijava preko Facebook-a nije uspela.',
  'unknownAuthError': 'Došlo je do nepoznate greške pri prijavi.',
  'inactiveAccount': 'Vaš nalog je deaktiviran. Kontaktirajte administratora.',
  'verificationEmailSent':
      'Registracija je uspešno završena. Poslali smo vam e-mail za potvrdu. Ako ga ne vidite u prijemnom sandučetu, proverite i folder Spam.',
  'emailNotVerified': 'Prvo potvrdite registraciju klikom na link u e-mailu.',
  'verificationEmailSentAgain':
      'Ponovo smo vam poslali e-mail za potvrdu. Ako ga ne vidite u prijemnom sandučetu, proverite i folder Spam.',
  'forgotPassword': 'Zaboravili ste lozinku?',
  'resetPasswordTitle': 'Obnova lozinke',
  'sendResetEmail': 'Pošalji e-mail',
  'passwordResetEmailSent':
      'Ako nalog sa ovim e-mailom postoji, poslali smo e-mail za obnovu lozinke.',
  'emailRequired': 'Unesite e-mail.',
  'emailNotProvided': 'E-mail nije dostavljen',
  'emailSaved': 'E-mail je sačuvan.',
  'emailSaveError': 'E-mail nije moguće sačuvati.',
  'emailChangeVerificationSent':
      'Na novi e-mail smo poslali link za potvrdu. Promena će biti završena nakon potvrde.',
  'emailChangeRequestError': 'Promenu e-maila nije moguće pokrenuti.',
  'emailChangeNotAvailable':
      'Promena e-maila dostupna je samo za naloge kreirane e-mailom i lozinkom.',
  'completeProfileTitle': 'Dopuna profila',
  'editProfile': 'Uredi profil',
  'firstName': 'Ime',
  'lastName': 'Prezime',
  'publicName': 'Prikazano ime',
  'publicNameHint': 'Npr. Barbora, Katka, Aďo',
  'firstNameRequired': 'Unesite ime.',
  'lastNameRequired': 'Unesite prezime.',
  'publicNameRequired': 'Unesite prikazano ime.',
  'profileSaved': 'Profil je sačuvan.',
  'profileSaveError': 'Profil nije moguće sačuvati.',
  'loggedInUser': 'Prijavljeni korisnik',
  'completeEmailTitle': 'Dopuna e-maila',
  'completeEmailDescription':
      'Za korišćenje aplikacije potrebna nam je vaša e-mail adresa. Koristićemo je kao kontakt e-mail za vaš nalog.',
  'deleteAccountRequest': 'Zatraži brisanje naloga',
  'deleteAccountRequestTitle': 'Brisanje naloga',
  'deleteAccountRequestDescription':
      'Nakon slanja zahteva nalog će biti deaktiviran i prijava neće biti moguća. Podaci će zatim biti obrađeni od strane administratora prema pravilima zaštite ličnih podataka.',
  'deleteAccountReason': 'Razlog zahteva',
  'deleteAccountConfirm': 'Da li zaista želite da zatražite brisanje naloga?',
  'deleteAccountRequestSent': 'Zahtev za brisanje naloga je poslat.',
  'deleteAccountRequestError': 'Zahtev za brisanje naloga nije moguće poslati.',
  'deleteAccountBlockedActiveReservations':
      'Nalog nije moguće obrisati jer imate aktivne rezervacije.',
  'accountDeletionRequests': 'Zahtevi za brisanje naloga',
  'accountDeletionRequestsWithCount': 'Zahtevi za brisanje naloga',
  'accountDeletionRequestsLoadError':
      'Zahteve za brisanje naloga nije moguće učitati.',
  'noAccountDeletionRequests': 'Nema evidentiranih zahteva na čekanju.',
  'completeAccountDeletion': 'Anonimizuj nalog',
  'completeAccountDeletionTitle': 'Anonimizuj nalog',
  'completeAccountDeletionQuestion':
      'Da li zaista želite da anonimizujete ovaj nalog? Ova akcija će prepisati lične podatke korisnika.',
  'accountDeletionCompleted': 'Nalog je anonimizovan.',
  'accountDeletionCompleteError': 'Nalog nije moguće anonimizovati.',
  'requestedAt': 'Zatraženo',
  'accountDeletionRequestsWaiting': 'Zahtevi koji čekaju obradu.',
  'changeEmail': 'Promeni e-mail',
  'changeEmailTitle': 'Promena e-maila',
  'changeEmailDescription':
      'Unesite novi e-mail i trenutnu lozinku. Na novi e-mail ćemo poslati link za potvrdu. Promena će biti završena tek nakon potvrde linka u e-mailu.',
  'changeEmailProfileHint': 'Dostupno za naloge kreirane e-mailom i lozinkom.',
  'newEmail': 'Novi e-mail',
  'currentPassword': 'Trenutna lozinka',
  'sendVerificationEmail': 'Pošalji e-mail za potvrdu',
  'wrongCurrentPassword': 'Trenutna lozinka nije tačna.',
  'requiresRecentLogin': 'Za ovu akciju se prvo odjavite i ponovo prijavite.',
  'changeProfilePhoto': 'Promeni profilnu fotografiju',
  'chooseFromGallery': 'Izaberi iz galerije',
  'takePhoto': 'Fotografiši',
  'removePhoto': 'Ukloni fotografiju',
  'editPhoto': 'Uredi fotografiju',
  'cropProfilePhoto': 'Iseci profilnu fotografiju',
  'profilePhotoUpdated': 'Profilna fotografija je sačuvana.',
  'profilePhotoUpdateError': 'Profilnu fotografiju nije moguće sačuvati.',
  'profilePhotoRemoveError': 'Profilnu fotografiju nije moguće ukloniti.',
  'requestDiscount': 'Zatraži popust',
  'discountStatus': 'Status popusta',
  'discountStatusNone': 'Bez popusta',
  'discountStatusPending': 'Čeka odobrenje',
  'discountStatusApproved': 'Odobren popust',
  'discountStatusRejected': 'Zahtev odbijen',
  'discountStatusExpired': 'Važenje popusta je isteklo',
  'discountType': 'Tip popusta',
  'discountTypeNormal': 'Običan korisnik',
  'discountTypeStudent': 'Student',
  'discountTypeSenior': 'Senior',
  'discountTypeZtp': 'Osoba sa invaliditetom',
  'discountTypeIndividual': 'Individualni popust',
  'discountRequestDescription':
      'Izaberite tip popusta koji tražite. Nakon slanja zahtev će proveriti administrator.',
  'discountRequestNote': 'Napomena uz zahtev',
  'discountRequestSent': 'Zahtev za popust je poslat.',
  'discountRequestError': 'Zahtev za popust nije moguće poslati.',
  'discountRequestAlreadyPending': 'Već imate zahtev za popust u obradi.',
  'discountRequestPending': 'Zahtev čeka odobrenje',
  'sendRequest': 'Pošalji zahtev',
  'discountDocument': 'Dokaz za popust',
  'discountDocumentDescription':
      'Otpremite fotografiju dokumenta na osnovu kog administrator proverava pravo na popust.',
  'chooseDiscountDocument': 'Izaberi dokument',
  'discountDocumentRequired':
      'Za slanje zahteva potrebno je priložiti dokument.',
  'discountDocumentSelected': 'Dokument je izabran',
  'takeDiscountDocumentPhoto': 'Fotografiši dokument',
  'chooseDiscountDocumentFromGallery': 'Izaberi iz galerije',
  'discountRequests': 'Zahtevi za popust',
  'discountRequestsDescription':
      'Odobravanje ili odbijanje zahteva korisnika za popust.',
  'discountRequestsLoadError': 'Zahteve za popust nije moguće učitati.',
  'noDiscountRequests': 'Nema evidentiranih zahteva za popust na čekanju.',
  'approveDiscount': 'Odobri popust',
  'rejectDiscount': 'Odbij zahtev',
  'discountApproved': 'Popust je odobren.',
  'discountRejected': 'Zahtev za popust je odbijen.',
  'discountDecisionError': 'Odluku o zahtevu nije moguće sačuvati.',
  'discountValidUntilRequired': 'Izaberite datum važenja popusta.',
  'discountAdminNote': 'Napomena administratora',
  'selectDiscountValidUntil': 'Izaberite važenje popusta',
  'discountDocumentPreview': 'Pregled dokumenta',
  'todayReservations': 'Današnje rezervacije',
  'noTodayReservations': 'Danas nemate rezervisan nijedan trening.',
  'nearestTraining': 'Najbliži trening',
  'nearestTrainings': 'Najbliži treninzi',
  'noNearestTraining': 'Nije planiran nijedan najbliži trening.',
  'todaysTrainings': 'Današnji treninzi',
  'noTodaysTrainings': 'Danas nisu planirani treninzi.',
  'myMemberships': 'Moje članarine',
  'activeMembershipsCount': 'Aktivne članarine',
  'availableEntriesSummary': 'Dostupni ulasci',
  'reservedEntriesSummary': 'Rezervisani ulasci',
  'dailyMembershipsSummary': 'Dnevne članarine',
  'tapToShowQrCode': 'Dodirnite za prikaz QR koda.',
  'nearestReservations': 'Najbliže rezervacije',
  'noNearestReservations': 'Nemate najbliže rezervacije.',
  'qrShort': 'QR',
  'membershipStatus': 'Status članarine',
  'remainingEntries': 'Preostali ulasci',
  'upcomingTraining': 'Najbliži današnji trening',
  'schedulePlaceholder': 'Ovde će biti raspored treninga.',
  'reservationsPlaceholder': 'Ovde će biti rezervacije.',
  'newsPlaceholder': 'Ovde će se prikazivati novosti i poruke od trenera.',
  'aboutApp': 'O aplikaciji',
  'aboutUs': 'O nama',
  'aboutAppDescription':
      'Aplikacija Body Fit Club TT služi za upravljanje treninzima, rezervacijama, članarinama i komunikacijom između fitnes centra i korisnika.',
  'aboutUsDescription':
      'Body Fit Club je fitnes centar u Trnavi usmeren na grupne i individualne treninge, kretanje, zdrav način života i lični pristup klijentima.',
  'bodyFitClubWebsite': 'https://bodyfitclub.sk/',
  'openWebsite': 'Otvori veb-stranicu',
  'businessTerms': 'Uslovi poslovanja',
  'legalDocumentsInfo':
      'Uslovi poslovanja i informacije o zaštiti ličnih podataka biće dostupni na veb-stranici Body Fit Club.',
  'contacts': 'Kontakti',
  'billingDetails': 'Podaci za fakturisanje',
  'address': 'Adresa',
  'phone': 'Telefon',
  'website': 'Veb-stranica',
  'socialNetworks': 'Društvene mreže',
  'openMap': 'Otvori mapu',
  'openFacebook': 'Facebook',
  'openInstagram': 'Instagram',
  'multisport': 'MultiSport',
  'multisportInfo':
      'Prihvatamo MultiSport karticu prema aktuelnim uslovima rada.',
  'bodyFitClubCompanyName': 'BODYFIT CLUB s.r.o.',
  'bodyFitClubOperationAddress': 'V Jame 24, Trnava',
  'bodyFitClubBillingAddress': 'J. G. Tajovského 18, 917 08 Trnava',
  'bodyFitClubPhonePrimary': '+421 902 860 008',
  'bodyFitClubPhoneSecondary': '+421 903 946 895',
  'bodyFitClubEmail': 'bodyfitclubtt@gmail.com',
  'bodyFitClubIco': '48074128',
  'ico': 'IČO: ',
  'companySeat': 'Sedište',
  'operation': 'Poslovnica',
  'bodyFitClubFacebookUrl': 'https://www.facebook.com/bodyfitclub.sk',
  'bodyFitClubInstagramUrl': 'https://www.instagram.com/bodyfitclub.tt/',
  'bodyFitClubMapUrl':
      'https://www.google.com/maps/search/?api=1&query=V%20Jame%206641%2F24%2C%20917%2001%20Trnava',
  'bodyFitClubMultiSportUrl':
      'https://multi-sport.sk/aktivity/partner/bodyfit-club/',
  'multisportInfo2':
      'Body Fit Club je partner programa MultiSport. Prihvatanje MultiSport kartice reguliše se aktuelnim uslovima poslovanja.',
  'bodyFitClubWebsiteLabel': 'www.bodyfitclub.sk',
  'dic': 'DIČ: ',
  'bodyFitClubDic': '2120035445',
  'notVatPayer': 'Društvo nije obveznik PDV-a',
  'legalDocuments': 'Pravni dokumenti',
  'priceList': 'Cenovnik',
  'priceListAudience': 'Za',
  'priceListAudienceNormal': 'obične korisnike',
  'priceListAudienceDiscount': 'korisnike sa popustom',
  'priceListAudienceAll': 'sve',
  'price': 'Cena',
  'singleEntries': 'Jednokratni ulasci',
  'priceListMemberships': 'Članarine',
  'chooseEntry': 'Izaberite ulaz',
  'noAvailablePlans': 'Trenutno nema dostupnih opcija kupovine.',
  'news': 'Novosti',
  'noPublicMessages': 'Još nema poruka.',
  'writeMessage': 'Napiši poruku',
  'writeMessageShort': 'Napiši',
  'editMessage': 'Uredi poruku',
  'deleteMessage': 'Obriši poruku',
  'deleteMessageQuestion': 'Da li zaista želite da obrišete ovu poruku?',
  'messageText': 'Tekst poruke',
  'messageHint': 'Napiši poruku...',
  'sendMessage': 'Pošalji',
  'updateMessage': 'Sačuvaj izmene',
  'messageSaved': 'Poruka je sačuvana.',
  'messageDeleted': 'Poruka je obrisana.',
  'messageSaveError': 'Poruku nije moguće sačuvati.',
  'messageDeleteError': 'Poruku nije moguće obrisati.',
  'editedBy': 'Uređeno',
  'editedByAdmin': 'Uredio administrator',
  'editedByTrainer': 'Uredio trener',
  'userFallback': 'Korisnik',
  'noTrainings': 'Trenutno nema dostupnih treninga.',
  'noTrainingsForSelectedDay': 'Za ovaj dan nisu planirani treninzi.',
  'trainer': 'Trener',
  'freeSpots': 'Slobodna mesta',
  'reserve': 'Rezerviši',
  'reserved': 'Rezervisano',
  'fullCapacity': 'Popunjeno',
  'trainingsLoadError': 'Raspored treninga nije moguće učitati.',
  'unknownTraining': 'Nepoznat trening',
  'unknownTrainer': 'Nepoznat trener',
  'unknownUser': 'Nepoznat korisnik',
  'trainingSessionFinished': 'Završeno',
  'trainingSessionTooFarInFuture':
      'Termin je predaleko u budućnosti. Ručno možete dodati trening samo u periodu prikazanom u rasporedu.',
  'managementDescription':
      'Ovde možete upravljati terminima treninga, prisustvom, članarinama i korisnicima.',
  'scheduleManagement': 'Upravljanje rasporedom',
  'scheduleManagementDescription':
      'Upravljanje tipovima treninga, šablonima rasporeda i konkretnim terminima treninga.',
  'attendanceManagement': 'Upravljanje prisustvom',
  'usersManagement': 'Upravljanje korisnicima',
  'usersManagementComingSoon': 'Upravljanje korisnicima biće dodato kasnije.',
  'scheduleTemplatesManagement': 'Upravljanje šablonima rasporeda',
  'reactivateUser': 'Aktiviraj korisnika',
  'reactivateUserQuestion':
      'Da li zaista želite ponovo da aktivirate ovog korisnika?',
  'userReactivated': 'Korisnik je ponovo aktiviran.',
  'trainingTypesManagement': 'Upravljanje tipovima treninga',
  'addTrainingType': 'Dodaj tip treninga',
  'editTrainingType': 'Uredi tip treninga',
  'deleteTrainingType': 'Obriši tip treninga',
  'trainingType': 'Tip treninga',
  'selectTrainingType': 'Izaberite tip treninga',
  'trainingName': 'Naziv treninga',
  'description': 'Opis',
  'defaultDuration': 'Podrazumevano trajanje',
  'defaultCapacity': 'Podrazumevani kapacitet',
  'noTrainingTypes': 'Trenutno nisu kreirani tipovi treninga.',
  'trainingTypesLoadError': 'Tipove treninga nije moguće učitati.',
  'trainingTypeCreated': 'Tip treninga je kreiran.',
  'trainingTypeUpdated': 'Tip treninga je izmenjen.',
  'trainingTypeDeleted': 'Tip treninga je obrisan.',
  'trainingTypeDeleteQuestion':
      'Da li zaista želite da obrišete ovaj tip treninga? Više se neće nuditi pri novim terminima.',
  'trainingTypeAlreadyExists': 'Tip treninga sa ovim nazivom već postoji.',
  'trainingTypeUsedByTemplate':
      'Tip treninga nije moguće obrisati jer se koristi u aktivnom šablonu rasporeda.',
  'trainingTypeUsedBySession':
      'Tip treninga nije moguće obrisati jer se koristi u budućem terminu treninga.',
  'addTrainingSession': 'Dodaj termin treninga',
  'editTrainingSession': 'Uredi detalje treninga',
  'trainingSessionCreated': 'Termin treninga je kreiran.',
  'trainingSessionUpdated': 'Termin treninga je izmenjen.',
  'updateTrainingSessionError': 'Termin treninga nije moguće izmeniti.',
  'trainingSessionInPast': 'Termin treninga ne može biti u prošlosti.',
  'trainingSessionOverlap': 'U ovom vremenu je već planiran drugi trening.',
  'capacityLowerThanReservations':
      'Kapacitet ne može biti manji od broja postojećih rezervacija.',
  'cancelTrainingSession': 'Otkaži termin',
  'cancelTrainingSessionTitle': 'Otkaži termin treninga',
  'cancelTrainingSessionQuestion':
      'Da li zaista želite da otkažete ovaj termin treninga? Aktivne rezervacije će biti otkazane, a rezervisani ulasci oslobođeni. Ako je ulaz već iskorišćen, biće vraćen korisniku.',
  'cancelTrainingSessionConfirm': 'Otkaži termin',
  'trainingSessionCancelled': 'Termin treninga je otkazan.',
  'cancelTrainingSessionError': 'Termin treninga nije moguće otkazati.',
  'trainerCanCancelOnlyOwnSession': 'Trener može otkazati samo svoj termin.',
  'trainerCannotCancelStartedSession':
      'Trener ne može otkazati termin koji je već počeo ili je završen.',
  'date': 'Datum',
  'startTime': 'Početak',
  'duration': 'Trajanje',
  'capacity': 'Kapacitet',
  'selectDate': 'Izaberite datum',
  'selectTrainer': 'Izaberite trenera',
  'trainersLoadError': 'Trenere nije moguće učitati.',
  'fillAllFields': 'Popunite sva obavezna polja.',
  'invalidCapacity': 'Kapacitet mora biti veći od 0.',
  'invalidDuration': 'Trajanje mora biti veće od 0.',
  'saveError': 'Čuvanje nije uspelo.',
  'addScheduleTemplate': 'Dodaj šablon rasporeda',
  'editScheduleTemplate': 'Uredi šablon rasporeda',
  'deleteScheduleTemplate': 'Obriši šablon rasporeda',
  'noScheduleTemplates': 'Trenutno nema kreiranih šablona rasporeda.',
  'weekday': 'Dan u nedelji',
  'selectWeekday': 'Izaberite dan u nedelji',
  'scheduleTemplateCreated': 'Šablon rasporeda je kreiran.',
  'scheduleTemplateUpdated': 'Šablon rasporeda je izmenjen.',
  'scheduleTemplateDeleted': 'Šablon rasporeda je obrisan.',
  'scheduleTemplateDeleteQuestion':
      'Da li zaista želite da obrišete ovaj šablon rasporeda? Više se neće koristiti pri generisanju novih termina.',
  'scheduleTemplateAlreadyExists': 'Takav šablon rasporeda već postoji.',
  'scheduleTemplateLoadError': 'Šablone rasporeda nije moguće učitati.',
  'scheduleTemplateOverlap':
      'U ovom vremenu već postoji drugi šablon rasporeda.',
  'capacityLabel': 'Kapacitet',
  'reservationCreated': 'Rezervacija je kreirana.',
  'reservationAlreadyExists': 'Već imate rezervaciju za ovaj trening.',
  'reservationTrainingFull': 'Ovaj trening je već popunjen.',
  'reservationTrainingNotAvailable':
      'Ovaj trening više nije dostupan za rezervaciju.',
  'reservationTrainingAlreadyStarted':
      'Za ovaj trening više nije moguće napraviti rezervaciju.',
  'reservationError': 'Rezervaciju nije moguće kreirati.',
  'myReservations': 'Moje rezervacije',
  'noReservations': 'Trenutno nemate rezervacije.',
  'cancelReservation': 'Otkaži rezervaciju',
  'cancelReservationTitle': 'Otkaži rezervaciju',
  'cancelReservationQuestion':
      'Da li zaista želite da otkažete ovu rezervaciju?',
  'reservationCancelled': 'Rezervacija je otkazana.',
  'reservationCancelError': 'Rezervaciju nije moguće otkazati.',
  'reservationsLoadError': 'Rezervacije nije moguće učitati.',
  'cancelReservations': 'Otkaži rezervacije',
  'cancelReservationsBeforeDeactivation':
      'Pre deaktivacije ili otkazivanja članarine prvo otkažite rezervisane termine.',
  'cancelReservationForMembership': 'Otkaži ovu rezervaciju',
  'cancelReservationForMembershipQuestion':
      'Da li zaista želite da otkažete ovu rezervaciju vezanu za članarinu? Rezervisani ulaz će biti oslobođen.',
  'reservationForMembershipCancelled':
      'Rezervacija je otkazana i rezervisani ulaz je oslobođen.',
  'noReservationsForTrainingHistory': 'Na ovom treningu nema rezervacija.',
  'reservationQrCode': 'QR kod rezervacije',
  'memberships': 'Članarine',
  'assignMembership': 'Dodeli članarinu',
  'selectUser': 'Izaberite korisnika',
  'selectMembershipPlan': 'Izaberite tip članarine',
  'membershipPlansLoadError': 'Tipove članarina nije moguće učitati.',
  'membershipAssigned': 'Članarina je dodeljena.',
  'membershipAssignError': 'Članarinu nije moguće dodeliti.',
  'membershipPlan': 'Tip članarine',
  'client': 'Korisnik',
  'buyMembership': 'Kupi članarinu',
  'buySingleEntry': 'Kupi jednokratni ulaz',
  'chooseMembership': 'Izaberite članarinu',
  'payment': 'Plaćanje',
  'pay': 'Plati',
  'paymentSuccessful': 'Plaćanje je uspešno.',
  'paymentFailed': 'Plaćanje nije uspelo.',
  'activeMembership': 'Aktivna članarina',
  'noActiveMembership': 'Nemate aktivnu članarinu.',
  'validUntil': 'Važi do',
  'membershipLoadError': 'Članarinu nije moguće učitati.',
  'noAvailableEntries': 'Nemate dostupan ulaz za rezervaciju.',
  'noUpcomingTraining': 'Danas nemate rezervisan nijedan trening.',
  'membershipsManagement': 'Upravljanje članarinama',
  'membershipDetail': 'Detalj članarine',
  'noMemberships': 'Trenutno nema dostupnih članarina.',
  'status': 'Status',
  'validFrom': 'Važi od',
  'entriesTotal': 'Ukupan broj ulazaka',
  'entriesRemaining': 'Preostali ulasci',
  'entriesReserved': 'Rezervisani ulasci',
  'entriesAvailable': 'Dostupni ulasci',
  'adminMembershipEdit': 'Administratorska izmena',
  'membershipStatusActive': 'Aktivna',
  'membershipStatusInactive': 'Neaktivna',
  'membershipStatusCancelled': 'Otkazana',
  'membershipStatusExpired': 'Istekla',
  'membershipStatusUsedUp': 'Iskorišćena',
  'membershipUpdated': 'Članarina je izmenjena.',
  'membershipUpdateError': 'Članarinu nije moguće izmeniti.',
  'invalidRemainingEntries': 'Unesite važeći broj preostalih ulazaka.',
  'allocatedReservations': 'Rezervisani termini',
  'cancelAllocatedReservations': 'Otkaži rezervisane termine',
  'cancelAllocatedReservationsQuestion':
      'Da li zaista želite da otkažete aktivne rezervacije vezane za ovu članarinu? Rezervisani ulasci će biti oslobođeni.',
  'cancelAllReservations': 'Otkaži sve rezervacije',
  'cancelAllocatedReservationsError':
      'Rezervisane termine nije moguće otkazati.',
  'usedEntries': 'Iskorišćeni ulasci',
  'noAllocatedReservations':
      'Za ovu članarinu trenutno nema rezervisanih termina.',
  'noUsedEntries': 'Iz ove članarine još nije iskorišćen nijedan ulaz.',
  'membershipUsageLoadError': 'Istoriju članarine nije moguće učitati.',
  'searchMemberships': 'Pretraži po korisniku ili članarini',
  'allMembershipStatuses': 'Svi statusi',
  'membershipStatusNotYetValid': 'Još nije važeća',
  'membershipStatusUsable': 'Aktivna',
  'invalidRemainingEntriesHigherThanTotal':
      'Preostali ulasci ne mogu biti veći od ukupnog broja ulazaka.',
  'invalidRemainingEntriesLowerThanReserved':
      'Preostali ulasci ne mogu biti manji od broja rezervisanih ulazaka.',
  'membershipPrefix': 'Članarina',
  'statusPrefix': 'Status',
  'attendance': 'Prisustvo',
  'attendanceLoadError': 'Prisustvo nije moguće učitati.',
  'noActiveReservationsForAttendance':
      'Trenutno nema aktivnih rezervacija za označavanje prisustva.',
  'attended': 'Došao',
  'noShow': 'Nije došao',
  'markAttendedTitle': 'Označi prisustvo',
  'markNoShowTitle': 'Označi izostanak',
  'markAttendedQuestion':
      'Da li zaista želite da označite korisnika kao prisutnog?',
  'markNoShowQuestion':
      'Da li zaista želite da označite korisnika kao odsutnog?',
  'attendanceMarked': 'Prisustvo je sačuvano.',
  'attendanceMarkError': 'Prisustvo nije moguće sačuvati.',
  'attendedStatus': 'Došao',
  'noShowStatus': 'Nije došao',
  'attendedCountLabel': 'Došli',
  'noShowCountLabel': 'Nisu došli',
  'attendanceActionDone': 'Promena prisustva je sačuvana.',
  'attendanceActionError': 'Promenu prisustva nije moguće sačuvati.',
  'showQrCode': 'QR kod',
  'showQrToTrainer': 'Pokažite ovaj QR kod treneru pri dolasku na trening.',
  'scanQrCode': 'Skeniraj QR kod',
  'scanQrCodes': 'Skeniraj QR kodove',
  'scanQrCodeHint': 'Usmerite kameru na QR kod rezervacije korisnika.',
  'invalidQrCode': 'Nevažeći QR kod rezervacije.',
  'qrCodeScanned': 'QR kod je skeniran.',
  'qrScanSuccessful':
      'QR kod je skeniran. Možete skenirati sledećeg korisnika.',
  'trainerQrScanTooEarly':
      'QR kod je moguće skenirati najranije 30 minuta pre početka treninga.',
  'trainingHistory': 'Istorija treninga',
  'trainingHistoryDetail': 'Detalj treninga',
  'trainingHistoryLoadError': 'Istoriju treninga nije moguće učitati.',
  'trainingHistoryReservationsLoadError':
      'Prisustvo na treningu nije moguće učitati.',
  'noTrainingHistoryInSelectedPeriod': 'U izabranom periodu nema treninga.',
  'fromDatePrefix': 'Od',
  'toDatePrefix': 'Do',
  'planned': 'Planirano',
  'cancelled': 'Otkazano',
  'finished': 'Završeno',
  'reservedStatus': 'Rezervisano',
  'reservedCountLabel': 'Rezervisano',
  'cancelledCountLabel': 'Otkazano',
  'markedAtPrefix': 'Označeno',
  'markAsAttended': 'Označi kao došao',
  'markAsNoShow': 'Označi kao nije došao',
  'revertAttendance': 'Poništi označeno prisustvo',
  'revertNoShow': 'Poništi označen izostanak',
  'markAsAttendedQuestion':
      'Da li zaista želite da označite korisnika kao prisutnog? Ulaz iz članarine će biti iskorišćen.',
  'markAsNoShowQuestion':
      'Da li zaista želite da označite korisnika kao odsutnog? Ulaz iz članarine će biti iskorišćen.',
  'revertAttendanceQuestion':
      'Da li zaista želite da poništite označeno prisustvo? Iskorišćeni ulaz će biti vraćen na članarinu.',
  'revertNoShowQuestion':
      'Da li zaista želite da poništite označen izostanak? Iskorišćeni ulaz će biti vraćen na članarinu.',
  'addTrainingAttendance': 'Dodaj učesnika',
  'selectAttendanceUser': 'Izaberite korisnika',
  'selectAttendanceMembership': 'Izaberite članarinu',
  'noUsersForAttendance': 'Nisu pronađeni aktivni korisnici.',
  'noUsableMembershipsForAttendance':
      'Korisnik nema upotrebljivu članarinu za ovaj trening.',
  'addTrainingAttendanceQuestion':
      'Da li zaista želite naknadno da dodate prisustvo korisnika na ovom treningu? Ulaz iz članarine će biti iskorišćen.',
  'trainingAttendanceAdded': 'Učesnik je dodat na trening.',
  'trainingAttendanceAddError': 'Učesnika nije moguće dodati.',
  'userAlreadyHasReservationForTraining':
      'Korisnik već ima zapis za ovaj trening.',
  'usersLoadError': 'Korisnike nije moguće učitati.',
  'allRoles': 'Sve uloge',
  'searchUsers': 'Pretraži korisnika',
  'noUsersFound': 'Nisu pronađeni korisnici.',
  'editUser': 'Uredi korisnika',
  'userUpdated': 'Korisnik je izmenjen.',
  'userUpdateError': 'Korisnika nije moguće izmeniti.',
  'cannotChangeOwnRole': 'Ne možete promeniti sopstvenu ulogu.',
  'changeRoleWarning':
      'Promenom uloge korisnika mogu se promeniti njegova ovlašćenja u aplikaciji.',
  'deactivateUser': 'Deaktiviraj korisnika',
  'deactivationReason': 'Razlog deaktivacije',
  'userDeactivated': 'Korisnik je deaktiviran.',
  'deactivateUserQuestion':
      'Da li zaista želite da deaktivirate ovog korisnika? Više neće moći da se koristi u upravljanju aplikacijom.',
  'cannotDeactivateYourself': 'Ne možete deaktivirati sopstveni nalog.',
  'userUsedByTemplate':
      'Korisnika nije moguće deaktivirati ili promeniti u običnog korisnika jer je dodeljen aktivnom šablonu rasporeda.',
  'userUsedByFutureSession':
      'Korisnika nije moguće deaktivirati ili promeniti u običnog korisnika jer je dodeljen budućem treningu.',
  'userHasActiveReservations':
      'Korisnika nije moguće deaktivirati jer ima aktivne rezervacije.',
  'userHasActiveMemberships':
      'Korisnika nije moguće deaktivirati jer ima aktivne članarine.',
  'inactiveUser': 'Neaktivan korisnik',
  'userCannotBeDeactivated': 'Korisnika nije moguće deaktivirati',
  'userCannotBeDeactivatedDescription':
      'Pre deaktivacije potrebno je prvo rešiti njegove aktivne rezervacije ili članarine.',
  'userHasBlockingItems': 'Korisnik ima:',
  'activeReservationsCount': 'Aktivne rezervacije',
  'showMemberships': 'Prikaži članarine',
  'auditLogs': 'Istorija izmena',
  'auditLogsDescription': 'Pregled važnih izmena u aplikaciji.',
  'auditLogsLoadError': 'Istoriju izmena nije moguće učitati.',
  'noAuditLogs': 'Nisu pronađene izmene.',
  'searchAuditLogs': 'Pretraži po korisniku, e-mailu ili opisu',
  'auditCategory': 'Kategorija',
  'auditAction': 'Akcija',
  'auditActor': 'Izvršio',
  'auditActorRole': 'Uloga izvršioca',
  'auditPeriod': 'Period',
  'auditAllCategories': 'Sve kategorije',
  'auditCategoryMemberships': 'Članarine',
  'auditCategoryReservations': 'Rezervacije',
  'auditCategoryAttendance': 'Prisustvo',
  'auditCategoryUsers': 'Korisnici',
  'auditCategorySchedule': 'Raspored',
  'auditCategoryMessages': 'Poruke',
  'auditCategoryPayments': 'Plaćanja',
  'auditCategoryProfile': 'Profil',
  'auditAllActions': 'Sve akcije',
  'auditActionCreated': 'Kreiranje',
  'auditActionUpdated': 'Izmena',
  'auditActionCancelled': 'Otkazivanje',
  'auditActionDeactivated': 'Deaktivacija',
  'auditActionActivated': 'Aktivacija',
  'auditActionAssigned': 'Dodela',
  'auditActionPurchased': 'Kupovina',
  'auditActionPaymentSucceeded': 'Plaćanje uspešno',
  'auditActionPaymentFailed': 'Plaćanje neuspešno',
  'auditActionAttendanceMarked': 'Prisustvo',
  'auditActionQrChecked': 'QR provera',
  'auditAllActorRoles': 'Sve uloge',
  'auditReservationCreatedTitle': 'Kreiranje rezervacije',
  'auditReservationCreatedDescription':
      'Korisnik je kreirao rezervaciju za trening.',
  'auditReservationCancelledTitle': 'Otkazivanje rezervacije',
  'auditReservationCancelledDescription': 'Rezervacija korisnika je otkazana.',
  'auditAttendanceAttendedTitle': 'Označeno prisustvo',
  'auditAttendanceAttendedDescription':
      'Korisnik je označen kao prisutan na treningu.',
  'auditAttendanceNoShowTitle': 'Označen izostanak',
  'auditAttendanceNoShowDescription':
      'Korisnik je označen kao odsutan sa treninga.',
  'auditTrainingTypeCreatedTitle': 'Kreiranje tipa treninga',
  'auditTrainingTypeUpdatedTitle': 'Izmena tipa treninga',
  'auditTrainingTypeDeactivatedTitle': 'Deaktivacija tipa treninga',
  'auditTrainingSessionCreatedTitle': 'Kreiranje termina',
  'auditTrainingSessionUpdatedTitle': 'Izmena termina',
  'auditTrainingSessionTimeChangedTitle': 'Promena vremena termina',
  'auditTrainingSessionCancelledTitle': 'Otkazivanje termina',
  'auditScheduleTemplateCreatedTitle': 'Kreiranje šablona rasporeda',
  'auditScheduleTemplateUpdatedTitle': 'Izmena šablona rasporeda',
  'auditScheduleTemplateDeactivatedTitle': 'Deaktivacija šablona rasporeda',
  'auditUserUpdatedTitle': 'Izmena korisnika',
  'auditUserUpdatedDescription': 'Administrator je izmenio podatke korisnika.',
  'auditUserRoleChangedTitle': 'Promena uloge korisnika',
  'auditUserRoleChangedDescription':
      'Administrator je promenio ulogu korisnika.',
  'auditUserDeactivatedTitle': 'Deaktivacija korisnika',
  'auditUserDeactivatedDescription': 'Administrator je deaktivirao korisnika.',
  'auditUserDeactivationBlockedTitle': 'Neuspešna deaktivacija korisnika',
  'auditUserDeactivationBlockedDescription':
      'Deaktivacija korisnika je blokirana proverom aktivnih veza.',
  'auditPublicMessageCreatedTitle': 'Kreiranje novosti',
  'auditPublicMessageCreatedDescription': 'Javna novost je kreirana.',
  'auditPublicMessageUpdatedTitle': 'Izmena novosti',
  'auditPublicMessageUpdatedDescription': 'Javna novost je izmenjena.',
  'auditPublicMessageDeletedTitle': 'Brisanje novosti',
  'auditPublicMessageDeletedDescription': 'Javna novost je obrisana.',
  'auditProfileCompletedTitle': 'Dopuna profila',
  'auditProfileCompletedDescription':
      'Korisnik je dopunio osnovne podatke profila.',
  'auditProfileUpdatedTitle': 'Izmena profila',
  'auditProfileUpdatedDescription': 'Korisnik je izmenio podatke profila.',
  'auditProfilePhotoUpdatedTitle': 'Izmena profilne fotografije',
  'auditProfilePhotoUpdatedDescription':
      'Korisnik je izmenio profilnu fotografiju.',
  'auditProfilePhotoRemovedTitle': 'Uklanjanje profilne fotografije',
  'auditProfilePhotoRemovedDescription':
      'Korisnik je uklonio ručno podešenu profilnu fotografiju.',
  'auditPaymentStartedTitle': 'Pokretanje plaćanja',
  'auditPaymentStartedDescription': 'Korisnik je pokrenuo plaćanje članarine.',
  'auditPaymentSucceededTitle': 'Uspešno plaćanje',
  'auditPaymentSucceededDescription': 'Plaćanje članarine je uspešno završeno.',
  'auditPaymentFailedTitle': 'Neuspešno plaćanje',
  'auditPaymentFailedDescription':
      'Plaćanje članarine nije uspelo ili je otkazano.',
  'auditMembershipUpdatedTitle': 'Izmena članarine',
  'auditMembershipUpdatedDescription':
      'Administrator je izmenio članarinu korisnika.',
  'auditMembershipStatusChangedTitle': 'Promena statusa članarine',
  'auditMembershipStatusChangedDescription':
      'Administrator je promenio status članarine korisnika.',
  'auditMembershipEntriesChangedTitle': 'Promena broja ulazaka članarine',
  'auditMembershipEntriesChangedDescription':
      'Administrator je promenio broj preostalih ulazaka članarine.',
  'auditMembershipReservationCancelledTitle':
      'Otkazivanje rezervisanog termina',
  'auditMembershipReservationCancelledDescription':
      'Administrator je otkazao rezervaciju vezanu za članarinu.',
  'auditMembershipAllReservationsCancelledTitle':
      'Otkazivanje svih rezervisanih termina',
  'auditMembershipAllReservationsCancelledDescription':
      'Administrator je otkazao sve rezervacije vezane za članarinu.',
  'auditMembershipAssignedTitle': 'Dodela članarine',
  'auditMembershipAssignedDescription':
      'Korisniku je ručno dodeljena članarina.',
  'auditMembershipPurchasedTitle': 'Kupovina članarine',
  'auditMembershipPurchasedDescription': 'Korisnik je kupio članarinu.',
  'auditActionMembershipAssigned': 'Dodela članarine',
  'auditActionMembershipPurchased': 'Kupovina članarine',
  'auditActionMembershipUpdated': 'Izmena članarine',
  'auditActionMembershipStatusChanged': 'Promena statusa članarine',
  'auditActionMembershipEntriesChanged': 'Promena ulazaka članarine',
  'auditActionMembershipReservationCancelled': 'Otkazivanje jedne rezervacije',
  'auditActionMembershipAllReservationsCancelled':
      'Otkazivanje svih rezervacija',
  'auditActionReservationCreated': 'Kreiranje rezervacije',
  'auditActionReservationCancelled': 'Otkazivanje rezervacije',
  'auditActionAttendanceAttended': 'Označeno prisustvo',
  'auditActionAttendanceNoShow': 'Označen izostanak',
  'auditActionTrainingTypeCreated': 'Kreiranje tipa treninga',
  'auditActionTrainingTypeUpdated': 'Izmena tipa treninga',
  'auditActionTrainingTypeDeactivated': 'Deaktivacija tipa treninga',
  'auditActionTrainingSessionCreated': 'Kreiranje termina',
  'auditActionTrainingSessionUpdated': 'Izmena termina',
  'auditActionTrainingSessionTimeChanged': 'Promena vremena termina',
  'auditActionTrainingSessionCancelled': 'Otkazivanje termina',
  'auditActionScheduleTemplateCreated': 'Kreiranje šablona',
  'auditActionScheduleTemplateUpdated': 'Izmena šablona',
  'auditActionScheduleTemplateDeactivated': 'Deaktivacija šablona',
  'auditActionUserUpdated': 'Izmena korisnika',
  'auditActionUserRoleChanged': 'Promena uloge',
  'auditActionUserDeactivationBlocked': 'Blokirana deaktivacija',
  'auditActionUserDeactivated': 'Deaktivacija korisnika',
  'auditActionPublicMessageCreated': 'Kreiranje novosti',
  'auditActionPublicMessageUpdated': 'Izmena novosti',
  'auditActionPublicMessageDeleted': 'Brisanje novosti',
  'auditActionProfileCompleted': 'Dopuna profila',
  'auditActionProfileUpdated': 'Izmena profila',
  'auditActionProfilePhotoUpdated': 'Izmena profilne fotografije',
  'auditActionProfilePhotoRemoved': 'Uklanjanje profilne fotografije',
  'auditActionPaymentStarted': 'Pokretanje plaćanja',
  'auditUserEmailCompletedTitle': 'Dopuna e-maila',
  'auditUserEmailCompletedDescription':
      'Korisnik je dopunio nedostajući e-mail za nalog.',
  'currentUserShort': 'vi',
  'auditUserEmailUpdatedTitle': 'Izmena e-maila korisnika',
  'auditUserEmailUpdatedDescription':
      'Administrator je izmenio kontakt e-mail korisnika.',
  'auditUserReactivatedTitle': 'Aktivacija korisnika',
  'auditUserReactivatedDescription':
      'Administrator je ponovo aktivirao korisnika.',
  'auditActionUserEmailCompleted': 'Dopuna e-maila',
  'auditActionUserEmailUpdated': 'Izmena e-maila korisnika',
  'auditActionUserReactivated': 'Aktivacija korisnika',
  'auditCategoryDiscounts': 'Popusti',
  'auditDiscountRequestedTitle': 'Zahtev za popust',
  'auditDiscountRequestedDescription':
      'Korisnik je poslao zahtev za odobrenje popusta.',
  'auditDiscountApprovedTitle': 'Odobrenje popusta',
  'auditDiscountApprovedDescription':
      'Administrator je odobrio popust korisniku.',
  'auditDiscountRejectedTitle': 'Odbijanje popusta',
  'auditDiscountRejectedDescription':
      'Administrator je odbio zahtev korisnika za popust.',
  'auditAccountDeletionRequestedTitle': 'Zahtev za brisanje naloga',
  'auditAccountDeletionRequestedDescription':
      'Korisnik je zatražio brisanje naloga.',
  'auditEmailChangeRequestedTitle': 'Zahtev za promenu e-maila',
  'auditEmailChangeRequestedDescription':
      'Korisnik je zatražio promenu e-mail adrese.',
  'auditEmailChangeCompletedTitle': 'Završetak promene e-maila',
  'auditEmailChangeCompletedDescription':
      'Korisnik je završio promenu e-mail adrese.',
  'auditPasswordResetRequestedTitle': 'Zahtev za obnovu lozinke',
  'auditPasswordResetRequestedDescription':
      'Korisnik je zatražio slanje e-maila za obnovu lozinke.',
  'auditActionDiscountRequested': 'Zahtev za popust',
  'auditActionDiscountApproved': 'Odobrenje popusta',
  'auditActionDiscountRejected': 'Odbijanje popusta',
  'auditActionAccountDeletionRequested': 'Zahtev za brisanje naloga',
  'auditActionEmailChangeRequested': 'Zahtev za promenu e-maila',
  'auditActionEmailChangeCompleted': 'Završetak promene e-maila',
  'auditActionPasswordResetRequested': 'Zahtev za obnovu lozinke',
};

const Map<String, List<String>> appTextListsSr = {
  'shortWeekdays': ['Pon', 'Uto', 'Sre', 'Čet', 'Pet', 'Sub', 'Ned'],
  'weekdays': [
    'Ponedeljak',
    'Utorak',
    'Sreda',
    'Četvrtak',
    'Petak',
    'Subota',
    'Nedelja',
  ],
};
