// Francúzske texty aplikácie.
const Map<String, String> appTextsFr = {
  'appName': 'Body Fit Club TT',
  'loading': 'Chargement...',
  'ok': 'OK',
  'save': 'Enregistrer',
  'delete': 'Supprimer',
  'cancel': 'Annuler',
  'back': 'Retour',
  'today': 'Aujourd’hui',
  'tomorrow': 'Demain',
  'todayLower': 'aujourd’hui',
  'tomorrowLower': 'demain',
  'minutes': 'min.',
  'refresh': 'Actualiser',
  'yesterday': 'Hier',
  'last7Days': '7 derniers jours',
  'last30Days': '30 derniers jours',
  'allTime': 'Toute la période',
  'close': 'Fermer',
  'reason': 'Motif',
  'unknownDate': 'Date inconnue',
  'notSet': 'Non défini',
  'confirm': 'Confirmer',
  'menu': 'Menu',
  'home': 'Accueil',
  'schedule': 'Planning',
  'reservations': 'Réservations',
  'management': 'Gestion',
  'profile': 'Profil',
  'settings': 'Paramètres',
  'appearance': 'Apparence',
  'appearanceDescription': 'Choisissez le mode clair, sombre ou système.',
  'themeSystem': 'Selon le système',
  'themeLight': 'Mode clair',
  'themeDark': 'Mode sombre',
  'menuPosition': 'Position du menu',
  'menuPositionDescription':
      'Choisissez de quel côté le menu principal doit s’afficher.',
  'rightHanded': 'Droitier',
  'leftHanded': 'Gaucher',
  'menuRightPositionDescription': 'Le menu sera en haut à droite.',
  'menuLeftPositionDescription': 'Le menu sera en haut à gauche.',
  'language': 'Langue',
  'languageDescription': 'Choisissez la langue de l’application.',
  'languageSlovak': '🇸🇰 Slovaque',
  'languageEnglish': '🇬🇧 Anglais',
  'languageGerman': '🇩🇪 Allemand',
  'languageFrench': '🇫🇷 Français',
  'languagePolish': '🇵🇱 Polonais',
  'languageHungarian': '🇭🇺 Hongrois',
  'languageUkrainian': '🇺🇦 Ukrainien',
  'languageRussian': '🇷🇺 Russe',
  'languageSerbian': '🇷🇸 Serbe',
  'languageCzech': '🇨🇿 Tchèque',
  'role': 'Rôle',
  'roleUser': 'Utilisateur',
  'roleTrainer': 'Entraîneur',
  'roleAdmin': 'Administrateur',
  'roleUnknown': 'Rôle inconnu',
  'privacyPolicy': 'Politique de confidentialité',
  'emailContact': 'E-mail',
  'loginTitle': 'Connexion',
  'registerTitle': 'Inscription',
  'continueWithGoogle': 'Continuer avec Google',
  'continueWithFacebook': 'Continuer avec Facebook',
  'or': 'ou',
  'email': 'E-mail',
  'password': 'Mot de passe',
  'login': 'Se connecter',
  'register': 'S’inscrire',
  'logout': 'Se déconnecter',
  'noAccountRegister': 'Vous n’avez pas de compte ? Inscription',
  'hasAccountLogin': 'Vous avez déjà un compte ? Connexion',
  'authError': 'Erreur de connexion',
  'acceptTerms': 'J’accepte les conditions générales',
  'acceptPrivacy': 'J’accepte le traitement des données personnelles',
  'termsConsentRequired':
      'Vous devez accepter les conditions générales pour vous inscrire.',
  'privacyConsentRequired':
      'Vous devez accepter le traitement des données personnelles pour vous inscrire.',
  'openTerms': 'Ouvrir les conditions générales',
  'openPrivacy': 'Ouvrir la politique de confidentialité',
  'termsVersion': '2026-05-16',
  'privacyVersion': '2026-05-16',
  'continueWithoutAccount': 'Continuer sans compte',
  'completeEmailOrLogout':
      'Si vous ne souhaitez pas ajouter d’e-mail, vous pouvez continuer sans compte et vous connecter plus tard avec un autre compte.',
  'fillEmailPassword': 'Remplissez l’e-mail et le mot de passe.',
  'invalidEmailFormat': 'Saisissez une adresse e-mail valide.',
  'passwordTooShort': 'Le mot de passe doit contenir au moins 6 caractères.',
  'wrongEmailOrPassword': 'L’e-mail ou le mot de passe saisi est incorrect.',
  'userAlreadyExists': 'Un utilisateur avec cette adresse e-mail existe déjà.',
  'weakPassword': 'Le mot de passe saisi est trop faible.',
  'tooManyRequests': 'Trop de tentatives. Veuillez réessayer plus tard.',
  'networkError': 'Vérifiez votre connexion Internet.',
  'signInCancelled': 'La connexion a été annulée.',
  'facebookLoginFailed': 'La connexion avec Facebook a échoué.',
  'unknownAuthError': 'Une erreur inconnue est survenue lors de la connexion.',
  'inactiveAccount': 'Votre compte est désactivé. Contactez l’administrateur.',
  'verificationEmailSent':
      'L’inscription a réussi. Nous vous avons envoyé un e-mail de vérification. Si vous ne le voyez pas dans votre boîte de réception, vérifiez aussi le dossier Spam.',
  'emailNotVerified':
      'Confirmez d’abord votre inscription en cliquant sur le lien dans l’e-mail.',
  'verificationEmailSentAgain':
      'Nous vous avons renvoyé l’e-mail de vérification. Si vous ne le voyez pas dans votre boîte de réception, vérifiez aussi le dossier Spam.',
  'forgotPassword': 'Mot de passe oublié ?',
  'resetPasswordTitle': 'Réinitialisation du mot de passe',
  'sendResetEmail': 'Envoyer l’e-mail',
  'passwordResetEmailSent':
      'Si un compte existe avec cet e-mail, nous avons envoyé un e-mail de réinitialisation du mot de passe.',
  'emailRequired': 'Saisissez un e-mail.',
  'emailNotProvided': 'Aucun e-mail n’a été fourni',
  'emailSaved': 'L’e-mail a été enregistré.',
  'emailSaveError': 'Impossible d’enregistrer l’e-mail.',
  'emailChangeVerificationSent':
      'Nous avons envoyé un lien de vérification au nouvel e-mail. Le changement sera terminé après confirmation.',
  'emailChangeRequestError': 'Impossible de lancer le changement d’e-mail.',
  'emailChangeNotAvailable':
      'Le changement d’e-mail est disponible uniquement pour les comptes créés avec e-mail et mot de passe.',
  'completeProfileTitle': 'Compléter le profil',
  'editProfile': 'Modifier le profil',
  'firstName': 'Prénom',
  'lastName': 'Nom',
  'publicName': 'Nom affiché',
  'publicNameHint': 'Par ex. Barbora, Katka, Aďo',
  'firstNameRequired': 'Saisissez le prénom.',
  'lastNameRequired': 'Saisissez le nom.',
  'publicNameRequired': 'Saisissez le nom affiché.',
  'profileSaved': 'Le profil a été enregistré.',
  'profileSaveError': 'Impossible d’enregistrer le profil.',
  'loggedInUser': 'Utilisateur connecté',
  'completeEmailTitle': 'Ajouter un e-mail',
  'completeEmailDescription':
      'Pour utiliser l’application, nous avons besoin de votre adresse e-mail. Elle sera utilisée comme e-mail de contact pour votre compte.',
  'deleteAccountRequest': 'Demander la suppression du compte',
  'deleteAccountRequestTitle': 'Suppression du compte',
  'deleteAccountRequestDescription':
      'Après l’envoi de la demande, le compte sera désactivé et vous ne pourrez plus vous connecter. Les données seront ensuite traitées par l’administrateur selon les règles de confidentialité.',
  'deleteAccountReason': 'Motif de la demande',
  'deleteAccountConfirm':
      'Voulez-vous vraiment demander la suppression du compte ?',
  'deleteAccountRequestSent':
      'La demande de suppression du compte a été envoyée.',
  'deleteAccountRequestError':
      'Impossible d’envoyer la demande de suppression du compte.',
  'deleteAccountBlockedActiveReservations':
      'Le compte ne peut pas être supprimé, car vous avez des réservations actives.',
  'accountDeletionRequests': 'Demandes de suppression de compte',
  'accountDeletionRequestsWithCount': 'Demandes de suppression de compte',
  'accountDeletionRequestsLoadError':
      'Impossible de charger les demandes de suppression de compte.',
  'noAccountDeletionRequests': 'Aucune demande en attente n’est enregistrée.',
  'completeAccountDeletion': 'Anonymiser le compte',
  'completeAccountDeletionTitle': 'Anonymiser le compte',
  'completeAccountDeletionQuestion':
      'Voulez-vous vraiment anonymiser ce compte ? Cette action remplacera les données personnelles de l’utilisateur.',
  'accountDeletionCompleted': 'Le compte a été anonymisé.',
  'accountDeletionCompleteError': 'Impossible d’anonymiser le compte.',
  'requestedAt': 'Demandé le',
  'accountDeletionRequestsWaiting': 'Demandes en attente de traitement.',
  'changeEmail': 'Changer l’e-mail',
  'changeEmailTitle': 'Changement d’e-mail',
  'changeEmailDescription':
      'Saisissez le nouvel e-mail et le mot de passe actuel. Nous enverrons un lien de vérification au nouvel e-mail. Le changement ne sera terminé qu’après confirmation du lien dans l’e-mail.',
  'changeEmailProfileHint':
      'Disponible pour les comptes créés avec e-mail et mot de passe.',
  'newEmail': 'Nouvel e-mail',
  'currentPassword': 'Mot de passe actuel',
  'sendVerificationEmail': 'Envoyer l’e-mail de vérification',
  'wrongCurrentPassword': 'Le mot de passe actuel est incorrect.',
  'requiresRecentLogin':
      'Pour cette action, déconnectez-vous d’abord puis reconnectez-vous.',
  'changeProfilePhoto': 'Changer la photo de profil',
  'chooseFromGallery': 'Choisir dans la galerie',
  'takePhoto': 'Prendre une photo',
  'removePhoto': 'Supprimer la photo',
  'editPhoto': 'Modifier la photo',
  'cropProfilePhoto': 'Rogner la photo de profil',
  'profilePhotoUpdated': 'La photo de profil a été enregistrée.',
  'profilePhotoUpdateError': 'Impossible d’enregistrer la photo de profil.',
  'profilePhotoRemoveError': 'Impossible de supprimer la photo de profil.',
  'requestDiscount': 'Demander une réduction',
  'discountStatus': 'Statut de réduction',
  'discountStatusNone': 'Sans réduction',
  'discountStatusPending': 'En attente d’approbation',
  'discountStatusApproved': 'Réduction approuvée',
  'discountStatusRejected': 'Demande rejetée',
  'discountStatusExpired': 'La validité de la réduction a expiré',
  'discountType': 'Type de réduction',
  'discountTypeNormal': 'Utilisateur standard',
  'discountTypeStudent': 'Étudiant',
  'discountTypeSenior': 'Senior',
  'discountTypeZtp': 'Personne handicapée',
  'discountTypeIndividual': 'Réduction individuelle',
  'discountRequestDescription':
      'Choisissez le type de réduction demandé. Après l’envoi, la demande sera vérifiée par un administrateur.',
  'discountRequestNote': 'Note de la demande',
  'discountRequestSent': 'La demande de réduction a été envoyée.',
  'discountRequestError': 'Impossible d’envoyer la demande de réduction.',
  'discountRequestAlreadyPending':
      'Vous avez déjà une demande de réduction en cours.',
  'discountRequestPending': 'La demande attend l’approbation',
  'sendRequest': 'Envoyer la demande',
  'discountDocument': 'Justificatif de réduction',
  'discountDocumentDescription':
      'Téléversez une photo du justificatif que l’administrateur utilisera pour vérifier votre droit à la réduction.',
  'chooseDiscountDocument': 'Choisir un justificatif',
  'discountDocumentRequired':
      'Un justificatif doit être joint avant l’envoi de la demande.',
  'discountDocumentSelected': 'Le justificatif a été sélectionné',
  'takeDiscountDocumentPhoto': 'Photographier le justificatif',
  'chooseDiscountDocumentFromGallery': 'Choisir dans la galerie',
  'discountRequests': 'Demandes de réduction',
  'discountRequestsDescription':
      'Approuver ou rejeter les demandes de réduction des utilisateurs.',
  'discountRequestsLoadError':
      'Impossible de charger les demandes de réduction.',
  'noDiscountRequests':
      'Aucune demande de réduction en attente n’est enregistrée.',
  'approveDiscount': 'Approuver la réduction',
  'rejectDiscount': 'Rejeter la demande',
  'discountApproved': 'La réduction a été approuvée.',
  'discountRejected': 'La demande de réduction a été rejetée.',
  'discountDecisionError':
      'Impossible d’enregistrer la décision concernant la demande.',
  'discountValidUntilRequired':
      'Sélectionnez la date de validité de la réduction.',
  'discountAdminNote': 'Note de l’administrateur',
  'selectDiscountValidUntil': 'Sélectionner la validité de la réduction',
  'discountDocumentPreview': 'Aperçu du justificatif',
  'todayReservations': 'Réservations d’aujourd’hui',
  'noTodayReservations': 'Vous n’avez aucun entraînement réservé aujourd’hui.',
  'nearestTraining': 'Entraînement le plus proche',
  'nearestTrainings': 'Entraînements les plus proches',
  'noNearestTraining': 'Aucun entraînement à venir n’est planifié.',
  'todaysTrainings': 'Entraînements d’aujourd’hui',
  'noTodaysTrainings': 'Aucun entraînement n’est planifié aujourd’hui.',
  'myMemberships': 'Mes cartes',
  'activeMembershipsCount': 'Cartes actives',
  'availableEntriesSummary': 'Entrées disponibles',
  'reservedEntriesSummary': 'Entrées allouées',
  'dailyMembershipsSummary': 'Cartes journalières',
  'tapToShowQrCode': 'Touchez pour afficher le QR code.',
  'nearestReservations': 'Réservations à venir',
  'noNearestReservations': 'Vous n’avez aucune réservation à venir.',
  'qrShort': 'QR',
  'membershipStatus': 'Statut de la carte',
  'remainingEntries': 'Entrées restantes',
  'upcomingTraining': 'Prochain entraînement aujourd’hui',
  'schedulePlaceholder': 'Le planning des entraînements sera affiché ici.',
  'reservationsPlaceholder': 'Les réservations seront affichées ici.',
  'newsPlaceholder':
      'Les actualités et messages des entraîneurs seront affichés ici.',
  'aboutApp': 'À propos de l’application',
  'aboutUs': 'À propos de nous',
  'aboutAppDescription':
      'L’application Body Fit Club TT sert à gérer les entraînements, les réservations, les cartes et la communication entre le centre de fitness et les utilisateurs.',
  'aboutUsDescription':
      'Body Fit Club est un centre de fitness à Trnava axé sur les entraînements collectifs et individuels, le mouvement, un mode de vie sain et une approche personnalisée des clients.',
  'bodyFitClubWebsite': 'https://bodyfitclub.sk/',
  'openWebsite': 'Ouvrir le site web',
  'businessTerms': 'Conditions générales',
  'legalDocumentsInfo':
      'Les conditions générales et les informations sur la protection des données personnelles seront disponibles sur le site web de Body Fit Club.',
  'contacts': 'Contacts',
  'billingDetails': 'Informations de facturation',
  'address': 'Adresse',
  'phone': 'Téléphone',
  'website': 'Site web',
  'socialNetworks': 'Réseaux sociaux',
  'openMap': 'Ouvrir la carte',
  'openFacebook': 'Facebook',
  'openInstagram': 'Instagram',
  'multisport': 'MultiSport',
  'multisportInfo':
      'Nous acceptons la carte MultiSport selon les conditions d’exploitation actuelles.',
  'bodyFitClubCompanyName': 'BODYFIT CLUB s.r.o.',
  'bodyFitClubOperationAddress': 'V Jame 24, Trnava',
  'bodyFitClubBillingAddress': 'J. G. Tajovského 18, 917 08 Trnava',
  'bodyFitClubPhonePrimary': '+421 902 860 008',
  'bodyFitClubPhoneSecondary': '+421 903 946 895',
  'bodyFitClubEmail': 'bodyfitclubtt@gmail.com',
  'bodyFitClubIco': '48074128',
  'ico': 'N° d’identification : ',
  'companySeat': 'Siège',
  'operation': 'Établissement',
  'bodyFitClubFacebookUrl': 'https://www.facebook.com/bodyfitclub.sk',
  'bodyFitClubInstagramUrl': 'https://www.instagram.com/bodyfitclub.tt/',
  'bodyFitClubMapUrl':
      'https://www.google.com/maps/search/?api=1&query=V%20Jame%206641%2F24%2C%20917%2001%20Trnava',
  'bodyFitClubMultiSportUrl':
      'https://multi-sport.sk/aktivity/partner/bodyfit-club/',
  'multisportInfo2':
      'Body Fit Club est partenaire du programme MultiSport. L’acceptation de la carte MultiSport suit les conditions d’exploitation actuelles.',
  'bodyFitClubWebsiteLabel': 'www.bodyfitclub.sk',
  'dic': 'N° fiscal : ',
  'bodyFitClubDic': '2120035445',
  'notVatPayer': 'La société n’est pas assujettie à la TVA',
  'legalDocuments': 'Documents juridiques',
  'priceList': 'Tarifs',
  'priceListAudience': 'Pour',
  'priceListAudienceNormal': 'utilisateurs standards',
  'priceListAudienceDiscount': 'utilisateurs avec réduction',
  'priceListAudienceAll': 'tous',
  'price': 'Prix',
  'singleEntries': 'Entrées uniques',
  'priceListMemberships': 'Cartes',
  'chooseEntry': 'Choisissez une entrée',
  'noAvailablePlans': 'Aucune option d’achat n’est actuellement disponible.',
  'news': 'Actualités',
  'noPublicMessages': 'Il n’y a pas encore de messages.',
  'writeMessage': 'Écrire un message',
  'writeMessageShort': 'Écrire',
  'editMessage': 'Modifier le message',
  'deleteMessage': 'Supprimer le message',
  'deleteMessageQuestion': 'Voulez-vous vraiment supprimer ce message ?',
  'messageText': 'Texte du message',
  'messageHint': 'Écrivez un message...',
  'sendMessage': 'Envoyer',
  'updateMessage': 'Enregistrer les modifications',
  'messageSaved': 'Le message a été enregistré.',
  'messageDeleted': 'Le message a été supprimé.',
  'messageSaveError': 'Impossible d’enregistrer le message.',
  'messageDeleteError': 'Impossible de supprimer le message.',
  'editedBy': 'Modifié',
  'editedByAdmin': 'Modifié par l’administrateur',
  'editedByTrainer': 'Modifié par l’entraîneur',
  'userFallback': 'Utilisateur',
  'noTrainings': 'Aucun entraînement n’est actuellement disponible.',
  'noTrainingsForSelectedDay':
      'Aucun entraînement n’est planifié pour ce jour.',
  'trainer': 'Entraîneur',
  'freeSpots': 'Places libres',
  'reserve': 'Réserver',
  'reserved': 'Réservé',
  'fullCapacity': 'Complet',
  'trainingsLoadError': 'Impossible de charger le planning des entraînements.',
  'unknownTraining': 'Entraînement inconnu',
  'unknownTrainer': 'Entraîneur inconnu',
  'unknownUser': 'Utilisateur inconnu',
  'trainingSessionFinished': 'Terminé',
  'trainingSessionTooFarInFuture':
      'La date est trop éloignée dans le futur. Vous pouvez ajouter manuellement un entraînement uniquement dans la période affichée dans le planning.',
  'managementDescription':
      'Vous pouvez gérer ici les créneaux d’entraînement, la présence, les cartes et les utilisateurs.',
  'scheduleManagement': 'Gestion du planning',
  'scheduleManagementDescription':
      'Gestion des types d’entraînement, des modèles de planning et des créneaux d’entraînement concrets.',
  'attendanceManagement': 'Gestion de la présence',
  'usersManagement': 'Gestion des utilisateurs',
  'usersManagementComingSoon':
      'La gestion des utilisateurs sera ajoutée plus tard.',
  'scheduleTemplatesManagement': 'Gestion des modèles de planning',
  'reactivateUser': 'Réactiver l’utilisateur',
  'reactivateUserQuestion': 'Voulez-vous vraiment réactiver cet utilisateur ?',
  'userReactivated': 'L’utilisateur a été réactivé.',
  'trainingTypesManagement': 'Gestion des types d’entraînement',
  'addTrainingType': 'Ajouter un type d’entraînement',
  'editTrainingType': 'Modifier le type d’entraînement',
  'deleteTrainingType': 'Supprimer le type d’entraînement',
  'trainingType': 'Type d’entraînement',
  'selectTrainingType': 'Sélectionnez un type d’entraînement',
  'trainingName': 'Nom de l’entraînement',
  'description': 'Description',
  'defaultDuration': 'Durée par défaut',
  'defaultCapacity': 'Capacité par défaut',
  'noTrainingTypes': 'Aucun type d’entraînement n’est actuellement créé.',
  'trainingTypesLoadError': 'Impossible de charger les types d’entraînement.',
  'trainingTypeCreated': 'Le type d’entraînement a été créé.',
  'trainingTypeUpdated': 'Le type d’entraînement a été modifié.',
  'trainingTypeDeleted': 'Le type d’entraînement a été supprimé.',
  'trainingTypeDeleteQuestion':
      'Voulez-vous vraiment supprimer ce type d’entraînement ? Il ne sera plus proposé pour les nouveaux créneaux.',
  'trainingTypeAlreadyExists':
      'Un type d’entraînement avec ce nom existe déjà.',
  'trainingTypeUsedByTemplate':
      'Le type d’entraînement ne peut pas être supprimé, car il est utilisé dans un modèle de planning actif.',
  'trainingTypeUsedBySession':
      'Le type d’entraînement ne peut pas être supprimé, car il est utilisé dans un créneau d’entraînement futur.',
  'addTrainingSession': 'Ajouter un créneau d’entraînement',
  'editTrainingSession': 'Modifier les détails de l’entraînement',
  'trainingSessionCreated': 'Le créneau d’entraînement a été créé.',
  'trainingSessionUpdated': 'Le créneau d’entraînement a été modifié.',
  'updateTrainingSessionError':
      'Impossible de modifier le créneau d’entraînement.',
  'trainingSessionInPast':
      'Le créneau d’entraînement ne peut pas être dans le passé.',
  'trainingSessionOverlap':
      'Un autre entraînement est déjà planifié à cette heure.',
  'capacityLowerThanReservations':
      'La capacité ne peut pas être inférieure au nombre de réservations existantes.',
  'cancelTrainingSession': 'Annuler le créneau',
  'cancelTrainingSessionTitle': 'Annuler le créneau d’entraînement',
  'cancelTrainingSessionQuestion':
      'Voulez-vous vraiment annuler ce créneau d’entraînement ? Les réservations actives seront annulées et les entrées allouées seront libérées. Si une entrée a déjà été utilisée, elle sera rendue à l’utilisateur.',
  'cancelTrainingSessionConfirm': 'Annuler le créneau',
  'trainingSessionCancelled': 'Le créneau d’entraînement a été annulé.',
  'cancelTrainingSessionError':
      'Impossible d’annuler le créneau d’entraînement.',
  'trainerCanCancelOnlyOwnSession':
      'L’entraîneur ne peut annuler que son propre créneau.',
  'trainerCannotCancelStartedSession':
      'L’entraîneur ne peut pas annuler un créneau qui a déjà commencé ou qui est terminé.',
  'date': 'Date',
  'startTime': 'Début',
  'duration': 'Durée',
  'capacity': 'Capacité',
  'selectDate': 'Sélectionnez une date',
  'selectTrainer': 'Sélectionnez un entraîneur',
  'trainersLoadError': 'Impossible de charger les entraîneurs.',
  'fillAllFields': 'Remplissez tous les champs obligatoires.',
  'invalidCapacity': 'La capacité doit être supérieure à 0.',
  'invalidDuration': 'La durée doit être supérieure à 0.',
  'saveError': 'L’enregistrement a échoué.',
  'addScheduleTemplate': 'Ajouter un modèle de planning',
  'editScheduleTemplate': 'Modifier le modèle de planning',
  'deleteScheduleTemplate': 'Supprimer le modèle de planning',
  'noScheduleTemplates': 'Aucun modèle de planning n’est actuellement créé.',
  'weekday': 'Jour de la semaine',
  'selectWeekday': 'Sélectionnez un jour de la semaine',
  'scheduleTemplateCreated': 'Le modèle de planning a été créé.',
  'scheduleTemplateUpdated': 'Le modèle de planning a été modifié.',
  'scheduleTemplateDeleted': 'Le modèle de planning a été supprimé.',
  'scheduleTemplateDeleteQuestion':
      'Voulez-vous vraiment supprimer ce modèle de planning ? Il ne sera plus utilisé lors de la génération de nouveaux créneaux.',
  'scheduleTemplateAlreadyExists': 'Un tel modèle de planning existe déjà.',
  'scheduleTemplateLoadError': 'Impossible de charger les modèles de planning.',
  'scheduleTemplateOverlap':
      'Un autre modèle de planning existe déjà à cette heure.',
  'capacityLabel': 'Capacité',
  'reservationCreated': 'La réservation a été créée.',
  'reservationAlreadyExists':
      'Vous avez déjà une réservation pour cet entraînement.',
  'reservationTrainingFull': 'Cet entraînement est complet.',
  'reservationTrainingNotAvailable':
      'Cet entraînement n’est plus disponible à la réservation.',
  'reservationTrainingAlreadyStarted':
      'Il n’est plus possible de réserver cet entraînement.',
  'reservationError': 'Impossible de créer la réservation.',
  'myReservations': 'Mes réservations',
  'noReservations': 'Vous n’avez actuellement aucune réservation.',
  'cancelReservation': 'Annuler la réservation',
  'cancelReservationTitle': 'Annuler la réservation',
  'cancelReservationQuestion':
      'Voulez-vous vraiment annuler cette réservation ?',
  'reservationCancelled': 'La réservation a été annulée.',
  'reservationCancelError': 'Impossible d’annuler la réservation.',
  'reservationsLoadError': 'Impossible de charger les réservations.',
  'cancelReservations': 'Annuler les réservations',
  'cancelReservationsBeforeDeactivation':
      'Avant de désactiver ou d’annuler la carte, annulez d’abord les réservations allouées.',
  'cancelReservationForMembership': 'Annuler cette réservation',
  'cancelReservationForMembershipQuestion':
      'Voulez-vous vraiment annuler cette réservation liée à la carte ? L’entrée allouée sera libérée.',
  'reservationForMembershipCancelled':
      'La réservation a été annulée et l’entrée allouée a été libérée.',
  'noReservationsForTrainingHistory':
      'Il n’y a aucune réservation pour cet entraînement.',
  'reservationQrCode': 'QR code de réservation',
  'memberships': 'Cartes',
  'assignMembership': 'Attribuer une carte',
  'selectUser': 'Sélectionnez un utilisateur',
  'selectMembershipPlan': 'Sélectionnez un type de carte',
  'membershipPlansLoadError': 'Impossible de charger les types de cartes.',
  'membershipAssigned': 'La carte a été attribuée.',
  'membershipAssignError': 'Impossible d’attribuer la carte.',
  'membershipPlan': 'Type de carte',
  'client': 'Utilisateur',
  'buyMembership': 'Acheter une carte',
  'buySingleEntry': 'Acheter une entrée unique',
  'chooseMembership': 'Choisissez une carte',
  'payment': 'Paiement',
  'pay': 'Payer',
  'paymentSuccessful': 'Paiement réussi.',
  'paymentFailed': 'Paiement échoué.',
  'activeMembership': 'Carte active',
  'noActiveMembership': 'Vous n’avez aucune carte active.',
  'validUntil': 'Valable jusqu’au',
  'membershipLoadError': 'Impossible de charger la carte.',
  'noAvailableEntries': 'Vous n’avez aucune entrée disponible pour réserver.',
  'noUpcomingTraining': 'Vous n’avez aucun entraînement réservé aujourd’hui.',
  'membershipsManagement': 'Gestion des cartes',
  'membershipDetail': 'Détail de la carte',
  'noMemberships': 'Aucune carte n’est actuellement disponible.',
  'status': 'Statut',
  'validFrom': 'Valable à partir du',
  'entriesTotal': 'Nombre total d’entrées',
  'entriesRemaining': 'Entrées restantes',
  'entriesReserved': 'Entrées allouées aux réservations',
  'entriesAvailable': 'Entrées disponibles',
  'adminMembershipEdit': 'Modification administrateur',
  'membershipStatusActive': 'Active',
  'membershipStatusInactive': 'Inactive',
  'membershipStatusCancelled': 'Annulée',
  'membershipStatusExpired': 'Expirée',
  'membershipStatusUsedUp': 'Épuisée',
  'membershipUpdated': 'La carte a été modifiée.',
  'membershipUpdateError': 'Impossible de modifier la carte.',
  'invalidRemainingEntries': 'Saisissez un nombre valide d’entrées restantes.',
  'allocatedReservations': 'Réservations allouées',
  'cancelAllocatedReservations': 'Annuler les réservations allouées',
  'cancelAllocatedReservationsQuestion':
      'Voulez-vous vraiment annuler les réservations actives liées à cette carte ? Les entrées allouées seront libérées.',
  'cancelAllReservations': 'Annuler toutes les réservations',
  'cancelAllocatedReservationsError':
      'Impossible d’annuler les réservations allouées.',
  'usedEntries': 'Entrées utilisées',
  'noAllocatedReservations':
      'Aucune réservation n’est actuellement allouée à cette carte.',
  'noUsedEntries': 'Aucune entrée de cette carte n’a encore été utilisée.',
  'membershipUsageLoadError': 'Impossible de charger l’historique de la carte.',
  'searchMemberships': 'Rechercher par utilisateur ou carte',
  'allMembershipStatuses': 'Tous les statuts',
  'membershipStatusNotYetValid': 'Pas encore valable',
  'membershipStatusUsable': 'Active',
  'invalidRemainingEntriesHigherThanTotal':
      'Les entrées restantes ne peuvent pas être supérieures au nombre total d’entrées.',
  'invalidRemainingEntriesLowerThanReserved':
      'Les entrées restantes ne peuvent pas être inférieures au nombre d’entrées allouées.',
  'membershipPrefix': 'Carte',
  'statusPrefix': 'Statut',
  'attendance': 'Présence',
  'attendanceLoadError': 'Impossible de charger la présence.',
  'noActiveReservationsForAttendance':
      'Il n’y a actuellement aucune réservation active à marquer pour la présence.',
  'attended': 'Présent',
  'noShow': 'Absent',
  'markAttendedTitle': 'Marquer la présence',
  'markNoShowTitle': 'Marquer l’absence',
  'markAttendedQuestion':
      'Voulez-vous vraiment marquer l’utilisateur comme présent ?',
  'markNoShowQuestion':
      'Voulez-vous vraiment marquer l’utilisateur comme absent ?',
  'attendanceMarked': 'La présence a été enregistrée.',
  'attendanceMarkError': 'Impossible d’enregistrer la présence.',
  'attendedStatus': 'Présent',
  'noShowStatus': 'Absent',
  'attendedCountLabel': 'Présents',
  'noShowCountLabel': 'Absents',
  'attendanceActionDone': 'La modification de présence a été enregistrée.',
  'attendanceActionError':
      'Impossible d’enregistrer la modification de présence.',
  'showQrCode': 'QR code',
  'showQrToTrainer':
      'Montrez ce QR code à l’entraîneur à votre arrivée à l’entraînement.',
  'scanQrCode': 'Scanner le QR code',
  'scanQrCodes': 'Scanner les QR codes',
  'scanQrCodeHint':
      'Dirigez la caméra vers le QR code de réservation de l’utilisateur.',
  'invalidQrCode': 'QR code de réservation non valide.',
  'qrCodeScanned': 'Le QR code a été scanné.',
  'qrScanSuccessful':
      'Le QR code a été scanné. Vous pouvez scanner l’utilisateur suivant.',
  'trainerQrScanTooEarly':
      'Le QR code peut être scanné au plus tôt 30 minutes avant le début de l’entraînement.',
  'trainingHistory': 'Historique des entraînements',
  'trainingHistoryDetail': 'Détail de l’entraînement',
  'trainingHistoryLoadError':
      'Impossible de charger l’historique des entraînements.',
  'trainingHistoryReservationsLoadError':
      'Impossible de charger la présence à l’entraînement.',
  'noTrainingHistoryInSelectedPeriod':
      'Aucun entraînement dans la période sélectionnée.',
  'fromDatePrefix': 'Du',
  'toDatePrefix': 'Au',
  'planned': 'Planifié',
  'cancelled': 'Annulé',
  'finished': 'Terminé',
  'reservedStatus': 'Réservé',
  'reservedCountLabel': 'Réservés',
  'cancelledCountLabel': 'Annulés',
  'markedAtPrefix': 'Marqué le',
  'markAsAttended': 'Marquer comme présent',
  'markAsNoShow': 'Marquer comme absent',
  'revertAttendance': 'Annuler la présence marquée',
  'revertNoShow': 'Annuler l’absence marquée',
  'markAsAttendedQuestion':
      'Voulez-vous vraiment marquer l’utilisateur comme présent ? Une entrée de la carte sera utilisée.',
  'markAsNoShowQuestion':
      'Voulez-vous vraiment marquer l’utilisateur comme absent ? Une entrée de la carte sera utilisée.',
  'revertAttendanceQuestion':
      'Voulez-vous vraiment annuler la présence marquée ? L’entrée utilisée sera rendue à la carte.',
  'revertNoShowQuestion':
      'Voulez-vous vraiment annuler l’absence marquée ? L’entrée utilisée sera rendue à la carte.',
  'addTrainingAttendance': 'Ajouter un participant',
  'selectAttendanceUser': 'Sélectionnez un utilisateur',
  'selectAttendanceMembership': 'Sélectionnez une carte',
  'noUsersForAttendance': 'Aucun utilisateur actif n’a été trouvé.',
  'noUsableMembershipsForAttendance':
      'L’utilisateur n’a aucune carte utilisable pour cet entraînement.',
  'addTrainingAttendanceQuestion':
      'Voulez-vous vraiment ajouter ultérieurement la présence de l’utilisateur à cet entraînement ? Une entrée de la carte sera utilisée.',
  'trainingAttendanceAdded': 'Le participant a été ajouté à l’entraînement.',
  'trainingAttendanceAddError': 'Impossible d’ajouter le participant.',
  'userAlreadyHasReservationForTraining':
      'L’utilisateur a déjà un enregistrement pour cet entraînement.',
  'usersLoadError': 'Impossible de charger les utilisateurs.',
  'allRoles': 'Tous les rôles',
  'searchUsers': 'Rechercher un utilisateur',
  'noUsersFound': 'Aucun utilisateur trouvé.',
  'editUser': 'Modifier l’utilisateur',
  'userUpdated': 'L’utilisateur a été modifié.',
  'userUpdateError': 'Impossible de modifier l’utilisateur.',
  'cannotChangeOwnRole': 'Vous ne pouvez pas modifier votre propre rôle.',
  'changeRoleWarning':
      'Le changement de rôle d’un utilisateur peut modifier ses autorisations dans l’application.',
  'deactivateUser': 'Désactiver l’utilisateur',
  'deactivationReason': 'Motif de désactivation',
  'userDeactivated': 'L’utilisateur a été désactivé.',
  'deactivateUserQuestion':
      'Voulez-vous vraiment désactiver cet utilisateur ? Il ne pourra plus utiliser la gestion de l’application.',
  'cannotDeactivateYourself':
      'Vous ne pouvez pas désactiver votre propre compte.',
  'userUsedByTemplate':
      'L’utilisateur ne peut pas être désactivé ou changé en utilisateur standard, car il est attribué à un modèle de planning actif.',
  'userUsedByFutureSession':
      'L’utilisateur ne peut pas être désactivé ou changé en utilisateur standard, car il est attribué à un entraînement futur.',
  'userHasActiveReservations':
      'L’utilisateur ne peut pas être désactivé, car il a des réservations actives.',
  'userHasActiveMemberships':
      'L’utilisateur ne peut pas être désactivé, car il a des cartes actives.',
  'inactiveUser': 'Utilisateur inactif',
  'userCannotBeDeactivated': 'L’utilisateur ne peut pas être désactivé',
  'userCannotBeDeactivatedDescription':
      'Avant la désactivation, il faut d’abord résoudre ses réservations ou cartes actives.',
  'userHasBlockingItems': 'L’utilisateur a :',
  'activeReservationsCount': 'Réservations actives',
  'showMemberships': 'Afficher les cartes',
  'auditLogs': 'Historique des actions',
  'auditLogsDescription': 'Aperçu des actions importantes dans l’application.',
  'auditLogsLoadError': 'Impossible de charger l’historique des actions.',
  'noAuditLogs': 'Aucune action trouvée.',
  'searchAuditLogs': 'Rechercher par utilisateur, e-mail ou description',
  'auditCategory': 'Catégorie',
  'auditAction': 'Action',
  'auditActor': 'Effectué par',
  'auditActorRole': 'Rôle de l’acteur',
  'auditPeriod': 'Période',
  'auditAllCategories': 'Toutes les catégories',
  'auditCategoryMemberships': 'Cartes',
  'auditCategoryReservations': 'Réservations',
  'auditCategoryAttendance': 'Présence',
  'auditCategoryUsers': 'Utilisateurs',
  'auditCategorySchedule': 'Planning',
  'auditCategoryMessages': 'Messages',
  'auditCategoryPayments': 'Paiements',
  'auditCategoryProfile': 'Profil',
  'auditAllActions': 'Toutes les actions',
  'auditActionCreated': 'Création',
  'auditActionUpdated': 'Modification',
  'auditActionCancelled': 'Annulation',
  'auditActionDeactivated': 'Désactivation',
  'auditActionActivated': 'Activation',
  'auditActionAssigned': 'Attribution',
  'auditActionPurchased': 'Achat',
  'auditActionPaymentSucceeded': 'Paiement réussi',
  'auditActionPaymentFailed': 'Paiement échoué',
  'auditActionAttendanceMarked': 'Présence',
  'auditActionQrChecked': 'Contrôle QR',
  'auditAllActorRoles': 'Tous les rôles',
  'auditReservationCreatedTitle': 'Création de réservation',
  'auditReservationCreatedDescription':
      'L’utilisateur a créé une réservation pour un entraînement.',
  'auditReservationCancelledTitle': 'Annulation de réservation',
  'auditReservationCancelledDescription':
      'La réservation de l’utilisateur a été annulée.',
  'auditAttendanceAttendedTitle': 'Présence marquée',
  'auditAttendanceAttendedDescription':
      'L’utilisateur a été marqué comme présent à l’entraînement.',
  'auditAttendanceNoShowTitle': 'Absence marquée',
  'auditAttendanceNoShowDescription':
      'L’utilisateur a été marqué comme absent de l’entraînement.',
  'auditTrainingTypeCreatedTitle': 'Type d’entraînement créé',
  'auditTrainingTypeUpdatedTitle': 'Type d’entraînement modifié',
  'auditTrainingTypeDeactivatedTitle': 'Type d’entraînement désactivé',
  'auditTrainingSessionCreatedTitle': 'Créneau créé',
  'auditTrainingSessionUpdatedTitle': 'Créneau modifié',
  'auditTrainingSessionTimeChangedTitle': 'Heure du créneau modifiée',
  'auditTrainingSessionCancelledTitle': 'Créneau annulé',
  'auditScheduleTemplateCreatedTitle': 'Modèle de planning créé',
  'auditScheduleTemplateUpdatedTitle': 'Modèle de planning modifié',
  'auditScheduleTemplateDeactivatedTitle': 'Modèle de planning désactivé',
  'auditUserUpdatedTitle': 'Utilisateur modifié',
  'auditUserUpdatedDescription':
      'L’administrateur a modifié les données de l’utilisateur.',
  'auditUserRoleChangedTitle': 'Rôle de l’utilisateur modifié',
  'auditUserRoleChangedDescription':
      'L’administrateur a modifié le rôle de l’utilisateur.',
  'auditUserDeactivatedTitle': 'Utilisateur désactivé',
  'auditUserDeactivatedDescription':
      'L’administrateur a désactivé l’utilisateur.',
  'auditUserDeactivationBlockedTitle':
      'Échec de la désactivation de l’utilisateur',
  'auditUserDeactivationBlockedDescription':
      'La désactivation de l’utilisateur a été bloquée par le contrôle des liens actifs.',
  'auditPublicMessageCreatedTitle': 'Actualité créée',
  'auditPublicMessageCreatedDescription': 'Une actualité publique a été créée.',
  'auditPublicMessageUpdatedTitle': 'Actualité modifiée',
  'auditPublicMessageUpdatedDescription':
      'Une actualité publique a été modifiée.',
  'auditPublicMessageDeletedTitle': 'Actualité supprimée',
  'auditPublicMessageDeletedDescription':
      'L’actualité publique a été supprimée.',
  'auditProfileCompletedTitle': 'Profil complété',
  'auditProfileCompletedDescription':
      'L’utilisateur a complété les données de base du profil.',
  'auditProfileUpdatedTitle': 'Profil modifié',
  'auditProfileUpdatedDescription':
      'L’utilisateur a modifié les données du profil.',
  'auditProfilePhotoUpdatedTitle': 'Photo de profil modifiée',
  'auditProfilePhotoUpdatedDescription':
      'L’utilisateur a modifié la photo de profil.',
  'auditProfilePhotoRemovedTitle': 'Photo de profil supprimée',
  'auditProfilePhotoRemovedDescription':
      'L’utilisateur a supprimé la photo de profil définie manuellement.',
  'auditPaymentStartedTitle': 'Paiement lancé',
  'auditPaymentStartedDescription':
      'L’utilisateur a lancé le paiement d’une carte.',
  'auditPaymentSucceededTitle': 'Paiement réussi',
  'auditPaymentSucceededDescription':
      'Le paiement de la carte a été terminé avec succès.',
  'auditPaymentFailedTitle': 'Paiement échoué',
  'auditPaymentFailedDescription':
      'Le paiement de la carte a échoué ou a été annulé.',
  'auditMembershipUpdatedTitle': 'Carte modifiée',
  'auditMembershipUpdatedDescription':
      'L’administrateur a modifié la carte de l’utilisateur.',
  'auditMembershipStatusChangedTitle': 'Statut de la carte modifié',
  'auditMembershipStatusChangedDescription':
      'L’administrateur a modifié le statut de la carte de l’utilisateur.',
  'auditMembershipEntriesChangedTitle': 'Nombre d’entrées de la carte modifié',
  'auditMembershipEntriesChangedDescription':
      'L’administrateur a modifié le nombre d’entrées restantes de la carte.',
  'auditMembershipReservationCancelledTitle': 'Réservation allouée annulée',
  'auditMembershipReservationCancelledDescription':
      'L’administrateur a annulé une réservation allouée liée à la carte.',
  'auditMembershipAllReservationsCancelledTitle':
      'Toutes les réservations allouées annulées',
  'auditMembershipAllReservationsCancelledDescription':
      'L’administrateur a annulé toutes les réservations allouées liées à la carte.',
  'auditMembershipAssignedTitle': 'Carte attribuée',
  'auditMembershipAssignedDescription':
      'Une carte a été attribuée manuellement à l’utilisateur.',
  'auditMembershipPurchasedTitle': 'Achat de carte',
  'auditMembershipPurchasedDescription': 'L’utilisateur a acheté une carte.',
  'auditActionMembershipAssigned': 'Carte attribuée',
  'auditActionMembershipPurchased': 'Carte achetée',
  'auditActionMembershipUpdated': 'Carte modifiée',
  'auditActionMembershipStatusChanged': 'Statut de la carte modifié',
  'auditActionMembershipEntriesChanged': 'Entrées de la carte modifiées',
  'auditActionMembershipReservationCancelled':
      'Une réservation allouée annulée',
  'auditActionMembershipAllReservationsCancelled':
      'Toutes les réservations allouées annulées',
  'auditActionReservationCreated': 'Réservation créée',
  'auditActionReservationCancelled': 'Réservation annulée',
  'auditActionAttendanceAttended': 'Présence marquée',
  'auditActionAttendanceNoShow': 'Absence marquée',
  'auditActionTrainingTypeCreated': 'Type d’entraînement créé',
  'auditActionTrainingTypeUpdated': 'Type d’entraînement modifié',
  'auditActionTrainingTypeDeactivated': 'Type d’entraînement désactivé',
  'auditActionTrainingSessionCreated': 'Créneau créé',
  'auditActionTrainingSessionUpdated': 'Créneau modifié',
  'auditActionTrainingSessionTimeChanged': 'Heure du créneau modifiée',
  'auditActionTrainingSessionCancelled': 'Créneau annulé',
  'auditActionScheduleTemplateCreated': 'Modèle créé',
  'auditActionScheduleTemplateUpdated': 'Modèle modifié',
  'auditActionScheduleTemplateDeactivated': 'Modèle désactivé',
  'auditActionUserUpdated': 'Utilisateur modifié',
  'auditActionUserRoleChanged': 'Rôle modifié',
  'auditActionUserDeactivationBlocked': 'Désactivation bloquée',
  'auditActionUserDeactivated': 'Utilisateur désactivé',
  'auditActionPublicMessageCreated': 'Actualité créée',
  'auditActionPublicMessageUpdated': 'Actualité modifiée',
  'auditActionPublicMessageDeleted': 'Actualité supprimée',
  'auditActionProfileCompleted': 'Profil complété',
  'auditActionProfileUpdated': 'Profil modifié',
  'auditActionProfilePhotoUpdated': 'Photo de profil modifiée',
  'auditActionProfilePhotoRemoved': 'Photo de profil supprimée',
  'auditActionPaymentStarted': 'Paiement lancé',
  'auditUserEmailCompletedTitle': 'E-mail ajouté',
  'auditUserEmailCompletedDescription':
      'L’utilisateur a ajouté l’e-mail manquant au compte.',
  'currentUserShort': 'vous',
  'auditUserEmailUpdatedTitle': 'E-mail de l’utilisateur modifié',
  'auditUserEmailUpdatedDescription':
      'L’administrateur a modifié l’e-mail de contact de l’utilisateur.',
  'auditUserReactivatedTitle': 'Utilisateur activé',
  'auditUserReactivatedDescription':
      'L’administrateur a réactivé l’utilisateur.',
  'auditActionUserEmailCompleted': 'E-mail ajouté',
  'auditActionUserEmailUpdated': 'E-mail de l’utilisateur modifié',
  'auditActionUserReactivated': 'Utilisateur activé',
  'auditCategoryDiscounts': 'Réductions',
  'auditDiscountRequestedTitle': 'Demande de réduction',
  'auditDiscountRequestedDescription':
      'L’utilisateur a envoyé une demande d’approbation de réduction.',
  'auditDiscountApprovedTitle': 'Réduction approuvée',
  'auditDiscountApprovedDescription':
      'L’administrateur a approuvé la réduction de l’utilisateur.',
  'auditDiscountRejectedTitle': 'Réduction rejetée',
  'auditDiscountRejectedDescription':
      'L’administrateur a rejeté la demande de réduction de l’utilisateur.',
  'auditAccountDeletionRequestedTitle': 'Demande de suppression de compte',
  'auditAccountDeletionRequestedDescription':
      'L’utilisateur a demandé la suppression du compte.',
  'auditEmailChangeRequestedTitle': 'Demande de changement d’e-mail',
  'auditEmailChangeRequestedDescription':
      'L’utilisateur a demandé un changement d’adresse e-mail.',
  'auditEmailChangeCompletedTitle': 'Changement d’e-mail terminé',
  'auditEmailChangeCompletedDescription':
      'L’utilisateur a terminé le changement d’adresse e-mail.',
  'auditPasswordResetRequestedTitle':
      'Demande de réinitialisation du mot de passe',
  'auditPasswordResetRequestedDescription':
      'L’utilisateur a demandé l’envoi d’un e-mail de réinitialisation du mot de passe.',
  'auditActionDiscountRequested': 'Demande de réduction',
  'auditActionDiscountApproved': 'Réduction approuvée',
  'auditActionDiscountRejected': 'Réduction rejetée',
  'auditActionAccountDeletionRequested': 'Demande de suppression de compte',
  'auditActionEmailChangeRequested': 'Demande de changement d’e-mail',
  'auditActionEmailChangeCompleted': 'Changement d’e-mail terminé',
  'auditActionPasswordResetRequested':
      'Demande de réinitialisation du mot de passe',
};

const Map<String, List<String>> appTextListsFr = {
  'shortWeekdays': ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam', 'Dim'],
  'weekdays': [
    'Lundi',
    'Mardi',
    'Mercredi',
    'Jeudi',
    'Vendredi',
    'Samedi',
    'Dimanche',
  ],
};
