// Slovenské texty aplikácie.
const Map<String, String> appTextsSk = {
  'appName': 'Body Fit Club TT',
  'loading': 'Načítavam...',
  'ok': 'OK',
  'save': 'Uložiť',
  'delete': 'Vymazať',
  'cancel': 'Zrušiť',
  'back': 'Späť',
  'today': 'Dnes',
  'tomorrow': 'Zajtra',
  'todayLower': 'dnes',
  'tomorrowLower': 'zajtra',
  'minutes': 'min.',
  'refresh': 'Aktualizovať',
  'yesterday': 'Včera',
  'last7Days': 'Posledných 7 dní',
  'last30Days': 'Posledných 30 dní',
  'allTime': 'Celé obdobie',
  'close': 'Zavrieť',
  'reason': 'Dôvod',
  'unknownDate': 'Neznámy dátum',
  'notSet': 'Nenastavené',
  'confirm': 'Potvrdiť',
  'menu': 'Menu',
  'home': 'Domov',
  'schedule': 'Rozvrh',
  'reservations': 'Rezervácie',
  'management': 'Správa',
  'profile': 'Profil',
  'settings': 'Nastavenia',
  'appearance': 'Vzhľad',
  'appearanceDescription': 'Vyberte svetlý, tmavý alebo systémový režim.',
  'themeSystem': 'Podľa systému',
  'themeLight': 'Svetlý režim',
  'themeDark': 'Tmavý režim',
  'menuPosition': 'Umiestnenie menu',
  'menuPositionDescription':
      'Vyberte, na ktorej strane sa má zobrazovať hlavné menu.',
  'rightHanded': 'Pravák',
  'leftHanded': 'Ľavák',
  'menuRightPositionDescription': 'Menu bude vpravo hore.',
  'menuLeftPositionDescription': 'Menu bude vľavo hore.',
  'language': 'Jazyk',
  'languageDescription': 'Vyberte jazyk aplikácie.',
  'languageSlovak': '🇸🇰 Slovenčina',
  'languageEnglish': '🇬🇧 Angličtina',
  'languageGerman': '🇩🇪 Nemčina',
  'languageFrench': '🇫🇷 Francúzština',
  'languagePolish': '🇵🇱 Poľština',
  'languageHungarian': '🇭🇺 Maďarčina',
  'languageUkrainian': '🇺🇦 Ukrajinčina',
  'languageRussian': '🇷🇺 Ruština',
  'languageSerbian': '🇷🇸 Srbčina',
  'languageCzech': '🇨🇿 Čeština',
  'role': 'Rola',
  'roleUser': 'Používateľ',
  'roleTrainer': 'Tréner',
  'roleAdmin': 'Administrátor',
  'roleUnknown': 'Neznáma rola',
  'privacyPolicy': 'Ochrana osobných údajov',
  'emailContact': 'E-mail',
  'loginTitle': 'Prihlásenie',
  'registerTitle': 'Registrácia',
  'continueWithGoogle': 'Pokračovať cez Google',
  'continueWithFacebook': 'Pokračovať cez Facebook',
  'or': 'alebo',
  'email': 'E-mail',
  'password': 'Heslo',
  'login': 'Prihlásiť',
  'register': 'Registrovať',
  'logout': 'Odhlásiť',
  'noAccountRegister': 'Nemáš účet? Registrovať',
  'hasAccountLogin': 'Už máš účet? Prihlásiť',
  'authError': 'Chyba prihlásenia',
  'acceptTerms': 'Súhlasím s obchodnými podmienkami',
  'acceptPrivacy': 'Súhlasím so spracovaním osobných údajov',
  'termsConsentRequired':
      'Pre registráciu je potrebné súhlasiť s obchodnými podmienkami.',
  'privacyConsentRequired':
      'Pre registráciu je potrebné súhlasiť so spracovaním osobných údajov.',
  'openTerms': 'Otvoriť obchodné podmienky',
  'openPrivacy': 'Otvoriť ochranu osobných údajov',
  'termsVersion': '2026-05-16',
  'privacyVersion': '2026-05-16',
  'continueWithoutAccount': 'Pokračovať bez účtu',
  'completeEmailOrLogout':
      'Ak nechceš doplniť e-mail, môžeš pokračovať bez účtu a prihlásiť sa neskôr iným účtom.',
  'fillEmailPassword': 'Vyplň e-mail aj heslo.',
  'invalidEmailFormat': 'Zadaj platný e-mail.',
  'passwordTooShort': 'Heslo musí mať aspoň 6 znakov.',
  'wrongEmailOrPassword': 'Zadaný e-mail alebo heslo nie je správne.',
  'userAlreadyExists': 'Používateľ s týmto e-mailom už existuje.',
  'weakPassword': 'Zadané heslo je príliš slabé.',
  'tooManyRequests': 'Príliš veľa pokusov. Skúste to neskôr.',
  'networkError': 'Skontrolujte internetové pripojenie.',
  'signInCancelled': 'Prihlásenie bolo zrušené.',
  'facebookLoginFailed': 'Prihlásenie cez Facebook sa nepodarilo.',
  'unknownAuthError': 'Nastala neznáma chyba pri prihlásení.',
  'inactiveAccount': 'Váš účet je deaktivovaný. Kontaktujte administrátora.',
  'verificationEmailSent':
      'Registrácia prebehla úspešne. Poslali sme vám overovací e-mail. Ak ho nevidíte '
      'v doručenej pošte, skontrolujte aj priečinok Spam.',
  'emailNotVerified':
      'Najskôr potvrďte registráciu kliknutím na odkaz v e-maile.',
  'verificationEmailSentAgain':
      'Overovací e-mail sme vám poslali opäť. Ak ho nevidíte v doručenej pošte, '
      'skontrolujte aj priečinok Spam.',
  'forgotPassword': 'Zabudli ste heslo?',
  'resetPasswordTitle': 'Obnovenie hesla',
  'sendResetEmail': 'Poslať e-mail',
  'passwordResetEmailSent':
      'Ak účet s týmto e-mailom existuje, poslali sme e-mail na obnovenie hesla.',
  'emailRequired': 'Zadajte e-mail.',
  'emailNotProvided': 'E-mail nebol poskytnutý',
  'emailSaved': 'E-mail bol uložený.',
  'emailSaveError': 'E-mail sa nepodarilo uložiť.',
  'emailChangeVerificationSent':
      'Na nový e-mail sme poslali overovací odkaz. Zmena sa dokončí po jeho potvrdení.',
  'emailChangeRequestError': 'Zmenu e-mailu sa nepodarilo spustiť.',
  'emailChangeNotAvailable':
      'Zmena e-mailu je dostupná iba pre účty vytvorené e-mailom a heslom.',
  'completeProfileTitle': 'Doplnenie profilu',
  'editProfile': 'Upraviť profil',
  'firstName': 'Meno',
  'lastName': 'Priezvisko',
  'publicName': 'Zobrazované meno',
  'publicNameHint': 'Napr. Barbora, Katka, Aďo',
  'firstNameRequired': 'Zadajte meno.',
  'lastNameRequired': 'Zadajte priezvisko.',
  'publicNameRequired': 'Zadajte zobrazované meno.',
  'profileSaved': 'Profil bol uložený.',
  'profileSaveError': 'Profil sa nepodarilo uložiť.',
  'loggedInUser': 'Prihlásený používateľ',
  'completeEmailTitle': 'Doplnenie e-mailu',
  'completeEmailDescription':
      'Pre používanie aplikácie potrebujeme vašu e-mailovú adresu. Použijeme ju ako '
      'kontaktný e-mail k vášmu účtu.',
  'deleteAccountRequest': 'Požiadať o vymazanie účtu',
  'deleteAccountRequestTitle': 'Vymazanie účtu',
  'deleteAccountRequestDescription':
      'Po odoslaní žiadosti bude účet deaktivovaný a nebude možné sa doň prihlásiť. '
      'Údaje budú následne spracované administrátorom podľa pravidiel ochrany '
      'osobných údajov.',
  'deleteAccountReason': 'Dôvod žiadosti',
  'deleteAccountConfirm': 'Naozaj chcete požiadať o vymazanie účtu?',
  'deleteAccountRequestSent': 'Žiadosť o vymazanie účtu bola odoslaná.',
  'deleteAccountRequestError':
      'Žiadosť o vymazanie účtu sa nepodarilo odoslať.',
  'deleteAccountBlockedActiveReservations':
      'Účet nie je možné vymazať, pretože máte aktívne rezervácie.',
  'accountDeletionRequests': 'Žiadosti o vymazanie účtu',
  'accountDeletionRequestsWithCount': 'Žiadosti o vymazanie účtu',
  'accountDeletionRequestsLoadError':
      'Žiadosti o vymazanie účtu sa nepodarilo načítať.',
  'noAccountDeletionRequests': 'Nie sú evidované žiadne čakajúce žiadosti.',
  'completeAccountDeletion': 'Anonymizovať účet',
  'completeAccountDeletionTitle': 'Anonymizovať účet',
  'completeAccountDeletionQuestion':
      'Naozaj chcete anonymizovať tento účet? Táto akcia prepíše osobné údaje používateľa.',
  'accountDeletionCompleted': 'Účet bol anonymizovaný.',
  'accountDeletionCompleteError': 'Účet sa nepodarilo anonymizovať.',
  'requestedAt': 'Požiadané',
  'accountDeletionRequestsWaiting': 'Čakajúce žiadosti na spracovanie.',
  'changeEmail': 'Zmeniť e-mail',
  'changeEmailTitle': 'Zmena e-mailu',
  'changeEmailDescription':
      'Zadajte nový e-mail a aktuálne heslo. Na nový e-mail pošleme overovací odkaz. '
      'Zmena sa dokončí až po potvrdení odkazu v e-maile.',
  'changeEmailProfileHint': 'Dostupné pre účty vytvorené e-mailom a heslom.',
  'newEmail': 'Nový e-mail',
  'currentPassword': 'Aktuálne heslo',
  'sendVerificationEmail': 'Poslať overovací e-mail',
  'wrongCurrentPassword': 'Aktuálne heslo nie je správne.',
  'requiresRecentLogin':
      'Pre túto akciu sa najskôr odhláste a znovu prihláste.',
  'changeProfilePhoto': 'Zmeniť profilovú fotku',
  'chooseFromGallery': 'Vybrať z galérie',
  'takePhoto': 'Odfotiť',
  'removePhoto': 'Odstrániť fotku',
  'editPhoto': 'Upraviť fotku',
  'cropProfilePhoto': 'Orezať profilovú fotku',
  'profilePhotoUpdated': 'Profilová fotka bola uložená.',
  'profilePhotoUpdateError': 'Profilovú fotku sa nepodarilo uložiť.',
  'profilePhotoRemoveError': 'Profilovú fotku sa nepodarilo odstrániť.',
  'requestDiscount': 'Požiadať o zľavu',
  'discountStatus': 'Zľavový status',
  'discountStatusNone': 'Bez zľavy',
  'discountStatusPending': 'Čaká na schválenie',
  'discountStatusApproved': 'Schválená zľava',
  'discountStatusRejected': 'Zamietnutá žiadosť',
  'discountStatusExpired': 'Platnosť zľavy skončila',
  'discountType': 'Typ zľavy',
  'discountTypeNormal': 'Bežný používateľ',
  'discountTypeStudent': 'Študent',
  'discountTypeSenior': 'Senior',
  'discountTypeZtp': 'ZŤP',
  'discountTypeIndividual': 'Individuálna zľava',
  'discountRequestDescription':
      'Vyberte typ zľavy, o ktorú žiadate. Po odoslaní žiadosť skontroluje administrátor.',
  'discountRequestNote': 'Poznámka k žiadosti',
  'discountRequestSent': 'Žiadosť o zľavu bola odoslaná.',
  'discountRequestError': 'Žiadosť o zľavu sa nepodarilo odoslať.',
  'discountRequestAlreadyPending': 'Už máte rozpracovanú žiadosť o zľavu.',
  'discountRequestPending': 'Žiadosť čaká na schválenie',
  'sendRequest': 'Odoslať žiadosť',
  'discountDocument': 'Doklad k zľave',
  'discountDocumentDescription':
      'Nahrajte fotografiu dokladu, podľa ktorého administrátor overí nárok na zľavu.',
  'chooseDiscountDocument': 'Vybrať doklad',
  'discountDocumentRequired':
      'Pre odoslanie žiadosti je potrebné priložiť doklad.',
  'discountDocumentSelected': 'Doklad bol vybraný',
  'takeDiscountDocumentPhoto': 'Odfotiť doklad',
  'chooseDiscountDocumentFromGallery': 'Vybrať z galérie',
  'discountRequests': 'Žiadosti o zľavu',
  'discountRequestsDescription':
      'Schvaľovanie alebo zamietnutie žiadostí používateľov o zľavu.',
  'discountRequestsLoadError': 'Žiadosti o zľavu sa nepodarilo načítať.',
  'noDiscountRequests': 'Nie sú evidované žiadne čakajúce žiadosti o zľavu.',
  'approveDiscount': 'Schváliť zľavu',
  'rejectDiscount': 'Zamietnuť žiadosť',
  'discountApproved': 'Zľava bola schválená.',
  'discountRejected': 'Žiadosť o zľavu bola zamietnutá.',
  'discountDecisionError': 'Rozhodnutie k žiadosti sa nepodarilo uložiť.',
  'discountValidUntilRequired': 'Vyberte dátum platnosti zľavy.',
  'discountAdminNote': 'Poznámka administrátora',
  'selectDiscountValidUntil': 'Vyberte platnosť zľavy',
  'discountDocumentPreview': 'Náhľad dokladu',
  'todayReservations': 'Dnešné rezervácie',
  'noTodayReservations': 'Dnes nemáte rezervované žiadne cvičenie.',
  'nearestTraining': 'Najbližšie cvičenie',
  'nearestTrainings': 'Najbližšie cvičenia',
  'noNearestTraining': 'Nie je naplánované žiadne najbližšie cvičenie.',
  'todaysTrainings': 'Dnešné cvičenia',
  'noTodaysTrainings': 'Dnes nie sú naplánované žiadne cvičenia.',
  'myMemberships': 'Moje permanentky',
  'activeMembershipsCount': 'Aktívne permanentky',
  'availableEntriesSummary': 'Dostupné vstupy',
  'reservedEntriesSummary': 'Alokované vstupy',
  'dailyMembershipsSummary': 'Denné permanentky',
  'tapToShowQrCode': 'Kliknutím zobrazíte QR kód.',
  'nearestReservations': 'Najbližšie rezervácie',
  'noNearestReservations': 'Nemáte žiadne najbližšie rezervácie.',
  'qrShort': 'QR',
  'membershipStatus': 'Stav permanentky',
  'remainingEntries': 'Zostávajúce vstupy',
  'upcomingTraining': 'Najbližšie dnešné cvičenie',
  'schedulePlaceholder': 'Tu bude rozvrh tréningov.',
  'reservationsPlaceholder': 'Tu budú rezervácie.',
  'newsPlaceholder': 'Tu sa budú zobrazovať novinky a správy od trénerov.',
  'aboutApp': 'O aplikácii',
  'aboutUs': 'O nás',
  'aboutAppDescription':
      'Aplikácia Body Fit Club TT slúži na správu tréningov, rezervácií, permanentiek '
      'a komunikácie medzi fitnescentrom a používateľmi.',
  'aboutUsDescription':
      'Body Fit Club je fitnescentrum v Trnave zamerané na skupinové aj individuálne '
      'tréningy, pohyb, zdravý životný štýl a osobný prístup ku klientom.',
  'bodyFitClubWebsite': 'https://bodyfitclub.sk/',
  'openWebsite': 'Otvoriť webovú stránku',
  'businessTerms': 'Obchodné podmienky',
  'legalDocumentsInfo':
      'Obchodné podmienky a informácie o ochrane osobných údajov budú dostupné na '
      'webovej stránke Body Fit Club.',
  'contacts': 'Kontakty',
  'billingDetails': 'Fakturačné údaje',
  'address': 'Adresa',
  'phone': 'Telefón',
  'website': 'Webová stránka',
  'socialNetworks': 'Sociálne siete',
  'openMap': 'Otvoriť mapu',
  'openFacebook': 'Facebook',
  'openInstagram': 'Instagram',
  'multisport': 'MultiSport',
  'multisportInfo':
      'Akceptujeme kartu MultiSport podľa aktuálnych podmienok prevádzky.',
  'bodyFitClubCompanyName': 'BODYFIT CLUB s.r.o.',
  'bodyFitClubOperationAddress': 'V Jame 24, Trnava',
  'bodyFitClubBillingAddress': 'J. G. Tajovského 18, 917 08 Trnava',
  'bodyFitClubPhonePrimary': '+421 902 860 008',
  'bodyFitClubPhoneSecondary': '+421 903 946 895',
  'bodyFitClubEmail': 'bodyfitclubtt@gmail.com',
  'bodyFitClubIco': '48074128',
  'ico': 'IČO: ',
  'companySeat': 'Sídlo',
  'operation': 'Prevádzka',
  'bodyFitClubFacebookUrl': 'https://www.facebook.com/bodyfitclub.sk',
  'bodyFitClubInstagramUrl': 'https://www.instagram.com/bodyfitclub.tt/',
  'bodyFitClubMapUrl':
      ' '
      'https://www.google.com/maps/search/?api=1&query=V%20Jame%206641%2F24%2C%20917%2001%20Trnava',
  'bodyFitClubMultiSportUrl':
      'https://multi-sport.sk/aktivity/partner/bodyfit-club/',
  'multisportInfo2':
      'Body Fit Club je partnerom programu MultiSport. Akceptovanie karty MultiSport '
      'sa riadi aktuálnymi podmienkami prevádzky.',
  'bodyFitClubWebsiteLabel': 'www.bodyfitclub.sk',
  'dic': 'DIČ: ',
  'bodyFitClubDic': '2120035445',
  'notVatPayer': 'Spoločnosť nie je platiteľom DPH',
  'legalDocuments': 'Právne dokumenty',
  'priceList': 'Cenník',
  'priceListAudience': 'Pre',
  'priceListAudienceNormal': 'bežní používatelia',
  'priceListAudienceDiscount': 'používatelia so zľavou',
  'priceListAudienceAll': 'všetci',
  'price': 'Cena',
  'singleEntries': 'Jednorazové vstupy',
  'priceListMemberships': 'Permanentky',
  'chooseEntry': 'Vyberte vstup',
  'noAvailablePlans': 'Momentálne nie sú dostupné žiadne možnosti nákupu.',
  'news': 'Novinky',
  'noPublicMessages': 'Zatiaľ nie sú žiadne správy.',
  'writeMessage': 'Napísať správu',
  'writeMessageShort': 'Napísať',
  'editMessage': 'Upraviť správu',
  'deleteMessage': 'Vymazať správu',
  'deleteMessageQuestion': 'Naozaj chcete vymazať túto správu?',
  'messageText': 'Text správy',
  'messageHint': 'Napíš správu...',
  'sendMessage': 'Poslať',
  'updateMessage': 'Uložiť zmeny',
  'messageSaved': 'Správa bola uložená.',
  'messageDeleted': 'Správa bola vymazaná.',
  'messageSaveError': 'Správu sa nepodarilo uložiť.',
  'messageDeleteError': 'Správu sa nepodarilo vymazať.',
  'editedBy': 'Upravené',
  'editedByAdmin': 'Upravené administrátorom',
  'editedByTrainer': 'Upravené trénerom',
  'userFallback': 'Používateľ',
  'noTrainings': 'Momentálne nie sú dostupné žiadne tréningy.',
  'noTrainingsForSelectedDay':
      'V tento deň nie sú naplánované žiadne tréningy.',
  'trainer': 'Tréner',
  'freeSpots': 'Voľné miesta',
  'reserve': 'Rezervovať',
  'reserved': 'Rezervované',
  'fullCapacity': 'Obsadené',
  'trainingsLoadError': 'Nepodarilo sa načítať rozvrh tréningov.',
  'unknownTraining': 'Neznámy tréning',
  'unknownTrainer': 'Neznámy tréner',
  'unknownUser': 'Neznámy používateľ',
  'trainingSessionFinished': 'Prebehlo',
  'trainingSessionTooFarInFuture':
      'Termín je príliš ďaleko v budúcnosti. Manuálne môžete pridať cvičenie iba do '
      'obdobia zobrazeného v rozvrhu.',
  'managementDescription':
      'Tu môžete spravovať termíny cvičení, dochádzku, permanentky a používateľov.',
  'scheduleManagement': 'Správa rozvrhu',
  'scheduleManagementDescription':
      'Správa typov cvičení, šablón rozvrhu a konkrétnych tréningových termínov.',
  'attendanceManagement': 'Správa dochádzky',
  'usersManagement': 'Správa používateľov',
  'usersManagementComingSoon': 'Správa používateľov bude doplnená neskôr.',
  'scheduleTemplatesManagement': 'Správa šablón rozvrhu',
  'reactivateUser': 'Aktivovať používateľa',
  'reactivateUserQuestion': 'Naozaj chcete znovu aktivovať tohto používateľa?',
  'userReactivated': 'Používateľ bol znovu aktivovaný.',
  'trainingTypesManagement': 'Správa typov cvičení',
  'addTrainingType': 'Pridať typ cvičenia',
  'editTrainingType': 'Upraviť typ cvičenia',
  'deleteTrainingType': 'Vymazať typ cvičenia',
  'trainingType': 'Typ cvičenia',
  'selectTrainingType': 'Vyberte typ cvičenia',
  'trainingName': 'Názov cvičenia',
  'description': 'Popis',
  'defaultDuration': 'Predvolené trvanie',
  'defaultCapacity': 'Predvolená kapacita',
  'noTrainingTypes': 'Momentálne nie sú vytvorené žiadne typy cvičení.',
  'trainingTypesLoadError': 'Nepodarilo sa načítať typy cvičení.',
  'trainingTypeCreated': 'Typ cvičenia bol vytvorený.',
  'trainingTypeUpdated': 'Typ cvičenia bol upravený.',
  'trainingTypeDeleted': 'Typ cvičenia bol vymazaný.',
  'trainingTypeDeleteQuestion':
      'Naozaj chcete vymazať tento typ cvičenia? Nebude sa už ponúkať pri nových termínoch.',
  'trainingTypeAlreadyExists': 'Typ cvičenia s týmto názvom už existuje.',
  'trainingTypeUsedByTemplate':
      'Typ cvičenia nie je možné vymazať, pretože sa používa v aktívnej šablóne rozvrhu.',
  'trainingTypeUsedBySession':
      'Typ cvičenia nie je možné vymazať, pretože sa používa v budúcom termíne cvičenia.',
  'addTrainingSession': 'Pridať termín cvičenia',
  'editTrainingSession': 'Upraviť detaily cvičenia',
  'trainingSessionCreated': 'Termín tréningu bol vytvorený.',
  'trainingSessionUpdated': 'Termín cvičenia bol upravený.',
  'updateTrainingSessionError': 'Termín cvičenia sa nepodarilo upraviť.',
  'trainingSessionInPast': 'Termín tréningu nemôže byť v minulosti.',
  'trainingSessionOverlap': 'V tomto čase už je naplánovaný iný tréning.',
  'capacityLowerThanReservations':
      'Kapacita nemôže byť nižšia ako počet existujúcich rezervácií.',
  'cancelTrainingSession': 'Zrušiť termín',
  'cancelTrainingSessionTitle': 'Zrušiť termín tréningu',
  'cancelTrainingSessionQuestion':
      'Naozaj chcete zrušiť tento termín tréningu? Aktívne rezervácie budú zrušené a '
      'alokované vstupy sa používateľom uvoľnia. Ak už bol vstup použitý, bude '
      'používateľovi vrátený.',
  'cancelTrainingSessionConfirm': 'Zrušiť termín',
  'trainingSessionCancelled': 'Termín tréningu bol zrušený.',
  'cancelTrainingSessionError': 'Termín tréningu sa nepodarilo zrušiť.',
  'trainerCanCancelOnlyOwnSession': 'Tréner môže zrušiť iba vlastný termín.',
  'trainerCannotCancelStartedSession':
      'Tréner nemôže zrušiť termín, ktorý už začal alebo prebehol.',
  'date': 'Dátum',
  'startTime': 'Začiatok',
  'duration': 'Trvanie',
  'capacity': 'Kapacita',
  'selectDate': 'Vyberte dátum',
  'selectTrainer': 'Vyberte trénera',
  'trainersLoadError': 'Nepodarilo sa načítať trénerov.',
  'fillAllFields': 'Vyplňte všetky povinné údaje.',
  'invalidCapacity': 'Kapacita musí byť väčšia ako 0.',
  'invalidDuration': 'Trvanie musí byť väčšie ako 0.',
  'saveError': 'Uloženie sa nepodarilo.',
  'addScheduleTemplate': 'Pridať šablónu rozvrhu',
  'editScheduleTemplate': 'Upraviť šablónu rozvrhu',
  'deleteScheduleTemplate': 'Vymazať šablónu rozvrhu',
  'noScheduleTemplates': 'Momentálne nie sú vytvorené žiadne šablóny rozvrhu.',
  'weekday': 'Deň v týždni',
  'selectWeekday': 'Vyberte deň v týždni',
  'scheduleTemplateCreated': 'Šablóna rozvrhu bola vytvorená.',
  'scheduleTemplateUpdated': 'Šablóna rozvrhu bola upravená.',
  'scheduleTemplateDeleted': 'Šablóna rozvrhu bola vymazaná.',
  'scheduleTemplateDeleteQuestion':
      'Naozaj chcete vymazať túto šablónu rozvrhu? Nebude sa už používať pri '
      'generovaní nových termínov.',
  'scheduleTemplateAlreadyExists': 'Takáto šablóna rozvrhu už existuje.',
  'scheduleTemplateLoadError': 'Nepodarilo sa načítať šablóny rozvrhu.',
  'scheduleTemplateOverlap': 'V tomto čase už existuje iná šablóna rozvrhu.',
  'capacityLabel': 'Kapacita',
  'reservationCreated': 'Rezervácia bola vytvorená.',
  'reservationAlreadyExists': 'Na tento tréning už máte vytvorenú rezerváciu.',
  'reservationTrainingFull': 'Tento tréning je už obsadený.',
  'reservationTrainingNotAvailable':
      'Tento tréning už nie je dostupný na rezerváciu.',
  'reservationTrainingAlreadyStarted':
      'Na tento tréning sa už nedá rezervovať.',
  'reservationError': 'Rezerváciu sa nepodarilo vytvoriť.',
  'myReservations': 'Moje rezervácie',
  'noReservations': 'Momentálne nemáte žiadne rezervácie.',
  'cancelReservation': 'Zrušiť rezerváciu',
  'cancelReservationTitle': 'Zrušiť rezerváciu',
  'cancelReservationQuestion': 'Naozaj chcete zrušiť túto rezerváciu?',
  'reservationCancelled': 'Rezervácia bola zrušená.',
  'reservationCancelError': 'Rezerváciu sa nepodarilo zrušiť.',
  'reservationsLoadError': 'Rezervácie sa nepodarilo načítať.',
  'cancelReservations': 'Zrušiť rezervácie',
  'cancelReservationsBeforeDeactivation':
      'Pred deaktiváciou alebo zrušením permanentky najskôr zrušte alokované rezervácie.',
  'cancelReservationForMembership': 'Zrušiť túto rezerváciu',
  'cancelReservationForMembershipQuestion':
      'Naozaj chcete zrušiť túto rezerváciu naviazanú na permanentku? Alokovaný vstup '
      'sa uvoľní.',
  'reservationForMembershipCancelled':
      'Rezervácia bola zrušená a alokovaný vstup bol uvoľnený.',
  'noReservationsForTrainingHistory':
      'Na tomto tréningu nie sú žiadne rezervácie.',
  'reservationQrCode': 'QR kód rezervácie',
  'memberships': 'Permanentky',
  'assignMembership': 'Priradiť permanentku',
  'selectUser': 'Vyberte používateľa',
  'selectMembershipPlan': 'Vyberte typ permanentky',
  'membershipPlansLoadError': 'Nepodarilo sa načítať typy permanentiek.',
  'membershipAssigned': 'Permanentka bola priradená.',
  'membershipAssignError': 'Permanentku sa nepodarilo priradiť.',
  'membershipPlan': 'Typ permanentky',
  'client': 'Používateľ',
  'buyMembership': 'Kúpiť permanentku',
  'buySingleEntry': 'Kúpiť jednorázový vstup',
  'chooseMembership': 'Vyberte permanentku',
  'payment': 'Platba',
  'pay': 'Zaplatiť',
  'paymentSuccessful': 'Platba úspešná.',
  'paymentFailed': 'Platba zlyhala.',
  'activeMembership': 'Aktívna permanentka',
  'noActiveMembership': 'Nemáte aktívnu permanentku.',
  'validUntil': 'Platná do',
  'membershipLoadError': 'Permanentku sa nepodarilo načítať.',
  'noAvailableEntries': 'Nemáte dostupný vstup na rezerváciu.',
  'noUpcomingTraining': 'Dnes nemáte rezervované žiadne cvičenie.',
  'membershipsManagement': 'Správa permanentiek',
  'membershipDetail': 'Detail permanentky',
  'noMemberships': 'Momentálne nie sú dostupné žiadne permanentky.',
  'status': 'Stav',
  'validFrom': 'Platná od',
  'entriesTotal': 'Celkový počet vstupov',
  'entriesRemaining': 'Zostávajúce vstupy',
  'entriesReserved': 'Alokované v rezerváciách',
  'entriesAvailable': 'Dostupné vstupy',
  'adminMembershipEdit': 'Administrátorská úprava',
  'membershipStatusActive': 'Aktívna',
  'membershipStatusInactive': 'Neaktívna',
  'membershipStatusCancelled': 'Zrušená',
  'membershipStatusExpired': 'Expirovaná',
  'membershipStatusUsedUp': 'Minutá',
  'membershipUpdated': 'Permanentka bola upravená.',
  'membershipUpdateError': 'Permanentku sa nepodarilo upraviť.',
  'invalidRemainingEntries': 'Zadajte platný počet zostávajúcich vstupov.',
  'allocatedReservations': 'Alokované rezervácie',
  'cancelAllocatedReservations': 'Zrušiť alokované rezervácie',
  'cancelAllocatedReservationsQuestion':
      'Naozaj chcete zrušiť aktívne rezervácie naviazané na túto permanentku? '
      'Alokované vstupy sa uvoľnia.',
  'cancelAllReservations': 'Zrušiť všetky rezervácie',
  'cancelAllocatedReservationsError':
      'Alokované rezervácie sa nepodarilo zrušiť.',
  'usedEntries': 'Použité vstupy',
  'noAllocatedReservations':
      'Na túto permanentku nie sú aktuálne alokované žiadne rezervácie.',
  'noUsedEntries': 'Z tejto permanentky zatiaľ nebol použitý žiadny vstup.',
  'membershipUsageLoadError': 'Históriu permanentky sa nepodarilo načítať.',
  'searchMemberships': 'Hľadať podľa používateľa alebo permanentky',
  'allMembershipStatuses': 'Všetky stavy',
  'membershipStatusNotYetValid': 'Ešte neplatná',
  'membershipStatusUsable': 'Aktívna',
  'invalidRemainingEntriesHigherThanTotal':
      'Zostávajúce vstupy nemôžu byť vyššie ako celkový počet vstupov.',
  'invalidRemainingEntriesLowerThanReserved':
      'Zostávajúce vstupy nemôžu byť nižšie ako počet alokovaných vstupov.',
  'membershipPrefix': 'Permanentka',
  'statusPrefix': 'Stav',
  'attendance': 'Dochádzka',
  'attendanceLoadError': 'Nepodarilo sa načítať dochádzku.',
  'noActiveReservationsForAttendance':
      'Momentálne nie sú žiadne aktívne rezervácie na označenie dochádzky.',
  'attended': 'Prišiel',
  'noShow': 'Neprišiel',
  'markAttendedTitle': 'Označiť účasť',
  'markNoShowTitle': 'Označiť neúčasť',
  'markAttendedQuestion': 'Naozaj chcete označiť používateľa ako prítomného?',
  'markNoShowQuestion': 'Naozaj chcete označiť používateľa ako neprítomného?',
  'attendanceMarked': 'Dochádzka bola uložená.',
  'attendanceMarkError': 'Dochádzku sa nepodarilo uložiť.',
  'attendedStatus': 'Prišiel',
  'noShowStatus': 'Neprišiel',
  'attendedCountLabel': 'Prišli',
  'noShowCountLabel': 'Neprišli',
  'attendanceActionDone': 'Zmena účasti bola uložená.',
  'attendanceActionError': 'Zmenu účasti sa nepodarilo uložiť.',
  'showQrCode': 'QR kód',
  'showQrToTrainer': 'Ukážte tento QR kód trénerovi pri príchode na tréning.',
  'scanQrCode': 'Skenovať QR kód',
  'scanQrCodes': 'Skenovať QR kódy',
  'scanQrCodeHint': 'Namierte kameru na QR kód rezervácie používateľa.',
  'invalidQrCode': 'Neplatný QR kód rezervácie.',
  'qrCodeScanned': 'QR kód bol naskenovaný.',
  'qrScanSuccessful':
      'QR kód bol naskenovaný. Môžete skenovať ďalšieho používateľa.',
  'trainerQrScanTooEarly':
      'QR kód je možné naskenovať najskôr 30 minút pred začiatkom cvičenia.',
  'trainingHistory': 'História tréningov',
  'trainingHistoryDetail': 'Detail tréningu',
  'trainingHistoryLoadError': 'Históriu tréningov sa nepodarilo načítať.',
  'trainingHistoryReservationsLoadError':
      'Účasť na tréningu sa nepodarilo načítať.',
  'noTrainingHistoryInSelectedPeriod':
      'V zvolenom období nie sú žiadne tréningy.',
  'fromDatePrefix': 'Od',
  'toDatePrefix': 'Do',
  'planned': 'Naplánované',
  'cancelled': 'Zrušené',
  'finished': 'Prebehlo',
  'reservedStatus': 'Rezervované',
  'reservedCountLabel': 'Rezervované',
  'cancelledCountLabel': 'Zrušené',
  'markedAtPrefix': 'Označené',
  'markAsAttended': 'Označiť ako prišiel',
  'markAsNoShow': 'Označiť ako neprišiel',
  'revertAttendance': 'Zrušiť označenú účasť',
  'revertNoShow': 'Zrušiť označenú neúčasť',
  'markAsAttendedQuestion':
      'Naozaj chcete označiť používateľa ako prítomného? Vstup z permanentky sa použije.',
  'markAsNoShowQuestion':
      'Naozaj chcete označiť používateľa ako neprítomného? Vstup z permanentky sa použije.',
  'revertAttendanceQuestion':
      'Naozaj chcete zrušiť označenú účasť? Použitý vstup sa vráti späť na permanentku.',
  'revertNoShowQuestion':
      'Naozaj chcete zrušiť označenú neúčasť? Použitý vstup sa vráti späť na permanentku.',
  'addTrainingAttendance': 'Pridať účastníka',
  'selectAttendanceUser': 'Vyberte používateľa',
  'selectAttendanceMembership': 'Vyberte permanentku',
  'noUsersForAttendance': 'Nenašli sa žiadni aktívni používatelia.',
  'noUsableMembershipsForAttendance':
      'Používateľ nemá použiteľnú permanentku pre tento tréning.',
  'addTrainingAttendanceQuestion':
      'Naozaj chcete dodatočne pridať účasť používateľa na tomto tréningu? Vstup z '
      'permanentky sa použije.',
  'trainingAttendanceAdded': 'Účastník bol pridaný do tréningu.',
  'trainingAttendanceAddError': 'Účastníka sa nepodarilo pridať.',
  'userAlreadyHasReservationForTraining':
      'Používateľ už má na tento tréning vytvorený záznam.',
  'usersLoadError': 'Nepodarilo sa načítať používateľov.',
  'allRoles': 'Všetky role',
  'searchUsers': 'Hľadať používateľa',
  'noUsersFound': 'Nenašli sa žiadni používatelia.',
  'editUser': 'Upraviť používateľa',
  'userUpdated': 'Používateľ bol upravený.',
  'userUpdateError': 'Používateľa sa nepodarilo upraviť.',
  'cannotChangeOwnRole': 'Nemôžete zmeniť vlastnú rolu.',
  'changeRoleWarning':
      'Pri zmene roly používateľa sa môžu zmeniť jeho oprávnenia v aplikácii.',
  'deactivateUser': 'Deaktivovať používateľa',
  'deactivationReason': 'Dôvod deaktivácie',
  'userDeactivated': 'Používateľ bol deaktivovaný.',
  'deactivateUserQuestion':
      'Naozaj chcete deaktivovať tohto používateľa? Nebude sa môcť ďalej používať v '
      'správe aplikácie.',
  'cannotDeactivateYourself': 'Nemôžete deaktivovať vlastný účet.',
  'userUsedByTemplate':
      'Používateľa nie je možné deaktivovať alebo zmeniť na bežného používateľa, '
      'pretože je priradený v aktívnej šablóne rozvrhu.',
  'userUsedByFutureSession':
      'Používateľa nie je možné deaktivovať alebo zmeniť na bežného používateľa, '
      'pretože je priradený k budúcemu cvičeniu.',
  'userHasActiveReservations':
      'Používateľa nie je možné deaktivovať, pretože má aktívne rezervácie.',
  'userHasActiveMemberships':
      'Používateľa nie je možné deaktivovať, pretože má aktívne permanentky.',
  'inactiveUser': 'Neaktívny používateľ',
  'userCannotBeDeactivated': 'Používateľa nemožno deaktivovať',
  'userCannotBeDeactivatedDescription':
      'Pred deaktiváciou je potrebné najskôr vyriešiť jeho aktívne rezervácie alebo '
      'permanentky.',
  'userHasBlockingItems': 'Používateľ má:',
  'activeReservationsCount': 'Aktívne rezervácie',
  'showMemberships': 'Zobraziť permanentky',
  'auditLogs': 'História zásahov',
  'auditLogsDescription': 'Prehľad dôležitých zásahov v aplikácii.',
  'auditLogsLoadError': 'Históriu zásahov sa nepodarilo načítať.',
  'noAuditLogs': 'Nenašli sa žiadne zásahy.',
  'searchAuditLogs': 'Hľadať podľa používateľa, e-mailu alebo popisu',
  'auditCategory': 'Kategória',
  'auditAction': 'Akcia',
  'auditActor': 'Vykonal',
  'auditActorRole': 'Rola vykonávateľa',
  'auditPeriod': 'Obdobie',
  'auditAllCategories': 'Všetky kategórie',
  'auditCategoryMemberships': 'Permanentky',
  'auditCategoryReservations': 'Rezervácie',
  'auditCategoryAttendance': 'Dochádzka',
  'auditCategoryUsers': 'Používatelia',
  'auditCategorySchedule': 'Rozvrh',
  'auditCategoryMessages': 'Správy',
  'auditCategoryPayments': 'Platby',
  'auditCategoryProfile': 'Profil',
  'auditAllActions': 'Všetky akcie',
  'auditActionCreated': 'Vytvorenie',
  'auditActionUpdated': 'Úprava',
  'auditActionCancelled': 'Zrušenie',
  'auditActionDeactivated': 'Deaktivácia',
  'auditActionActivated': 'Aktivácia',
  'auditActionAssigned': 'Priradenie',
  'auditActionPurchased': 'Nákup',
  'auditActionPaymentSucceeded': 'Platba úspešná',
  'auditActionPaymentFailed': 'Platba zlyhala',
  'auditActionAttendanceMarked': 'Dochádzka',
  'auditActionQrChecked': 'QR kontrola',
  'auditAllActorRoles': 'Všetky role',
  'auditReservationCreatedTitle': 'Vytvorenie rezervácie',
  'auditReservationCreatedDescription':
      'Používateľ vytvoril rezerváciu na tréning.',
  'auditReservationCancelledTitle': 'Zrušenie rezervácie',
  'auditReservationCancelledDescription':
      'Rezervácia používateľa bola zrušená.',
  'auditAttendanceAttendedTitle': 'Označená účasť',
  'auditAttendanceAttendedDescription':
      'Používateľ bol označený ako prítomný na tréningu.',
  'auditAttendanceNoShowTitle': 'Označená neúčasť',
  'auditAttendanceNoShowDescription':
      'Používateľ bol označený ako neprítomný na tréningu.',
  'auditTrainingTypeCreatedTitle': 'Vytvorenie typu cvičenia',
  'auditTrainingTypeUpdatedTitle': 'Úprava typu cvičenia',
  'auditTrainingTypeDeactivatedTitle': 'Deaktivácia typu cvičenia',
  'auditTrainingSessionCreatedTitle': 'Vytvorenie termínu',
  'auditTrainingSessionUpdatedTitle': 'Úprava termínu',
  'auditTrainingSessionTimeChangedTitle': 'Zmena času termínu',
  'auditTrainingSessionCancelledTitle': 'Zrušenie termínu',
  'auditScheduleTemplateCreatedTitle': 'Vytvorenie šablóny rozvrhu',
  'auditScheduleTemplateUpdatedTitle': 'Úprava šablóny rozvrhu',
  'auditScheduleTemplateDeactivatedTitle': 'Deaktivácia šablóny rozvrhu',
  'auditUserUpdatedTitle': 'Úprava používateľa',
  'auditUserUpdatedDescription': 'Administrátor upravil údaje používateľa.',
  'auditUserRoleChangedTitle': 'Zmena roly používateľa',
  'auditUserRoleChangedDescription': 'Administrátor zmenil rolu používateľa.',
  'auditUserDeactivatedTitle': 'Deaktivácia používateľa',
  'auditUserDeactivatedDescription': 'Administrátor deaktivoval používateľa.',
  'auditUserDeactivationBlockedTitle': 'Neúspešná deaktivácia používateľa',
  'auditUserDeactivationBlockedDescription':
      'Deaktivácia používateľa bola zablokovaná kontrolou aktívnych väzieb.',
  'auditPublicMessageCreatedTitle': 'Vytvorenie novinky',
  'auditPublicMessageCreatedDescription': 'Bola vytvorená verejná novinka.',
  'auditPublicMessageUpdatedTitle': 'Úprava novinky',
  'auditPublicMessageUpdatedDescription': 'Bola upravená verejná novinka.',
  'auditPublicMessageDeletedTitle': 'Vymazanie novinky',
  'auditPublicMessageDeletedDescription': 'Verejná novinka bola vymazaná.',
  'auditProfileCompletedTitle': 'Doplnenie profilu',
  'auditProfileCompletedDescription':
      'Používateľ doplnil základné údaje profilu.',
  'auditProfileUpdatedTitle': 'Úprava profilu',
  'auditProfileUpdatedDescription': 'Používateľ upravil údaje profilu.',
  'auditProfilePhotoUpdatedTitle': 'Úprava profilovej fotky',
  'auditProfilePhotoUpdatedDescription': 'Používateľ upravil profilovú fotku.',
  'auditProfilePhotoRemovedTitle': 'Odstránenie profilovej fotky',
  'auditProfilePhotoRemovedDescription':
      'Používateľ odstránil manuálne nastavenú profilovú fotku.',
  'auditPaymentStartedTitle': 'Spustenie platby',
  'auditPaymentStartedDescription': 'Používateľ spustil platbu za permanentku.',
  'auditPaymentSucceededTitle': 'Úspešná platba',
  'auditPaymentSucceededDescription':
      'Platba za permanentku bola úspešne dokončená.',
  'auditPaymentFailedTitle': 'Neúspešná platba',
  'auditPaymentFailedDescription':
      'Platba za permanentku zlyhala alebo bola zrušená.',
  'auditMembershipUpdatedTitle': 'Úprava permanentky',
  'auditMembershipUpdatedDescription':
      'Administrátor upravil permanentku používateľa.',
  'auditMembershipStatusChangedTitle': 'Zmena stavu permanentky',
  'auditMembershipStatusChangedDescription':
      'Administrátor zmenil stav permanentky používateľa.',
  'auditMembershipEntriesChangedTitle': 'Zmena počtu vstupov permanentky',
  'auditMembershipEntriesChangedDescription':
      'Administrátor zmenil počet zostávajúcich vstupov permanentky.',
  'auditMembershipReservationCancelledTitle': 'Zrušenie alokovanej rezervácie',
  'auditMembershipReservationCancelledDescription':
      'Administrátor zrušil alokovanú rezerváciu naviazanú na permanentku.',
  'auditMembershipAllReservationsCancelledTitle':
      'Zrušenie všetkých alokovaných rezervácií',
  'auditMembershipAllReservationsCancelledDescription':
      'Administrátor zrušil všetky alokované rezervácie naviazané na permanentku.',
  'auditMembershipAssignedTitle': 'Priradenie permanentky',
  'auditMembershipAssignedDescription':
      'Používateľovi bola manuálne priradená permanentka.',
  'auditMembershipPurchasedTitle': 'Nákup permanentky',
  'auditMembershipPurchasedDescription': 'Používateľ si zakúpil permanentku.',
  'auditActionMembershipAssigned': 'Priradenie permanentky',
  'auditActionMembershipPurchased': 'Nákup permanentky',
  'auditActionMembershipUpdated': 'Úprava permanentky',
  'auditActionMembershipStatusChanged': 'Zmena stavu permanentky',
  'auditActionMembershipEntriesChanged': 'Zmena vstupov permanentky',
  'auditActionMembershipReservationCancelled':
      'Zrušenie jednej alokovanej rezervácie',
  'auditActionMembershipAllReservationsCancelled':
      'Zrušenie všetkých alokovaných rezervácií',
  'auditActionReservationCreated': 'Vytvorenie rezervácie',
  'auditActionReservationCancelled': 'Zrušenie rezervácie',
  'auditActionAttendanceAttended': 'Označená účasť',
  'auditActionAttendanceNoShow': 'Označená neúčasť',
  'auditActionTrainingTypeCreated': 'Vytvorenie typu cvičenia',
  'auditActionTrainingTypeUpdated': 'Úprava typu cvičenia',
  'auditActionTrainingTypeDeactivated': 'Deaktivácia typu cvičenia',
  'auditActionTrainingSessionCreated': 'Vytvorenie termínu',
  'auditActionTrainingSessionUpdated': 'Úprava termínu',
  'auditActionTrainingSessionTimeChanged': 'Zmena času termínu',
  'auditActionTrainingSessionCancelled': 'Zrušenie termínu',
  'auditActionScheduleTemplateCreated': 'Vytvorenie šablóny',
  'auditActionScheduleTemplateUpdated': 'Úprava šablóny',
  'auditActionScheduleTemplateDeactivated': 'Deaktivácia šablóny',
  'auditActionUserUpdated': 'Úprava používateľa',
  'auditActionUserRoleChanged': 'Zmena roly',
  'auditActionUserDeactivationBlocked': 'Blokovaná deaktivácia',
  'auditActionUserDeactivated': 'Deaktivácia používateľa',
  'auditActionPublicMessageCreated': 'Vytvorenie novinky',
  'auditActionPublicMessageUpdated': 'Úprava novinky',
  'auditActionPublicMessageDeleted': 'Vymazanie novinky',
  'auditActionProfileCompleted': 'Doplnenie profilu',
  'auditActionProfileUpdated': 'Úprava profilu',
  'auditActionProfilePhotoUpdated': 'Úprava profilovej fotky',
  'auditActionProfilePhotoRemoved': 'Odstránenie profilovej fotky',
  'auditActionPaymentStarted': 'Spustenie platby',
  'auditUserEmailCompletedTitle': 'Doplnenie e-mailu',
  'auditUserEmailCompletedDescription':
      'Používateľ doplnil chýbajúci e-mail k účtu.',
  'currentUserShort': 'vy',
  'auditUserEmailUpdatedTitle': 'Úprava e-mailu používateľa',
  'auditUserEmailUpdatedDescription':
      'Administrátor upravil kontaktný e-mail používateľa.',
  'auditUserReactivatedTitle': 'Aktivácia používateľa',
  'auditUserReactivatedDescription':
      'Administrátor znovu aktivoval používateľa.',
  'auditActionUserEmailCompleted': 'Doplnenie e-mailu',
  'auditActionUserEmailUpdated': 'Úprava e-mailu používateľa',
  'auditActionUserReactivated': 'Aktivácia používateľa',
  'auditCategoryDiscounts': 'Zľavy',
  'auditDiscountRequestedTitle': 'Žiadosť o zľavu',
  'auditDiscountRequestedDescription':
      'Používateľ odoslal žiadosť o schválenie zľavy.',
  'auditDiscountApprovedTitle': 'Schválenie zľavy',
  'auditDiscountApprovedDescription':
      'Administrátor schválil používateľovi zľavu.',
  'auditDiscountRejectedTitle': 'Zamietnutie zľavy',
  'auditDiscountRejectedDescription':
      'Administrátor zamietol používateľovi žiadosť o zľavu.',
  'auditAccountDeletionRequestedTitle': 'Žiadosť o vymazanie účtu',
  'auditAccountDeletionRequestedDescription':
      'Používateľ požiadal o vymazanie účtu.',
  'auditEmailChangeRequestedTitle': 'Žiadosť o zmenu e-mailu',
  'auditEmailChangeRequestedDescription':
      'Používateľ požiadal o zmenu e-mailovej adresy.',
  'auditEmailChangeCompletedTitle': 'Dokončenie zmeny e-mailu',
  'auditEmailChangeCompletedDescription':
      'Používateľ dokončil zmenu e-mailovej adresy.',
  'auditPasswordResetRequestedTitle': 'Žiadosť o obnovenie hesla',
  'auditPasswordResetRequestedDescription':
      'Používateľ požiadal o odoslanie e-mailu na obnovenie hesla.',
  'auditActionDiscountRequested': 'Žiadosť o zľavu',
  'auditActionDiscountApproved': 'Schválenie zľavy',
  'auditActionDiscountRejected': 'Zamietnutie zľavy',
  'auditActionAccountDeletionRequested': 'Žiadosť o vymazanie účtu',
  'auditActionEmailChangeRequested': 'Žiadosť o zmenu e-mailu',
  'auditActionEmailChangeCompleted': 'Dokončenie zmeny e-mailu',
  'auditActionPasswordResetRequested': 'Žiadosť o obnovenie hesla',
};

const Map<String, List<String>> appTextListsSk = {
  'shortWeekdays': ['Po', 'Ut', 'St', 'Št', 'Pi', 'So', 'Ne'],
  'weekdays': [
    'Pondelok',
    'Utorok',
    'Streda',
    'Štvrtok',
    'Piatok',
    'Sobota',
    'Nedeľa',
  ],
};
